### PR TITLE
Scripts/Scarlet Enclave: Death Comes From On High

### LINKED ISSUE #20843: [3.3.5][Quest] Death Comes From On High (12641)
**Description:**

The Eye of Acherus does not behave as it should in regards to launching and its movement speed.

**Current behaviour:**

At the start of the quest, the Eye is not launched towards New Avalon. The Movement speed of the Eye is much slower than retail.

**Expected behaviour:**

The Eye of Acherus should launch towards New Avalon with notifications for "The Eye of Acherus launches towards its destination." and "The Eye of Acherus is in your control."
After gaining control the Eye should also move faster. 
Video for reference: https://www.youtube.com/watch?v=VAQwxyWrXrc

**Steps to reproduce the problem:**

1. Create a new deathknight.
2. Complete the intro quest chain up until this point.
3. Begin quest and use the Eye of Acherus.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3e74ef1528db 2017-11-10 23:45:42 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** TDB_full_world_335.63_2017_04_18

**Operating system:** Fedora 26

### PR DESCRIPTION
**Pull request by DanVS**
**Changes proposed:**
Possible fix for quest [Death Comes From On High (12641)](https://woehead.way-of-elendil.fr/?quest=12641). Schedule launch event on initialization stage.

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #20843

**Tests performed:** Does build and works in-game.

### CODE REVIEW

**Comment by pedroevil51** [comment]
Tested and working on latest commit 
[https://github.com/TrinityCore/TrinityCore/commit/aa1883060e11d43d6de8fa38387d96a7e2df4ca6](url)

**Review by klister803 — APPROVED** [review]
Working on latest commit, no problems.  https://github.com/TrinityCore/TrinityCore/commit/2b3f29aa6d2d3787c063ebc2a541149bd2181c85

**Comment by pedroevil51** [comment]
Here, proof
https://vimeo.com/user87940621/review/282568317/7642f85436
Sorry about the background sound (i was watching a podcast)

**Comment by jackpoz** [comment]
thank you for the PR :)

**Pull request merged**
