### PR TITLE
Game/Pools: Workaround for pools units and gameobjects

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
**Changes proposed:**

-  Game/Pools: Workaround for pools units and gameobjects
-  Now poolig at least works again, it was fucking broke since 5 years now
-  This reverts the state of pooling to this mechanic https://github.com/TrinityCoreLegacy/TrinityCore/commit/f716e795dfab96b458cb7f6a5cc0545db7396cc2#diff-90acd023cd4bbb796987fe7e52212398 just with the removal of:

```
if (spawns.IsActiveObject<T>(itr->guid) && urand(1, 4) != 1)
```
to
```
if (spawns.IsActiveObject<T>(itr->guid))
```

which enables pooling for all kind of pools again.

**Target branch(es):** 3.3.5/master

- 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
https://github.com/TrinityCore/TrinityCore/pull/23603
https://github.com/TrinityCore/TrinityCore/issues/21331
https://github.com/TrinityCore/TrinityCore/pull/24283

**Tests performed:** (Does it build, tested in-game, etc.)
yes all good

**Known issues and TODO list:** (add/remove lines as needed)

- To do: database update queries still assume one timer per spawnid, needs fix (I need help to fix that)

### CODE REVIEW

**Comment by jackpoz** [comment]
could you explain a bit more in detail what caused the issue and how your code fixes it ?

**Comment by Rushor** [comment]
It is a revert of the latest change Actually

**Comment by illfated** [comment]
PR title detail: I notice the use of "Game/Pools" (directory structure reference) which in itself is fine. Just for my own curiosity's sake, TC usually refers to `/src/server/game/` as "Core" in PR titles (although several other source directories are considered "Core" as well). Do you consider "Game/Pools" just as useful as the conservative "Core/Pools" nomenclature?

**Comment by jackpoz** [comment]
> It is a revert of the latest change Actually

Which latest changes ? Could you please write a full complete description of this PR ?

**Comment by Rushor** [comment]
@jackpoz 

-  This reverts the state of pooling to this mechanic https://github.com/TrinityCoreLegacy/TrinityCore/commit/f716e795dfab96b458cb7f6a5cc0545db7396cc2#diff-90acd023cd4bbb796987fe7e52212398 just with the removal of:

```
if (spawns.IsActiveObject<T>(itr->guid) && urand(1, 4) != 1)
```
to
```
if (spawns.IsActiveObject<T>(itr->guid))
```

which enables pooling for all kind of pools again.

**Comment by Rushor** [comment]
missing outdated can be removed :)

**Comment by jackpoz** [comment]
Isn't the db query still on the todo ?

**Comment by Rushor** [comment]
you are right - but with this change a huge issue is fixed or at least on the same level as it was 5 years ago. we all should really start testing prs better for the future. i willy also try to get time to do so with any new pr.

**Comment by jackpoz** [comment]
@Rushor got any luck with the db query part ?

**Comment by jackpoz** [comment]
Replaced by https://github.com/TrinityCore/TrinityCore/pull/24949

**Pull request closed without merging**
