### PR TITLE
Fix: Can cast on fear if rooted [3.3.5a]

### LINKED ISSUE #13964: [3.3.5a] Can cast on fear if rooted
Core rev: https://github.com/TrinityCore/TrinityCore/commit/0b8a86886bec1979b698b4109c1f667ba1257fc0

When you are on fear and then you get rooted, you can cast when rooted (until roots end), even dispel the fear.

Screenshots (in this case I used .aura just to not login with a third account, I used root spell 64695 which is the roots of the shaman totem: http://www.wowhead.com/spell=64695/earthgrab (tested without .aura and it got bugged too), tested with frost nova and the same):

Notice that as soon as I got rooted, I was able to cast anything.

When roots end, if you are still in fear, you start to move in fear again and you can't cast so the bug is only when you are rooted.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8074326-3-3-5a-can-cast-on-fear-if-rooted?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
by @Xiledria; closes  #13964

Removes the ability to cast while in fear and rooted.
Tested and found working by @Raydor and @Xiledria

### CODE REVIEW

**Comment by tkrokli** [comment]
I know where the compile failed; 27% into the compile. I'm fixing it now, removing unneeded parameter.

**Comment by jackpoz** [comment]
this requires to test all cases that the removed lines were supposed to fix, to ensure old bugs don't get added back

**Comment by Xiledria** [comment]
I was testing that too - Fear -> roots, roots -> fear and both at once.
With just reverted #13095 I was teleported everytime I tried to cast root on moving target with fear, which I was not able to reproduce again after this commit.

In SetStunned() and SetRooted() was StopMoving() call only for creatures which made them to stop moving correctly with fear, but not players.

Last commit that had to fix teleport issues by stopping whole fear in FleeingMovementGenerator<Player>::DoFinalize(Player* owner) which allowed players to cast by removing UNIT_STATE_FLEEING flag and stopped moving by StopMoving().

This commit makes player to only stop their movement inside SetStunned(true) and SetRooted(true), as creatures were before, without removing their UNIT_STATE_FLEEING flag.

Fleeing movement generator has disabled updates with UNIT_STATE_ROOT flag on, so any further update in movement is not an issue, only apply of roots flag while moving was causing teleportations.

**Comment by Frytiks** [comment]
Ye, this pull request fixed it, i tested it, 2 days no report from players. But there is problem when u fear player, he just like moving like blinking by 1 yard

**Comment by ccrs** [comment]
Tested and working as intended.

**Comment by tkrokli** [comment]
Thanks for testing, guys. Others are welcome to test as well, to see if this will fix any issue you may have.

**Comment by Raydor** [comment]
24 hours with it in a 400 players server and no reports yet, working well.

**Comment by tkrokli** [comment]
:+1: Thanks for the feedback, @Raydor. Have you asked any of them to test specifically (in PvP) to use fear => root (as well as root => fear) to see if they get issues?

**Comment by Raydor** [comment]
@tkrokli I tested everything myself before apply it and it worked ok and yes, I told them to test it and report me if they see something strange, no reports for the moment.

**Comment by tkrokli** [comment]
Excellent, happy to hear that it solves the issue and not creating new ones.

**Comment by Aokromes** [comment]
What about the feared victim view for caster? It's seen properly or it's "teleported" for caster?

**Comment by Xiledria** [comment]
Works fine for me, I was testing it with 2 characters

**Comment by tkrokli** [comment]
@Xiledria : You did not see any of the "blink" movement mentioned by @Frytiks in https://github.com/TrinityCore/TrinityCore/pull/14641#issuecomment-99079488 ?
I was going to test it with 2 warlock characters, but aren't there more classes than warlock using Fear spells, like priest? What about any difference between player and non-player creature, even beast creatures, do they react correctly with this PR applied to the core? (I was about to compile and test it myself, but I am uncertain about how to test it correctly, to verify that there is no bug there.)

**Comment by Xiledria** [comment]
There should not be any difference between fears, all of them go through the same function..
And no, I have not noticed any "blink" :\
Maybe @Frytiks applied that old version that was here before :D otherwise he might try to describe how to reproduce it again, because I seem not to be able to force my 2nd character "blink"... 
Apply roots stops character without blink, remove roots too :\
If I apply both at once via .cast macro, character does not even move, before character were teleported X yards away, which is not happening...

**Comment by tkrokli** [comment]
That looks like a good and thorough test, I will just wait and see if anyone else has got something to say.

**Comment by jackpoz** [comment]
Thanks to the positive community feedback, I'm going to merge this PR. Please provide any additional feedback here if any issue arises

**Comment by tkrokli** [comment]
:+1: Thanks, @jackpoz. :smirk_cat: Grats, @Xiledria. There is your fix, integrated in the source.

**Pull request merged**
