### PR TITLE
Added the ability to use TLS when connecting to a database.

### PR DESCRIPTION
**Pull request by myuzhobcplidtkieno**
**Changes proposed:**

-  Added the ability to use TLS when connecting to a database.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

Built and tested connections via TLS to an external database.

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by jackpoz** [comment]
could you please do a test without the "ssl" option too ?

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by kuskmen** [comment]
@jackpoz , @myuzhobcplidtkieno on my first setup of trinityCore I get

```
Error: identifier "MYSQL_OPT_SSL_ENFORCE" is undefined	Porject: database	File: MySQLConnection.cpp	Line: 150	
```
Am I doing something wrong?

**Comment by Killyana** [comment]
Update MySQL ≥ 5.7

**Comment by kuskmen** [comment]
In this case maybe you need to change Windows Requirements, because it says we should download MySQL 5.6.xx version

**Comment by Aokromes** [comment]
requirements where updated before you posted that error.

**Comment by kuskmen** [comment]
@Aokromes , I am sorry, now I saw it says >= 5.7 at the top, maybe we need to change it at step 3 as well?

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977296/Windows+Requirements

**Comment by illfated** [comment]
Done.

**Pull request merged**
