### PR TITLE
Scripts/Pets: Mojo

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Move script to SAI.

**Target branch(es):** 3.3.5

~**Issues addressed:**~

**Tests performed:** Works fine

~**Known issues and TODO list:**~

### CODE REVIEW

**Comment by Killyana** [comment]
Looks fine

**Comment by illfated** [comment]
Cosmetic tip: Use double quote characters to surround the entire text line in SQL to skip backslash escape character before single quotes around parts of the text line.

**Comment by Sorikoff** [comment]
@Killyana, are you sure this pet works only in raid/party? I can't find info about this.

**Comment by Killyana** [comment]
The original cpp, has this condition, I don't know how it work in retail, probably mustn't respond to the opposite faction emotes?

**Comment by Sorikoff** [comment]
Yeah, I see now. I guess it can't be handled by SAI then? (need a way to run SAI only if Horde/Alliance player)

**Comment by illfated** [comment]
SourceTypeOrReferenceId | ID | SourceGroup | SourceEntry | SourceId | ConditionTarget | Notes
-- | -- | -- | -- | -- | -- | --
CONDITION_SOURCE_TYPE_SMART_EVENT | 22 | ID (smart_scripts.id)+1 | EntryOrGuid (smart_scripts.entryorguid) | SourceType (smart_scripts.source_type) | 0 = Invoker <br> 1 = Object |  


ConditionTypeOrReference (name) | Value | ConditionValue1 | ConditionValue2 | ConditionValue3
-- | -- | -- | -- | --
CONDITION_TEAM | 6 | Team id :Alliance = 469 / Horde = 67 | Always 0 | Always 0

**Comment by Sorikoff** [comment]
But this does not allow to check for owner.

**Comment by illfated** [comment]
Oh. Right. I forgot about that part. Not sure if that condition exists.

**Comment by illfated** [comment]
Not sure, but maybe this needs a combined condition, like in the CPP, combining at 2 or 3 conditions. Maybe this condition info could be useful, although I haven't tried to convert it to SQL:


ConditionTypeOrReference (name) | Value | ConditionValue1 | ConditionValue2 | ConditionValue3
-- | -- | -- | -- | --
CONDITION_RELATION_TO | 33 | Target to which relation is checked.- one of the ConditionTargets available in current SourceType | RelationType - defines relation of current ConditionTarget to target specified in ConditionValue1.<br><br>0 - RELATION_SELF<br>1 - RELATION_IN_PARTY<br>2 - RELATION_IN_RAID_OR_PARTY<br>3 - RELATION_OWNED_BY (ConditionTarget is owned by ConditionValue1)<br>4 - RELATION_PASSENGER_OF (ConditionTarget is passenger of ConditionValue1)<br>5 - RELATION_CREATED_BY (ConditionTarget is summoned by ConditionValue1) | Always 0

**Comment by Killyana** [comment]
@Sorikoff the condition I did will make the pet respond only to the owner or players party. It works fine.

**Comment by illfated** [comment]
Thank you for clearing up that misunderstanding. Sorry for causing confusion.
Just to sum it up, the SQL can look something like this:
```sql
-- Mojo
UPDATE `creature_template` SET `AIName`='SmartAI',`ScriptName`='' WHERE `entry`=24480;

DELETE FROM `smart_scripts` WHERE `entryorguid`=24480 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(24480,0,0,1,22,0,100,0,58,15000,15000,0,1,0,1,0,0,0,0,7,0,0,0,0,0,0,0,'Mojo - On Emote Received - Say Line 0'),
(24480,0,1,2,61,0,100,0, 0, 0, 0, 0,11,43906,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mojo - Linked Event - Cast 'Feeling Froggy'"),
(24480,0,2,0,61,0,100,0, 0, 0, 0, 0,11,43919,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mojo - Linked Event - Cast 'Feeling Froggy'");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry` IN (24480) AND `SourceGroup`=1;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(22, 1, 24480, 0, 0, 33, 0, 1, 2, 0, 0, 0, 0, "", "SAI triggers only if player in raid or party");
```

**Comment by Sorikoff** [comment]
Now I see. Thanks for help!

**Review by ghost — APPROVED** [review]

**Comment by illfated** [comment]
Just out of curiosity, do you prefer using the escape character ( `\` ) along with single quotes ( ' ' ) in SQL, as compared to double quotes " " around the text? I don't remember which one is recommended, but both methods do the same job. I guess it is more a matter of taste and which school of SQL you adhere to.

**Comment by jackpoz** [comment]
is this ready to be merged ?

**Comment by illfated** [comment]
Pretty much, Killyana has verified the SQL content.

**Comment by Sorikoff** [comment]
@illfated, on this project I prefer first option for some reason, but again, there is no actual difference as you noted. And TC wiki links to 404 SQL rules (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130055/How-to).

@jackpoz, yes.

**Comment by illfated** [comment]
Thank you for those details. Confirmed, TC SQL guideline page link is broken (404).

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
