### PR TITLE
New Vehicle seat flag B - Copy vehicle animations

### PR DESCRIPTION
**Pull request by Smerdokryl**
**Changes proposed:**

-  Added new flag to VehicleSeatFlagsB

**Target branch(es):**

- [x] master

**Tests performed:**

Builds, tested ingame

### CODE REVIEW

**Comment by msoky** [comment]
can anyone check if this is correct and can be merged? this PR waiting for 8 months only with one row change...

**Comment by MaxtorCoder** [comment]
> can anyone check if this is correct and can be merged? this PR waiting for 8 months only with one row change...

Iirc we don't merge UNK flags.

**Comment by msoky** [comment]
> > can anyone check if this is correct and can be merged? this PR waiting for 8 months only with one row change...
> 
> Iirc we don't merge UNK flags.

so this PR will be closed because it is useless?

**Comment by MaxtorCoder** [comment]
> > > can anyone check if this is correct and can be merged? this PR waiting for 8 months only with one row change...
> > 
> > Iirc we don't merge UNK flags.
> 
> so this PR will be closed because it is useless?

Pretty much, yes.

**Comment by msoky** [comment]
@Shauren @jackpoz  could you check/close this?

**Comment by jackpoz** [comment]
@msoky I'm focused on 3.3.5 branch, not master

**Comment by msoky** [comment]
@Shauren could you look at this please? close or merge?

**Comment by Shauren** [comment]
this is correct

**Pull request closed without merging**
