### PR TITLE
Core/SpellEffects: Implement SPELL_EFFECT_SET_CHROMIE_TIME

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement effect 277 (SPELL_EFFECT_SET_CHROMIE_TIME)
- 
**Tests performed:**

Tested in-game

### CODE REVIEW

**Comment by mdX7** [comment]
i think the spelleffect is doing a bit more than just setting the updatefield

**Comment by Shauren** [comment]
Is this PR going to see more development? In current state it doesn't do anything useful

**Comment by funjoker** [comment]
Doesn’t this need also the implementation of contentuning replacement for chosen zone?

**Comment by MaxtorCoder** [comment]
> Doesn’t this need also the implementation of contentuning replacement for chosen zone?

Yes and it needs the starter quests for each expansion (this is fairly easy to do), the content tuning however, might be a bit more complicated, iirc you also move to the Chromie Time phase, works the same way with Warmode

**Comment by fluxurion** [comment]
When we select chromie time CTROptions ContentTuningConditionMask and ExpansionLevelMask updatefield does change too

**Comment by MaxtorCoder** [comment]
> When we select chromie time CTROptions ContentTuningConditionMask and ExpansionLevelMask updatefield does change too

Correct, ContentTuningConditionMask is for ContentTuning (as the name suggests) and ExpansionLevelMask comes from UiChromieTimeExpansionInfo.db2

**Comment by aquadeus** [comment]
oh i see is this right? 

[0] (CtrOptions) ContentTuningConditionMask: 5
[0] (CtrOptions) Field_4: 3
[0] (CtrOptions) ExpansionLevelMask: 32

**Comment by MaxtorCoder** [comment]
> oh i see is this right?
> 
> [0] (CtrOptions) ContentTuningConditionMask: 5 [0] (CtrOptions) Field_4: 3 [0] (CtrOptions) ExpansionLevelMask: 32

Yes, Field_4 is unused still, but both of those come from DB2 iirc.

**Comment by aquadeus** [comment]
could be that this effect only changes UiChromieTimeExpansionID and the opcode SMSG_CHROMIE_TIME_SELECT_EXPANSION_SUCCESS is the one which sends all the data from the db2, taking the value of the miscvalue selected?

**Comment by MaxtorCoder** [comment]
> could be that this effect only changes UiChromieTimeExpansionID and the opcode SMSG_CHROMIE_TIME_SELECT_EXPANSION_SUCCESS is the one which sends all the data from the db2, taking the value of the miscvalue selected?

No, `SMSG_CHROMIE_TIME_SELECT_EXPANSION_SUCCESS` is an empty packet, `CMSG_CHROMIE_TIME_SELECT_EXPANSION` has the UiChromieTimeExpansionInfo ID :)

**Comment by aquadeus** [comment]
> 

Ahh makes sense now, then ill go first with the opcode

**Comment by aquadeus** [comment]
yes the packets are very easy, only send guid and expansion fields

**Comment by MaxtorCoder** [comment]
> yes the packets are very easy, only send guid and expansion fields

Yessir!

**Pull request closed without merging**
