### PR TITLE
Core/Units: Update PlayHoverAnim state when flying or hovering

### PR DESCRIPTION
**Pull request by meji46**
**Changes proposed:**

-  Update PlayHoverAnim state when flying or hovering (related to https://github.com/TrinityCore/TrinityCore/pull/28208)

**Issues addressed:**
None

**Tests performed:**
Builds, tested in-game

**Known issues and TODO list:** (add/remove lines as needed)
None

### CODE REVIEW

**Comment by Ovahlord** [comment]
This is not correct to do this way because there are a ton of flying units which do not use hover anim at all and merely play flying animations by using the animTier value

**Comment by meji46** [comment]
> This is not correct to do this way because there are a ton of flying units which do not use hover anim at all and merely play flying animations by using the animTier value. Same applies for hovering. Both use animTiers which then also uses the HoverHeight update field. The hover animation opcode / bit field itself is almost exclusivey used for levitating auras or special cases.

As I told you in the other PR, the anthropomorphic creature models use this value to do the anim either while flying or hovering (AnimTier not involved). Besides, all flying creatures have the bit set to true (I've only found one special case for an invisible trigger with root).

I've given several examples for cases with/without auras:
https://github.com/TrinityCore/TrinityCore/pull/28208#issuecomment-1238631848

**Comment by CraftedRO** [comment]
maybe we'll get this merged this year

**Comment by Nyr97** [comment]
So this change means we won't ever use or allow SetPlayHoverAnim scripting-wise, the whole usability is left to SetDisableGravity and SetHover to decide.

**Pull request merged**
