### PR TITLE
Update cs_guild.cpp

### PR DESCRIPTION
**Pull request by JustZerooo**
You forget name check ...

**Changes proposed:**

-  Adding Guild Name Check (Valid Characters)
-  
-  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [X] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by jackpoz** [comment]
this looks like just missing https://github.com/TrinityCore/TrinityCore/commit/ae8750716f63ddc41f21bb38ceafe949d7260f0e cherrypick (PR https://github.com/TrinityCore/TrinityCore/pull/23201 )

**Comment by TheNeoTV** [comment]
but check was in and after a while removed hä`???

**Comment by Aokromes** [comment]
no yet cherry picked, master branch lags on cherry picks, and better follow the order.

**Comment by Shauren** [comment]
Indeed, this is in cherry-pick queue (current state is somewhere in 2017)

Either way, will not merge this one, I want cherry-picks to be done in order on master branch

**Comment by funjoker** [comment]
Soon being back from my vacation.

**Pull request closed without merging**
