### PR TITLE
Issue/20600 PR

### PR DESCRIPTION
**Pull request by kaldown**
a PR for https://github.com/TrinityCore/TrinityCore/issues/20600

### CODE REVIEW

**Comment by tkrokli** [comment]
This is a so-called "SQL only" fix, post it in a code block on the issue page itself.
Pull Requests are for C++ code or C++ files _and_ SQL together (not SQL alone).

**Comment by Aokromes** [comment]
Also, we don't change RewardFactionValue(x) without sniffs.

**Comment by kaldown** [comment]
@Aokromes what is "sniff" ?

**Comment by tkrokli** [comment]
- https://www.lifewire.com/introduction-to-packet-sniffing-2486803
- https://www.lifewire.com/what-is-a-packet-sniffer-2487312
- https://en.wikipedia.org/wiki/Packet_analyzer

**Comment by kaldown** [comment]
Yeap, thanks. I kinda understand what is sniff, but why you use this word for apply sql patch?
I mean, what are you going to sniff?
Maybe I can do that, but I don't know what to search for and how.
I tested a output after db changes, asked some questions in IRC and thought it would be enough to solve an issue.

**Comment by tkrokli** [comment]
What you need to do, if nobody has got that info already, is to use a trusted package sniffer (like the one on from TC forum pages) to produce sniffed packet data from when you hand in the quest on a retail server. Remember that there is a big amount of info packets received during game play, so you would need to limit the sniffer to singular interactions where you get the reputation change added to your character.

**Comment by kaldown** [comment]
But there is no retail wotlk now. I can only try to sniff on a legion.
But I still quite unsure why to do this, because people say that it must be 750 reputation.
If, accepting this quest. Character reputation truelly increase by 750 (which will be printed out) - so why then we need a sniffer?

**Comment by tkrokli** [comment]
Ask in the issue page. I usually follow what the owners ask of me, when dealing with requirements.

**Comment by Aokromes** [comment]
It's outdated but we never change wdb fields without sniffs, and RewardFactionValue is one of them.
https://community.trinitycore.org/topic/58-wdb-fields/

**Comment by tkrokli** [comment]
OK, I see. The columns used to be named `RewRepValue1` / `RewRepValue2` and `RewRepFaction2`.

**Pull request closed without merging**
