### PR TITLE
Core/Misc: Remove unneeded files

### PR DESCRIPTION
**Pull request by r4d1sh**
These 3 BlackRock Mountain scripts can be removed from source:
- boss_anubshiah.cpp
- boss_gorosh_the_dervish.cpp
- boss_grizzle.cpp

They already removed from the creatures in DB, and are currently causing DBErrors.

### CODE REVIEW

**Comment by tkrokli** [comment]
Suggestion for a description text, both here in this PR post and in the commit text (2 lines below title):
```
These 3 BlackRock Mountain scripts can be removed from source:

- boss_anubshiah.cpp
- boss_gorosh_the_dervish.cpp
- boss_grizzle.cpp

They already removed from the creatures in DB, and are currently causing DBErrors.

**Comment by Tonghost** [comment]
@tkrokli Thank you!

**Comment by jackpoz** [comment]
Thanks for the PR

**Comment by tkrokli** [comment]
Good job with the files, @Tonghost. Thank you for doing the work. :+1:

**Pull request merged**
