### PR TITLE
Core/WorldSession: Add RBAC permission for skipping idle connection c…

### PR DESCRIPTION
**Pull request by r4d1sh**
…heck

**Changes proposed:**

Add RBAC permission for skipping idle connection check. Players with this permission will not be kicked from server even if their clients didn't sendind anything for too long. This is useful for debugging

**Target branch(es):** 3.3.5

- [x] 3.3.5
- [ ] master

### CODE REVIEW

**Comment by tkrokli** [comment]
I presume you want to wait until this request gets some form of approval before adding any changes to `sql/base/auth_database.sql` because it may take some time before necessary feedback and comments are added. Or are you OK with adding those changes now so travis-ci will give you a green light?

**Comment by Tonghost** [comment]
I just forgot to do it. Now everithing should be fine.

**Comment by Keader** [comment]
debug now is a hell :/

**Comment by tkrokli** [comment]
@Keader : I don't get exactly what you refer to, do you mean before or after adding the PR content to your own source?

**Comment by Tonghost** [comment]
What about merge. my kittens?

**Comment by tkrokli** [comment]
This PR content is a new feature. I prefer that one of the TC members with more experience and more insight (into which consequences it could have for the source) to do the merge and perhaps also give some additional feedback before merging.

If you would like more instant feedback, try asking about this PR in the **#trinity** channel on **irc.rizon.net** (just remember to be patient when waiting for replies).

**Comment by Shauren** [comment]
What was the id 7 before it was marked "reuse"?

**Comment by Aokromes** [comment]
https://github.com/Tonghost/TrinityCore/commit/953575abfa631b9c58d8a8acc1fc8a37359f6fa6#diff-ff3b59d5f6fc8303cc01120ec5c190fcL57

**Comment by Shauren** [comment]
Ok, safe to reuse

**Pull request merged**
