### PR TITLE
 Scripts/HoO: Templeguardian Anhuur Changes

### PR DESCRIPTION
**Pull request by ghost**
*Temple Guardian Anhuurs Devine Reckoning will now target a random target instead of his victim
*Also his heroic version of Devine Reckoning will now heal Anhuur
*Reverberating Hymn will now get interrupted when Anhuur takes any damage when the shield of light is gone
*simplyfied the shield counter and damage check
*Implement the achievement 'I hate that Song'.

*possible todo: spell attribe usable_while_stunned may be required also for channeled spells to make the reverberating hymn work properly

### CODE REVIEW

**Comment by danlapps** [comment]
@NorthStrider is this a dead PR project ?

**Comment by NorthStrider** [comment]
I don't have the time for it to rework it again atm.
So if nobody else wanna fix the minor change recommendations it can be closed for now.

**Comment by DDuarte** [comment]
Let it open. We'll try to get this merged once 6.x sort of stabilizes.

**Comment by DDuarte** [comment]
TODO: Port to 6.x. (PR was closed automatically by a branch deletion.)

**Comment by Aokromes** [comment]
more than 1 year and still rooting. anyone can open a new pr for 6.x branch?

**Pull request closed without merging**
