### PR TITLE
Scripts/Ulduar: Fix Flame Leviathan movement

### LINKED ISSUE #24657: [3.3.5] Ulduar - Flame Leviathan: Movement
**Description:**

Seems when Flame Leviathan finish ACTION_MOVE_TO_CENTER_POSITION, it doesn't move anymore.

I do .npc info and appear:
```
React state: PASSIVE
```

maybe related with passive state?

**Expected behaviour:**

Should move

**Steps to reproduce the problem:**

1. Start encounter with Flame Leviathan
2. go away and see

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 2815db5

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Change MoveChase to AttackStart to allow movement

**Target branch(es):**

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #24657

**Tests performed:** tested in-game

### CODE REVIEW

**Comment by Keader** [comment]
If i remember right, he's passive because he use one spell to select and chase targets

**Comment by Jildor** [comment]
so why is set agressive here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp#L569
and defensive in reset:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp#L272
?

**Comment by jackpoz** [comment]
could you check https://github.com/TrinityCore/TrinityCore/issues/21265 and https://github.com/TrinityCore/TrinityCore/commit/b3e0c892385c7f75a061feef08c3ac05b53b4e2e to see if you can find any answer there ?

also please let me know when I can merge the PR

**Comment by Jildor** [comment]
React passive is added here: https://github.com/TrinityCore/TrinityCore/commit/7ec351a79d39458dac80e52db25cf7a7cc280c4f

I will focus only on the issue, maybe it should be like this about the react passive

you can merge whenever you want

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
