### PR TITLE
Core/PacketIO: Updated and enabled CMSG_TRANSMOGRIFY_ITEMS

### PR DESCRIPTION
**Pull request by opcod3**
Full transmogrification support working

### CODE REVIEW

**Comment by YaGa** [comment]
nice!

**Comment by Carbenium** [comment]
@Gigi1237: did you figure out a solution for the problem?

**Comment by Gigi1237** [comment]
@Carbenium nope. Haven't had much time to work on TC sadly...

**Comment by Aokromes** [comment]
We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.

**Pull request closed without merging**
