### PR TITLE
Core/Game: Write directly to UpdateData's ByteBuffer

### PR DESCRIPTION
**Pull request by Lordron**
**Changes proposed:**

-  Use ByteBuffer from UpdateData and write to it instead of copying to it after. 
-  
-  

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

Build, logged in

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
Are you sure this won't introduce any issues?

**Comment by Lordron** [comment]
Yes, AddUpdateBlock used to append ByteBuffer to the end of internal m_data. Now we just use it directly removing unneeded allocation and following copying.

**Comment by jackpoz** [comment]
is there any case where the buffer is supposed to be reused for different packets, like when sending similar information to different players ?

**Comment by Lordron** [comment]
Nope. Look previously it worked like this: 

1. Allocate an intermediate ByteBuffer
2. Write movement\updates to it
3. Append ByteBuffer to UpdateData::m_data in AddUpdateBlock
4. Append UpdateData::m_data to WorldPacket in BuildPacket

Now

1. Take the reference to UpdateData::m_data
2. Write movement\updates to it
3. Append UpdateData::m_data to WorldPacket in BuildPacket

Internal ByteBuffer (m_data) is never reused. 1 UpdateData allocated for 1 player. It could be reused and even with that these changes won't break anything

Possible places for reusing

1. [Move outside loop and clear](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp#L310)
2. [Move outside loop and clear](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Groups/Group.cpp#L514)
3. [Move outside loop and clear](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/Map.cpp#L698)

**Pull request merged**
