### PR TITLE
Core/Spell: Jump Speed Calculations

### LINKED ISSUE #565: Deathgrip ("Missle Speed")
Deathgrip should pull players much faster than it currently does.
Right now it almost pulls players in slow motion and they seem to "parachute" in the air during the spell and often times disappear briefly before reaching final destination.

Should not be effected by player to player latency?
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/66535-deathgrip-missle-speed?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by DanVS**
**Changes proposed:**
Partially implement #22547. Rework is required for proper implementation (SpeedZ and SpeedXY), so I think that right now we could make at least first step to the right direction.
Credit @xvwyh.

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #565

**Tests performed:** Works with Death Grip.

### CODE REVIEW

**Comment by Ovahlord** [comment]
It is correct. 4.x contains many spells like Heroic Leap that are perfectly synch when using the speed value.

**Comment by xvwyh** [comment]
The previous message was written before I could see the edits, thanks, github.
Spell batching? Sure, you can use it as a counterargument. Heroic Leap was changed in MoP already, so newer expansions are meaningless as proofs. In that case I can only convince you with cata sniffs, of which I, sadly, have none, only MoP. But doesn't TC have a storage of sniffs on their forum? It's write-only, so I can't know if they even have cata sniffs, but if they do - would be nice to see them as a final say in this discussion. What we care about is seeing the SMSG_MONSTER_MOVE packet from Heroic Leap. We can use movement distance and duration to calculate speed. If it will turn out to be ~50 - I'm right, if around ~35 - you are. Spell's speed afaik can't be influenced by anything, it's not even sent in packets, so it's gonna have to be 35 no matter what.

**Comment by xvwyh** [comment]
Alright, here's one. Not Heroic Leap and not from cata, but from MoP build 18414. Spinning Pain Spike (66281) is also a spell with SPELL_EFFECT_JUMP_DEST (0.4 multiplier) and spell missile speed (20 yards/sec), so basically the same as Heroic Leap, with the only difference being the lack of SPELL_EFFECT_TRIGGER_MISSILE effect. Neither spell's speed, nor effects have changed since WotLK till MoP.

```
ServerToClient: SMSG_UPDATE_OBJECT (0x1792) Length: 936 ConnIdx: 2 Time: 08/30/2014 16:17:16.703 Number: 18393
Map: 649
Count: 4
(...)
[3] UpdateType: CreateObject2
[3] GUID: Full: XXX Type: Vehicle Entry: 34826 (Mistress of Pain) Low: XXX
[3] Object Type: Unit (3)
[3] bit676: False
[3] Has Anim Kits: False
[3] Is Living: True
[3] bit810: False
[3] Transport Frames Count: 0
[3] Has Vehicle Data: True
[3] bit1044: False
[3] bit476: False
[3] Has GameObject Rotation: False
[3] bit680: False
[3] Has Attacking Target: False
[3] Has Scene Object Data: False
[3] bit1064: False
[3] bit668: False
[3] Has Transport Position: False
[3] bit681: False
[3] Has Stationary Position: False
[3] Has Pitch: True
[3] Has Transport Data: False
[3] bits98: 0
[3] Has SplineElevation: True
[3] Has SplineData: False
[3] Extra Movement Flags: PreventStrafe, PreventJumping, DisableCollision, FullSpeedTurning (15)
[3] Fly Speed: 7
[3] Turn Speed: 3.141593
[3] Time?: 655381898
[3] Swim Speed: 4.5
[3] Pitch Speed: 3.141593
[3] Orientation: 2.122008
[3] Walk Speed: 7
[3] Fly Back Speed: 4.5
[3] Run Back Speed: 2.5
[3] Run Speed: 14
[3] Swim Back Speed: 4.72222
[3] Position: X: 528.9659 Y: 121.6318 Z: 394.8119
[3] Vehicle Id: 446
[3] Vehicle Orientation: 2.122008

(...there were no speed change packets in-between...)

ServerToClient: SMSG_ON_MONSTER_MOVE (0x1A07) Length: 68 ConnIdx: 2 Time: 08/30/2014 16:17:37.000 Number: 19780
Move Ticks: 32212
Float12: 0
Float13: 0
Float11: 0
bit56: False
[0] Spline Waypoint: X: 554.4636 Y: 117.7875 Z: 394.4944
Float21: 250.7997
Spline Flags: Done, AnimationTier, Transport, Unknown7 (44040448)
Move Time: 893
Owner GUID: Full: XXX Type: Vehicle Entry: 34826 (Mistress of Pain) Low: XXX
GUID2: 0x0
Position: X: 566.4191 Y: 108.7285 Z: 394.4713

ServerToClient: SMSG_SPELL_GO (0x09D8) Length: 86 ConnIdx: 2 Time: 08/30/2014 16:17:37.000 Number: 19781
Target Flags: Unit, SourceLocation, DestinationLocation (98)
[0] Guid8: Full: XXX Type: Vehicle Entry: 34826 (Mistress of Pain) Low: XXX
Int50: 655402187
Position: X: 554.4636 Y: 117.7875 Z: 394.4944
DestLocationTargetGUID: 0x0
Cast Flags: PendingCast, Unknown2, Unknown7, Unknown8, Unknown12 (17157)
Position: X: 566.4191 Y: 108.7285 Z: 394.4713
SourceLocationTargetGUID: 0x0
Byte1A0: 1
CastCount: 0
Spell ID: Spinning Pain Spike (66281)
casterUnitGUID: Full: XXX Type: Vehicle Entry: 34826 (Mistress of Pain) Low: XXX
CasterGUID: Full: XXX Type: Vehicle Entry: 34826 (Mistress of Pain) Low: XXX
targetGUID: 0x0
ItemTargetGUID: 0x0
UnkGUID: 0x0
```

Run Speed: 14 yards/sec
From: X: 566.4191 Y: 108.7285 Z: 394.4713
To: X: 554.4636 Y: 117.7875 Z: 394.4944
Duration: 0.893 secs

Therefore...
Distance: 15 yards (matches the spell's effect radius)
Final jump speed: 15 / 0.893 = **16.7973** yards / sec
Already not the spell's speed, but let's continue.
Spell's value multiplier is 0.4. Therefore jump speed should be: 14 * 3 * 0.4 = **16.8**.

**Comment by DanVS** [comment]
I understand correctly, that currently the whole thing is wrong since calculations are not correct?

**Comment by xvwyh** [comment]
Nothing is wrong. Ovahlord is trying to claim something is wrong because he believes it is wrong without having any evidence to back up his claims, so far.

**Comment by Ovahlord** [comment]
@xvwyh I am back home in about a week. Once I can get my hands on my sniffs I'll dig myself into it. The answer can be found by comparing the spline duration of the move packet with the time stamps of the spell_start and spell_go packets.

**Comment by Sorikoff** [comment]
Any news?

**Comment by Wyrserth** [comment]
Can this be merged? Tested it, behavior is far closer to retail than the current implementation and it looks blizzlike to me. If there are remaining issues that can be proven then it can be done separately from this.

**Comment by jackpoz** [comment]
@xvwyh what has to be done instead to implement it the way you have in mind ?

**Comment by jackpoz** [comment]
Nvm, the PR is actually the "Easy Implementation" at https://github.com/TrinityCore/TrinityCore/issues/22547

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by xvwyh** [comment]
@jackpoz, lots and lost of changes everywhere. The entire paradigm of specifying "horizontal speed" (speedXY) and "vertical speed" (speedZ) everywhere where there needs to be a jump is wrong, blizzard specifies not vertical speed but desired jump height, not horizontal speed but a multiplier over the default run speed of the unit multiplied by 3. To adopt this properly would require a lot of changes to core scripts (going through every `GetMotionMaster()->*Jump*()` and manually replacing speeds with heights and multipliers), changes to SAI scripts (doing the same thing for all `SMART_ACTION_JUMP_TO_POS` uses). It's a lot of work that I doubt someone would take on.

**Pull request merged**
