### PR TITLE
Core/Packets: Add structure for CMSG_GM_TICKET_GET_CASE_STATUS, SMSG_GM_...

### PR DESCRIPTION
**Pull request by Carbenium**
...TICKET_CASE_STATUS, CMSG_GM_TICKET_ACKNOWLEDGE_SURVEY and SMSG_GM_TICKET_RESPONSE_ERROR

Implement CMSG_GM_TICKET_GET_TICKET and SMSG_GM_TICKET_GET_TICKET_RESPONSE
Update SMSG_FEATURE_SYSTEM_STATUS to support customizable ticket system and add config options

### CODE REVIEW

**Comment by Carbenium** [comment]
For debugging it can be helpful... And it doesn't hurt, if its there

**Comment by soulfrost** [comment]
logs for all packets allready implented in other place =/

**Comment by Carbenium** [comment]
Do you mean the PacketLogFile? If yes, I find it less troublesome to look at a console message instead of parsing the whole pkt file

**Comment by soulfrost** [comment]
no... i meen console logs

**Comment by Shauren** [comment]
That is correct, opcode names are logged for every sent/received packet
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/WorldSocket.cpp#L221 (received)
and
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/WorldSocket.cpp#L346 (sent)

**Comment by DDuarte** [comment]
6751ac2 and 74f577e

**Pull request closed without merging**
