### PR TITLE
Game/Entities: Teleport Units with AI to db-spawnlocation on respawn

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
**Changes proposed:**

-  Teleport Units with AI to db-spawn location on respawn

**Target branch(es):** 3.3.5/master

- [X] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
- https://github.com/TrinityCore/TrinityCore/issues/17568
- https://github.com/TrinityCore/TrinityCore/issues/18739
- https://github.com/TrinityCore/TrinityCore/issues/16915

**Tests performed:** (Does it build, tested in-game, etc.)
yes and yes

**Known issues and TODO list:** (add/remove lines as needed)
- I know this code is wrong and it's a hack. anyway this PR is a good way to make core devs think about the real reason of the issue. I don't know what causes the issue and i don't know how to fix it propperly, but it breaks around 150 scripts ingame.

### CODE REVIEW

**Comment by Ovahlord** [comment]
I dunno if this is a proper solution for that issue since it appears that Blizz is creating entirely new creatures instead of recycling the old ones.

**Comment by Rushor** [comment]
yea but that's a complete different issue

**Comment by streetrat** [comment]
i think setposition or what is it called would be enough before adding the unit to the map, so it won't trigger any teleport packets

**Comment by Rushor** [comment]
no setposition in respawn is also a hack, we need to find the reason in core why the creatures respawns on despawnposition

**Comment by Rushor** [comment]
and btw @streetrat would you like to look at https://github.com/TrinityCore/TrinityCore/issues/18865 and discuss a bit about it (i think it's not that huge amount of changes that need to be done in core)

**Comment by Rushor** [comment]
and yea tried it with

```c++
        float x, y, z, o;
        GetRespawnPosition(x, y, z, &o);
        SetPosition(x, y, z, o);
```

result: same issue as without the addition

**Comment by jackpoz** [comment]
> I don't know what causes the issue and i don't know how to fix it propperly

take your time to debug the respawn and see why it respawns in the wrong place. you can post your findings on the issue so others can contribute to the discussion too.

**Comment by Rushor** [comment]
@jackpoz 

@BAndysc already found the reason. pls give a skilled comment to it https://github.com/TrinityCore/TrinityCore/issues/17568#issuecomment-272994471 ty

**Pull request closed without merging**
