### PR TITLE
[SQL] pvpstats_players allow to accept uint32

### PR DESCRIPTION
**Pull request by Palabola**
**Changes proposed:**

-  
-  
-  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Shauren — CHANGES_REQUESTED** [review]
All mediumints in that table should be ints

**Comment by Aokromes** [comment]
sql only changes must be tickets, not prs.

**Comment by illfated** [comment]
Yes, TC does not use Pull Requests for SQL-only solutions.

**Comment by Palabola** [comment]
Full SQL update commited.

**Review by Shauren — APPROVED** [review]

**Comment by Shauren** [comment]
To everyone commenting how sql only prs are bad - I am willing to make exceptions for structure changes

**Pull request merged**
