### PR TITLE
Core/Spells: Fix Power Word: Shield (Priest) absorb amount

### LINKED ISSUE #22090: [3.3.5] Priest: Power Word: Shield
**Description:**

ID - 17 Power Word: Shield (Rank 1)
spell_pri_power_word_shield
https://github.com/TrinityCore/TrinityCore/blob/16f524ff2537646417d1150ef3bdab8e4cc8a2b1/src/server/scripts/Spells/spell_priest.cpp#L1021-L1022

This part of absorb script is wrong, because Focused Power isn't the only one that has this effect (SPELL_AURA_MOD_HEALING_DONE_PERCENT).

By example, Power Word: Shield is affected by ICC buff (the result is correct, but ICC buff should be fixed (https://github.com/TrinityCore/TrinityCore/issues/21415))
And maybe another auras with SPELL_AURA_MOD_HEALING_DONE_PERCENT are affecting, so this script need a better check.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 98fd8d4c7489 2018-06-15 12:56:33 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on:
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/335/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/trinity/data/335/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /home/trinity/data/335/data/mmaps. Total size: 2152621156 bytes
Using esES DBC Locale as default. All available DBC locales: esES
Using World DB: TDB 335.64

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Modify absorb amount in PW:Shield script, shouldn't be modified by all SPELL_AURA_MOD_HEALING_DONE_PERCENT auras (explained here: #22090)

PW:shield should be affected by Focused Power and Arena/Battleground - Dampening:
https://wowwiki.fandom.com/wiki/Power_Word:_Shield?oldid=2365404
```
Focused Power increases the amount absorbed by the shield.

Hotfix (2010-02-05): "The amount of damage being absorbed by Sacred Shield and Power Word: Shield is being reduced by 10% correctly in only battlegrounds, Arenas, and Wintergrasp."
```
But actually after this commit: https://github.com/TrinityCore/TrinityCore/commit/e672793a3cb6aae03cfea6cea68bbf0acb3cb4fc
Can be modified by spells like:
priest Blessed Resilience and it shouldn't:
https://www.wowhead.com/forums&topic=134352.2#p1658132

```
Effect = Heal
Spiritual Healing - Healing
Blessed Resilience - Healing
Test of Faith - Healing
NON OF THESE TALENTS INCREASE ABSORBTION OF POWER WORD: SHIELD, ONLY THE GLYPH
```
and others

Should be affected by ICC buff, but, as I explain in the issue: #22090
I don't know how want fix this @ariel- ( #21415 )

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #22090

**Tests performed:** Tested in-game

### CODE REVIEW

**Comment by illfated** [comment]
👍 Thank you for this contribution, it looks clean and well made (even if I am unable to see the direct implications in the coding).

**Comment by Keader** [comment]
Why not include ICC buff on it?
Will be need anyway right?

**Comment by Jildor** [comment]
I can, but is the right implementation? Maybe need do a generic implementación for ICC buff, but I don't know what spells need increase absorb effect with ICC buff.

if I should include ICC buff for priest power word:shield spell script by the moment, please tell me ;)

**Comment by Keader** [comment]
Well, if ariel know a best way to fix it, he will do when back.
Right now, to me, looks the best way to handle with it.

**Pull request merged**
