### PR TITLE
Core/Creatures: Added possibility to set PlayHoverAnim state on spawn

### PR DESCRIPTION
**Pull request by meji46**
**Changes proposed:**

-  Added a new field **PlayHoverAnim**  in the table **creature(_template)_addon** to control this state
- Extended function **SetPlayHoverAnim** to avoid sending SMSG_SET_PLAY_HOVER_ANIM in case of spawning

**Issues addressed:**
None

**Tests performed:**
Builds, tested in-game.

**Known issues and TODO list:** (add/remove lines as needed)

- I'm not sure if the functions **Set*AnimKitId** should also be extended to not send **SMSG_SET_*_ANIM_KIT** in case of spawning

### CODE REVIEW

**Comment by Ovahlord** [comment]
Just set the anim tier value in the bytes column. The play hover anim opcode is only used to update hover states between update object packets. In other words: the PR adds nothing that's already supported.

**Comment by meji46** [comment]
> Just set the anim tier value in the bytes column. The play hover anim opcode is only used to update hover states between update object packets. In other words: the PR adds nothing that's already supported.

That's not true. The opcode is used to update the hover state as you say but this PR doesn't cover the update. This covers creatures that are always using the hover state.

PlayHoverAnim allows ground creatures to use hovering animation (and no, AnimTier::Hover doesn't force this animation).
WoWScrnShot_082122_203407

**Comment by Shauren** [comment]
Is there a creature that has hover but does not set playhoveranim?

**Comment by meji46** [comment]
> Is there a creature that has hover but does not set playhoveranim?

I don't think so (that's what I tried to do here https://github.com/TrinityCore/TrinityCore/pull/27352). But there are flying creatures that have PlayHoverAnim set to true or false

```
[50] Object Guid: Full: 0x20424042403D9980000229000044F902 Creature/0 R4240/S553 Map: 530 (Outland) Entry: 63078 (Flutters) Low: 4520194
[50] Object Type: 5 (Unit)
[50] PlayHoverAnim: True
[50] MovementFlags: 268435456 (Hover)

[0] Object Guid: Full: 0x2042404240112080000229000044F902 Creature/0 R4240/S553 Map: 530 (Outland) Entry: 17538 (O'ros) Low: 4520194
[0] Object Type: 5 (Unit)
[0] PlayHoverAnim: True
[0] MovementFlags: 1536 (DisableGravity, Root)

[180] Object Guid: Full: 0x2042640000946040000015000044E6A4 Creature/0 R4249/S21 Map: 0 (Eastern Kingdoms) Entry: 151937 (Portal Controller) Low: 4515492
[180] Object Type: 5 (Unit)
[180] PlayHoverAnim: False
[180] MovementFlags: 1536 (DisableGravity, Root)

[69] Object Guid: Full: 0x2042640000332E00000015000044E6AA Creature/0 R4249/S21 Map: 0 (Eastern Kingdoms) Entry: 52408 (Coridormi) Low: 4515498
[69] Object Type: 5 (Unit)
[69] PlayHoverAnim: True
[69] MovementFlags: 268435968 (DisableGravity, Hover)

[111] Object Guid: Full: 0x20426400001FC200000015000044E6A2 Creature/0 R4249/S21 Map: 0 (Eastern Kingdoms) Entry: 32520 (Totally Generic Bunny (All Phase)) Low: 4515490
[111] Object Type: 5 (Unit)
[111] PlayHoverAnim: True
[111] MovementFlags: 512 (DisableGravity)
```

**Comment by CraftedRO** [comment]
One more example:
> [16] Object Guid: Map: 530 (Outland) Entry: 19152 (Interrogator Khan)
> [15] AnimTier: 0
> [16] PlayHoverAnim: True

**Comment by CraftedRO** [comment]
One more example:
> [16] Object Guid: Map: 530 (Outland) Entry: 19152 (Interrogator Khan)
> [15] AnimTier: 0
> [16] PlayHoverAnim: True
> [16] MovementFlags: 512 (DisableGravity)

**Comment by CraftedRO** [comment]
another one:
[15] Object Guid: Map: 571 (Northrend) Entry: 26471 (Image of Archmage Aethas Sunreaver)
[15] AnimTier: 0
[15] PlayHoverAnim: True
[15] MovementFlags: 1536 (DisableGravity, Root)

**Comment by meji46** [comment]
https://github.com/TrinityCore/TrinityCore/pull/29434

**Pull request closed without merging**
