### PR TITLE
ConnectionPatcher Change CDN host

### PR DESCRIPTION
**Pull request by funjoker**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Add Patching of CDN adress

**Target branch(es):** 3.3.5/master

- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
No issue number. Blizzard removes the remote configs in future.
To prevent it to break game we cahnge it to own adress

**Tests performed:** (Does it build, tested in-game, etc.)

### CODE REVIEW

**Comment by funjoker** [comment]
Do not merge now :D

**Comment by funjoker** [comment]
Okay. Can be merged. Need to change CDNs in file later, when trinity-root.org works

**Comment by Aokromes** [comment]
sync with head to remove travis' complain.

**Comment by funjoker** [comment]
If somone needs this feature just look into PR.
Otherwise it's unimportant as long data is at Blizz CDN

**Pull request closed without merging**
