### PR TITLE
Update 2016_04_24_00_hotfixes.sql

### PR DESCRIPTION
**Pull request by bragib**
**Changes proposed**:
## 
## 
- 

**Target branch(es)**: 335/6x

**Issues addressed**: Fixes #

**Tests performed**: (Does it build, tested in-game, etc)

**Known issues and TODO list**:
- [ ] 
- [ ]

### CODE REVIEW

**Comment by Aokromes** [comment]
whut?

**Comment by bragib** [comment]
[Err] 1054 - Unknown column 'Unknown620' in 'creature_display_info'
[Err] ALTER TABLE `creature_display_info` CHANGE `Unknown620` `PlayerModelScale` float NOT NULL DEFAULT '0';
[Msg] Finished - Unsuccessfully

**Comment by Aokromes** [comment]
Update your core.

**Comment by bragib** [comment]
Updated to the last Comit

**Comment by tkrokli** [comment]
You must be trying to re-apply the SQL file after the column has been renamed already.
Also, it is useless to suggest to revert a column name change that has already been decided by TC.

Before I have applied /sql/updates/hotfixes/6.x/2016_04_24_00_hotfixes.sql to my DB, the column name is still `Unknown620` so the existing TC SQL update will work as intended for me.
```sql
SELECT * FROM `hotfixes`.`creature_display_info`;
```
```
    ID  ModelID  SoundID  ExtendedDisplayInfoID  CreatureModelScale  Unknown620  CreatureModelAlpha  TextureVariation1  TextureVariation2  TextureVariation3  PortraitTextureName  PortraitCreatureDisplayInfoID  SizeClass  BloodID  NPCSoundID  ParticleColorID  CreatureGeosetData  ObjectEffectPackageID  AnimReplacementSetID   Flags  Gender  StateSpellVisualKitID  VerifiedBuild  
------  -------  -------  ---------------------  ------------------  ----------  ------------------  -----------------  -----------------  -----------------  -------------------  -----------------------------  ---------  -------  ----------  ---------------  ------------------  ---------------------  --------------------  ------  ------  ---------------------  ---------------
```
(I only pasted the column headers to prove my point)

To solve your issue, you can empty or drop your hotfixes DB and let Worldserver rebuild it from scratch.

**Pull request closed without merging**
