### PR TITLE
GameObjects/CapturePoints

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

-  Add a generic script for capture points. The ones in seething shore behave differently and should have different script
-  Add SMSG_UPDATE_CAPTURE_POINT
-  Also added new Arathi Battleground for testing of this pr

**Target branch(es):**

- master

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

- Builds
- Queued for new aratahi and clicked on the flags

**Known issues and TODO list:**

- [x] The gameobject is still clickable by the owning faction
- [x] I don't know how to handle the other cases like seething shore azerite. Seems like that one is handled a bit differently.
- [x] https://github.com/TrinityCore/TrinityCore/pull/27041

SQL:
```sql
-- New Arathi Basin
DELETE FROM `battleground_template` WHERE `id` = 1018;
INSERT INTO `battleground_template` (`id`, `AllianceStartLoc`, `HordeStartLoc`, `Weight`, `Comment`) VALUES
(1018, 7056, 7055, 1, 'Arathi Basin');

-- Some spawns
SET @OGUID := 900000;
DELETE FROM `gameobject` WHERE `guid` BETWEEN @OGUID+0 AND @OGUID+4;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `PhaseId`, `PhaseGroup`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(@OGUID+0, 227420, 2107, 10053, 10518, 0, 0, 0, 1166.85595703125, 1200.12158203125, -56.3867416381835937, 0.886092901229858398, 0, 0, 0.428693771362304687, 0.903449833393096923, 7200, 255, 1, 40120), -- Capture Point (Area: -Unknown- - Difficulty: 0)
(@OGUID+1, 227536, 2107, 10053, 10518, 0, 0, 0, 806.25, 874.279541015625, -56.5307502746582031, 0.818242669105529785, 0, 0, 0.397803306579589843, 0.917470753192901611, 7200, 255, 1, 40120), -- Capture Point (Area: -Unknown- - Difficulty: 0)
(@OGUID+2, 227522, 2107, 10053, 10518, 0, 0, 0, 977.50518798828125, 1051.0728759765625, -44.7925682067871093, 0.497109025716781616, 0, 0, 0.246003150939941406, 0.969269037246704101, 7200, 255, 1, 40120), -- Capture Point (Area: -Unknown- - Difficulty: 0)
(@OGUID+3, 227538, 2107, 10053, 10518, 0, 0, 0, 1146.9288330078125, 848.2274169921875, -110.917579650878906, 2.417101383209228515, 0, 0, 0.935103416442871093, 0.354374974966049194, 7200, 255, 1, 40120), -- Capture Point (Area: -Unknown- - Difficulty: 0)
(@OGUID+4, 227544, 2107, 10053, 10518, 0, 0, 0, 856.8663330078125, 1150.2135009765625, 11.04314804077148437, 0.989707827568054199, 0, 0, 0.474903106689453125, 0.880038082599639892, 7200, 255, 1, 40120); -- Capture Point (Area: -Unknown- - Difficulty: 0)

```

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
> Why is this a script and not native GameObject code? You can store all the type-specific values in `m_goValue`

Ah, that is what felt weird to me.

**Comment by Golrag** [comment]
I had no idea about m_goValue, i'll take a look at that

**Comment by Golrag** [comment]
This PR is still a draft because some things need to be figured out:
- Handle the seething shore capture points correctly
- Not sure about updating the dynamic flags like that, maybe there is a more proper way to do it. (Is there a  "trigger dynamic flags update now" function?)

Would be great to get some opinions on how to solve those tasks :)

**Comment by Shauren** [comment]
To force update dynamic flags you have to do what `Player::UpdateForQuestWorldObjects` does using `MarkChanged`

**Comment by Golrag** [comment]
Okay. So what would be the better approach to select the list of players affected by the capture point state change?
- Get a list of players in the whole map
- Get a list of players in the battleground
- Get a list of players that only have the gameobject in question in their m_clientGUIDs. I think this would be the better one but I'm not sure on how to achieve this

**Comment by Shauren** [comment]
visit grid in `visibility_range_radius` (from capture point as center)

**Comment by Golrag** [comment]
I think https://github.com/TrinityCore/TrinityCore/pull/27034/commits/7a66dba0caf7ee89c005129a3b52eb9a78044622 handles that case then

For the other issue with seething shore, I could try to check if the fields related to capturing are 0 etc, but maybe those should just have a script disabling default behavior?


```
+--------+---------+-------------+-------------+-----------+-----------+-------------------------+-------------------------+--------------------------+----------------------------+----------------------------+-----------------------------+-------------+---------------------+-------------------+--------------------+------------------------+----------------------+-----------------------+--------------+--------------+--------------+--------------+--------------+---------------+------------------------+
| entry  | name    | CaptureTime | GiganticAOI | highlight | open_lock | AssaultBroadcastHordeID | CaptureBroadcastHordeID | DefendedBroadcastHordeID | AssaultBroadcastAllianceID | CaptureBroadcastAllianceID | DefendedBroadcastAllianceID | worldState1 | ContestedEventHorde | CaptureEventHorde | DefendedEventHorde | ContestedEventAlliance | CaptureEventAlliance | DefendedEventAlliance | SpellVisual1 | SpellVisual2 | SpellVisual3 | SpellVisual4 | SpellVisual5 | SpawnVignette | InteractRadiusOverride |
+--------+---------+-------------+-------------+-----------+-----------+-------------------------+-------------------------+--------------------------+----------------------------+----------------------------+-----------------------------+-------------+---------------------+-------------------+--------------------+------------------------+----------------------+-----------------------+--------------+--------------+--------------+--------------+--------------+---------------+------------------------+
| 272471 | Azerite |       60000 |           1 |         1 |      2825 |                  134113 |                       0 |                        0 |                     134114 |                          0 |                           0 |           0 |                   0 |                 0 |                  0 |                      0 |                    0 |                     0 |        68590 |            0 |            0 |            0 |            0 |          2405 |                      0 |
| 281306 | Azerite |       60000 |           1 |         1 |      2825 |                  134113 |                       0 |                        0 |                     134114 |                          0 |                           0 |           0 |                   0 |                 0 |                  0 |                      0 |                    0 |                     0 |        68590 |            0 |            0 |            0 |            0 |          2405 |                      0 |
| 281307 | Azerite |       60000 |           1 |         1 |      2825 |                  134113 |                       0 |                        0 |                     134114 |                          0 |                           0 |           0 |                   0 |                 0 |                  0 |                      0 |                    0 |                     0 |        68590 |            0 |            0 |            0 |            0 |          2405 |                      0 |
+--------+---------+-------------+-------------+-----------+-----------+-------------------------+-------------------------+--------------------------+----------------------------+----------------------------+-----------------------------+-------------+---------------------+-------------------+--------------------+------------------------+----------------------+-----------------------+--------------+--------------+--------------+--------------+--------------+---------------+------------------------+
```

**Comment by Golrag** [comment]
I think it's okay for review now
A small thing I'm still considering: moving the capture point packets to game object instead of battleground

**Pull request merged**
