### PR TITLE
Might of Ursoc

### PR DESCRIPTION
**Pull request by ghost**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Set Health replaced on Set Health Percent.
-  
-  

**Target branch(es):** 3.3.5/master
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
Not issued.

**Tests performed:** (Does it build, tested in-game, etc.)
Should be working fine.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ] 

[//]: # (**DEPRECATION NOTICE** Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE** If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

Increment health pct for spell 105737.

``` SQL
-- spell_dru_might_of_ursoc
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dru_might_of_ursoc';
INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
(105737,'spell_dru_might_of_ursoc');
```

### CODE REVIEW

**Comment by Keader** [comment]
this sql part should be in a sql file.

**Comment by Unknown-1000** [comment]
@Keader you want say, what pull request better rebase?

**Comment by Keader** [comment]
Nop
Sql part that you put in pr description, should be in pr body (create one sql file, put in sql folder and push xD)

**Comment by Unknown-1000** [comment]
It's done!

**Comment by Unknown-1000** [comment]
It's done.
I think - in SpellAuraEffects.cpp fix more easy. No need scriptname and sql files XD.

**Comment by Keader** [comment]
Spellscript is more cleaner :)

**Comment by Ulduar** [comment]
@Keader spellscript It can handled by no means all.
``` CPP
ID - 165102 Вечная тьма
=================================================
Description: Чо'Галл окутывает тьмой случайно выбранного игрока, поглощая все получаемое им исцеление и превращая его в энергию энтропии. 

Когда "Вечная тьма" рассеивается, высвобождается энтропия. Этот эффект восстанавливает всем игрокам здоровье в размере поглощенного исцеления, поровну разделенного между ними.

ToolTip: Поглощение всего получаемого исцеления и превращение его в энергию энтропии.
Category = 0, SpellIconID = 173, activeIconID = 0, SpellVisual = (40709,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
AttributesEx1: 0x00000088 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_CANT_BE_REFLECTED)
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
AttributesEx3: 0x00000100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS)
AttributesEx8: 0x40001000 (SPELL_ATTR8_AURA_SEND_AMOUNT, SPELL_ATTR8_UNK30)
=================================================
MaxAffectedTargets: 3
Spell Level = 103, base 103, max 0

Category = 0
DispelType = 1 (DISPEL_MAGIC)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 16) = 1,50
Duration: ID (21)  -1, 0, -1
Interrupt Flags: 0x0000002D, AuraIF 0x00480000, ChannelIF 0x00000000
  Ex Target Aura Spell (165102) Вечная тьма
Chance = 0, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 301 (SPELL_AURA_SCHOOL_HEAL_ABSORB), value = 0, misc = 127 (127), miscB = 0, periodic = 0
Max Radius (Id 30) 500,00

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 25
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 239 (SPELL_AURA_MOD_SCALE_2), value = 25, misc = 0 (0), miscB = 0, periodic = 0
Max Radius (Id 30) 500,00
```
You can handle this spell in spellscripts?

**Comment by Keader** [comment]
i dont understand what you talking about...
btw 165102 is unrelated with this pr.

**Comment by Ulduar** [comment]
@Keader 
You can handle SPELL_AURA_SCHOOL_HEAL_ABSORB in spellscript?
165102 for example.

**Pull request closed without merging**
