### PR TITLE
[master] 3.3.5 -> master cherry-pick

### PR DESCRIPTION
**Pull request by funjoker**
**Changes proposed:**

-  Cherrypicking

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by funjoker** [comment]
@Shauren please take a deep look at 8e13ab676d9710da63d9e6eb726930e52c4c8b02

**Comment by funjoker** [comment]
CPs until end of March 2017.

Done with this CPs.
Continuing after this is merged

**Comment by funjoker** [comment]
5a1e059896164016c36b8b1851ef427a41396279 most important

**Comment by Shauren** [comment]
Something's not quite right...

obraz

**Pull request merged**
