### PR TITLE
Core/Player: Do not remove auras from Gamemasters in arenas

### PR DESCRIPTION
**Pull request by Gooyeth**
**Changes proposed:**

Avoid removing the auras of Game Master (affects the invisible aura of .gm visible off, for example)

**Target branch(es):** 3.3.5

**Tests performed:** Build & tested ingame

### CODE REVIEW

**Comment by ariel-** [comment]
Do note that even when the aura is removed, the serverside visibility is not modified (ie aura is only a 'visual' indicator of GM invisibility)

**Comment by Gooyeth** [comment]
@ariel-: Yes, I have it in mind, however I feel that the gms shouldn't be removed the auras

**Comment by Shauren** [comment]
Does that aura even do anything? description is something about transparency but I haven't noticed anything like that (is it even sent to client with all our stupid aura visibility checks?)

**Comment by Aokromes** [comment]
It was added to show gms they are on gm visible of mode it adds one small transparency to character.

**Comment by Jildor** [comment]
Info about transparency:
Commit: https://github.com/TrinityCore/TrinityCore/commit/c32c83ed67420a90e95f433a9d71febaefd2ecfd

Aura:
<details>

```
ID - 37800 Transparency (50%)
=================================================
Category = 0, SpellIconID = 331, activeIconID = 0, SpellVisual = (8739,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x24000100 (SPELL_ATTR0_HIDE_IN_COMBAT_LOG, SPELL_ATTR0_NEGATIVE_1, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x00000400 (SPELL_ATTR1_NO_THREAT)
AttributesEx3: 0x10000000 (SPELL_ATTR3_UNK28)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 13) "Anywhere":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 50000, MaxRangeFriendly = 50000

CastingTime (Id 1) = 0,00
Duration: ID (21)  -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT
```

</details>

**Comment by Keader** [comment]
I agree with this PR
Is very anoing lose auras when use .ap in someone in arena

**Comment by Gooyeth** [comment]
The idea is to keep the auras always, for possible tests or other situations before appearing in the arena.

**Comment by Shauren** [comment]
honestly, this falls into "whatever" category

**Pull request merged**
