### PR TITLE
Implement real time statistic visualization

### LINKED ISSUE #15075: [3.3.5][6.x] Implement real time statistic visualization in TrinityCore
### Software:
- https://influxdb.com/ Time-series oriented database
- http://grafana.org/ Dashboard/graphs visualization
- https://github.com/DDuarte/influxdb-cpp C++ InfluxDB driver (TODO)

Alternatives to InfluxDB: http://graphite.wikidot.com/ (also supported by Grafana)

#### Technical oriented
- I/O networking traffic:
    - Packets sent
    - Packets received
    - Average ping
    - Traffic in
    - Traffic out
- World session update time
- Map update time
- Database async queries queued count
- Server uptime
- Active connections
- Queued connections
- CPU usage
- RAM usage

#### Game oriented
- Players online (per faction)
- Logins per hour, per day, day of week, etc
- Mails sent
- Auction house usage
- Character levels
- Heatmap of players position
- Gold earn/spend
- LFG queues

### Notes / implementation details:
- Batch inserts to the DB (i.e keep X (10/100?) events in memory and then send them at once)
- This feature is absolutely optional and disabled by default
- Tracking code should have low impact in performance
- It should be possible to enable and disable statistic code at runtime (worldserver.conf + reloads)
- The data could be written at each world update loop or using asio at configurable intervals

### PR DESCRIPTION
**Pull request by DDuarte**
**Changes proposed**:

Provide a way to monitor a TrinityCore worldserver by writing metrics/statistics to an InfluxDB database and visualizing them in Grafana. This is a fully optional feature, disabled by default. Sample grafana dashboards are provided in the /contrib/grafana directory.

Tentative documentation is available at https://trinitycore.atlassian.net/wiki/display/tc/Monitoring+a+TrinityCore+server and more info can be found in https://github.com/TrinityCore/TrinityCore/issues/15075 and https://github.com/jackpoz/TrinityCore/issues/41.

This feature has been mostly implemented by jackpoz.

**Target branch(es)**: 335 and 6x (cp)

**Issues addressed**: Closes #15075

**Tests performed**:
- Ubuntu 15.10, InfluxDB 0.12.1, Grafana 3.0.0-beta3
- Windows 10, InfluxDB 0.9.4, Grafana 2.6.0

### CODE REVIEW

**Comment by jackpoz** [comment]
Even if enabled this whole Metrics system uses very little CPU thanks to data being sent async in batches to InfluxDB . Note altho that InfluxDB CPU usage can get quite high if Grafana keeps refreshing data, this is clearly out of scope; in a best-case scenario InfluxDB and Grafana will have their own dedicated server.

This PR looks very nice now with all the change history, it will be squashed just before merging.

**Comment by Nelidon** [comment]
Can you rebase the branch to have only few commits to port it on the 6.x branch easier?

**Comment by Warpten** [comment]
read "to have less commits to cherry-pick".

GitHub has a squash feature. This is unneeded

**Comment by jackpoz** [comment]
Grafana 3.0 Stable has been released with support to InfluxDB 0.11+ http://grafana.org/blog/2016/05/11/grafana-3-0-stable-released.html

**Comment by Aokromes** [comment]
No one looks to care about this :-1:

**Comment by jackpoz** [comment]
https://github.com/mvadu/influxdb/releases/tag/v0.13.0 influxdb 0.13 binaries for Win x64 are now available

**Comment by Kittnz** [comment]
So this can be merged? ^^

**Comment by jackpoz** [comment]
this PR has been ready to be merged since it was opened

**Comment by Kittnz** [comment]
Then merge it @jackpoz

**Comment by tkrokli** [comment]
When you merge, please please use the button option [Squash and merge] to avoid adding 63 commits to the base branch.

**Comment by jackpoz** [comment]
https://influxdata.com/blog/influxdb-1-0-beta-time-series-metrics-iot-real-time/ InfluxDB (and the whole TICK stack) 1.0 GA released with improvements suited for Grafana templated dashboards

**Comment by jackpoz** [comment]
http://grafana.org/blog/2016/07/12/grafana-3-1-released.html Grafana 3.1.0 released

**Comment by jackpoz** [comment]
https://www.influxdata.com/influxdb-1-1-released-with-up-to-60-performance-increase-and-new-query-functionality/ InfluxDB 1.1 release with Grafana specific improvements

**Comment by jackpoz** [comment]
http://grafana.org/blog/2017/01/11/grafana-4.1-release/ Grafana 4.1 Released

**Comment by Astraithious** [comment]
Hello! I am not really a programmer however I've taken quite the interest to this project as I love analytics and WoW. I am confused as to how to add more metrics however and was curious if anybody could give me a very detailed process of how it would be done.

As an example from **main.cpp**

    **LoadRealmInfo();

    sMetric->Initialize(realm.Name, *ioService, []()
    {
        TC_METRIC_VALUE("online_players", sWorld->GetPlayerCount());
    });**

Then I go look at the current how to 

**TC_METRIC_EVENT(category, title, description)
category: Arbitrary string, table where the values and events are stored. By convention, event logs should be suffixed by "_events";
title: Name of the event log;
description: Additional info about a log event;

TC_METRIC_VALUE(category, value)
category: Same as above;
value: A measurement, it can have one of the following types: bool, std::string, float, double or any integral type (int, int32, uint, etc).**

Does this mean it's placement location is the key? like in 

**603 | sScriptMgr->OnPlayerLogout(_player);
604 |  
605 | TC_METRIC_EVENT("player_events", "Logout", _player->GetName());**

So then this would capture the event because its right below it or is it there for convenience? 

The "logout" is the event log name and the "_player->GetName()" is the additional info according to the documentation but I don't quite understand where the placements should be and why.

Does this create its own logs from these triggers or does it copy data that is going to another log anyhow and convert it for influxdb? 

If somebody could give me any sort of explanation that would be amazing, I would share all the metrics I plan to implement as I am spending a lot of time on this as a part of a data analysis project since it interests me. 

Thank you for the time and likely patience! I hope to contribute to the community soon

**Comment by jackpoz** [comment]
TC_METRIC_EVENT is used to create InfluxDB annotations with TC_METRIC_EVENT("events", "World initialized", "World initialized in ...") one of the most clear examples. InfluxDB annotations can then be displayed on Grafana as vertical red line with a title and a description, see for example the red lines at https://cloud.githubusercontent.com/assets/1153754/13717165/07a0441e-e7e0-11e5-812e-924136f1f1be.jpg

TC_METRIC_VALUE is a single metric that can change value over time, with TC_METRIC_VALUE("online_players", sWorld->GetPlayerCount()) being an example. 

Events can be aggregated and counted by Grafana to display graphs like "how many players did login at the same moment ?".

The function sMetric->Initialize(...) accepts as last argument a lambda to be called at recurring time (config value Metric.OverallStatusInterval). This allows to keep sending some metrics every once in a while, like the number of online players.

The macros TC_METRIC_* queue InfluxDB data with the timestamp of when the macro gets called, where you put them in the code will affect only how close the timestamp will be to the actual event being logged. IMHO events should be logged after the event was fully processed.

I'd suggest to mess around a bit with the InfluxDB CLI and Grafana to get a closer understanding of they work. I found their documentation very helpful when implementing metrics in TC.

**Comment by Astraithious** [comment]
I have been looking through the documentation and I've been getting a better understanding but would you be able to give me an example of another one that isn't already made, I am currently trying to do something with character stats like levels but not entirely sure what part I should be getting it from, thank you for the previous reply though it did help me explore a bunch more

**Pull request merged**
