### PR TITLE
CI/GitHub: Add issue form for SQL fixes

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Add issue form for SQL fixes

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

None

**Tests performed:**

Tested at https://github.com/jackpoz/TrinityCore/issues/new/choose

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Comment by Faq** [comment]
My suggestion is add an examples for some points (link to correct sql commit, or just add in the issue text), so there anyone talks in same language and there are no misunderstandings.
Now it is like don't do that, or that, but after would be nice to see correct line how things should be done.

**Comment by offl** [comment]
That is something I'm thinking about but not sure if
> link to correct sql commit, or just add in the issue text

is the proper way to do it

**Comment by jackpoz** [comment]
@Faq right now I just copied the old template and pasted it as an issue form. It sounds good to have a reference example of correctly filled form, either with text or even just with a screenshot

**Comment by Faq** [comment]
Yeah the main idea is so there is not needed much explaining like for issue https://github.com/TrinityCore/TrinityCore/issues/26650#issuecomment-873396215 so any other reporter knows how it should be done.
True, it will look a bit like guide.

**Comment by jackpoz** [comment]
we could include a link to https://github.com/TrinityCore/TrinityCore/wiki with a page that we can update separately, with every information and step we want to give users

**Comment by jackpoz** [comment]
@Faq how about this ?
image

It points to https://github.com/TrinityCore/TrinityCore/wiki/SQL-Fix that can be modified without the need of PRs or commits or so

**Pull request merged**
