### PR TITLE
Scripts/Icecrown: Move Squire David to SmartAI

### PR DESCRIPTION
**Pull request by Carbenium**
Someone should check this (especially the spell target position).
Done that a while ago and I seem to recall that it worked.

### CODE REVIEW

**Comment by Killyana** [comment]
Spell (Id: 63026, effIndex: 0) listed in `spell_target_position` does not have target TARGET_DEST_DB (17).
I get the same problem with  http://wotlk.openwow.com/spell=63137 , impossible to use a target position https://github.com/TrinityCore/TrinityCore/issues/8718#issuecomment-100518249

**Comment by Carbenium** [comment]
Did you compile or just applied the sql?
Since with [this](https://github.com/Carbenium/TrinityCore/commit/881402ba3f6a1b38d772282d7680fa7f02c4fecd#diff-f82ab5d79483dd6e1f5bd8c4d94299d3R2957) the error message should disappear.

**Comment by Killyana** [comment]
Just applied the sql.

**Comment by Carbenium** [comment]
64bed16a5761ee98da5386575ae39f237a8721d3

**Pull request closed without merging**
