### PR TITLE
Add support for Catch2 as unit test framework

### PR DESCRIPTION
**Pull request by Carbenium**
**Changes proposed:**

-  Add catch2 as unit test framework which is called through ctest
-  Add some basic tests for EventMap

**How to run unit tests**:
 - Run CMake with `-DBUILD_TESTING=1`
 - Build tests with `make all` or `make tests-common`
 - Run tests with `make test`

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Tests performed:** build and **unit tests**

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Wire it up for CI
- [ ] Add some docs how to execute unit tests

### CODE REVIEW

**Comment by Shauren** [comment]
too big

**Comment by Carbenium** [comment]
@Shauren Well, in principle it's a header-only lib. It would be possible to pull-in the one header file only (https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp) and the 1 or 2 CMake scripts.

I, personally am also okay with leaving the sources completely out-of-tree. Not sure how you would solve it on Windows.

**Comment by Warpten** [comment]
> we want less deps as source
Git submodule is calling

**Comment by Carbenium** [comment]
@Naios Thanks for the suggestion! I implemented it with `FetchContent` now. Could you take a look if this is fine for you?

**Comment by Naios** [comment]
@Carbenium LGTM! Maybe you could even use the archive github download link since it will be faster than via git: `https://github.com/catchorg/Catch2/archive/v2.13.0.zip`.

**Pull request merged**
