### PR TITLE
Core/Maps: Update SpawnGroup Conditions when loading all cells

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

-  Update SpawnGroup Conditions when loading cells

**Issues addressed:**

Closes: none

Current issue: SpawnGroups that don't despawn on condition failure are being spawned even tho the condition to spawn has never been met.

**Tests performed:**

- Builds
- Tested in game while reworking alterac valley

**Known issues and TODO list:**

- This might not be the proper fix

### CODE REVIEW

**Review by Shauren — CHANGES_REQUESTED** [review]
This one is rejected in current state, proper implementation would be to make a specialized version of `UpdateSpawnGroupConditions` that only marks groups as active/inactive (`SetSpawnGroupActive`, without touching WorldObjects) and call that on map construction, in MapManager::Create functions after setting bg/instancescript but before LoadAllCells

 - staying open as a reminder either until either of us do that

**Comment by Golrag** [comment]
@Shauren, something like this? It seems to work on my alterac pr

**Comment by Shauren** [comment]
I would make that not depend on load cells config and always call it

**Comment by Golrag** [comment]
I still have it in the debug command, not sure if that was needed tho

**Review by Shauren — APPROVED** [review]

**Comment by Shauren** [comment]
Not needed, as it was already guaranteed to have been called on map creation

**Pull request merged**
