### PR TITLE
Core/Pooling: Remove respawn times from the database when despawning a pool

### LINKED ISSUE #21132: [3.3.5] Noblegarden Eggs Remain in Game Beyond Game Event Expiry
**Description:**

Bloodhoof Village in Mulgore still has Brightly Colored Eggs (Item #45072) despite Noblegarden Event turned off. Collection of said egg still warrants the Achievement "I Found One!" and changes you into a Bunny.

https://i.imgur.com/UOet09K.jpg

https://i.imgur.com/xMIUM3o.jpg

**Current behaviour:**

Eggs appear and are selectable out of season. 

**Expected behaviour:**

Eggs should vanish when Noblegarden ends.

**Steps to reproduce the problem:**

1. Go to Bloodhoof Village (Have not tested in other start zones)
2. Observe eggs.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 9d454eb

**TDB version:**  3.3.5.63

**Operating system:** Win10

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Remove respawn times from the database when despawning a pool. This is needed when a Game Event ends but there are still some respawn times saved in the database.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** 
Closes #21132

**Tests performed:** (Does it build, tested in-game, etc.)
Tests described at https://github.com/TrinityCore/TrinityCore/issues/21132#issuecomment-498440769 

**Known issues and TODO list:** (add/remove lines as needed)

- Not sure if it work 100% or sometimes the issue still happens. If it does, please let me know and I'll check which other case triggers it.

### CODE REVIEW

**Comment by illfated** [comment]
Looks quite neat and interesting, fairly explanatory too.

**Comment by Killyana** [comment]
Test results:

Steps to reproduce the issue:
.go gameo 151930 or 151929
.event start 9
.loot the gob
.event stop 9
.list respawn and wait for the respawn

The gob I looted:
```
Listing Gameobject respawns for Forêt d'Elwynn (zone 12)
SpawnID | Entry | GridXY| Zone | Respawn time (Full)
151931 | 113768 | [14,32] | Forêt d'Elwynn (12) | 24s
```
Notice the respawn is in going even if  the event is stopped, this doesn't happen for non pooled units.

After the respawn time hits 0 lots of eggs appears, I got all their guids and this is the result:
``` sql
SELECT * FROM `pool_members` WHERE SpawnId IN (151939,151941,151942,151924,151928,151927,151926,151930,151932,151933,151935,151936) AND TYPE=1;
``` 
All this gobs are from the same Pool as the gob I looted:

``` 
type, spawnId, poolSpawnId, chance, description
 1, 151924, 5700, 0, Noblegarden Egg
 1, 151926, 5700, 0, Noblegarden Egg
 1, 151927, 5700, 0, Noblegarden Egg
 1, 151928, 5700, 0, Noblegarden Egg
 1, 151930, 5700, 0, Noblegarden Egg
 1, 151931, 5700, 0, Noblegarden Egg -- the gob I looted
 1, 151932, 5700, 0, Noblegarden Egg
 1, 151933, 5700, 0, Noblegarden Egg
 1, 151935, 5700, 0, Noblegarden Egg
 1, 151936, 5700, 0, Noblegarden Egg
 1, 151939, 5700, 0, Noblegarden Egg
 1, 151941, 5700, 0, Noblegarden Egg
 1, 151942, 5700, 0, Noblegarden Egg

**Comment by jackpoz** [comment]
Is that starting from a clean respawn table or did you have already some respawns before ?

**Comment by Killyana** [comment]
I cleaned respawn table before starting the server

**Comment by jackpoz** [comment]
There, updated, give it another try please

**Comment by Killyana** [comment]
It looks fine, the respawn is removed upon the even is stopped:
```
Vous recevez le butin : [Oeuf vivement coloré].   <---- loot
.list respawn
Listing Creature respawns for Forêt d'Elwynn (zone 12)
SpawnID | Entry | GridXY| Zone | Respawn time (Full)
Listing Gameobject respawns for Forêt d'Elwynn (zone 12)
SpawnID | Entry | GridXY| Zone | Respawn time (Full)
151930 | 113772 | [14,32] | Forêt d'Elwynn (12) | 38s   <----Looted gob
.event stop 9
.list respawn
Listing Creature respawns for Forêt d'Elwynn (zone 12)
SpawnID | Entry | GridXY| Zone | Respawn time (Full)
Listing Gameobject respawns for Forêt d'Elwynn (zone 12)
SpawnID | Entry | GridXY| Zone | Respawn time (Full)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <---- The gob was removed for the respawn
``` 
After a while no egg related to the even was spawned.

**Comment by illfated** [comment]
Neat. Looks very promising.

**Pull request merged**
