### PR TITLE
Update Travis CI to run on container-based infrastructure

### PR DESCRIPTION
**Pull request by armano2**
- Update Travis CI to run on container-based infrastructure
- Correct compile errors after https://github.com/TrinityCore/TrinityCore/commit/3604025bb7e1e1e7803a44b0f13931b88fcd26ac

### CODE REVIEW

**Comment by tkrokli** [comment]
Dang. Your PR crashes because https://github.com/TrinityCore/TrinityCore/commit/3604025bb7e1e1e7803a44b0f13931b88fcd26ac#commitcomment-12417340 has not been fixed yet.

**Comment by armano2** [comment]
i know i fixed it in next commit

**Comment by tkrokli** [comment]
Yes, well done. :+1: I didn't even manage to post my comment before you fixed it. :p

**Comment by DDuarte** [comment]
This has been done before. See the discussion in #14939

**Comment by DDuarte** [comment]
We chose not to move to docker since builds take 6 times longer (from 5 to 30 mins, average).

We also tried running Docker with ccache and disabled PCH and some builds (when only .cpp files change or SQL only commits) took less than 2 minutes, any commit changed a common header meant the build would take 40+ minutes.

**Pull request closed without merging**
