### PR TITLE
Port Core/Networking: Fixed unsafe access to _worldSession member in WorldSocket

### PR DESCRIPTION
**Pull request by ariel-**

### CODE REVIEW

**Comment by jackpoz** [comment]
the commit should be generated with git cherry-pick command, including the source commit reference (-x parameter should do it)

**Comment by ariel-** [comment]
Fix'd

**Comment by Shauren** [comment]
add 3da0f7e40920b652d2222fa88dbb4b516d24725d

**Comment by jackpoz** [comment]
this code keeps being changed in 6.x and these changes are being tracked at https://github.com/TrinityCore/TrinityCore/issues/14418 . while we thank you for the effort into submitting a PR, I have to close it because we prefer to deal with cherry-picks on our own .

It might be better also to merge these changes when they are stable on 6.x

**Pull request closed without merging**
