### PR TITLE
Core/Pools: Fix pools with 1 member never spawning anything anymore

### PR DESCRIPTION
**Pull request by jackpoz**
Attempts to fix a 6 years old bug and never fixed by the original author.

**Changes proposed:**

- Fix pools with 1 member never spawning anything anymore
- When a pool tries to respawn a Creature, instead of staring at it and doing nothing, despawn and spawn that creature
- "respawn" database table will have the row related to the specific Creature/GameObject delete after the respawn has been handled

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes a lot of issues, reported and not reported, since 2015

**Tests performed:**

- Killed https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=18683
- Looted
- .respawn -> the mob respawns
- Killed again
- Stop worldserver
- Waited 20 hours
- Start worldserver -> the mob is ingame

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Need to handle gameobjects too as they are probably just as broken

### CODE REVIEW

**Comment by jackpoz** [comment]
https://user-images.githubusercontent.com/1153754/123163891-8ce35100-d472-11eb-8ccf-db5e16d7406b.mp4

**Comment by ccrs** [comment]
@Treeston maybe you have some input about these changes?

**Comment by Treeston** [comment]
not overly so, current pooling is a clusterfuck that i never fully understood

**Comment by jackpoz** [comment]
Not sure if gameobjects have ever had any issue with pools, I will try to find a case to see if the "respawn" case is bugged with them too

**Comment by Treeston** [comment]
what even is the use case for a pool with a single member?

**Comment by Treeston** [comment]
like, i'm not saying the fix is bad, i'm saying i don't want to figure out a month down the line that the fix broke something elsewhere

**Comment by jackpoz** [comment]
not sure about the "only 1 member" case, but this PR is some sort of continuation from https://github.com/TrinityCore/TrinityCore/pull/24949 where a pool with 2 members might try to respawn the currently active one and end up spawning nothing.

**Comment by jackpoz** [comment]
I applied the same change to gameobjects too, tested it with https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=3658

poolSpawnId | id | name | position_x | position_y | position_z | map
| --- | --- | --- | --- | --- | --- | --- | 
501 | 3658 | Water Barrel | -9729.42 | 656.299 | 31.8338 | 0
501 | 3719 | Food Crate | -9729.42 | 656.299 | 31.8338 | 0

**Comment by Aokromes** [comment]
tested with
https://github.com/TrinityCore/TrinityCore/issues/21331#issuecomment-361615047
and noble garden eggs
look to work.

**Pull request merged**
