### PR TITLE
Core/Objects: Units possessing another ones must use the detection of the latter

### LINKED ISSUE #23528: [3.3.5] Core: Players visibility should use invisibility detection from the currently controlled unit
Title. In cases of auras like invisibility being applied on the owner the possessed unit should not have the vision restrictions applied on it.
Also to note, the client will also use the indivisibility glow filter effect but shouldn't.
Example spell: Coax Marmot (38544) - applies an invisibility aura on the caster and the controlled unit shares the vision effects.
https://youtu.be/Amsn4iBbxAI?t=14

Steps to reproduce:
1. .quest add 10720
2. .go xyz 3346.222168, 5783.050781, -7.563022, 530
3. /use Kodohide Drum

rev. eeba12778b330f799eab1530da14bcd8a01b8269 (yesterday's)

### PR DESCRIPTION
**Pull request by meji46**
**Changes proposed:**

-  Units with invisibility auras should be able to see units that cannot detect them.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #23528

**Tests performed:**
Builds, tested in-game

### CODE REVIEW

**Comment by jackpoz** [comment]
Does this PR still work with the case of https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=66 mentioned in the removed comment ?

**Comment by meji46** [comment]
> Does this PR still work with the case of https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=66 mentioned in the removed comment ?



> Does this PR still work with the case of https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=66 mentioned in the removed comment ?

I guess not. i have seen the following comment "Since 4.0.1, invisible Mages can see other players, although they cannot see other invisible mages (unless party members)".

Perhaps this mechanic should only be applied for INVISIBILITY_GENERAL (0)?

**Comment by kelno** [comment]
I think the current logic is fine, it's just missing that it should use detection from the currently controlled unit rather than always the player character.

**Comment by meji46** [comment]
@kelno I prefer your approach so I have changed the logic. Now the unit uses detection from the currently controlled unit.

Tested with https://www.wowhead.com/spell=38544/coax-marmot and https://www.wowhead.com/spell=66/invisibility

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
