### PR TITLE
Core/Creature: Added Helper method for Add or Disable Encounter frame…

### PR DESCRIPTION
**Pull request by BertiRean**
…s Engage

**Changes proposed:**

-  Use a helper method instead making a if in each case where you need add/remove an Encounter frame
-  
-  

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Ovahlord** [comment]
at this point you can just get rid of the instance script depency and send plain packets instead. Since open world bosses use it as well (since MoP?).

**Comment by BertiRean** [comment]
> at this point you can just get rid of the instance script depency and send plain packets instead. Since open world bosses use it as well (since MoP?).

Well that could be done also, maybe @Shauren have a better opinion about if we need remove or not the instance dependency

**Comment by Shauren** [comment]
I don't see the value in this PR. Since all (new) boss scripts are supposed to use BossAI, they already have a InstanceScript* member (so you dont need to check it), all this is going to do is change 1 line (`instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me, priority);` with another 1 line (`me->AddInstanceEncounterFrame(priority)`

**Comment by BertiRean** [comment]
> 

Well for BossAI you can use the instance pointer on structure, but for scripts that are normally like trash or something. If you don't want make a InstanceScirpt* as struct member in each script, this method save a lot of time and avoid write InstanceScript _instance in each script of normal mob or boss add.

**Comment by Shauren** [comment]
Right, it looks like you missed/forgot one more thing
https://github.com/TrinityCore/TrinityCore/blob/34ae77ca8685ecc0252f580a184d6f37277f33be/src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.h#L563-L569

When you use functions like that me->GetInstanceScript() is guaranteed to return something valid (eliminating the need to check it, just like in BossAI)

**Comment by BertiRean** [comment]
I've attached a video about how Serpentrix on Eye of Azshara show different frames for each head.

**Comment by Shauren** [comment]
Yeah but my latest comment still applies to scripted & summoned adds

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Creature/Creature.cpp

**Comment by mdX7** [comment]
> at this point you can just get rid of the instance script depency and send plain packets instead. Since open world bosses use it as well (since MoP?).

Cannot confirm. Tested @ 167526 & 178958 (Shadowlands worldbosses) and 83746 (WoD worldboss)

**Comment by BertiRean** [comment]
> Yeah but my latest comment still applies to scripted & summoned adds

But then the method should be on ScriptedAI or CreatureAI?. Because BossAI is only used by the bosses.

**Comment by Nyr97** [comment]
> > at this point you can just get rid of the instance script depency and send plain packets instead. Since open world bosses use it as well (since MoP?).
> 
> Cannot confirm. Tested @ 167526 & 178958 (Shadowlands worldbosses) and 83746 (WoD worldboss)

@Seyden also couldn't confirm this as Galion (MoP worldboss) does not send it either.

**Comment by Ovahlord** [comment]
Doolmlord Kazzak in Taanan Jungle clearly does have the frame and he is a world boss.

**Comment by ImmortalusDev** [comment]
> Doolmlord Kazzak in Taanan Jungle clearly does have the frame and he is a world boss.

Where do you saw that?

**Comment by mdX7** [comment]
Also Kazzak in Tanaan Jungle is not having that
<details>
<summary>Ref</summary>

grafik

</details>

**Comment by ImmortalusDev** [comment]
It was always related only to instanced creatures, bosses and it's summons, nothing else.

**Pull request closed without merging**
