### PR TITLE
Core/SpellAuras: Add target check to area auras

### LINKED ISSUE #16999: [3.3.5] Hodir- NPC's are being affected by biting cold
NPC's during Hodir encounter are getting high amounts of stacks of biting cold and dying super quickly.
http://www.wowhead.com/npc=32845/hodir#article (NPC links)

NPC's suffer from biting cold http://www.wowhead.com/spell=62039/biting-cold, thus dying and making the fight much more difficult and impossible for Hardmode

NPC's should not be affected by biting cold

Go to Ulduar and start Hodir encounter
Break NPC's out of Flash Freeze

3.3.5

Commit hash:    4afea55b2c6035a986162a8d800a57fb1ae4cf98

TDB 335.60

Win7

### PR DESCRIPTION
**Pull request by mik1893**
**Changes proposed**:
- Add target spell validity check to area auras

**Target branch(es)**: 335/6x

**Issues addressed**: Fixes #16999

**Tests performed**: Build - to be tested extensively in game

**Known issues and TODO list**:
-  [x] Extensively test in game (try different bosses with area auras)
-  [x] Clean up code and add additional conditions (if needed)

### CODE REVIEW

**Comment by mik1893** [comment]
@Keader - this is a kind of generic solution, i'm not entirely sure I'm addressing it properly but if you can try this we can see how it behaves

**Comment by mik1893** [comment]
although this works, i'm not entirely sure that the implementation is correct.
I think the problem is in the Spell::CheckCast function, that executes all the condition and target checks only when m_targets returns an ObjectTarget or a UnitTarget - not going through the list of all the targets...

**Comment by joschiwald** [comment]
@mik1893 what do you mean?

**Comment by mik1893** [comment]
i  mean that the way i have done it, it does some check for targets, but its not all that it should do - there are other things (e.g. conditions) that are not checker.
Also it's quite ugly to have a check on a spellcast result on an aura application (my personal 2 cents)
might need to write a method that properly executes some target checks for auras

**Comment by joschiwald** [comment]
checkcast is a bit different to that you need here, checkcast do checks on caster and on explicit target, here you need implicit target checks
one big problem here is, how are targets searched

**Comment by mik1893** [comment]
i will doing some basics to fix the errors related to anubarak and hodir, then will likely add smth better on the way

**Comment by mik1893** [comment]
i have left only the checks that I THINK might be useful.

**Comment by Keader** [comment]
Now looks like more clean ^^

**Comment by P-Kito** [comment]
I dont know why, but I have a feeling that this might break something or make spellscripts useless that had some filtering, which we need to take out then.

**Comment by mik1893** [comment]
well we tested it quite extensively and it is looking fine - 
the spellscripts doing target filtering will filter after this list is done - so in the worst case they are useless

**Comment by P-Kito** [comment]
Okay then I have no doubts. :P

**Comment by QAston** [comment]
LGTM, though there's always risk of breaking some scripts.

**Comment by mik1893** [comment]
I'll merge soon need to do a small change

**Comment by Treeston** [comment]
This breaks the "Ghost" debuff from being applied to dead characters releasing.

**Comment by ccrs** [comment]
Where is the conditions check?

**Comment by Aokromes** [comment]
@mik1893 

mik1893 commented on Jul 12
I'll merge soon need to do a small change

**Comment by Shauren** [comment]
Do not merge - https://github.com/TrinityCore/TrinityCore/pull/17321#issuecomment-233002317

**Comment by Aokromes** [comment]
I known i was waking mik to fix that :P

**Comment by Aokromes** [comment]
@mik1893 stop changing diapers for a while and give love to your another baby :P

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Spells/Auras/SpellAuras.cpp

**Comment by Shauren** [comment]
Since it breaks generic stuff in favor of some special situations - closing.

**Pull request closed without merging**
