### PR TITLE
Core/Movement: allow waypoints to use 0 as valid facing value

### LINKED ISSUE #26037: Core/Waypoints: orientation field 0 is wrongly treated as no orientation
**Description:**

`orientation` field 0 is wrongly treated as no orientation while 0 is valid orientation and is used by Blizz
Of course we can use 6.2831853072 but it's not the same

**Expected behaviour:**

treat 0 as valid orientation

**Branch(es):** both
**TC rev. hash/commit:** 3cb70ee62a3f30ae492a6985b5306052d90c89c4

### PR DESCRIPTION
**Pull request by Ovahlord**
**Changes proposed:**

-  make waypoint orientation values nullable to support angle values of 0 as well as there actually are some cases that use such values

Closes #26037

**Target branch(es):**
- 3.3.5

**Tests performed:**
- tested on 4.x, no issues discovered

### CODE REVIEW

**Comment by Macsimka** [comment]
Also need made changes here, to prevent use 0.0f for all scripted waypoints.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Scripting/ScriptSystem.cpp#L83

**Review by ccrs — APPROVED** [review]

**Comment by jackpoz** [comment]
> Also need made changes here, to prevent SetFacing to 0.0f for all scripted waypoints.

are there other places that need to be checked or is this PR ready to be merged ?

**Comment by Ovahlord** [comment]
apparently smartai waypoints also need a bit love. will take care of it soon(tm)

**Comment by offl** [comment]
Can be merged without additions to `waypoints`
335 was without orientation column in `waypoints` for 10 years, now it's clear that orientation should be always scripted

**Comment by Shauren** [comment]
> Can be merged without additions to `waypoints` 335 was without orientation column in `waypoints` for 10 years, now it's clear that orientation should be always scripted

Actually it cannot - you might think it's not neccessary however this isn't the full story. This PR modifies code shared by both waypoint systems and without explicitly supporting SAI in it, it will make all SAI waypoints behave as if they are intended to face 0 on each point

**Comment by Shauren** [comment]
github borked, its merged (4747515872775553de35cc3267e1ccd5e0076ca4)

**Pull request closed without merging**
