### PR TITLE
Scripts/Ulduar: Updated Ignis and Assembly of Iron Scripts to the new model.

### PR DESCRIPTION
**Pull request by NathanNatNat**
Changes proposed:
- Update Ignis and Assembly of Iron Scripts to the new model.

Target branch(es): 335/master
- [x]  3.3.5
- [ ] master

Tests performed:
- Builds
- Runs
- Works ingame (as much as I can test solo).

### CODE REVIEW

**Comment by Ovahlord** [comment]
You would be surprised if I tell you that I'm currently giving the Assembly of Iron a whole rework so yeah. Kinda wasted efforts here since my rework contains a model update as well.

**Comment by natnat201193** [comment]
@Ovahlord Cool, I added Ignis new Model as well, can the assembly one be removed or should this be closed and new PR made? I'm not sure how, even had a hard time figuring out how to do a PR properly xD

**Comment by natnat201193** [comment]
@Ovahlord I was going to have a look at it as well, already did a few Spell conditions if you would like them.

```
-- Supercharge spell target Conditions.
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=61920;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(13, 7, 61920, 0, 0, 31, 0, 3, 32867, 0, 0, 0, 0, '', 'Ulduar Assembly of iron - supercharge - All Effects hit Steelbreaker'),
(13, 7, 61920, 0, 1, 31, 0, 3, 32927, 0, 0, 0, 0, '', 'Ulduar Assembly of iron - supercharge - All Effects hit Runemaster Molgeim'),
(13, 7, 61920, 0, 2, 31, 0, 3, 32857, 0, 0, 0, 0, '', 'Ulduar Assembly of iron - supercharge - All Effects hit Stormcaller Brundir');

-- Lightning Channel pre-fight visual target Conditions.
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=61942;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(13, 1, 61942, 0, 0, 31, 0, 3, 32867, 0, 0, 0, 0, '', 'Ulduar Assembly of iron - Lightning Channel visual - EFFECT_0 hits Steelbreaker');

-- Rune of power Channel pre-fight visual target conditions.
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=61975;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(13, 1, 61975, 0, 0, 31, 0, 3, 32867, 0, 0, 0, 0, '', 'Ulduar Assembly of iron - Rune of Power - EFFECT_0 hits Steelbreaker');
```

**Comment by Ovahlord** [comment]
https://git.io/JUyVd way ahead of you already. Gonna wrap this stuff up soon

**Comment by natnat201193** [comment]
Nice nice

**Pull request closed without merging**
