### PR TITLE
Core/Auras: vehicles should not despawn during seat change

### PR DESCRIPTION
**Pull request by gonzo1247**
**Changes proposed:**

-  Vehicles are despawned while Seat Changes. Some tests and with a big help from Shauren (https://gist.github.com/Shauren/a5a7ebf7f0004ca1dbb8e0aac283bebb) its works now. My change was that at the check only considered auras from caster and not all on the vehicle(without this, that broke some other things(eject from vehicle, despawn vehicle accessory if more as one Vehicle ride spell on the vehicle)
-  
-  

**Target branch(es):** 3.3.5/master

- [x] master
For 3.3.5 will i creat a extra PR
**Issues addressed:**

Closes #  (insert issue tracker number)
https://github.com/TrinityCore/TrinityCore/issues/18089 to half. Seat Change works, timed despawn missed

**Tests performed:**

(Does it build, tested in-game, etc.)
Build works, ingame test works, teset with 3 different Seat Change spells.

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by illfated** [comment]
Cosmetic detail, suggestion for a PR title, old-school style:

**Core/Auras: vehicles should not despawn during seat change**

(not a big deal, feel free to use it if you like)

**Comment by gonzo1247** [comment]
> 
> 
> Cosmetic detail, suggestion for a PR title, old-school style:
> 
> **Core/Auras: vehicles should not despawn during seat change**
> 
> (not a big deal, feel free to use it if you like)

thx it's changed

**Comment by Shauren** [comment]
Damn github, didnt automatically mark as merged after e26122dc54b5c5a356a97a842718168dab97a0aa

**Comment by illfated** [comment]
Maybe there is a limit to which words GitHub reacts to, like "Closes #", "Fixes #", "Resolves #", "Solves #" and similar.

**Comment by Shauren** [comment]
It used to work when I did it like that in the past

**Pull request closed without merging**
