### PR TITLE
Core/Networking: Fix memory leak

### PR DESCRIPTION
**Pull request by jackpoz**
Fix memory leak reported by ASan happening when ports fail to bind in Authserver

**Changes proposed:**

-  Fix memory leak reported by ASan happening when ports fail to bind in Authserver

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
None

**Tests performed:** (Does it build, tested in-game, etc.)
None

**Known issues and TODO list:** (add/remove lines as needed)
- [ ] Need to reproduce the issue
- [ ] Need to verify that the change fixes the issue

### CODE REVIEW

**Comment by jackpoz** [comment]
Yeah, it's just to get a clean ASan log without any background noise

**Comment by jameyboor** [comment]
@Jackpoz You're background noise.

**Comment by ccrs** [comment]
wtf? that better be a friendly joke @jameyboor

**Comment by jameyboor** [comment]
@ccrs I'd expect a member to know it's a joke.

**Review by Shauren — APPROVED** [review]

**Pull request merged**
