### PR TITLE
Scripts/SunkenTemple: Add Eventsupport for NPC: Malfurion Stormrage

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
- This adds the Event which is decribed here: 
- http://www.wowhead.com/quest=8733/eranikus-tyrant-of-the-dream
- http://www.wowhead.com/quest=8733/eranikus-tyrant-of-the-dream#screenshots:id=9155
- Unsure with the Areatrigger:
  Currently the summon of Malfurion will be triggered if the player completed quest 8555 and does not rewarded quest: 8733. Is this right? the commends are a bit different.

### CODE REVIEW

**Comment by DDuarte** [comment]
@Rushor: I think you can ship this ^^

**Comment by Rushor** [comment]
yay succesfully clicked on the merge button xD

**Comment by DDuarte** [comment]
You need to change the date of the .sql

**Comment by Rushor** [comment]
documetation:
done in https://github.com/TrinityCore/TrinityCore/commit/e27fcb91c345e10462225384ff4027ea66dd89ad

**Pull request merged**
