### PR TITLE
Core/SAI: MOVE_TO_POS new parameters

### PR DESCRIPTION
**Pull request by Lopfest**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  added new parameter closePoint (bool) which enables the initiator to go to the target at specific range (not exaxtly at the target position)
-  when enabled, you must also specify distance parameter

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Tests performed:** (Does it build, tested in-game, etc.)
tested in-game

### CODE REVIEW

**Comment by Rushor** [comment]
wasn't this already added in 3.3.5?

**Comment by Lopfest** [comment]
I have no idea. I hope I didnt write it for nothing :D

**Comment by Rochet2** [comment]
See this https://github.com/TrinityCore/TrinityCore/pull/18720

**Comment by Lopfest** [comment]
Okay cool. I'm looking forward to see it in master branch.

**Pull request closed without merging**
