### PR TITLE
Core/DB: Add DB error for missing gossip npcflag

### LINKED ISSUE #22912: [DEV] Core/Gossip: DB error for missing npcflag hasgossip
**Description:** We need a DB error to get npcs  that have gossipmenu>0 and npcflags not containing the flag=1

**Branch(es):** both

**TC rev. hash/commit:** rev. dd81978f432f

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Add on-boot check for creature templates that have gossip assigned, but no `UNIT_NPC_FLAG_GOSSIP` set.

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #22912

**Tests performed:** Works as intended

~**Known issues and TODO list:**~

### CODE REVIEW

**Comment by Shauren** [comment]
Does this trigger any errors in current db?
Sometimes it might be desirable for a creature to not have gossip flag and only gain it at a later point in a script

**Comment by Killyana** [comment]
I know some cases like this, what we do is we remove and add the flag via the script.

**Comment by Sorikoff** [comment]
> Does this trigger any errors in current db?

It does indeed.

**Comment by jackpoz** [comment]
maybe it could be changed from TC_LOG_ERROR to a lower level then ?

**Comment by Killyana** [comment]
I will fix every case manually anyway, after checking the scripts.

**Comment by Sorikoff** [comment]
> maybe it could be changed from TC_LOG_ERROR to a lower level then ?

There isn't much of them right now. I think TC_LOG_ERROR should be fine.

**Comment by Faq** [comment]
@Sorikoff what is the ~number? No much doesn't mean anything without magic number.

**Comment by jackpoz** [comment]
could you post the log in this PR while at it ?

**Comment by Sorikoff** [comment]
```
>> Loaded 1735 creature template resistances in 13 ms
>> Loaded 9641 creature template spells in 21 ms
Creature (Entry: 37223) has assigned gossip menu 10950, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 37187) has assigned gossip menu 10953, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 36955) has assigned gossip menu 10860, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 12018) has assigned gossip menu 4093, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 23191) has assigned gossip menu 21335, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 37221) has assigned gossip menu 11031, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 27657) has assigned gossip menu 9573, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 27658) has assigned gossip menu 9708, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 27659) has assigned gossip menu 9574, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 37554) has assigned gossip menu 10909, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
Creature (Entry: 37200) has assigned gossip menu 10933, but npcflag does not include UNIT_NPC_FLAG_GOSSIP.
>> Loaded 29923 creature definitions in 599 ms
```

**Comment by jackpoz** [comment]
@Killyana how about first fixing the errors and then merging this PR ?

**Comment by Killyana** [comment]
@Sorikoff you get only this npcs?

**Comment by Sorikoff** [comment]
@Killyana yes (my DB is a little outdated).

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
