### PR TITLE
Core/Spell: add proper cooldowns to some spells used by vehicles

### PR DESCRIPTION
**Pull request by Wyrserth**
**Changes proposed:**

-  Some spells used by vehicles don't have a cooldown, but they should have one that's specified in the tooltips but not in DBC data.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

### CODE REVIEW

**Comment by Killyana** [comment]
Same for this spell https://github.com/TrinityCore/TrinityCore/issues/22512 the CD=10secs and there's many others, maybe if the spell doesn't have a CD and used by a controlled unit it must get a default 10secs CD

**Comment by Wyrserth** [comment]
Yeah the vehicle for the quest [Post-partum Aggression](https://www.wowhead.com/quest=12614) also has a spell that I recall should have a 10-sec cooldown but doesn't.

There's also the issue that cooldown is not sent to the client, so it shows as useable even if you add the cooldown serverside.

It does seem that they all have 10-sec cooldown, I'll see if there's a good way to handle it globally.

**Comment by D0d0** [comment]
@Wyrserth the same issue apply to these spells for the quest https://github.com/TrinityCore/TrinityCore/issues/4974. I think the main reason why it is not send to client is that there is a difference in spell cooldown. As you can see the cooldown is just written after spell description, instead of written in the right upper corner. Maybe we should send different packet to client using these spells?

https://www.wowhead.com/spell=56513/jormungar-strike
https://www.wowhead.com/spell=56524/acid-breath

**Comment by jackpoz** [comment]
>Spell 32274 has '(null)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 32282 has '(null)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 47911 has '(10 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 51748 has '(15 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 51756 has '(20 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 54996 has '(20 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 54997 has '(10 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 55797 has '(10 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 56513 has '(2 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 56524 has '(6 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 58856 has '(10 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 59925 has '(10 sec. cooldown)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 60079 has '(5 sec. cooldown, 100 yard range)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()
Spell 60100 has '(5 sec. cooldown, 40 yard range)' in the description but not in Spell.dbc, please apply a correction in LoadSpellInfoCorrections()

**Comment by sirikfoll** [comment]
Related to this, I had noted that the missing cooldown from this 2 spells do not match what the tooltip says:
54996 Ice Slick (Tooltip says 20s cooldown, but should be 12s, checked in Cata sniffs)
54997 Cast Net (Tooltip says 10s cooldown, but should be 6s, checked in Cata sniffs)
<details>

```
ServerToClient: SMSG_SPELL_COOLDOWN (0x4B16) Length: 17 ConnIdx: 2 Time: 06/19/2012 00:28:08.678 Number: 57495
GUID: Full: 0xF15074CF00825509 Type: Vehicle Entry: 29903 (Frostbite) Low: 8541449
Unk mask: 0
Spell ID: 54996 (Ice Slick)
Time: 12000
```
</details>

Also, all of those spells do not send cooldown info automatically, so spell will be on cooldown serverside only, I don't know it there's a way to make it generic, but maybe a generic SpellScript could be used? For example, something like this:
<details>

```cpp
// 54996 - Ice Slick
// 54997 - Cast Net
class spell_gen_trigger_vehicle_spell_cooldown : public SpellScript
{
    PrepareSpellScript(spell_gen_trigger_vehicle_spell_cooldown);

    void HandleCast()
    {
        Unit* caster = GetCaster();
        if (Player* owner = caster->GetCharmerOrOwnerPlayerOrPlayerItself())
        {
            WorldPacket data;
            caster->GetSpellHistory()->BuildCooldownPacket(data, SPELL_COOLDOWN_FLAG_NONE, GetSpellInfo()->Id, GetSpellInfo()->RecoveryTime);
            owner->SendDirectMessage(&data);
        }
    }

    void Register() override
    {
        OnCast += SpellCastFn(spell_gen_trigger_vehicle_spell_cooldown::HandleCast);
    }
};
```

</details>

**Comment by Wyrserth** [comment]
Thanks a lot! I didn't realize there were so many spells like that, and a common spellscript seems the best idea.

**Comment by Wyrserth** [comment]
Should be fine now. Some listed spells are tied to items but already work properly, so I just added the script to the vehicle spells.

Thanks for the help!

**Comment by jackpoz** [comment]
tested ingame, works and such ? can I merge it ?

**Comment by Wyrserth** [comment]
Yeah I tested it before pushing, works perfectly.

**Comment by Killyana** [comment]
This 3 Spells 37727, 51752, 48620 are fixed?

**Comment by Wyrserth** [comment]
Nope, didn't know about those. Going to add them if I can find the cooldown time.

**Comment by Killyana** [comment]
Also this ones: 37919, 37917, 37918, 37851
used by https://www.wowhead.com/npc=21909/arcano-scorp

**Comment by Wyrserth** [comment]
@Killyana: 37851 is 3 seconds, 37917 should not be in the action bar (it's probably some internal spell, not sure when/how it is used), from [this video](https://www.youtube.com/watch?v=ebySnNcXSnU&feature=youtu.be).

Not sure about the others as I can't find a video where they're cast.

**Comment by Wyrserth** [comment]
Added all but 37918 and 37919 because I can't find anything about them. They can be added later if there's a sniff or something else regarding those.

**Comment by Killyana** [comment]
In this case it could pushed , I will open a new issue about remaining spells to try getting some help, maybe we can get some info from retail or sniffs.

**Comment by Killyana** [comment]
@Wyrserth this could be pushed?

**Comment by Wyrserth** [comment]
Yes, it works as it should so it's fine to merge.

The two spells missing can be added at a later time, when someone finds more info.

**Comment by illfated** [comment]
Cosmetic PR title detail: I would like to argue that the PR content is 2/3 about **Scripts/Spells** (new spell script & name + SQL part) and 1/3 **Core/Spells** (SpellMgr.cpp). Feel free to disagree.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Rushor** [comment]
this is nice!

**Pull request merged**
