### PR TITLE
Add InhabitType override possibility in creature table

### PR DESCRIPTION
**Pull request by Traesh**
**Changes proposed:**

-  Add 'InhabitType' column in creature to override creature_template data if needed

**Target branch(es):**

- [x] master

**Issues addressed:** Malcrom bad mood

**Tests performed:**
Compiled, not tested ingame yet

**Known issues and TODO list:**

- None ATM

### CODE REVIEW

**Comment by Ovahlord** [comment]
I would prefer using a guid bount smart script to make creature hover by default since if there is a creature using this, it is mostly a scripted one.

**Comment by Traesh** [comment]
It's a request made by Malcrom for some creatures, maybe better to see with him

For guid bound smart script, i think there is already another PR (don't know if it has been merged yet) that allow to have a ScriptName on a creature

**Comment by Kittnz** [comment]
Is this in 335? I doubt it is, is this cherry pickable?

**Comment by malcrom** [comment]
It will go in a new table. Working on the SQL.

**Comment by Traesh** [comment]
I will make another PR with new table

**Pull request closed without merging**
