### PR TITLE
Core/SAI: Add new action SMART_ACTION_SET_HEALTH_PCT

### LINKED ISSUE #25317: Core/SAI: Request - SAI Action to modify a creatures current HP
**Description:**

As i was recently checking some Scholomance creatures, i stumbled over creature [Reanimated Corpse](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10481).

Retail behavior:
After this creature is damaged down to 1 hp, it goes down on the floor for 15 seconds, than it rises up once again to continue the fight. If its beaten up once again, it dies.
See for reference: https://www.youtube.com/watch?v=s-2GXud7CJI&feature=youtu.be&t=339

While it being invincible on the ground, it can still be targeted and hit by players. It also keeps players in combat for that time.

For SAI at the moment, 1 things are missing/needed here:

~~Addition to action:
SMART_ACTION_SET_INVINCIBILITY_HP_LEVEL - this action cant be removed after it was set once. Since we cant work with Evade in this case (creature has to store its aggro list), we need the option to add/remove invincibility on demand instead of just set it active till the creature evades.~~

^It seems like we already can do this - thanks @dr-j for pointing this out.

Missing action:
SMART_ACTION_SET(_CURRENT?)_HEALTH - i might be wrong in this creatures case since i dont have any sniffs from it, maybe there is a spell that set its health back to full. But anyway, we dont have a single action that can modify a creatures health at all. In my opinion we need an action that can either set the creatures current health to a specific value via param1 and maybe to the creatures maxhealth via param2=1 if param1 is 0.

Or as a variant - set to % instead of absolut value.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

7cdc4b46bb6ce63ae3830fb1f8e0464093e1a015

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Add new action SMART_ACTION_SET_HEALTH_PCT (142) with one single parameter "percent" to set the Unit health.
Close #25317

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #25317

**Tests performed:**

None

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Should test the action once

### CODE REVIEW

**Comment by jackpoz** [comment]
@offl this is a draft to set HP % in SAI

**Comment by offl** [comment]
Nice, requires tests?

**Comment by jackpoz** [comment]
> Nice, requires tests?

that would be nice, yes, but I'm going to risk it and write some tests too of my own :)

If you write a couple of tests I can record and post the usual video with the result.

**Comment by offl** [comment]
```sql
-- 46107 in normal / 62315 in heroic
DELETE FROM `smart_scripts` WHERE `entryorguid` = 20869 AND `source_type` = 0 AND `id` = 4;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(20869,0,4,0,25,0,100,0,0,0,0,0,0,142,40,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Arcatraz Sentinel - On Reset - Set Health 40%");
UPDATE `creature` SET `curhealth` = 115269 WHERE `id` = 20869;
```

**Comment by jackpoz** [comment]
My own test:
image

(disable hp regen on created, every 2 seconds use SMART_ACTION_SET_HEALTH_PCT to set the HP to 100%, then 75%, then 50%, then 25%)


https://user-images.githubusercontent.com/1153754/105639302-b83c2280-5e77-11eb-9136-984d28f41711.mp4

**Comment by jackpoz** [comment]
@offl do I need to go to the arcatraz or can I spawn the creature outside or ?

**Comment by offl** [comment]
Doesn't matter

**Comment by jackpoz** [comment]
well the creature looks "dead" when out of combat, anyway you can see the hp goes back to 40% after a reset


https://user-images.githubusercontent.com/1153754/105756006-5ac5d580-5f4c-11eb-9905-73b08a3fc11c.mp4

**Comment by jackpoz** [comment]
does it look good enough to be merged ?

**Comment by offl** [comment]
Yes

**Review by offl — APPROVED** [review]

**Pull request merged**
