### PR TITLE
3.3.5 game event respawn

### LINKED ISSUE #21519: [3.3.5] Pooling + dynamic_spawning
Description:
The server crashes after starting

https://gist.github.com/Tauriella/7b4e94f73174fddea29e5bbd0266dacb

Branch(es):

TC rev. hash/commit:
TrinityCore rev. 3eab2d7efcc2 2018-02-27 16:18:38 +0100 (3.3.5 branch)

TDB version: TDB_full_world_335.64_2018_02_19 + all updates

Operating system: Win7

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  remove respawn times from creatures/gameobjects when starting/stopping a game event

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #21519

**Tests performed:** (Does it build, tested in-game, etc.)
- .go xyz -773.906067 -5010.133301 17.237411 1
- .event start 61
- /tar darkspear scout
- .damage 50000
- .event stop 61
- .event start 61

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] This handles only the issue described in #21519 , it doesn't attempt to fix whatever other issues game event, respawn times (and pools) might have together
- [ ] @r00ty-tc is working on a different solution that should fix some other issues too. This PR could be used in the time being (either merged in TC or even just merged locally by users)

### CODE REVIEW

**Comment by Killyana** [comment]
I tested this case https://github.com/TrinityCore/TrinityCore/issues/21132#issuecomment-498440769
After stopping the event, the command .list respawn show the gob:
SpawnID | Entry | GridXY| Zone | Respawn time (Full)
151932 | 113769 | [ 14,  32] | Forêt d'Elwynn (12) | 23s

And using .resp near the gob make it respawn

**Comment by jackpoz** [comment]
Need to check if that's part of a pool, as this PR doesn't fix that case

**Comment by Killyana** [comment]
Yes this gobs are inside a pool

**Comment by jackpoz** [comment]
@Killyana I removed the pool checks because r00ty said it was (maybe) ok to remove them, could you try now ?

**Pull request merged**
