### PR TITLE
Script/Spell: prevent Counterattack! and Charge from removing two charges of Defend

### LINKED ISSUE #22193: Spell/Script: Thrust remove two shield layers instead of one
**Description:** The spell https://woehead.way-of-elendil.fr/?spell=62544 remove 2 shield layers instead of one.

**Steps to reproduce the problem:**

1. Connect an alliance char that doesn't starts the argent tournament.
2. .Quest add  13667   and .quest rew  13667
3. .quest add 13828  and .add 46069
4. .go c 75473 equip the spare and ride the horse
5. activate 3 shields
6. go to a melee target and use the spell Thrust: https://woehead.way-of-elendil.fr/?spell=62544
7. Notice 2 shield layers are removed instead of one

related script: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L660-L666

**Branch(es):** 3.3.5

TrinityCore rev. b7c0f1961c88 2018-07-24 10:46:14 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.6.15
Using CMake version: 3.11.2
Compiled on: Windows 
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2229000480 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR 
Using World DB: TDB 335.64

### PR DESCRIPTION
**Pull request by Rynem**
**Changes proposed:**

I'm not sure how it worked in the past, but as of 9a924fb9d557434c5a2e4020c80db6e6bfe466ad the [Defend](https://www.wowhead.com/spell=62552) aura is shared between player and mount. So removing a stack from the mount will also remove it from the player, and the other way around.

For example, mounting an Argent Tournament mount, casting Defend and using .unaura 62552 on the mount will also remove it from the player.

The script currently removes one stack from the mount and one stack from the player, which results in two stacks taken from the aura instead of one.

**Target branch(es):** both.

**Issues addressed:** Closes #22193.

**Tests performed:** builds, tested and working properly.

### CODE REVIEW

**Comment by illfated** [comment]
Just a minor (cosmetic) F.Y.I. : the original way of starting the PR title used to be "**Scripts/Spells:** " as a reference to `/src/server/scripts/Spells/`

Nowadays it seems as if the title format gets somewhat ignored, as long as it is "close enough".
(Never mind, it's just an observation from my point of view.)

**Comment by PolarCookie** [comment]
This might have been unintentionally fixed in https://github.com/TrinityCore/TrinityCore/pull/22794

The Defend spell works like this
```
Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (27, 0) (TARGET_UNIT_MASTER, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -30
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 87 (SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN), value = -30, misc = 127 (127), miscB = 0, periodic = 0
```
Where the second effect is cast on the player and handles the visual shields.
Before weird stuff happened with sharing actual aura instances which is disabled in the PR linked.
With the aura change Defend works fine without changing scripts, but both PRs together makes the visual shields not update.

**Comment by Aokromes** [comment]
So, this PR is unneeded when #22794 is merged @PolarCookie ?

**Comment by PolarCookie** [comment]
Yes, I'd say so.

**Pull request closed without merging**
