### PR TITLE
Scripts/HellfireRamparts: Vazruden the Herald - Improve Reset-/ Aggrobehaviour

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
by @CDawg

### CODE REVIEW

**Comment by Nyeriah** [comment]
This boss is a mess... I started rewriting it but gave up half way, failed to get around the circling movement :P

This can be accepted for now but there are likely better ways to deal with this and the boss still needs a major revamp

**Comment by Aokromes** [comment]
ugly and working better than ugly and broken.

**Comment by jackpoz** [comment]
was this PR debugged line by line before being submitted ?

**Comment by jackpoz** [comment]
this PR doesn't include the fixes suggested at https://github.com/TrinityCore/TrinityCore/pull/11682/files#r12508197 , also next time you reopen a PR include it in the description

**Pull request merged**
