### PR TITLE
Core/Handlers: fix ".whisper on" with opposite faction/low level

### LINKED ISSUE #22283: Whispers from horde player to alliance gm and vice versa
I have seen there is a closed issue about this https://github.com/TrinityCore/TrinityCore/issues/22271
I am having the same problem.
And not only me, I have asked a friend if he can compile and try.
We both have the same issue.
Aokromes closed the issue, but I would like to ask if someone can just try a new fresh compilation and check this.

This is tested on Debian 9, windows 7, windows 8.1
Tested revisions:
e5b8b1e99a4e7361be862ae6e1f29189907167e4
0df3cb5bcc8097070b1f215032d3914d6a577f01
cbacc72d934c10448762b67a0fa97ea4eb38cb63
TDB: 335.64
Branch: 3.3.5a

### PR DESCRIPTION
**Pull request by Gooyeth**
**Changes proposed:**

-  Fix the problem of whisper by opposite faction and low level if the gm has .whisper on

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes #22283

**Tests performed:** It needs to be tested.

### CODE REVIEW

**Comment by illfated** [comment]
> This branch is 223 commits behind TrinityCore:3.3.5.

(in case you wonder why the travis-ci build is failing / complaining)

**Comment by jackpoz** [comment]
could you explain more in detail why IsInWhisperWhiteList() is not enough ?

**Comment by Gooyeth** [comment]
@jackpoz: IsInWhisperWhiteList() only allows the whisper with ".whisper off", the functionality of it is to avoid that anyone can give whispers if it is not on the list, instead ".whisper on" allows whisper to all players

**Comment by Gooyeth** [comment]
@illfated: is failing because of this eb1972f21d6e79da32a89cb58c5c28eb98b0a4fb 😛

**Comment by illfated** [comment]
You are right. I should have noticed.
None of the TC members have fixed that build issue yet. :-\

**Comment by jackpoz** [comment]
> Tests performed: It needs to be tested.

please test it ingame, after that I'd say it can be merged

**Comment by Gooyeth** [comment]
@jackpoz: https://github.com/TrinityCore/TrinityCore/issues/22283#issuecomment-414896588

**Comment by jackpoz** [comment]
could you please describe a bit more in detail the tests done ? like, was a test with no GM account done to ensure the old checks still apply ?

**Comment by WOW-Reborn** [comment]
Tested on my server and is working correctly.  I can now as a horde GM whisper to alliance players without them receiving the error about me being in a different faction.

**Comment by illfated** [comment]
@Gooyeth : could you rebase your PR branch on current 3.3.5 source so the travis-ci check does not show that outdated "fail" status?

**Comment by Gooyeth** [comment]
@illfated: Ready 😄

**Comment by Asandru** [comment]
Works

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Aokromes** [comment]
now if you have CONFIG_CHAT_WHISPER_LEVEL_REQ  for example to level 10 people under level 10 can whisper other persons @Gooyeth

**Comment by jackpoz** [comment]
> could you please describe a bit more in detail the tests done ? like, was a test with no GM account done to ensure the old checks still apply ?

I asked on the 23rd of August to test that exact test case...
When fixing an issue one is supposed not just to test if the change fixes the issue but if all the existing code still works as intended.

**Comment by jackpoz** [comment]
I reverted this PR since it was bugged, quite sad none tested what I asked 4 months ago to be tested.
Please re-submit the changes with support to existing checks about CONFIG_CHAT_WHISPER_LEVEL_REQ

**Comment by jackpoz** [comment]
PR rewritten at https://github.com/TrinityCore/TrinityCore/commit/f11117584d0b787bbf36ae61dad2b46e559b0953

**Pull request merged**
