### PR TITLE
Core/SmartScripts: new SAI action SMART_ACTION_SET_MOVEMENT_SPEED

### PR DESCRIPTION
**Pull request by Lopfest**
**Changes proposed:**
-  implement new SMART_ACTION_SET_MOVEMENT_SPEED
- action_param_1 = movementType from UnitMoveType enum
- action_param_2 = sniff speed value (only integer part, before decimal point)
- action_param_3 = sniff speed value (only fraction part, after decimal point if any)

**Target branch(es):** 3.3.5/master
- [x] master

**Issues addressed:** -

**Tests performed:** tested in-game

**Known issues and TODO list:** -

### CODE REVIEW

**Comment by Infinito47** [comment]
Woul this also affect swim speed?

**Comment by Shauren** [comment]
Why do you see the need to use 2 separate fields? (speedDivider)

**Comment by Lopfest** [comment]
more precise speed adjustment.
RunSpeed: 8 in sniffs is 1.14286 in DB right?
When you want to set (sniff) speed to 14, you will set action_param_2=2, action_param_3=1
8/1,14286=7 - should be basic run coefficient
14/7=2
Thats ok, but what if I want set (sniff) speed to something indivisible by 7, for example 10,5 for simplicity?
10,5/7=1,5 - what two whole numbers give result 1,5?
3/2=1,5 - action_param_2=3, action_param_3=2

im not saying it will be accurate, but setting speed only to whole numbers is not always what you want.

**Comment by Shauren** [comment]
right, i forgot they are ints in db, not floats

**Comment by Lopfest** [comment]
@Shauren, should I add these parameters also to SMART_ACTION_SET_FLY and SMART_ACTION_SET_SWIM?

**Comment by Shauren** [comment]
Wouldnt it be better to extract this into a new SMART_ACTION_SET_MOVEMENT_SPEED with your 2 params + movement type?

**Comment by Lopfest** [comment]
ok, i dont have problem with that. ill do it today

**Comment by Aokromes** [comment]
@Shauren this can be merged?

**Pull request merged**
