### PR TITLE
Core/AI: Make charmed creatures follow their owner

### LINKED ISSUE #24103: Core/AI: Charrmed creature must follow the owner upon charmed
**Description:** If you charm a creature it will not follow you unless you use the command from the pet bar, this is wrong as some charms doesn't have that, like here https://github.com/TrinityCore/TrinityCore/issues/22330#issuecomment-577941413

**Steps to reproduce the problem:**

1. .cast 260  in any creature
2. notice it will not follow you

**Branch(es):** both

**TC rev. hash/commit:** rev. 78c1216bcf60

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Make charmed creatures follow their owner (it doesn't affect CHARM_TYPE_POSSESS and CHARM_TYPE_VEHICLE, not sure about CHARM_TYPE_CONVERT)

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #24103

**Tests performed:** Tested #24103 casting spell 260 to a creature

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] test charming a creature into a pet

### CODE REVIEW

**Comment by jackpoz** [comment]
@Killyana please test this when you have time

**Comment by Killyana** [comment]
I get 2 issues:
1- If npc is using SmartAI it will not follow you
2- if you dismiss the charmed unit it will keeps follow you instead returning to homepos (if it cannot attacks you)

**Comment by jackpoz** [comment]
The 2nd issue exists already in 335

**Comment by Killyana** [comment]
Entry: 3100  with SAI
Entry: 4311 without SAI

**Comment by jackpoz** [comment]
Fixed the SAI issue

**Comment by Killyana** [comment]
It works fine now for both AI

**Comment by jackpoz** [comment]
The "charmed unit should return home" issue will be fixed in another PR as it exists in 335 already

**Comment by Rushor** [comment]
this fix is dope, after all those years - finally! Thank you jack <3

**Pull request merged**
