### PR TITLE
[3.3.5] Game/SpellMgr: DBC correction for Pestilence

### PR DESCRIPTION
**Pull request by P-Kito**
**Changes proposed**:
- Pestilence currently only works for targets infront of the DK, remove cone effect which makes no sense

**Target branch(es)**: 335

**Issues addressed**: https://github.com/TrinityCore/TrinityCore/issues/15040

**Tests performed**: Ingame tested

**Known issues and TODO list**:     --------

### CODE REVIEW

**Comment by P-Kito** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15040
Some discussion there

**Comment by NorthStrider** [comment]
Isn't effect_1 a dummy effect and according to that not the actual trigger? effect_2 is a 10 yards script effect which should handle the spreading. So the spellscript seems to be more inaccurate.

**Comment by Shauren** [comment]
What really happens here:
1. EFFECT_0 targeting - the unit we selected to spread diseases from
2. EFFECT_1 targeting - moves DEST 5 yards in front of caster
3. EFFECT_2 targeting - selects all enemies in 10 yard radius centered on DEST moved in EFFECT_1

Not sure if this is a bug at all.

**Comment by P-Kito** [comment]
According to the discussion diseases will only spread in that cone effect. But you are right @Shauren , it should be like that exactly.

**Comment by ccrs** [comment]
not cone, but 10 yards around 5 yards in front of caster

**Comment by P-Kito** [comment]
Suggestion: Rewrite the spellscript according to Shaurens idea.

**Comment by Greymane** [comment]
Just use a OnDestinationTargetSelect hook into EFFECT_1 and move the Dest back to EFFECT_0 target's position, that will fix the problem.

**Pull request closed without merging**
