### PR TITLE
Core/PacketIO: Update more opcodes for 6.1.0 (3 commits in total)

### PR DESCRIPTION
**Pull request by DJScias**
Edit: Removed the ticket-related opcodes.

Documentation used:
- https://github.com/TrinityCore/WowPacketParser/commit/0ab3e7ae01739f2d539f7ccfd670916013a3f7ce -- REMOVED
- https://github.com/TrinityCore/WowPacketParser/commit/ee24504ade21ed1fbd23f5f50fe081557fb643d6 -- REMOVED
- https://github.com/TrinityCore/WowPacketParser/commit/1a96b789726fa786e476e8af53d43f24d73681e6

**Note: I only change opcodes.cpp status to what they were before they were all put back to 'STATUS_UNHANDLED' for update 6.1. The ones that were 'UNHANDLED' before I don't change the status of as I have no means to figure these out correctly.**

### CODE REVIEW

**Comment by MitchesD** [comment]
do not update opcodes related to this https://github.com/TrinityCore/TrinityCore/pull/14169

**Comment by DJScias** [comment]
@MitchesD Will revert to last stable commit and only push the speed change opcodes.

**Comment by DJScias** [comment]
Removed the ticket-related opcodes per your request @MitchesD.

**Comment by Carbenium** [comment]
Please squash your commits.

**Comment by DJScias** [comment]
Fixed what had to be fixed, will use a new branch next time for commits.

Thanks @DDuarte.

**Pull request merged**
