### PR TITLE
[3.3.5] Core/Scripts: Migrates Professor Dabiri to SAI.

### PR DESCRIPTION
**Pull request by mysterious-static**
**Changes proposed**:
- Removes Professor Dabiri from zone script and adds him to SAI.

**Target branch(es)**: 3.3.5

**Tests performed**: Tested in-game; the scripted behavior still works fine after migrating to SAI.

**Known issues and TODO list**:
- [ ] I'd imagine this NPC still behaves the same on live since it's an Outland NPC, so if anyone with an active account could check, that might be a good idea.

It was rough to disappear for so long. Battles with eyestrain put me in a bad place to continue actively working on this. Apologies to @tkrokli and to devs for dropping off the face of the planet for 6 months. I'm  hoping to be able to contribute more consistently moving forward.

### CODE REVIEW

**Comment by velinath** [comment]
i missed you folks a lot.

**Comment by tkrokli** [comment]
NewLine (Enter) missing at the end of the SQL file. Going to test this PR ASAP.

**Comment by velinath** [comment]
rebased, thanks :+1:

**Comment by Aokromes** [comment]
You don't need to rebase anymore :)

**Comment by tkrokli** [comment]
Updated your SQL, it was missing `<space>` between the comment dashes -- and the comment text.

**Comment by velinath** [comment]
sorry, personal codestyle leaking :P

**Pull request merged**
