### PR TITLE
Core/AI: Clarify CreatureAI::UpdateVictim() return values

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Change CreatureAI::UpdateVictim() to return true only if me->GetVictim() would return a valid object. This is the expected behavior by a lot of scripts:
```cpp
void UpdateAI(uint32 diff) override
{
  if (!UpdateVictim())
    return;
  me->GetVictim()->DoStuff();
}
```

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

 None

**Tests performed:** (Does it build, tested in-game, etc.)

No build or tests performed

**Known issues and TODO list:** (add/remove lines as needed)

No todo list

### CODE REVIEW

**Comment by jackpoz** [comment]
Summoning @Treeston

**Comment by jackpoz** [comment]
Is that the new behavior or has it always been like that ?

**Comment by Treeston** [comment]
Always been like that to the best of my knowledge.

**Comment by Shauren** [comment]
Except `UpdateVictim` currently does not make it enter evade mode in the last elseif branch

**Comment by jackpoz** [comment]
then maybe those scripts that expect UpdateVictim() to return true when there's a victim should call something like UpdateAndCheckVictim() (or UpdateAndHasVictim() or whatever name) instead

**Comment by Treeston** [comment]
...or just `if (!UpdateVictim() || !me->GetVictim()) return;`?

**Comment by jackpoz** [comment]
let's keep that as new suggested pattern for scripts then

**Comment by Shauren** [comment]
Scripts werent using UpdateVictim to check if there is one but as a "IsInCombat" check combined with updating the current target

**Pull request closed without merging**
