### PR TITLE
Core/AT: Fix areatrigger type disk on growing radius

### PR DESCRIPTION
**Pull request by aquadeus**
Credits to: meji46

**Changes proposed:**

-  Fix areatrigger type disk on growing radius (like disintegration halo)

**Tests performed:**

Tested in-game

### CODE REVIEW

**Comment by Seyden** [comment]
Thats a bad way of doing it, because there are probably a lot more factors playing a role here.. Scale Curve, Extra Scale Curve and and and and

**Comment by mdX7** [comment]
> Thats a bad way of doing it, because there are probably a lot more factors playing a role here.. Scale Curve, Extra Scale Curve and and and and

scale curve stuff is nyi and that stuff can be added when its implemented

**Comment by Traesh** [comment]
This fix won't work as some disk areatriggers just don't grow overtime.

Example with Kurog, search for "Erupting Bedrock" https://www.mythictrap.com/en/vault/kurog

He spawns multiple disks one after another but each disk is static

**Comment by Nyr97** [comment]
Halls of Infusion for Khajin boss as well: we have the same entry areatrigger being sent for 3 different disk sizes (also it's a serverside areatrigger, spell is unk).

**Pull request closed without merging**
