### PR TITLE
[3.3.5] replace UNIT_FLAG_REMOVE_CLIENT_CONTROL with UNIT_STATE_ROOT

### PR DESCRIPTION
**Pull request by adeutscher**
Uploading this change for review, but I still need to double-check most of the encounters.

**Changes proposed**:
- Applications and removals of UNIT_FLAG_REMOVE_CLIENT_CONTROL (formerly UNIT_FLAG_DISABLE_MOVE) should be replaced with the setting of the UNIT_STATE_ROOT state.

**Target branch(es)**: 335

**Issues addressed**: None

**Tests performed**:

Testing incomplete - I still want to go through each changed encounter and double-check, but the items that have been tested look good:
- Ionar successfully stays in place when dispersing (also confirmed that he would follow the player while invisible in a tongue-in-cheek build that did not set the state).
- Ulduar: Hodir is strange in general at the moment, but Flash Freezes don't seem to move.
- ToC25 - Beasts of Northrend - Worms are successfully switching root states when they burrow.
- Azjol-Nerub: Spikes don't seem to be moving

**Known issues and TODO list**:

These are the encounters that I have yet to double-check:
- [ ] Ulduar: Confirm Vezax
- [ ] Ulduar: Confirm Ignis
- [ ] Ulduar: Confirm Kologarn
- [ ] VoA: Confirm Toravon
- [x] Forge of Souls: Confirm Devourer of Souls
- [ ] Naxxramas: Confirm Kel'thuzad
- [ ] ToC25: Confirm Icehowl
- [x] Confirm Archaedas
- [x] Confirm general Uldaman/Ironaya

### CODE REVIEW

**Comment by adeutscher** [comment]
Strange place for a build error, looks like the merge introduced a hiccup that I didn't check for before making this PR (was building successfully prior to the merge). Investigating.

**Comment by tkrokli** [comment]
It wasn't your PR that did it. Refresh your PR and you will see that travis-ci will compile it OK. :-)

**Comment by adeutscher** [comment]
Thanks! I'm unfamiliar with the model management stuff that was wonky, so I was doing a fair bit of stumbling.

**Comment by jackpoz** [comment]
"Feature remove disable move" looks like an unclear and misleading title for this PR, is this the rework of some instance ?

**Comment by LordUsagi** [comment]
Thanks. This is what I did immediately after realizing the change.

**Comment by tkrokli** [comment]
Suggestion for a more precise PR title, based on the details in the first PR comment:
**[3.3.5] replace UNIT_FLAG_REMOVE_CLIENT_CONTROL with UNIT_STATE_ROOT**
(you may want to specify the details in the first PR post, like that this is for some bosses and instances)

**Comment by sirikfoll** [comment]
If you can, please, drop the part about boss_ahune, i'm changing it on pr #17320, thanks :bowtie:

**Comment by adeutscher** [comment]
@sirikfoll , done. `boss_ahune.cpp` is now back to matching the 3.3.5 branch.

**Comment by Shauren** [comment]
Question - are these bosses supposed to be visible to client as rooted (Root movement flag sent) or just not moving serverside? (using `Unit::SetControlled(true, UNIT_STATE_ROOT);`)

**Comment by adeutscher** [comment]
@Shauren , I'm not entirely sure that I understand the distinction. I can confirm that in most of these cases (Ionar would be an exception) that the NPC should be visible to the player while they're rooted, though not necessarily selectable.

**Comment by Shauren** [comment]
Simple - AddUnitState does not cause MOVEMENTFLAG_ROOT to be added to creature while SetControlled does.

**Comment by Aokromes** [comment]
Any new on this? @Shauren @adeutscher

**Comment by adeutscher** [comment]
I hope to start working on the checklist this weekend, things have been busy.

**Comment by adeutscher** [comment]
Tested a few items:

* The encounters in Uldaman seem to be behaving properly.
* The targetting on the Devourer of Souls' Wailing Souls spell is pretty out to lunch, with the real damage looking like it's always seems to happen at the same angle out of the boss, but the boss is still staying in one place as it rotates. Also, the boss will adjust its facing temporarily in response to a direct damage attack. The wonky attack field seems like it is outside the scope of this PR, but the facing is something is somewhat related to movement. I've fixed this for the moment by also adding in `UNIT_STATE_CANNOT_TURN` (which does not affect the manual turning of the Wailing Souls event).

**Pull request closed without merging**
