### PR TITLE
Core/Waypoints: Attempt to fix "smooth" waypoints

### PR DESCRIPTION
**Pull request by gerripeach**
WIP

this will send the next 3 wp verticies to the client.

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
#13467

**Known issues and TODO list:** (add/remove lines as needed)
- [ ] check if formations still work as intended

### CODE REVIEW

**Comment by Ovahlord** [comment]
formations are broken. the troup is following only if a point has been reached. I think formations need a constant update rather than just on point reached

**Comment by Ovahlord** [comment]
Also another small issue: 
if the creature's next wayoint makes her turn arround by about 180 degrees for example the creature skips a bit of her path. you might check that out to make those waypoints not affected by the smoothing

**Comment by Krudor** [comment]
I think thats more a matter of the path reaching its destination and resetting.
Paths should generally end where the creature needs to do a 180 turn.

**Comment by lachtanek** [comment]
Maybe I'm wrong, I don't really understand all the waypoint code, but does MovementInform still work for the points that were sent together?
Also, the first condition if the for loop could be part of the loop's condition

**Comment by gerripeach** [comment]
will update it later

**Comment by ccrs** [comment]
unfinished, but the concept is correct

**Comment by gerripeach** [comment]
haveing problems with movement inform.. fixes leading to crashes..

**Pull request closed without merging**
