### PR TITLE
Fixed wrong permissions for .lookup map commands

### PR DESCRIPTION
**Pull request by kelno**
Due to a typo

### CODE REVIEW

**Comment by Warpten** [comment]
Nice.

**Comment by Shauren** [comment]
toppest kek

**Comment by illfated** [comment]
👍 Nice work, thank you for finding that typo. Also, thanks for the chuckle. 😄

**Comment by kelno** [comment]
Thank you I'm happy to contribute with those major issues, tonight I'll sleep well knowing TrinityCore is one step closer to perfect.

**Comment by MaxtorCoder** [comment]
Lmfao 😂😂

**Pull request merged**
