### PR TITLE
Scripts/Spells: Deathbolt

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Migrate spell Deathbolt to spell scripts system.

**Target branch(es):** 3.3.5

**Tests performed:** Works

### CODE REVIEW

**Comment by Aokromes** [comment]
btw, i have one tip for you to allow yo to do more prs at once without making one big pr

if you want to move spells 1,2,3,4,5,6,7,8,9
make pr for 1,3,5,7,9
when they are merged you can do 2,4,6,8

**Comment by Sorikoff** [comment]
But https://github.com/TrinityCore/TrinityCore/pull/23454#issuecomment-504028884

**Comment by Aokromes** [comment]
no no, i mean separate prs for each of those spells.

**Comment by Sorikoff** [comment]
:+1:

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
