### PR TITLE
Core/Entities: reset creature states when Hunter dismisses a pet

### LINKED ISSUE #20769: Mind Control rendering mobs/NPCs useless
**Description:**

Using Mind Control on a humanoid and canceling it renders it useless, not attacking the attacker, just standing, or following his waypoints, he will not retaliate or start casting spells if attacked, he will not aggro.

**Current behaviour:**

I use Mind Control, Cancel it and the mob stops attacking me, and will never attack again until killed and respawned.

**Expected behaviour:**

I use Mind Control, he gets controled, after I cancel it, he should start attacking me if I reach his aggro range or start attacking him.

**Steps to reproduce the problem:**

1. Use Mind Control (Spell ID 605) on a humanoid,

I tested it on Wastewander Bandit, and one of my players reported it in Stratholme.

**Branch(es):**  3.3.5

**TC rev. hash/commit:** TrinityCore rev. 6070340 2017-10-07 17:13:34 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Operating system:** Windows 10

### PR DESCRIPTION
**Pull request by Langerz82**
**Changes proposed:**

Fixes Creature states when Hunter dismisses a pet.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #20769

**Tests performed:**
Tested on different repository and patch applied and tested.

**Known issues and TODO list:**

- [ ] Needs to be tested with all Minions/Pets.
- [x] No SQL change needed.

### CODE REVIEW

**Comment by Langerz82** [comment]
This is my first PR so please be gentle if I've made any mistakes regarding submission. ^__^

**Comment by tkrokli** [comment]
In the PR description, you state that this PR "Fixes Creature states when Hunter dismisses a pet." and that it closes issue #20769 (**Mind Control rendering mobs/NPCs useless**). That issue is mostly about humanoids not returning to their original react state and not attacking player after Mind Control ends or being cancelled. Does this PR fix that issue too, or is this only about resetting player combat pet creatures and their react state towards player after being dismissed from a taming session?

**Comment by Langerz82** [comment]
PR Needs to fix original issue properly.

**Comment by tkrokli** [comment]
OK, I see. My intention was to make sure the PR description matches the PR content, so if it does not solve the referred issue ticket, maybe it solves a different issue? If that is the case, you could choose to change the description to refer to a different issue being solved by the current PR content. Then again, if you want to focus on solving the linked issue, the choice is yours.

**Comment by Langerz82** [comment]
I would ideally like to fix both issues, so that's what I'm trying to do. My last PR was breaking Mind control so I definitely gotta fix it.

**Pull request closed without merging**
