### PR TITLE
[master] 3.3.5 -> master cherry-pick

### PR DESCRIPTION
**Pull request by funjoker**
**Changes proposed:**

-  
-  
-  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by funjoker** [comment]
WTF is this auth error xD 
Is there something broken with my repo ?

**Comment by funjoker** [comment]
final

**Comment by msoky** [comment]
I am not totally sure, but probably there is missing this commit
https://github.com/TrinityCore/TrinityCore/commit/59db2eeea0a35028779fd76372ae06cc98c8086f

for this issue
https://github.com/TrinityCore/TrinityCore/issues/20980

**Comment by funjoker** [comment]
it was seperate branch and was added around end of July 2017 even if it's dated may.

**Comment by msoky** [comment]
thank you and what about this? https://github.com/TrinityCore/TrinityCore/commit/4096b02a560499d2cb2f40c67ac0b30ed4c48ffd

**Comment by funjoker** [comment]
this is merges afaik

**Pull request merged**
