### PR TITLE
Core/Criterias: Send Scenario GUID in scenario progress packet

### PR DESCRIPTION
**Pull request by Ghaster**
**Changes proposed:**

-  Modified SetCriteriaProgress to take an ObjectGuid rather than a player.
-  This allows us to send the Scenario GUID as the "player" in the scenario progress packet (matches sniff behavior)

**Issues addressed:**

None

**Tests performed:**

Builds, tested in game in with dungeon bosses display.

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Review by Shauren — CHANGES_REQUESTED** [review]
This doesn't work at all, criteria updates for scenario (actual updates, not initial loading) happen through `Player::UpdateCriteria` which still uses `referencePlayer` to fill the guid

**Comment by Ghaster** [comment]
Refactored it a bit s.t. the guid is retrieved based on the relevant class instead. Tested ingame and doesn't crash. Still not sure about SMSG_GUILD_CRITERIA_UPDATE as I don't have any usage of that in my sniffs, but should be easy enough to implement now incase it uses the guild guid.

**Review by Shauren — CHANGES_REQUESTED** [review]
This is all completely unneccessary, just edit `Scenario::SendCriteriaUpdate` (and possibly `Scenario::GetCriteriasProgressFor`)

Got sniff of SMSG_SCENARIO_PROGRESS_UPDATE and SMSG_SCENARIO_STATE with non-empty criteria progress?

**Comment by Ghaster** [comment]
> Got sniff of SMSG_SCENARIO_PROGRESS_UPDATE and SMSG_SCENARIO_STATE with non-empty criteria progress?

Both from 10.2.6, SMSG_SCENARIO_PROGRESS_UPDATE parsing is broken, but the guid is still correctly parsed.

```
ServerToClient: SMSG_SCENARIO_STATE (0x2628) Length: 453 ConnIdx: 1 Time: 04/10/2024 20:55:20.606 Number: 22952
ScenarioGUID: Full: 0x????????????????????????????????? Scenario/0 R?/S? Map: 1475 Low: ?
ScenarioID: 824
CurrentStep: 1792
DifficultyID: 0 (0)
WaveCurrent: 0
WaveMax: 0
TimerDuration: 0
CriteriaProgressCount: 7
BonusObjectiveDataCount: 0
PickedStepsCount: 3
SpellsCount: 0
PlayerGUID: Full: 0x????????????????????????????????? Player/0 R?/S0 Map: 0 Low: ?
[0] PickedStep: 1790
[1] PickedStep: 1792
[2] PickedStep: 1791
ScenarioComplete: False
(CriteriaProgress) [0] CriteriaID: 28125 (28125)
(CriteriaProgress) [0] Quantity: 1
(CriteriaProgress) [0] PlayerGUID: Full: 0x????????????????????????????????? Scenario/0 R?/S? Map: 1475 Low: ?
(CriteriaProgress) [0] Unused_10_1_5: 0
(CriteriaProgress) [0] Flags: 0
(CriteriaProgress) [0] CurrentTime: 04/10/2024 20:53:00
(CriteriaProgress) [0] ElapsedTime: 01/01/1970 00:01:46
(CriteriaProgress) [0] CreationTime: 01/01/1970 00:01:46
(CriteriaProgress) [0] HasRafAcceptanceID: False
```

```
ServerToClient: SMSG_SCENARIO_PROGRESS_UPDATE (0x2629) Length: 54 ConnIdx: 1 Time: 04/10/2024 20:55:20.606 Number: 22951
(Progress) Id: 28117 (28117)
(Progress) Quantity: 30
(Progress) Player: Full: 0x????????????????????????????????? Scenario/0 R?/S? Map: 1475 Low: ?
(Progress) Date: 01/01/2000 00:00:00
(Progress) TimeFromStart: 01/01/1970 00:00:00
(Progress) TimeFromCreate: 11/12/1982 12:57:27
(Progress) Flags: 7
```

**Review by Shauren — APPROVED** [review]

**Pull request merged**
