### PR TITLE
Scripts/TrialOfTheCrusader: Anub'Arak Enable Emerge Emote

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Enable Emerge Emote Anub'Arak. The emote is in the database, but it was never called in the script.

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [X] master

**Issues addressed:** Closes #  (insert issue tracker number)
- none

**Tests performed:** (Does it build, tested in-game, etc.)
yes and yes

### CODE REVIEW

**Comment by Keader** [comment]
Maybe this can help you @Rushor https://gist.github.com/Keader/6dda8a7dd898c9bd294da6265224b253
Needs some cleanup (i did it sometime ago to my old server)
(idk if you saw in irc xd)

**Comment by Rushor** [comment]
but i only want to enable the emote, not cleanup the whole script :D

**Comment by Keader** [comment]
implement intro event too !!! :(

**Comment by Keader** [comment]
haha, okey :/

**Pull request merged**
