### PR TITLE
DB\CORE: IP HISTORY LOGGING

### PR DESCRIPTION
**Pull request by acidmanifesto**
**Changes proposed:**

- new Auth Table account_ip_history
- Enables the account ip history logging to account_ip_history of the auth table.
- Primary Keys are Account and IP.
- Assist in logging account ip history of the user every time they login.
- Loggs Account, RealmID,IP, date_recent, date_first.
- comment collumn added for any manual review notes
- conf set to disable for whatever nsa\fbi\dickpic\gdprroflmaocopter requirement.
- Added a del prep statement to clear account specific ip history log when account is deleted.

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

Builds and Tested in game
image
Observe the screen shot.
Account 1 logged in at for the first time since this PR at 2024-04-17 17:54:03 in date_first
Account 1 then logged off and relogged in with the same IP at 2024-04-17 17:55:01 Date Recemt
Account 3 is logging in the same ip as Account 1. So since it is its first login, both date_recent and date_first are the same.
If Account 1 logged in from a different ip then a new row is created.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by CraftedRO** [comment]
what about some "auto-clean" old records function ?

**Comment by acidmanifesto** [comment]
> what about some "auto-clean" old records function ?

This is a history log for ip history of a player account. I am not entirely certain what you mean by a auto-clean?

Only new entries are created if the account and ip changes.

It will only update timestamps of exsisting accounts/ip address entries.

It isnt like say a server.log or anticheat.log where it just continuously fills.

**Comment by Jinnaix** [comment]
Looks good to me

**Comment by Aokromes** [comment]
i requested such feature long time ago :)

**Comment by Faq** [comment]
But what is real use case for such info?

**Comment by Jinnaix** [comment]
Use cases are clear for anyone who ever had TC in a productive environment

**Comment by acidmanifesto** [comment]
> But what is real use case for such info?

Identifying a user(s) that may be multiboxing, vpn ips, various ips for either tracking of potentional malicious behavior or ban bypassing just to name a few.

**Comment by Faq** [comment]
I guess then some helper would be view to show accounts with same IPs? As now you will check this only if reported, but could be done proactive? You know best where you will use this info, just saying that it can be improved, as now, this looks like basic implementation.

**Comment by acidmanifesto** [comment]
> I guess then some helper would be view to show accounts with same IPs? As now you will check this only if reported, but could be done proactive? You know best where you will use this info, just saying that it can be improved, as now, this looks like basic implementation. Just thinking next steps from use case perspective, nothing against such implementations.

I am up for any suggestions.

**Comment by Aokromes** [comment]
> I guess then some helper would be view to show accounts with same IPs? As now you will check this only if reported, but could be done proactive? You know best where you will use this info, just saying that it can be improved, as now, this looks like basic implementation. Just thinking next steps from use case perspective, nothing against such implementations.

imho all this must be handled by minimanager taking data from this table, ie searching accounts who used certain ips etc.

**Comment by Jinnaix** [comment]
@acidmanifesto 

Just for logical reasons - can you please bind this to the following feature being enabled?

image

Would be stupid to suppress ip logging in database but still create logging history.

It would also make more sense to place your config option right below that setting here https://github.com/TrinityCore/TrinityCore/blob/3a9c129747a743e9e722d1877b23491e5c24bd0c/src/server/worldserver/worldserver.conf.dist#L1431 instead of the file log area.

**Comment by acidmanifesto** [comment]
> @acidmanifesto
> 
> Just for logical reasons - can you please bind this to the following feature being enabled?
> 
> image
> 
> Would be stupid to suppress ip logging in database but still create logging history.
> 
> It would also make more sense to place your config option right below that setting here
> 
> https://github.com/TrinityCore/TrinityCore/blob/3a9c129747a743e9e722d1877b23491e5c24bd0c/src/server/worldserver/worldserver.conf.dist#L1431
> 
> instead of the file log area.

done https://github.com/TrinityCore/TrinityCore/pull/29926/commits/ca06252bba23bf14d8271fc1f103ed00305b6ff4

**Comment by acidmanifesto** [comment]
> @acidmanifesto
> 
> Just for logical reasons - can you please bind this to the following feature being enabled?
> 
> image
> 
> Would be stupid to suppress ip logging in database but still create logging history.
> 
> It would also make more sense to place your config option right below that setting here
> 
> https://github.com/TrinityCore/TrinityCore/blob/3a9c129747a743e9e722d1877b23491e5c24bd0c/src/server/worldserver/worldserver.conf.dist#L1431
> 
> instead of the file log area.

https://github.com/TrinityCore/TrinityCore/pull/29926/commits/ab09dbfc85da8385941396d7a4979b401f7218c2

**Comment by Shauren** [comment]
I'm going to close this - it unneccessarily duplicates what `Allow.IP.Based.Action.Logging` (combined with `AllowLoggingIPAddressesInDatabase`) already does

Query to extract the same data as what this PR proposes
```sql
SELECT
    lia.account_id, 
    lia.ip, 
    MIN(lia.time) AS date_first, 
    MAX(lia.time) AS date_recent
FROM
    logs_ip_actions AS lia
WHERE
    lia.type = 0 -- successful logins
GROUP BY
    lia.account_id, 
    lia.ip
```

**Pull request closed without merging**
