### PR TITLE
Fixed a typo in MovementHandler.cpp

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5

- [x] 3.3.5

**Tests performed:** Compiles

Fixed a typo according to the comment.

### CODE REVIEW

**Comment by Kittnz** [comment]
Did you test this?

**Comment by xinef1** [comment]
Had this changed since 2014 and no complaints. The logic is simple, if environmental damage didn't kill player (because of immunity aura or something else), we should kill him by force.

**Comment by chaodhib** [comment]
Thanks for the PR.

I did not test the changes but it does make sense.

**Comment by Palabola** [comment]
This change work, tested at Eye of the Storm and some other Zones.

**Pull request merged**
