### PR TITLE
Core/Networking: Give 30 seconds on shutdown to close all connections

### PR DESCRIPTION
**Pull request by jackpoz**
Give max 30 seconds on shutdown to close all connections before forcibly closing the connection.

**Changes proposed:**

-  Give max 30 seconds on shutdown to close all connections before forcibly closing the connection.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
Ref #20032

**Tests performed:** (Does it build, tested in-game, etc.)
None

**Known issues and TODO list:** (add/remove lines as needed)
- [ ] Test on Windows
- [ ] Test on *nix
- [ ] Test TCSOAP

### CODE REVIEW

**Comment by jackpoz** [comment]
Please not shutdown will take some more time as it will try to wait up to 30 seconds for the client to acknowledge the socket closing

**Comment by illfated** [comment]
Please note: * ^

**Comment by Hir0shi** [comment]
@Shauren => Seems legit to me too !

**Comment by Hir0shi** [comment]
thank you @jackpoz 

you so sexy!

**Comment by TheWinchesters** [comment]
Should the issue be closed if this works?
The problem will still occur if worldserver crashes.

**Comment by illfated** [comment]
in that case, there are 2 desirable features we could wish for:
1. The 30 seconds delay to be activated only if SOAP is activated (or any similar socket acceptor usage)
2. Force close all sockets when a crash is triggered (if that is at all possible)

**Comment by jackpoz** [comment]
@Hir0shi did you apply this PR locally ? does it work ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/46f2595f511011d577be0ecee3d9f44c980ddc92

**Pull request closed without merging**
