### PR TITLE
Vmap: Introduce skipping of antiportals and unreachable mogp

### PR DESCRIPTION
**Pull request by killerwife**
Introduces mogp skip flags, antiportals from master, unreachable from my own repository (cmangos)

Note: I will not be porting fixes for https://github.com/cmangos/mangos-wotlk/commit/a734a7288a673400ca231aafa50fab3a52780302 if someone wants to do it go ahead.

### CODE REVIEW

**Comment by Shauren** [comment]
@ whoever merges: either make code in ExtractSingleWmo look like it does in master branch, or adjust master branch to look like this one

**Comment by jackpoz** [comment]
this PR has been updated with the codestyle of master branch

**Comment by ccrs** [comment]
@jackpoz maybe you can take a look to those remaining fixes @killerwife mentioned? 😅

**Comment by jackpoz** [comment]
To do: bump vmap version

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
