### PR TITLE
Core/Spells: Fixed a possible crash in spell_pal_light_s_beacon

### PR DESCRIPTION
**Pull request by Zedron**
Fixes a possible crash in spell_pal_light_s_beacon aurascript

### CODE REVIEW

**Comment by joschiwald** [comment]
did you got such crash? actiontarget should not be null in this situation

**Comment by Zedron** [comment]
in Unit::Kill, victim->ProcDamageAndSpell(NULL

**Comment by jackpoz** [comment]
> No description provided.

Please provide a description

**Comment by joschiwald** [comment]
this aura should not proc in Unit::Kill

please provide a crash log

**Comment by Shauren** [comment]
@joschiwald it doesn't matter - crashing depending on database data (proc flag overrides are possible after all) is not a good thing.

**Pull request merged**
