### PR TITLE
Core/Movement: Fix Scatter Shot issue on moving players - cleaner approach 

### PR DESCRIPTION
**Pull request by chaodhib**
Cleaner approach to https://github.com/TrinityCore/TrinityCore/pull/18336

The first commit is sufficient as a fix on its own (and as you can see, it does not actually touch the Confused MoveGen code). In the second commit I try to make Confused MoveGen more retail like but it's minor changes.

The general idea of the fix is that the methods Unit::IsStopped() and Unit::StopMoving() should now work properly on player-moved units, which was not the case until now.

The PR is ready to be reviewed and potentially merged. However, the changes here have much broader implications than in the first PR, so extensive testing is needed.

**Target branch(es):**

- [X] 3.3.5

**Issues addressed:** Closes #  https://github.com/TrinityCore/TrinityCore/issues/15952

**Tests performed:** Tested IG. Works against moving players.

**Known issues and TODO list:** Nothing that I'm aware of.

### CODE REVIEW

**Comment by ForesterDev** [comment]
Maybe we should use same methods to fix "fear teleport" report? https://github.com/TrinityCore/TrinityCore/issues/18306#issuecomment-263516101

**Comment by chaodhib** [comment]
@ForesterDev I replied in the thead. I don't think it will help with Fear. The movement generator that fear uses probably needs to be rewritten.

**Comment by Aokromes** [comment]
So, close https://github.com/TrinityCore/TrinityCore/pull/18336 ?

**Comment by shenhuyong** [comment]
I tested it, I found a bug, the waypoints of creatures are not working.

**Comment by chaodhib** [comment]
could you go more into the details? What is not working exactly? How to reproduce? Could you provide screenshots and/or a video?

**Comment by shenhuyong** [comment]
Go into Karazhan, you can find any mob or npc with waypoints will not move and only stay at the start point.

**Comment by chaodhib** [comment]
Indeed. Thanks for the feedback. I will see how to fix that.

**Comment by chaodhib** [comment]
Should work correctly now.

**Comment by Eliminationzx** [comment]
Looks ok to me.

**Comment by chaodhib** [comment]
Bump. This PR is also, as far as I can tell, ready to be merged.

**Comment by Aokromes** [comment]
jump into irc :)

**Comment by Treeston** [comment]
@chaodhib rebase & fix conflicts please then I can merge

**Comment by tripleslash** [comment]
@chaodhib Doesn't the issue mentioned in the issue post from you [here](https://github.com/TrinityCore/TrinityCore/issues/15952#issuecomment-263153057) still apply? Specifically this one:

When the player gets affected by the spell, he will be at a certain position. That position is what the players will see on their screens when the spell land. However because the server does not use extrapolation, it thinks that the player is still at the latest received position. Therefore, when the Confused MoveGen is gonna kick in, it's gonna start the spline at the wrong place.

**Comment by chaodhib** [comment]
@tripleslash 
No, I was wrong in my initial investigation:

The teleportation had 2 sources of "lag" and they were adding up. The first source was what i explained in the comment you mentioned. The second source however is much much bigger than the first. To the point where, the first source is actually a non issue. The glitch disappaears entirely once the second source is removed.

So what was the second source of lag? cf description of https://github.com/TrinityCore/TrinityCore/pull/18336#issue-192134046

I will resume working on this PR shortly after https://github.com/TrinityCore/TrinityCore/pull/18771 is merged.

**Comment by Killyana** [comment]
If you cast Scatter Shot on a player with a flying mount it will lands directly and execute Confused movements on ground.

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Movement/MovementGenerators/ConfusedMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp

**Comment by robinsch** [comment]
This is still a valid issue. Fix above doesn't work.

**Comment by chaodhib** [comment]
I can't reproduce the issue anymore, from 3.3.5 branch. Is it still valid?

**Comment by Killyana** [comment]
Still able to reproduce it, use 2 characters, put one on auto run with a mount and use Scatter Shot on it, he will play the confuse movement then instead stop moving he will kind of slide to a position and continue running.

**Comment by robinsch** [comment]
All movement gens have this issued. You can spam w and s and then fear the unit. It will desync the movement

**Comment by chaodhib** [comment]
@Killyana 
The only aim of this PR was to solve the small jump the target had at the start/end of the Scatter Shot effect (which made the follow up with Freezing Arrow very hard to execute). Since that jump is already fixed on the 3.3.5 branch, I don't see the point of this PR anymore. The animation at the end of the effect is out of scope. I don't think my PR ever fixed that problem sadly.

@robinsch I'm confused. Which issue are we talking about?

**Pull request closed without merging**
