### PR TITLE
Core/Spells: Fix reset ComboPoints

### PR DESCRIPTION
**Pull request by thomas33**
Target branch(es): master

Tests performed: Compiles and basic ingame tests

Reset Combo Points

### CODE REVIEW

**Comment by thomas33** [comment]
huh?

**Comment by Shauren** [comment]
Author: cyka blyat

**Comment by zamalaev** [comment]
From 284000a5226b5be0605f1c683320d1ca7666d126 Mon Sep 17 00:00:00 2001
From: zamalaev <zgn88@mail.ru>
Date: Tue, 3 Jan 2017 18:27:05 +0300
Subject: [PATCH] Core/Spell: add POWER_CHI to ResetAllPowers and fix clear
 combo points Rogue and Druid

---
 src/server/game/Entities/Player/Player.cpp | 7 +++++++
 1 file changed, 7 insertions(+)

```
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index e1c56fb..ef295aa 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -2024,6 +2024,10 @@ void Player::RegenerateHealth()
 
 void Player::ResetAllPowers()
 {
+
+    if (getClass() == CLASS_ROGUE || getClass() == CLASS_DRUID)
+        ClearComboPoints();
+
     SetHealth(GetMaxHealth());
     switch (getPowerType())
     {
@@ -2042,6 +2046,9 @@ void Player::ResetAllPowers()
         case POWER_LUNAR_POWER:
             SetPower(POWER_LUNAR_POWER, 0);
             break;
+        case POWER_CHI:
+            SetPower(POWER_CHI, 0);
+            break;
         default:
             break;
     }
```
original patch

**Comment by Warpten** [comment]
Oh look. Private fork owner complaining.

**Comment by zamalaev** [comment]
@Warpten It became private because they do not indicate the source

**Comment by Eliminationzx** [comment]
`if (getClass() == CLASS_ROGUE || getClass() == CLASS_DRUID) `
is necessary ?

**Comment by robinsch** [comment]
Isn't combo points used for reactives too?

**Comment by Shauren** [comment]
Not anymore, there are no reactives left in the game in legion

**Comment by lorac2k14** [comment]
@zamalaev I guess you cant read then ( private fork ) against the license and this action does nothing to help Trinitycore
Without Trinitycore you would not have a private fork
so instead of trolling the persons pr because they provided a solution regardless if it is yours or not maybe you should read the GPL you received in your initial pull 
I could have sworn it states somewhere any fixes are to be shared with the orig creators of source.
By going private you are hurting community as a whole then to come here and qq because someone opened a pull request with your code in it that too hurts the community so if you cant share please dont come here crying because somehow someone got hold of your source and posted a good fix  or a fix in general to help the community. it just shows you cant read the GPL or you just want to take and not give back.

**Pull request closed without merging**
