### PR TITLE
Core/Misc: Log more information in asserts

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Add a new function GetDebugInfos() to types that could trigger an ASSERT() to easily include more useful information in crashlogs.
-  If the type doesn't have the function, the global default one is picked which doesn't log anything.
- Types supported:
  - [x] Object
  - [x] WorldLocation
  - [x] WorldObject
  - [x] Unit
  - [x] Creature
  - [x] GameObject
  - [x] Player
  - [x] Item
  - [x] Bag
  - [x] Spell
  - [x] Aura
  - [x] Map
  - [x] InstanceMap
  - [x] base-AI classes
  - [x] Transport
  - [x] TempSummon
  - [x] Minion
  - [x] Pet
  - [x] Guardian
  - [ ] Missed anything ?

On my journey across a lot of different TC classes I found some weird code that I chose to fix in this PR because I was too lazy to switch to another branch.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
No issues

**Tests performed:** (Does it build, tested in-game, etc.)
It builds, still need to trigger a few asserts on purpose to properly test it

**Known issues and TODO list:** (add/remove lines as needed)

- Add GetDebugInfos() function to more types

### CODE REVIEW

**Comment by illfated** [comment]
I would like to point out that "infos" (with the plural S) is a modernism predominantly found in non-English languages (typically French). In English, the word "information" is an uncountable noun, as well as the English understanding of "info". Not saying that you should change your command name `debugInfos` -- there may be other reasons for why you chose that word form. I simply wanted to put it into perspective.

**Comment by Faq** [comment]
Hirsoshi would be good tester as lately he has many problems :)

**Comment by ccrs** [comment]
Really necessary

**Comment by jackpoz** [comment]
Please suggest what fields to log for each type (like what should we log for Unit that is not logged already for WorldObject ?)

**Comment by jackpoz** [comment]
Creature:
>Assertion message: 
d:\wow\trinitycore\src\server\game\entities\creature\creature.cpp:295 in Creature::AddToWorld ASSERTION FAILED:
  false
MapID: 571 X: 4948.98 Y: 2937.79 Z: 550.517 O: 1.81514
GUID Full: 0xf130003b6e000001 Type: Creature Entry: 15214  Low: 1 Entry 15214
IsAIEnabled: 1 DeathState: 0
AIName: SmartAI ScriptName: WaypointPath: 0

**Comment by Shauren** [comment]
add SpawnId to creature log

**Comment by ccrs** [comment]
Maybe add motionmaster debug information to unit? take a look to `.debug move` command 👍

**Comment by jackpoz** [comment]
GetUnitMovementFlags() and GetExtraUnitMovementFlags() ?

**Comment by ccrs** [comment]
my mistake, I was thinking about https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Commands/cs_misc.cpp#L2109
but actually thats useful information too 💃

**Comment by jackpoz** [comment]
Updated example of Creature:
>Assertion message: 
d:\giacomo\wow\trinitycore\src\server\game\entities\creature\creature.cpp:295 in Creature::AddToWorld ASSERTION FAILED:
  false
MapID: 571 X: 4948.98 Y: 2937.79 Z: 550.517 O: 1.81514
GUID Full: 0xf130003b6e000001 Type: Creature Entry: 15214  Low: 1 Entry 15214
IsAIEnabled: 1 DeathState: 0 UnitMovementFlags: 1024 ExtraUnitMovementFlags 0
AIName: SmartAI ScriptName: WaypointPath: 0 SpawnId: 0

**Comment by ccrs** [comment]
what about "IsInInstanceSript" and "Instance BossStates" or something like that ?

**Comment by jackpoz** [comment]
they don't sound that much useful, the mapid is already logged and that's enough to know if there is an instancescript

**Comment by illfated** [comment]
Nice progression. 👍

**Comment by Warpten** [comment]
Things off the top of my head for spells:

targets (gameobjects, units, explicit and implicit) (not always set depending on where it crashes!)
caster
cast item
cast flags

**Comment by jackpoz** [comment]
For spells I chose the lazy way of doing
```cpp
"Id: " << GetSpellInfo()->Id << " OriginalCaster: " << m_originalCasterGUID.ToString() << " State: " << getState();
```
logging the caster guid instead of checking all the different types of casters. As for the targets, that looked like a LOT of work to get things right! Maybe the spellId will already be enough (after all this is for asserts only, not for crashes). More info can be logged in the future whenever we get an assertion triggered.

**Comment by illfated** [comment]
Just a little Friday joke: Wouldn't it be funny if either a boss or instance NPC causing a worldserver crash would say "This world is coming to an end. I can sense it." when a crash is imminent? 😄

**Comment by Seyden** [comment]
Someone merge this into master! GO GO GO! :D

**Pull request merged**
