### PR TITLE
Enable Script as per @Kilyana's request

### PR DESCRIPTION
**Pull request by danlapps**

### CODE REVIEW

**Comment by Killyana** [comment]
I'm not really good at c++ but SAY_NESINGWARY_1 is not supposed to be declared?

**Comment by danlapps** [comment]
Im not good either, just thought you wanted the ignore removed :S

**Comment by danlapps** [comment]
All I could find is 
#define SAY_NESINGWARY_1 -1571008
Would that make any sense to anyone or is this for an older core values ?

**Comment by Rushor** [comment]
outdated data, it's just: SAY_NESINGWARY_1    = 0
committing this soon

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f723b18164b07378ba4d149590ab87504fb14dc4

**Pull request closed without merging**
