### PR TITLE
Try to solve spell  Chains of Naberius(36146)

### PR DESCRIPTION
**Pull request by w5860363**
test https://github.com/TrinityCore/TrinityCore/issues/27289

### CODE REVIEW

**Comment by offl** [comment]
This spell indeed should target only one player but this more looks like castFlag 'cast only if threat size is > 1'
On retail in lots of cases creature actually can cast spell on current target but usually it does not because threat size is 1

Atm SMART_TARGET_HOSTILE_RANDOM_NOT_TOP here provides correct spell target selection under any condition but that happens probably only because the spell is AOE

**Comment by w5860363** [comment]
@offl The original TDB is smart_ TARGET_ VICTIM

I didn't find out from the scattered retail videos that he would control the current hate players

**Comment by offl** [comment]
I'm not sure what will happen with 2 players but if there is 1 player and his guardians, he will mind control player (spell can target only players)

**Comment by offl** [comment]
What I was trying to say is 6 is fine, it does not require changes

**Pull request merged**
