### PR TITLE
Core/Spells: proc updates

### LINKED ISSUE #16478: [3.3.5][6.x] Core/Spell: Val'anyr, Hammer of Ancient Kings - Procc
[Val'anyr, Hammer of Ancient Kings] does proc on the target that you heal, however if you are a paladin and if you use  [Glyph of Holy Light] the proc of the weapon does not get apply'd the 5 other friendly targets.

Info:
http://wotlk.openwow.com/item=41106
http://wotlk.openwow.com/item=46017

http://wotlk.openwow.com/spell=64413

0813261c6fff568de2a3ce8df4b93c77d2e10d21

### LINKED ISSUE #16853: Paladins T2
**Set bonus of 8 pieces currently not working**:

**Nothing happens when you judge**

**When you judge effect of 8 pieces should trigger**

**Steps to reproduce the problem**:

1. Roll a paladin
2. Get 8 pieces of T2
3. Try to do sume judgements

**Branch(es)**: 3.3.5

**TDB version**:335.60

**TC hash/commit**:[ef7a91d](https://github.com/TrinityCore/TrinityCore/commit/ef7a91d1938becb53fc9201275f0b5f02248765c)

**Operating system**:Win7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### LINKED ISSUE #20234: [3.3.5] CC Auras which use their amount to drop not removed by some spells
**Description:**

CC Auras which use their amount to drop:
- SPELL_AURA_MOD_CONFUSE
- SPELL_AURA_MOD_FEAR
- SPELL_AURA_MOD_STUN
- SPELL_AURA_MOD_ROOT
- SPELL_AURA_TRANSFORM

**Current behaviour:**

CC Auras which use their amount to drop not removed by spell triggered damage.

**Expected behaviour:**

CC Auras which use their amount to drop should be removed by spell triggered damage

**Steps to reproduce the problem:**

1. Cast on target [Psychic Scream](https://woehead.way-of-elendil.fr/?spell=10890).
2. After first step - cast on target these spells : [Mind flay](https://woehead.way-of-elendil.fr/?spell=48156), [Improved Devouring Plague](https://woehead.way-of-elendil.fr/?spell=63627), [ Drain Mana](https://woehead.way-of-elendil.fr/?spell=5138).
3. The result is that fear not removed by these spells.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/ccfcf3940e98d333a20684e910483d700933945a

**TDB version:**  TDB 335.63

**Operating system:** Linux debian 8

[Possible bug location.](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L6159)

### LINKED ISSUE #20337: [3.3.5] Beacon of Light wrong proc with Judgement of Light
**Description:** Spell Beacon of Light (53563) is proccing with Judgement of Light (20271) and making paladin overpower.

**Current behaviour:** If you cast  Judgement of Light in 1 target, put Beacon of Light in some friend, everyonde that hit melee damage in target affected by your judgement will generate a Heal to your friend.

**Expected behaviour:** Beacon of Light should not proc with Judgement of Light.

**Steps to reproduce the problem:**

1. Put a paladin and other character in party.
2. Use Beacon of Light on you, and use Judgement of Light in some dummy.
3. Make other character attack by melee on dummy
4. You will see alot of heal come to you by Beacon of Light

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 971ed856a49dc56ea33d9a0779b1386eea5cd3ca

### PR DESCRIPTION
**Pull request by ariel-**
**Changes proposed:**

-  Changes in the implementation of flags SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED, SPELL_ATTR2_TRIGGERED_CAN_TRIGGER_PROC, SPELL_ATTR3_TRIGGERED_CAN_TRIGGER_PROC_2
-  Suspected current implementation is wrong (see amount of previous fixes which consisted on adding attribute to spell_proc), now the attribute is removed for auras with SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED since it should be better handled by core
-  The reason this is made PR is because the potential impact is big
- Spells may have different class masks per effect now (this is needed for #21398 for example)

**Target branch(es):** 

- [x] 3.3.5
- [x] master

**Issues addressed:**
Closes #16478
Closes #16853
Closes #20234
Closes #20337
Closes #21217 
Updates #21398

**Tests performed:** Builds, tested changed procs for any abnormal behaviour

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Check interaction of Paladin Judgements with itself, and many procs that shouldn't be proccing from those (ie Guarded by the Light)

### CODE REVIEW

**Comment by Keader** [comment]
Is good check Valanyr proc with judgement of light too

**Comment by ariel-** [comment]
Valanyr has two procs: one aura dummy on the weapon makes it proc the 15 second buff. The other is the 15 second buff itself, which is the one proccing the shields.

Which of those should trigger (if any) is the question

**Comment by Keader** [comment]
Both effects is proccing now ariel.
dont looks correct proc shield effect to me with judgement of Light.
Will make paladin over power using valanyr.

**Comment by ariel-** [comment]
Ok, decided I'll extend a liitle more the scope for this PR. Updated description

**Comment by joschiwald** [comment]
how many spells require a per-effect proc class mask?

**Comment by ariel-** [comment]
I already mentioned Inner Focus, but Lock and Load could be cleaned up with per-effect class masks

**Comment by Persephone** [comment]
Woah, this is awesome. Any news if itll be merged?

**Comment by joschiwald** [comment]
@ariel- can you push your first commit first?

**Comment by Keader** [comment]
Has a chance (i not tested, conflicting files haha) of this PR make 51940 Earthliving Weapon (Passive) (Rank 1) (and all other ranks) proc with Earth Shield (trigger heal)/ Healing Totem and not should.

**Comment by jackpoz** [comment]
should the first commit be merged and the 2nd one be skipped ? @joschiwald

**Comment by joschiwald** [comment]
the first part yes
for the second one, i would prefer to make the proc mask per spell effect optional and keep the proc mask for the entire spell

**Comment by jackpoz** [comment]
It would be nice if anyone with enough time and knowledge could clean up this PR to have only the "first part" (whatever that means, if the first commit or what else)

**Comment by ccrs** [comment]
@ariel- we miss you

**Comment by jackpoz** [comment]
Closing this PR as it seems abandoned. Feel free to ask here to reopen it if anyone would like to work on it.

**Comment by junker1609** [comment]
Light guide allows the tank to receive heal from all attackers when judgment is active on the boss, it's really annoying, the tank is almost indestructible.
I think this is a major class bug, I hope we can fix it soon

**Comment by jackpoz** [comment]
The most motivated person to fix an issue is the person experiencing the issue and considering it important, which in this case might be you. You could start working on it and get some help on irc/forum/github from other people who are experiencing the same issue.

**Comment by junker1609** [comment]
> The most motivated person to fix an issue is the person experiencing the issue and considering it important, which in this case might be you. You could start working on it and get some help on irc/forum/github from other people who are experiencing the same issue.

It’s a new world for me what you’ve done so far, and I’m still learning and I aspire to help whenever I can.

**Pull request closed without merging**
