### PR TITLE
Core/Unit: improve SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL immunities

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Remove SPELL_ATTR3_IGNORE_HIT_RESULT check in SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL immunity check

We only have one spell with SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL ID - 48707 Anti-Magic Shell

after ariel- commit: https://github.com/TrinityCore/TrinityCore/commit/352c84943c4495631a5dd1e9285cde35fdc23c37 Anti-Magic Shell does not grant immunity to spells with the attribute SPELL_ATTR3_IGNORE_HIT_RESULT.
old related issues:
https://github.com/TrinityCore/TrinityCore/issues/21343
https://github.com/TrinityCore/TrinityCore/issues/20326
https://github.com/TrinityCore/TrinityCore/issues/23305

proofs:
for some reason warcraftmovies has problems with google chrome, use edge by example.

https://www.warcraftmovies.com/movieview.php?id=124549
At 2:54 is seen that paladin holy gets an immune after cast Judgment of Light on DK with Anti-Magic Shell, the debuff is not applied.

https://www.warcraftmovies.com/movieview.php?id=145857
At 3:44, paladin retry cast Judgment of Justice on DK with Anti-Magic Shell and DK is immune.

https://www.warcraftmovies.com/movieview.php?id=158419
At 2:01 - cast Icy Touch and Frost Fever is not applied, is immune.

https://www.youtube.com/watch?v=230QLHFpeUw
At 1:40 - cast Icy Touch on DK with Anti-Magic Shell and DK is immune.

https://www.youtube.com/watch?v=XpzEHKVOevw&t=83s
At 1:25 - cast Plague Strike on DK with Anti-Magic Shell and DK is immune to Blood Plague.

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:**

nothing open I think

**Tests performed:**

tested in-game

### CODE REVIEW

**Comment by Keader** [comment]
https://archive.org/details/Snutz_-_Snutz__Warlock__BG_9_Warlock_2009-09-09_4.90 (time: 15:57)
Glyph of Shadowflame should not pass anti magic shell

**Comment by Keader** [comment]
Tested this PR and is working for me.
Idk if has some side effects

**Comment by Keader** [comment]
@Jildor This branch has conflicts that must be resolved

**Comment by Jildor** [comment]
updated ;)

**Comment by jackpoz** [comment]
Just a heads up about PRs: please don't force-push, it makes the review harder. Thank you 👍

**Comment by jackpoz** [comment]
Thanks for the PR 🚀 😃

**Pull request merged**
