### PR TITLE
Fixes for 6.x

### PR DESCRIPTION
**Pull request by doctaweeks**
Cosmetic or warning cleanup. 2d1b43b fixes a precision issue which may have performance implications on some platforms.

### CODE REVIEW

**Comment by Carbenium** [comment]
@doctaweeks: could you check the merge conflicts? 
And again thanks for your work :+1:

**Comment by doctaweeks** [comment]
e567541 fixed the newline issue in ddf17b8. Just throw away ddf17b8.

**Comment by Carbenium** [comment]
It just would be easier for me to be able to press the "Merge pull request" button ;)

**Comment by Carbenium** [comment]
Closed by 64848856002a796e30b822d70a31087495084bfa , 62ff887236ad835f1353c415ae6baca6ac6b94b8 , 27923b8d8fc10b46f86a2419cf27e9c9f1a96be8 , 71ba35a6cd4446d7f2a39c7eb41fa17aac4e6c5c , 9c197e82a3b6742a7d2b521efe9cd9232e9ab8f1 and f48b86fd8ad734855744e766109a543208fce454

**Pull request closed without merging**
