### PR TITLE
Core/AI boss_mother_shahraz

### PR DESCRIPTION
**Pull request by w5860363**
.go xyz 980.47 164.25 192.84 564 
Nearby will be out of combat, so you should avoid transmitting players to nearby areas

The spell cast by the health check is wrong

This aura causes the boss to cast melee spell once a second

### CODE REVIEW

**Comment by w5860363** [comment]
/src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp#L54
The safety zone is set, but the wall is not in the safety zone

**Comment by offl** [comment]
In sniff SPELL_RANDOM_PERIODIC is not used on aggro, but on 10% HP (old behavior is correct); SPELL_FRENZY is not used at all

Saber Lash procs from aura 40816 which always is applied on boss (old behavior is correct). You're testing boss without tank with tank gear and it procs on every boss melee attack. There's problem with divided damage and probably spell should have hidden cooldown in spell_proc. I'll open an issue later about that stuff

After checking videos & sniffs almost sure boss teleports players to random positions around boss (like currently (GetCaster()->GetRandomNearPosition(50.0f))
Even if she teleports players to predefined positions, that means you need way much more positions and chose only the ones which are close to boss, otherwise she will teleport players way too far(that does not happen in videos & sniffs). It's simply too complicated for Blizz to be true

>https://github.com/TrinityCore/TrinityCore/issues/27540

Comparing TC's BT which was fully updated from sniffs with another projects more likely will revert correct changes than really fix what is needed to be fixed. There are lots of things which can be updated or handled differently in BT but definitely not like that.

**Comment by w5860363** [comment]
@offl https://tbc.wowhead.com/spell=40816/saber-lash have a 7 second cooldown

https://wowwiki-archive.fandom.com/wiki/Mother_Shahraz
([Saber Lash]—Very frequent frontal cleave, 20 yard range, ~30k damage on plate, divided between up to three targets, provides immunity to Fatal Attraction for 30 sec
)

 [Enrage]—at 10% she periodically increases damage and attack speed for a short time. After 10 minutes, she enrages permanently.
---------------------------------
Then refresh the immune time if it is triggered every time

Enrage Will trigger at 10%
-----------
As for GetRandomNearPosition, it's only because BossBoundaryData is triggered near the wall.
test .go xyz 980.47 164.25 192.84 564

**Comment by offl** [comment]
Yes, 7 seconds is literally what I see in https://tbc.warcraftlogs.com/reports/Ax7rW18VY9tLZzFX#fight=20&view=events&type=damage-done&hostility=1

>enrage

It's not an hidden aura and can be seen in sniffs or videos but I don't see it

**Comment by w5860363** [comment]
@offl https://www.youtube.com/watch?v=6dvLGBxe-ro Video before 13year 2:38-2:40
Maybe Blizzard retail has changed the display method of aura

**Pull request closed without merging**
