### PR TITLE
Core/Spell Add Slowing effect to mage Frostball

### PR DESCRIPTION
**Pull request by HannibalRoG**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Add slowing movement speed 50% for 15s to Frostball. Taken from @Keader https://gist.github.com/Keader/02eaf2fd3fa32e7c29f808802a52c111

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
#18932

**Tests performed:** (Does it build, tested in-game, etc.)
Build and tested in game.

### CODE REVIEW

**Comment by Edreisantafe** [comment]
Why the commits for priest appear here?? what doing wrong?

**Comment by Aokromes** [comment]
you must create one branch for each fix.

**Comment by Edreisantafe** [comment]
That 's what I did

**Comment by Edreisantafe** [comment]
I don´t know how to resolve this conflicts, i need sugestions.
With the commits with Conjure refreshment now i have conflicts, please instruct me how to resolve.

**Comment by DoctorKraft** [comment]
I don't think it's a good idea to place this script here because Chilled is also cast on "Blizzard" and "Frost Armor"
And for your confict update your branch master and create a new branch, you can't continue with this branch you have 2 PRs

**Comment by tkrokli** [comment]
Yes, like Keader said, you need to switch to the local `master` branch first, then create a new branch for your `Frostbolt` fix ("frostball" is not a World of Warcraft name, use **Frostbolt** to reference the spell properly). Any new branches you create should always be based on your updated `master` branch to avoid conflicts.

**Pull request closed without merging**
