### PR TITLE
Support for targetting spells onto in flight units

### PR DESCRIPTION
**Pull request by r00ty-tc**
This adds support to spell_custom_attr to allow a spell to be cast
upon a unit on a taxi/in flight.

This will allow the Issue with Horde quest Test At Sea (11170) to be corrected. Resolving https://github.com/TrinityCore/TrinityCore/issues/11880

Example SQL to use functionality:

``` SQL
-- Spell for Test at Sea kill credit - allow cast on flying units.
INSERT INTO spell_custom_attr (entry, attributes) VALUES (43138, 262144);
```

### CODE REVIEW

**Comment by dr-j** [comment]
Another example is Mission: Plague this after recent tc commit which uses spell instead of kill credit however when player is on the taxi flight for this quest credit fails for hitting the plague tanks even though if you cast spell on yourself it gives credit, but always fails in sai regardless of cast flags.

This is same as with test at sea it works with killcredit but no credit to player on taxi when spell is used

**Comment by pete318** [comment]
I'll try it with this too. See if it works. Would be nice if there was more than one that could benefit from this.

**Comment by pete318** [comment]
Yep:

```SQL
INSERT INTO spell_custom_attr (entry, attributes) VALUES (43419, 262144);
```

Works fine for that one too. :)

**Comment by Unholychick** [comment]
have you considered that casting spells with effect SPELL_EFFECT_KILL_CREDIT2 maybe should not be prevented from being cast in the first place?

**Comment by pete318** [comment]
Well actually I've been considering since this PR that maybe only hostile spells should be prevented from being cast on taxi units.

But that will be somewhat more of a change.

**Comment by pete318** [comment]
I think what we need to decide here, is whether we should stick with this method and add any spells into the spell_custom_attr table, or we just trust that the client will limit spells casting on flight units and remove the restriction in the server.

Comments/ideas otherwise?

**Comment by pete318** [comment]
Just bumping this, so maybe we can get a decision. Remove restriction entirely and have the client decide when to block spell casts on taxi units, or keep it as is, with the extra flag to define spells which can hit units on a taxi?

**Pull request closed without merging**
