### PR TITLE
Core/Misc: Replace boost::shared_mutex with std::shared_mutex

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Replace boost::shared_mutex with std::shared_mutex

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**
None

**Tests performed:** (Does it build, tested in-game, etc.)
It builds.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Test ingame that no strange issues happen

### CODE REVIEW

**Comment by Faq** [comment]
C++17 added std::shared_mutex https://en.cppreference.com/w/cpp/thread/shared_mutex

**Comment by jackpoz** [comment]
@Faq that's what this PR uses

**Comment by Faq** [comment]
yes, just dropped as info.

**Comment by jackpoz** [comment]
It seems people like boost more than C++

**Comment by jackpoz** [comment]
one more try

**Comment by jackpoz** [comment]
https://app.circleci.com/pipelines/github/TrinityCore/TrinityCore/1552/workflows/42929a9b-66a8-4f5d-b9fc-4594fcb19a67/jobs/8781/steps that built https://github.com/TrinityCore/TrinityCore/commit/d974800e9d1e393ce3459ed8be4f4bd9defcc8f3 took 6:55m for the build step, https://app.circleci.com/pipelines/github/jackpoz/TrinityCore/200/workflows/f9764c8c-20f0-455e-b07f-caa168a077ea/jobs/1198/steps that built this PR took 6:42m (it's just 1 comparison but at least the build time didn't double up)

**Pull request merged**
