### PR TITLE
Core/Spell: Fix Devastate + Glyph of Sunder armor stacking

### LINKED ISSUE #14633: [3.3.5] Glyph of Sunder Armor
Glyph of sunder armor should work with Devastate too, just for applying the debuff not the damage to second target. But in trinity core the debuff didn't stack on the second target. It is like the second target gets only one sunder armor effect even if the primary target has five of them.

http://www.wowwiki.com/Glyph_of_Sunder_Armor
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12687773-3-3-5-glyph-of-sunder-armor?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pjasicek**
Fixes #14633

### CODE REVIEW

**Comment by Robens** [comment]
This can be implemented as spellscript

**Comment by jackpoz** [comment]
anyone would like to test the behavior with and without this PR and provide feedback ?

**Comment by tkrokli** [comment]
@ikir83 should be one of the most interested in testing this, he opened issue #14633.
Just to point out some relevant info to those who may have forgotten about it:
http://wow.gamepedia.com/Devastate `Level 26 Protection warrior ability` (6.2.2)
http://wotlk.openwow.com/spell=20243 `Devastate: Protection warrior level 50 ability` (3.3.5)
http://wow.gamepedia.com/Glyph_of_Devastate `Requires Level 50`
http://wotlk.openwow.com/item=43415 `Glyph of Devastate`
http://wow.gamepedia.com/Sunder_Armor `Protection Warrior Level 10 ability`
http://wotlk.openwow.com/spell=7386/sunder-armor/#see-also-ability
http://wow.gamepedia.com/Glyph_of_Sunder_Armor `Requires Level 25` (4.1.0)
http://wotlk.openwow.com/item=43427/glyph-of-sunder-armor `Requires Level 15`(3.3.5)

**Comment by jackpoz** [comment]
2 months and no feedback

**Comment by tkrokli** [comment]
I would have tried to test it, but I suck at testing player classes I don't know very well from playing online.
Unfortunately, there seems to be no activity from the OP since he posted this PR and @ikir83 has not been active since 2015-09-14 (he would stand the most to gain from testing it).

**Comment by jackpoz** [comment]
@pjasicek could you explain more in detail your PR ? The description "Fixes #14633" doesn't really explain anything and it's unclear why the previous "cast the spell only if target doesn't have the aura and then modify the number of stacks" isn't good anymore

**Comment by jackpoz** [comment]
Please ask a TrinityCore member to reopen this Pull Request once you provide the requested feedback. There is no need to open a new Pull Request with the same changes.

Opening a Pull Request without a clear description about all the changes doesn't really help us reviewing it.

**Pull request closed without merging**
