### PR TITLE
[3.3.5] Scripts/Spells: Life Tap

### LINKED ISSUE #17559: [3.3.5] Scripts/Spells: Life Tap
**Description**: [Life Tap](http://wotlk.openwow.com/spell=57946) HP requirement goes up the more spirit players have causing the players to not be able to use it at times when they should be able to.

**Current behaviour**: The more spirit the player has the more HP required for the player to use the item goes.

**Expected behaviour**: Spell shouldn't scale with spirit.

**Steps to reproduce the problem**:
1. Take all gear off.
2. Use [Life Tap](http://wotlk.openwow.com/spell=57946) you'll notice that the spell will convert X HP to Y mana.
3. Equip gear that gives extra spirit.
4. Use [Life Tap](http://wotlk.openwow.com/spell=57946) you'll notice that the spell description states that more HP is required to use the spell.
5. Use [Life Tap](http://wotlk.openwow.com/spell=57946) you'll notice that the spell will convert still convert X HP to Y mana (as it should).

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Additional note**: The spell performs HP check based on HP percentage (not sure if that is how it should be).

### PR DESCRIPTION
**Pull request by PolarCookie**
This PR hurts me as a warlock main, life tap was already rough at lower levels.
On my lvl 56 GD lock life tap would go from 346 life -> 492 mana to 482 life -> 444 mana, and that's with improved life tap :cry: 

**Changes proposed:**
Fixes Life tap to accurately drain life and grant mana according to the tooltip.

Life tap costs a base amount for each rank + spirit * 1.5, while granting the same base amount + shadow power * 0.5.
https://wotlk.evowow.com/?spell=57946
https://web.archive.org/web/20100813053911/http://www.wowhead.com/spell=57946

Life tap can now be used 1 hp above the drain cost.
https://www.wowhead.com/spell=1454/life-tap#comments:id=19418

Wowhead comments on ranks 2-8 seem to be lost, what a shame.

**Target branch(es):**
3.3.5

**Issues addressed:** Closes #17559

**Tests performed:** (Does it build, tested in-game, etc.)
I tested at various levels with different combination of heirloom gear, couldn't find any difference between tooltip and results.

### CODE REVIEW

**Comment by PolarCookie** [comment]
https://wow.gamepedia.com/Patch_3.3.3
> [Life Tap]: This spell no longer scales with spirit, and instead scales with spell power.

This could be a poorly worded changelog, because if true they forgot to update the tooltip for 6 months, strange as they fixed the mana part.

Here's the relevant part in simcraft for 3.3.5
```c++
    direct_power_mod = 0.5;
    double mana = ( base_tap + ( direct_power_mod * p -> composite_spell_power( SCHOOL_SHADOW ) ) );
    p -> resource_loss( RESOURCE_HEALTH, mana );
    mana *= ( 1.0 + p -> talents.improved_life_tap * 0.10 );
    p -> resource_gain( RESOURCE_MANA, mana, p -> gains_life_tap );
```

Anyone got sniffs for life tap (1454, 1455, 1456, 11687, 11688, 11689, 57946) dated between 23.03.2010 and 12.10.2010?

**Comment by PolarCookie** [comment]
Sniffs were given, inc update

**Comment by PolarCookie** [comment]
For those curious where the ```+ (6.3875 * GetSpellInfo()->BaseLevel))))``` came from, here's a trip down memory lane.
https://github.com/TrinityCore/TrinityCore/commit/8b8ededec29b0bc8d0c405234adcacdebe14725a
https://github.com/TrinityCore/TrinityCore/commit/dd1a750921af53a435e166e23bb3caa84093d01e
https://github.com/TrinityCore/TrinityCore/commit/ff7308f754455843b36a76457245f0f31bf769b7

What's funny is that the first commit was actually the most accurate, in any case ```+ (6.3875 * GetSpellInfo()->BaseLevel))))``` used to be part of the hp cost, but was later removed when Life Tap was made a SpellScript, yet kept around for the fizzle check.

https://github.com/TrinityCore/TrinityCore/commit/c517806a23751dd92d6a064b7f721507f182bc75
https://github.com/TrinityCore/TrinityCore/commit/c23ff109dfda710c5518b7ec0e7d0a4c09e48159

**Comment by Keader** [comment]
Missing Penalty.
Mana should be:
```cpp
                    float penalty = caster->CalculateLevelPenalty(GetSpellInfo());
                    int32 mana = int32(base + (caster->GetUInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS+SPELL_SCHOOL_SHADOW) * 0.5f * penalty));
```

**Comment by PolarCookie** [comment]
Noted, but there's no such function as ```CalculateLevelPenalty```, source tree wide search gives nothing.

**Comment by Keader** [comment]
what? '-'

**Comment by PolarCookie** [comment]
Did you mean ```CalculateSpellpowerCoefficientLevelPenalty```?

**Comment by Killyana** [comment]
New name CalculateSpellpowerCoefficientLevelPenalty

**Comment by Keader** [comment]
Yeah, it's changed the name

**Comment by PolarCookie** [comment]
anything else?

**Comment by Keader** [comment]
Ty

**Pull request merged**
