### PR TITLE
Contrib/Grafana: updated dashboards

### PR DESCRIPTION
**Pull request by freekode**
**Changes proposed:**

- updated grafana dashboards
- all dashboards moved to one
- also added to grafana repo [here](https://grafana.com/dashboards/3386)

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Tests performed:** (Does it build, tested in-game, etc.)

tested in grafana on cloud

### CODE REVIEW

**Comment by jackpoz** [comment]
I liked the idea of having different dashboards, it's just a minor change anyway

**Comment by freekode** [comment]
reason to make one dashboard is that Grafana Cloud free account allows only 5 dashboards, so to save free dashboards I combine them into one.

**Comment by jackpoz** [comment]
ah ok, maybe keep all versions ? with yours somehow saying that it includes everything and that it's useful for Grafana Cloud

**Comment by freekode** [comment]
done :)

**Comment by jackpoz** [comment]
thank you for the PR

**Pull request merged**
