### PR TITLE
Core/Spells: add exclusion to cast interrupt if you don't have AURA_484

### PR DESCRIPTION
**Pull request by ghost**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**
If unit target has AuraType 484, but player does not have aura 484, you cannot interrupt cast.
Else if you have aura 484 and unit target have 484, you can interrupt cast.
Shadowlord Iskar encounter feature.

-  Aura 484 (Eye of Anzu spell.)
-  Prevent interrupt if target has 484 aura, but caster interrupt spell not have 484 aura.
-  Need more review.

**Target branch(es):** 3.3.5/master
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
Not have issue.

**Tests performed:** (Does it build, tested in-game, etc.)
Compile testing.

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Review. Need review.
- [ ] 

[//]: # (**DEPRECATION NOTICE**) Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE**) Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE**) If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION**) When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

### CODE REVIEW

**Comment by Krudor** [comment]
Not actual behavior.
It's the right place to check it, but not the right method.

Loop the targets AURA_484 auras.
If the caster has an AURA_484 aura with spell id matching the misc value of the targets AURA_484, allow the interrupt.

**Comment by Unknown-1000** [comment]
You can add better variant?
I don't know more better variant.

**Comment by Krudor** [comment]
This would work, not sure if it's the proper way to do it though.
There should be another check on the caster's SPELL_AURA_ALLOW_INTERUPT aura misc value, to see if the targets casted spell is the same value, but that would break functionality for spell id 187998.
Blizzard either scrapped that check in order to make eye of anzu in this case, be able to interrupt multiple spells, or that spell has a special check and the default behavior is to check target spell id.

```
void Spell::EffectInterruptCast(SpellEffIndex effIndex)
{
    if (effectHandleMode != SPELL_EFFECT_HANDLE_HIT_TARGET)
        return;

    if (!unitTarget || !unitTarget->IsAlive())
        return;

    Unit::AuraEffectList const& auraAllowGetInterruptedList = unitTarget->GetAuraEffectsByType(SPELL_AURA_ALLOW_INTERRUPT);

    /// @todo not all spells that used this effect apply cooldown at school spells
    // also exist case: apply cooldown to interrupted cast only and to all spells
    // there is no CURRENT_AUTOREPEAT_SPELL spells that can be interrupted
    for (uint32 i = CURRENT_FIRST_NON_MELEE_SPELL; i < CURRENT_AUTOREPEAT_SPELL; ++i)
    {
        if (Spell* spell = unitTarget->GetCurrentSpell(CurrentSpellTypes(i)))
        {
            SpellInfo const* curSpellInfo = spell->m_spellInfo;

            bool interruptOverride = false;
            for (Unit::AuraEffectList::const_iterator itr = auraAllowGetInterruptedList.begin(); itr != auraAllowGetInterruptedList.end(); ++itr)
            {
                Unit::AuraEffectList const& auraAllowInterruptList = m_caster->GetAuraEffectsByType(SPELL_AURA_ALLOW_INTERRUPT);
                for (Unit::AuraEffectList::const_iterator itr2 = auraAllowInterruptList.begin(); itr2 != auraAllowInterruptList.end(); ++itr2)
                {
                    if ((*itr)->GetMiscValue() != (*itr2)->GetId())
                        continue;

                    interruptOverride = true;
                    break;
                }

                if (interruptOverride)
                    break;
            }

            // check if we can interrupt spell
            if ((spell->getState() == SPELL_STATE_CASTING
                || (spell->getState() == SPELL_STATE_PREPARING && spell->GetCastTime() > 0.0f))
                && (interruptOverride || ((curSpellInfo->PreventionType & SPELL_PREVENTION_TYPE_SILENCE)
                && ((i == CURRENT_GENERIC_SPELL && curSpellInfo->InterruptFlags & SPELL_INTERRUPT_FLAG_INTERRUPT)
                    || (i == CURRENT_CHANNELED_SPELL && curSpellInfo->ChannelInterruptFlags & CHANNEL_INTERRUPT_FLAG_INTERRUPT)))))
            {
                if (m_originalCaster)
                {
                    int32 duration = m_spellInfo->GetDuration();
                    unitTarget->GetSpellHistory()->LockSpellSchool(curSpellInfo->GetSchoolMask(), unitTarget->ModSpellDuration(m_spellInfo, unitTarget, duration, false, 1 << effIndex));
                }
                ExecuteLogEffectInterruptCast(effIndex, unitTarget, curSpellInfo->Id);
                unitTarget->InterruptSpell(CurrentSpellTypes(i), false);
            }
        }
    }
}
```

**Comment by Unknown-1000** [comment]
Need more information.
Aura 484 also allow see chains of despair 185510 spell id.

**Comment by Krudor** [comment]
Not related to PR

**Comment by Unknown-1000** [comment]
Need developers point.

**Comment by Krudor** [comment]
AURA_484 is not responsible for handling the chains of despair functionality.
Chains of despair apply a vehicle id to the owner.
The spell applying AURA_484 ALSO apply an aura effect triggering phase updates, most likely revealing creatures mounted on the players, in the vehicle set by the chains of despair. Those creatures most likely channel a chain visual spell on another chains of despair creature in that phase. (Thus making the one with Eye of Anzu able to see the chains), but I'm only speculating here.

The code I provided appears to be working and is one example of how you can handle it.

**Comment by Ulduar** [comment]
``` CPP
ID - 179202 Глаз Анзу
=================================================
Description: Бросить Глаз Анзу выбранному союзнику. Обладатель Глаза Анзу не будет введен в заблуждение темными иллюзиями.

ToolTip: Темные иллюзии не вводят в заблуждение.
Triggred by spell: (180310) Бросить Глаз Анзу
Triggred by spell: (185348) Ответный удар Тьмы
=================================================
Category = 0, SpellIconID = 10188, activeIconID = 0, SpellVisual = (45806,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x89000000 (SPELL_ATTR0_CASTABLE_WHILE_MOUNTED, SPELL_ATTR0_CASTABLE_WHILE_SITTING, SPELL_ATTR0_CANT_CANCEL)
AttributesEx1: 0x000008A8 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_NOT_BREAK_STEALTH, SPELL_ATTR1_CANT_BE_REFLECTED, SPELL_ATTR1_UNK11)
AttributesEx2: 0x20004001 (SPELL_ATTR2_CAN_TARGET_DEAD, SPELL_ATTR2_UNK14, SPELL_ATTR2_CANT_CRIT)
AttributesEx3: 0x00150100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS, SPELL_ATTR3_CANT_TRIGGER_PROC, SPELL_ATTR3_IGNORE_HIT_RESULT, SPELL_ATTR3_DEATH_PERSISTENT)
AttributesEx4: 0x00003081 (SPELL_ATTR4_IGNORE_RESISTANCES, SPELL_ATTR4_CAN_CAST_WHILE_CASTING, SPELL_ATTR4_UNK12, SPELL_ATTR4_UNK13)
AttributesEx5: 0x00060008 (SPELL_ATTR5_USABLE_WHILE_STUNNED, SPELL_ATTR5_USABLE_WHILE_FEARED, SPELL_ATTR5_USABLE_WHILE_CONFUSED)
AttributesEx6: 0x20000000 (SPELL_ATTR6_NO_DONE_PCT_DAMAGE_MODS)
AttributesEx8: 0x40000020 (SPELL_ATTR8_UNK5, SPELL_ATTR8_UNK30)
AttributesEx9: 0x00100000 (SPELL_ATTR9_UNK20)
AttributesEx10: 0x00010000 (SPELL_ATTR10_UNK16)
AttributesEx13: 0x00000080 (SPELL_ATTR13_UNK7)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 14) "Extra Long Range":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 60, MaxRangePositive = 60

Speed 35,00
Cast time (Id 1) = 0,00
RecoveryTime: 1000 ms, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
Duration: ID (21)  -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x80480000, ChannelIF 0x00000000
  Ex Target Aura Spell (179202) Глаз Анзу
Proc flag 0x01000000, chance = 100, charges - 0
=================================================
  24 On death
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
Aura Id 170 (SPELL_AURA_DETECT_AMORE), value = 0, misc = 3 (3), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
Aura Id 293 (SPELL_AURA_OVERRIDE_SPELLS), value = 0, misc = 574 (574), miscB = 0, periodic = 0

Overriding Spells:
	 - #1 (179202) Глаз Анзу


Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
Aura Id 42 (SPELL_AURA_PROC_TRIGGER_SPELL), value = 0, misc = 0 (0), miscB = 0, periodic = 0
   Trigger spell (181492) Глаз Анзу. Chance = 100

Effect 3: Id 164 (SPELL_EFFECT_REMOVE_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
   Trigger spell (181957) Ирреальные ветра. Chance = 100
   Description: Description: $@spelldesc181956

   ToolTip: Ирреальные ветра сдувают вас на край.
Наличие эффекта "$@spellname179202" развеивает эту иллюзию.

Effect 4: Id 64 (SPELL_EFFECT_TRIGGER_SPELL) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
   Trigger spell (182016) Eye of Anzu Hidden Movement force canceling aura. Chance = 100
Charges - 0
=================================================
  24 On death

=================================================

Effect 5: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
Aura Id 484 (SPELL_AURA_484), value = 0, misc = 181827 (181827), miscB = 0, periodic = 0

Effect 6: Id 164 (SPELL_EFFECT_REMOVE_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
   Trigger spell (184546) Вуаль. Chance = 100

Effect 7: Id 64 (SPELL_EFFECT_TRIGGER_SPELL) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
   Trigger spell (184546) Вуаль. Chance = 100

Effect 8: Id 164 (SPELL_EFFECT_REMOVE_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
   Trigger spell (182325) Ирреальные раны. Chance = 100
   Description: Description: $@spelldesc182323

   ToolTip: $s2 ед. урона раз в $t2 сек.
Кровотечение будет продолжаться, пока запас вашего текущего здоровья не превысит $s3% от максимального.
Наличие эффекта "$@spellname179202" развеивает эту иллюзию.
Charges - 0
=================================================
  11 Taken positive spell hit
  15 Taken positive magic spell hit
  31

=================================================

Effect 9: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 0, misc = 0 (0), miscB = 0, periodic = 5000
   Trigger spell (185128) Глаз Анзу. Chance = 100

Effect 10: Id 164 (SPELL_EFFECT_REMOVE_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
   Trigger spell (181824) Ирреальная порча. Chance = 100
   Description: Description: Поражает цель "Ирреальной порчей". Жертва взрывается, нанося $s1 ед. урона от огня всем находящимся поблизости противникам и увеличивая получаемый ими урон от огня на $187344s1% в течение $d. Все обладающие способностью "$@spellname179202" невосприимчивы к этому эффекту.

   ToolTip: Наносит окружающим союзникам $s1 ед. урона от огня.

ID - 181827 Проводник Скверны
=================================================
Description: Поддерживает эффект $@spellname181832 раз в $t1 сек., нанося $181832s1 ед. урона от сил природы и затем переходя на других находящихся поблизости противников. Поражает всего до $181832x1 $lцели:целей:целей;. С каждым применением способности $@spellname181832 наносимый урон от сил природы увеличивается на $181831s2%. Эту способность могут прервать только противники со способностью "$@spellname179202".

ToolTip: Поддержание эффекта $@spellname181832 раз в $t1 сек.
Category = 0, SpellIconID = 2356, activeIconID = 0, SpellVisual = (46292,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
AttributesEx1: 0x00000040 (SPELL_ATTR1_CHANNELED_2)
AttributesEx11: 0x00000001 (SPELL_ATTR11_UNK0)
AttributesEx12: 0x00800000 (SPELL_ATTR12_UNK23)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 216) = 1,90
Duration: ID (105)  9000, 0, 9000
Interrupt Flags: 0x00000009, AuraIF 0x00000000, ChannelIF 0x80480018
Chance = 0, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 0, misc = 0 (0), miscB = 0, periodic = 1500
   Trigger spell (181831) Наделение силой Скверны. Chance = 0
   Description: Description: Наносимый урон от сил природы увеличивается на $s2%.

   ToolTip: Наносимый урон от сил природы увеличен на $s2%.

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 484 (SPELL_AURA_484), value = 0, misc = 179202 (179202), miscB = 0, periodic = 0

Effect 2: Id 64 (SPELL_EFFECT_TRIGGER_SPELL) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
   Trigger spell (184452) Проводник Скверны. Chance = 0

ID - 187998 Проводник Скверны
=================================================
Description: Поддерживает заклинание "$@spellname181832" раз в $t1 сек., нанося $181832s1 ед. урона от сил природы, после чего эффект распространяется на других находящихся поблизости противников. Поражает всего до $181832x1 $lцели:целей:целей;. Эту способность могут прервать только противники со способностью "$@spellname179202".

ToolTip: Поддержание эффекта $@spellname181832 раз в $t1 сек.
Category = 0, SpellIconID = 2356, activeIconID = 0, SpellVisual = (46292,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
AttributesEx1: 0x00000040 (SPELL_ATTR1_CHANNELED_2)
AttributesEx11: 0x00000001 (SPELL_ATTR11_UNK0)
AttributesEx12: 0x00800000 (SPELL_ATTR12_UNK23)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 216) = 1,90
Duration: ID (105)  9000, 0, 9000
Interrupt Flags: 0x00000009, AuraIF 0x00000000, ChannelIF 0x80480018
Chance = 0, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 0, misc = 0 (0), miscB = 0, periodic = 1500
   Trigger spell (188438) Проводник Скверны. Chance = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 484 (SPELL_AURA_484), value = 0, misc = 179202 (179202), miscB = 0, periodic = 0

Effect 2: Id 64 (SPELL_EFFECT_TRIGGER_SPELL) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
   Trigger spell (184452) Проводник Скверны. Chance = 0

**Comment by Ulduar** [comment]
@Unknown-1000 I will add your suggestions variant. Compiling testing.
If working fine, can not change nothing.

**Comment by Keader** [comment]
@Ulduar stop post things in Russian...

**Comment by Unknown-1000** [comment]
@Keader 
I perfectly understood what he said.

**Comment by Unknown-1000** [comment]
@Ulduar after test, give feedback please.

**Comment by tkrokli** [comment]
I have replaced the Russian text in the SpellWork output with English text from www.wowhead.com
(you may want to check your local SpellWork output to check if the text info values are correct).

**Pull request closed without merging**
