### PR TITLE
Core/Spells: don't save Magma aura.

### PR DESCRIPTION
**Pull request by Gooyeth**
**Changes proposed:**

Avoid if a pet dies by magma, when invoked always die for magma.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Tests performed:** Build

### CODE REVIEW

**Comment by tkrokli** [comment]
Needs to be fixed when the file name update to `characters` is decided on (when merging):
```
Database Updater check script:
  Checking database 'characters' for missing filenames in tables...
- "sql/updates/characters/9999_99_99_21682_characters.sql" is missing in the 'characters'.'updates' table.
Fatal error:
  The Database Updater is broken for the 'characters' database,
  because the applied update is missing in the 'characters'.'updates' table.
How to fix:
  Insert the missing names of the already applied sql updates
  to the 'updates' table of the 'characters' base dump ('sql/base/characters_database.sql').
The command "./contrib/check_updates.sh characters 3.3.5 characters" exited with 1.
```

**Comment by tkrokli** [comment]
Very well, it should fix the travis-ci issue for now.
You also need to add the following line already in TDB :
https://github.com/TrinityCore/TrinityCore/blob/fb31cb7c047f4d79e7bea04b72175e6ef251a317/sql/base/characters_database.sql#L2625

**Comment by Gooyeth** [comment]
I need to update the fork :sweat_smile:

**Comment by tkrokli** [comment]
All right. I presume you found it easier to start a new PR.

**Pull request closed without merging**
