### PR TITLE
Remove all Class Specific Obsolete Quest

### LINKED ISSUE #18935: [master] Obsolete starter quests
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
This quest was marked obsolete:
http://www.wowhead.com/quest=10068/frost-nova

**Current behaviour:** (Tell us what happens.)
You can accept this quest but you can't complete

**Expected behaviour:** (Tell us what should happen instead.)
This quest shouldn't be offered

**Steps to reproduce the problem:**

1. Create a Blood Elf Mage
2. Level up to 2
3. Go to Julia Sunstriker <Mage Trainer>

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/1c00f0b2d405d5f9eee4009ca5810e9721cd36ce

**TDB version:** 703.00 + updates

**Operating system:** Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by Keldo**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Remove all Class Specific Obsolete Quest 

**Target branch(es):**
- [x] master

**Issues addressed:** Closes #18935

**Tests performed:** In Game

**TODO list:**

**HORDE**
- [x] Blood Elf
- [x] Undead  
- [ ] Orc 
- [ ] Gobblin 
- [ ] Troll

**Alliance**
- [ ] Human
- [ ] Night Elf
- [ ] Draenei
- [ ] Gnome
- [ ] Dwarf

### CODE REVIEW

**Comment by Aokromes** [comment]
Thx, but we don't use PRs for sql only fixes.

**Comment by Shauren** [comment]
Files changed: almost 2k
I think you messed up something here

**Comment by tkrokli** [comment]
https://github.com/Keldo/TrinityCore :
> This branch is 19 commits ahead, 367 commits behind TrinityCore:master.

**Comment by Keldo** [comment]
funny when I pulled current and push to mine, but whatever Github breaks, not my issue

**Pull request closed without merging**
