### PR TITLE
Fix boss respawn behavior

### PR DESCRIPTION
**Pull request by Treeston**
> `[//]: # (***************************)`
> `[//]: # (** FILL IN THIS TEMPLATE **)`
> `[//]: # (***************************)`

~Bosses don't respawn if state is `DONE`. Pending work from @Keader.~

Anything with instance boss flag doesn't respawn anymore unless specifically told to (via respawn delay override).

Tagging issue #18824

### CODE REVIEW

**Comment by Noryad** [comment]
>New idea using dungeon boss flag. Drycoded.

This can cause [c6060dd0c511_worldserver.exe_[6-2_11-38-14].txt](https://github.com/TrinityCore/TrinityCore/files/755246/c6060dd0c511_worldserver.exe_.6-2_11-38-14.txt)

**Comment by Keader** [comment]
Dont work btw

**Comment by Treeston** [comment]
if it still doesn't work after latest commit, give me a solid simple repro case please

**Comment by Keader** [comment]
Change respawn time of Illidari Council Controller (to make more easy reproduce)
```sql
UPDATE `creature` SET `spawntimesecs`=YourTimeInSecsHere WHERE `guid`=52479;
```

.go crea 52479
Kill illidari council (bosses) or .die on trigger.
Wait he respawn

Trigger uses BossAI, and he summon illidari council.

**Comment by Treeston** [comment]
I'll take a look

**Comment by Keader** [comment]
@Noryad now it works :D

**Comment by Treeston** [comment]
Requesting quick lookover to make sure I didn't miss anything.

**Comment by r00ty-tc** [comment]
I think it looks OK. But, overall it's really bad this is the way to achieve such a simple concept. Hopefully something better can be done with the base that's available in dynamic spawn? Is there something else I should provide there to make this easier?

**Comment by Treeston** [comment]
@r00ty-tc with dynspawn, couldn't we change that to simply "do not schedule respawn" instead of the max time_t hack?

**Comment by r00ty-tc** [comment]
Yep. I think this is fine, based on the limitations we have. Just, something better should be done within the structure of dynamic spawning.

**Comment by Noryad** [comment]
merged!!!

**Comment by Noryad** [comment]
Fix not working for difficulty 25 (Lady Deathwhisper and Blood Prince Council).

**Comment by Keader** [comment]
Repro steps/boss?

**Comment by Noryad** [comment]
Confirmed with Lady Deathwhisper, probably Blood Prince Council too.

**Comment by Noryad** [comment]
@Treeston ?

**Comment by Keader** [comment]
Weird, was working in Black Temple (25 man)

**Comment by Noryad** [comment]
Merged in 94a6dd7
At this time it works ok for 10 man, not for 25 man, current revision 76f3e0e 

lady

**Comment by Keader** [comment]
Post it on the issue, still open i think

**Pull request merged**
