### PR TITLE
Core/Movement: Add new flag MOVEMENTGENERATOR_FLAG_PERSIST_ON_DEATH

### LINKED ISSUE #23095: Core/Unit: prevent the full cleanup of movements on death
**Description:** When you kill an accessory of a vehicle it remains installed and moves with the vehicle.

**Steps to reproduce the problem:**

1.  .go c id 29698 OR  27213
2. Kill the rider
3. Notice the rider remains in the vehicle once dead

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 78d6115fdc

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Add new flag MOVEMENTGENERATOR_FLAG_PERSIST_ON_DEATH to keep movement generators even after death.
- Keep Knockback movement generator after death

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Fixes #23095
Could replace ff26027453179448bb972d88a51e565d71e95f3f

**Tests performed:**

- target a mob
- .cast 59576 to trigger the knockback
- .damage 10000000 to kill the mob in the air

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Replace ff26027453179448bb972d88a51e565d71e95f3f with the flag added in this PR

### CODE REVIEW

**Comment by Jildor** [comment]
I think can also happens with jump effect and maybe more, by example Devourer of souls boss spell: 68820

target a hostile npc a bit far away (about 20-30 yards) to make the jump longer and have time to kill him in the air
.cast back 68820
.damage 10000000 to kill the mob in the air

**Comment by ccrs** [comment]
Damn, sorry, I didnt say anything at all before doing changes. Apologies.

**Comment by jackpoz** [comment]
@ccrs as long as they work it's all good. In a way having a PR on this can be a catalyst to get attention on the topic 😃

**Comment by jackpoz** [comment]
@Jildor I applied the same treatment to MoveJump too

**Comment by jackpoz** [comment]
anything left before I can merge this ?

**Comment by ccrs** [comment]
no objection from my side, there is something I'd like to add, but can be merged as is for now.

**Pull request merged**
