### PR TITLE
Add Boost 1.7x support

### PR DESCRIPTION
**Pull request by funjoker**
**Changes proposed:**

-  Added support for newer boost

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by jackpoz** [comment]
shouldn't there be some cherry-picked commits from 335 in this PR ?

**Comment by funjoker** [comment]
Well this would work yes. Didn’t check 335

**Comment by jackpoz** [comment]
there are some other commits adding different boost versions too, you could check the history of the cmake files

**Comment by Daribon** [comment]
Just grab the lastest FindBoost.cmake from cmake and it works out of the box.

**Comment by funjoker** [comment]
No need anymore

**Pull request closed without merging**
