### PR TITLE
Core/Misc: Update Worldserver.conf for AhBot Pricing -make things more clear

### LINKED ISSUE #14576: [Config] AHbot AuctionHouseBot.BuyPrice.Seller settings
The default config settings for AuctionHouseBot.BuyPrice.Seller is 1 and this means using SellPrice (the lower price).

In this way a player can earn easily 1000 gold per day just to go to AH buy items and sell it to any vendors. That's like cheating.

Strongly recommend to set this option to 0 (use BuyPrice, the higher one) by default.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11506972-ahbot-auctionhousebot-buyprice-seller-settings?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Jinnaix**
**Changes proposed:**

-  no functional changes, only makes things more clear

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:**

Closes #14576

**Tests performed:**

not needed

**Known issues and TODO list:** (add/remove lines as needed)

none

### CODE REVIEW

**Comment by jackpoz** [comment]
does the original issue about sell/buy price and people earning free gold still apply ? Maybe this PR doesn't actually solve that (and we should indeed flip the default value, in another PR though)

**Comment by Jinnaix** [comment]
Well, yes - without tweaking the AH Bot settings in general, there are several ways of generating gold for free/low effort.
Especially if you enable the AH Bot Buyer.

**Comment by illfated** [comment]
Cosmetic/grammar detail regarding this phrase: `the items BuyPrice or SellPrice`

As long as the words BuyPrice + SellPrice are meant to belong to "the items", the possessive apostrophe is recommended, like this:
- Singular: Should the Seller use the item's BuyPrice or SellPrice to determine Bid Prices
- Plural: Should the Seller use the items' BuyPrice or SellPrice to determine Bid Prices

Alternate, general phrasing: Should the Seller use item BuyPrice or SellPrice to determine Bid Prices

**Comment by Jinnaix** [comment]
@jackpoz - ive made changes due to our conversation in irc and added some more information for the two sided auctionhouse setting too.

**Comment by jackpoz** [comment]
Looks good

**Comment by jackpoz** [comment]
I updated the C++ default setting too (one has to change those too when changing .conf)

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
