### PR TITLE
ADD SOME DH SPELL 

### PR DESCRIPTION
**Pull request by bozoweed**
thanks to ovahlord for creat it & conana for this script
 https://github.com/Ovahlord
https://github.com/conan513

**Changes proposed:**
-  add fel rush
-  add chaos strike
-  add demon blades

**Target branch(es):** 6.x

**Issues addressed:** Closes #

**Tests performed:** tested and work :)

**Known issues and TODO list:**
- [ double jump work when we plane] 
  -[ some time we continue to plane and the wings is "close" ]

sorry for my bad english

ps : i have update the world and hotfix TDB but i don't know how can i give it to you 
in my tdb we have some quest of legion and npc spawn in legion

**NOTE** Enable the setting "Allow edits from maintainers." when creating your pull request.  
**NOTE** If your Pull Request is ONLY SQL create an issue instead!  
**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

**SUGGESTION** If your Pull Request contains SQL give it an impossible date, for example 9999_99_99_99_database.sql. This way it will be free on merge. Myself, i prefer to use 9999_99_99_xxxxx.sql where xxxxx is the id of the pull request, on that way we can merge multiple pull requests containing sql files on a row and rename the files with a single commit.

### CODE REVIEW

**Comment by Shauren** [comment]
Everything except demon blades looks like a copypaste from #17656

**Comment by bozoweed** [comment]
It's not look to the github of https://github.com/conan513 i havr takr it on this github for add it to trinitycore maybe it's the same code but i haven't copy paste from https://github.com/TrinityCore/TrinityCore/pull/17656

**Comment by Ovahlord** [comment]
He was probably copy pasting from my repository since @funjoker was also pushing the demon blades fix into my repo into a seperate branch. So as long as you are not the autor of the changes better do not PR things here.

**Comment by bozoweed** [comment]
I have look the pull request what you say and it seem to be the same but my pull request is most complet

**Comment by bozoweed** [comment]
I have copy it from this repository https://github.com/conan513 it's free leak source i was pull request it because they don't work on tc and i think they can help tc to make a better source and i was say from where i have take the source in top of my pr im not a stealer

**Comment by Ovahlord** [comment]
Conan has been watching my repository since a few days so it is more than obvious that the changes are copy pasted from my repository.  Just look at that code and then look at my one and you will see that it is the exact same code.

**Comment by bozoweed** [comment]
Why are you so close ? Why you juste don't pr your script if you do it ? I'm go to see you repository and in trinicore repository in branche 6.x your script is just full empty so why not let me pr this and let the other dev work on it for make it work better

**Comment by bozoweed** [comment]
And so your github is overhald ? Nop so stop flame thanks
https://github.com/conan513/SingleCore_TC/commit/7a2bf62939ece9c643de53669904e93ef1480c19

**Comment by bozoweed** [comment]
Look at this before say conan have copy on you
https://github.com/conan513/SingleCore_TC/commit/7a2bf62939ece9c643de53669904e93ef1480c19
https://github.com/conan513/SingleCore_TC/commit/7a2bf62939ece9c643de53669904e93ef1480c19
Thx

**Comment by Aokromes** [comment]
https://github.com/conan513/SingleCore_TC/commit/7a2bf62939ece9c643de53669904e93ef1480c19

Merge branch 'DHSpells' of https://github.com/Ovahlord/TrinityCore in…
…to 6.x

your reading skills are quite bad.

**Comment by bozoweed** [comment]
Oooooooooooooh damn sorry

**Comment by bozoweed** [comment]
I haven't good seen i have read it rapidly so sorry for that error

**Comment by bozoweed** [comment]
So you are the autor so all right go ovahlord

**Comment by bozoweed** [comment]
So ovahlord do you want delete the pr ? If you want so please delete it cause all right go to ovahlord 
But if you want let this pr for help tc you are awsome and i will say to a big thanks 
I let you choose what we do..

**Comment by funjoker** [comment]
PS:

The Proc was from me.
https://github.com/Ovahlord/TrinityCore/commits/DHSpells

on Ovahlords Repo too ;)

**Pull request closed without merging**
