### PR TITLE
Core/Player: add helper methods GetNativeGender/SetNativeGender/SetGender

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  fix some cases, where we should get player gender, instead of modified by display gender

-  
-  

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

### CODE REVIEW

**Comment by jackpoz** [comment]
I would prefer to have the rename of getGender() to GetGender() out of this PR (maybe I can even do it myself from visual studio)

**Comment by jackpoz** [comment]
is this ready to be merged ?

**Comment by ForesterDev** [comment]
Now it's ready. Can you review changes?

**Comment by jackpoz** [comment]
They look ok, can you test ingame latest commit about virtual too ?

**Comment by ForesterDev** [comment]
Just tested some cases - works good

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
