### PR TITLE
Core/BG: Fix score in AB

### PR DESCRIPTION
**Pull request by thomas33**
Battleground Arathi basin have max score 1500.

### CODE REVIEW

**Comment by CreshandKesh** [comment]
http://us.battle.net/wow/en/game/pvp/battlegrounds/arathi-basin
- - -
"The team that is the fastest to gather 1600 resources wins! "

**Comment by thomas33** [comment]
i played some time ago and was 1500.. sorry

**Comment by soulfrost** [comment]
ye, atm u need 1500 ( not 1600 ) on retail

**Comment by thomas33** [comment]
@soulfrost  no, 1600. It's my fail.

**Pull request closed without merging**
