### PR TITLE
Core/Movement: Remove MOVEMENTFLAG_MASK_MOVING and MOVEMENTFLAG_FLYIN…

### PR DESCRIPTION
**Pull request by HoustonCore**
**Changes proposed:**

- Remove flag can fly when mobs falling.

**Target branch(es):** 3.3.5/master

- [√ ] 3.3.5

**Tests performed:**

Does it build, tested in-game, etc.

**Follow-up**
- We need more checks and feedback.
- Please correct me in the standards.

[Video](https://www.youtube.com/watch?v=dmKeSj49Inc&feature=youtu.be)

### CODE REVIEW

**Comment by jackpoz** [comment]
which scenario does this fix ?

**Comment by HoustonCore** [comment]
> which scenario does this fix ?
> could you check what happens to the corpses of flying creatures when they die ?

Now I will try to record a video before and after)

**Comment by HoustonCore** [comment]
> which scenario does this fix ?
> could you check what happens to the corpses of flying creatures when they die ?

Done [video](https://www.youtube.com/watch?v=dmKeSj49Inc&feature=youtu.be)

**Comment by Shauren** [comment]
This is a completely wrong way to fix that.

**Comment by HoustonCore** [comment]
Ok

**Pull request closed without merging**
