### PR TITLE
Scripts/ScarletEnclave: reworked Eye of Acherus script

### LINKED ISSUE #23952: Movement/Quest: Death Comes from on High
**Description:** After this 2 commits, the auras used to change the speed are no longer working, the vehicle moves like it doesn't have any speed change.
I reverted:
https://github.com/TrinityCore/TrinityCore/commit/81475f709f067eea0437361e7098b7a6b9cf3a26
https://github.com/TrinityCore/TrinityCore/commit/fa9a4ee20d6a63f2e99e9feb45cd0ecf83ccc7f5

And the issue got fixed.

**Steps to reproduce the problem:**

1. .quest add 12641
2. .go game 65961
3. click the gob
4. Notice the speed during the traveling and after

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. e0835b467390

### PR DESCRIPTION
**Pull request by Ovahlord**
**Changes proposed:**
- updated script model to new standard
- corrected spell usage and timers based on sniff data
- removed hacks
- hi @ccrs 

For the smartasses that are trying to point on the removed fall movement: that one was a hack. The eye does not fall via spline but instead it's suposed to fall naturally by removing the canfly state from creature_template_movement. However, by doing so it's going to expose another movement bug that when you apply a flight aura at the same time when you remove one (like when arriving in new avalon) you will fall to the ground.

**Target branch(es):**

- [x] 3.3.5
- [ ] master

**Issues addressed:**
closes #23952

**Tests performed:**
- tested ingame, tests confirmed by @Killyana for 335

### CODE REVIEW

**Comment by jackpoz** [comment]
should we merge this right away or are you waiting for any other feedback by anyone ?

**Comment by illfated** [comment]
The code looks pretty streamlined & efficient to me.
Nice to see the "Tests performed" comment, but of course,
a last minute confirmation by the author would not hurt.

**Comment by Ovahlord** [comment]
If nobody has complaints against it, feel free to push the shiny button

**Review by ccrs — APPROVED** [review]
looks good, the less hacks the better
tbh I did never took the time to review whats blizzlike here, so kudos @Ovahlord 
also, thanks for testing it @Killyana  👍

**Review by ghost — APPROVED** [review]

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
