### PR TITLE
Implemented Book "Soothsaying for dummies"

### LINKED ISSUE #4425: [BUG] Book "Evil Soothsaying for Dummies" not work
This book
http://www.wowhead.com/object=177226#comments
works for switching profession specialization, learn and unlearn. Gnomish, goblin Engineering, Leatherworking specialty like Elemental or Dragonscale, alchemy specialization.

Item not work :-(

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65599-bug-book-evil-soothsaying-for-dummies-not-work?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ariel-**
Closes #4425
Loosely based on @elecyb work: elecyb@fb0ca6a

Same as #13356, using DB for gossips (I had no idea back then D:)

### CODE REVIEW

**Comment by tkrokli** [comment]
Good idea, it will be nice to have that profession feature working in-game. :+1:

**Comment by Keader** [comment]
@ariel-  Fix works. But enters the same problem as all other NPCs removing specialization... after relog specialization back to spellbook

**Comment by ariel-** [comment]
That is another bug, not in the scope of this PR to fix.

**Comment by elecyb** [comment]
@Keader Here is the fix for removing specialization: https://gist.github.com/elecyb/fcc302bbcc8bb9bc8275
Code is a bit old, but may apply in the current code

**Comment by Keader** [comment]
@elecyb work, but does not break anything else?I could open up a PR about it?

@ariel- Forgiveness escape the main objective of the PR

**Comment by elecyb** [comment]
@Keader yeah, feel free to PR it. 
It doesn't break anything, the code removed is completely obsolete and pre-wotlk https://github.com/cmangos/mangos-svn/commit/604224fdf4106cc667a120fe9ebb28aefc893882
Excluded spells are all profession specializations:
```
Effect_1=47 && Effect_2=0 AND NOT baseLevel

2656	Smelting
9787	Weaponsmith
9788	Armorsmith
10656	Dragonscale Leatherworking
10658	Elemental Leatherworking
10660	Tribal Leatherworking
17039	Master Swordsmith
17040	Master Hammersmith
17041	Master Axesmith
20219	Gnomish Engineer
20222	Goblin Engineer
26797	Spellfire Tailoring
26798	Mooncloth Tailoring
26801	Shadoweave Tailoring
28672	Transmutation Master
28675	Potion Master
28677	Elixir Master
```

Continue the discussion on the related issue #226

**Comment by ariel-** [comment]
@Keader I mean I didn't look into that issue, but the book working should be independant of the core bug which relearns a tradeskill specialization.

**Comment by jackpoz** [comment]
does this work flawlessly now that the "fix learn on login" PR has been merged ? can this be merged ? hand on the <insert your holy book of preference> ?

**Comment by Keader** [comment]
@jackpoz When tested, tested with two applied patches (before the merge, had manually applied here) and was functioning normally.

**Comment by jackpoz** [comment]
is wotlk.openwow.com/npc=7944 supposed to offer http://wotlk.openwow.com/quest=3647 after I unlearn Gnomish Engineering with the book and show the "Train Me" option with Gnomish Engineering recipes ?

**Comment by jackpoz** [comment]
so ?

**Comment by elecyb** [comment]
In pre-wotlk the renewal quests was required to get gnomish/goblin schematics from the trainer, after 3.1.0 the quest was removed and the schematics added to trainers. http://www.wowhead.com/item=11827/schematic-lil-smoky#comments:id=7687:reply=91409
For relearning spec, you just need to pay the fee and select the new one.
Here is a video that helped me with the initial implementation: https://www.youtube.com/watch?v=9ffNV2ZRI7M

Anyways, this implementation without the Leatherworking unlearn part, is incomplete.

**Comment by ariel-** [comment]
So, the same book should be able to change LW spec also? Thought there was NPC for that.

**Comment by jackpoz** [comment]
Please let me know when this PR is complete once it's clear how it should be (LW/trainer behavior)

**Comment by elecyb** [comment]
I mean learn LW spec in my previous comment, the unlearning is done by the npcs. To clarify, the book allows:
* Unlearn engineering specialization
* Learn engineering spec
* Learn leatherworking spec

Here is the same implementation with the LW spec learning implemented: https://gist.github.com/elecyb/78fb41f78f6940466350

**Comment by ariel-** [comment]
Makes me wonder, which one is the correct gossip whenever the player has both Engineering and Leatherworking?

**Comment by Treeston** [comment]
Both, I'd assume.

**Comment by Treeston** [comment]
Also, the LW trainers apparently offer to train you even if you don't have their spec. I think that's a bug?

**Comment by lonestarly** [comment]
I found I can learn Armorsmith with Weaponsmith Spec, Vice versa; I can learn Gnormish Engineer with Globin Engineer Spec, Vice versa. This did not happen with 2012ish TC patch, so it should be a bug.

**Comment by tkrokli** [comment]
@lonestarly : if you find a bug, report it in a new issue, unless an issue already exists for that bug.
Make sure you search the issues (use the search function) for related bugs before opening a new issue.

**Pull request merged**
