### PR TITLE
Tools/Maps: implement support for vMaps, MMaps on MapIDs with more than 3 digits

### PR DESCRIPTION
**Pull request by JustZerooo**
Example: SOO = MapID 1136

You need to reextract Maps & vMaps and regenerate MMaps.

Credits to https://github.com/Nightprince

**Changes proposed:**

-  Map, vMap, MMap Names
-  Typo Fix
-  Add Support for Maps with 4 digits
-  Teste myself and with some other peoples

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
-  Build and tests are successfully

**Known issues and TODO list:** (add/remove lines as needed)

- [X] No issues known

### CODE REVIEW

**Comment by SkyFire** [comment]
The highest map in 3.3.5A is map 724

**Comment by Shoxxo** [comment]
Sure, but they will merg it into Legion, that is what i think ;)

**Comment by Aokromes** [comment]
master already have support for 4 digits maps and it's unneeded on 3.3.5a / 4.3.4.

**Comment by Shoxxo** [comment]
FloatFix etc unneeded? Whats going wrong? It is needed. Rofl. ,Now i understand why it is unstable. TC Admin thinks they are masters lol.

**Comment by Keader** [comment]
Because:

> The highest map in 3.3.5A is map 724

why we should support something that never happens? 
Master branch is the only one that need it, and already support it.

**Comment by Shoxxo** [comment]
Did you self checked my changes? You have incorrect Float values and dont will be change it? Uninteresting if now supporting 4 dgits or not, but your code are dirty with wrong float values...

Like this : https://github.com/TrinityCore/TrinityCore/pull/20741/commits/8042c991d6cc5c7a2556ecf0d075a97636390a4c

**Comment by Jildor** [comment]
then make a new pull request with those corrections

if you have a problem with @Aokromes talk with him xD

**Comment by Aokromes** [comment]
so, you complain because i closed the pr because most of it is unneeded on 3.3.5a and you hide some valid fix on it?

**Comment by Aokromes** [comment]
4.3.4 higher map id:

980 - [Tol'Vir Arena]

**Comment by Wyreth** [comment]
@Shoxxo this problem is not related to 3.3.5, but you targeted branch 3.3.5, so it got closed since nothing useful can be done with it.

If you want to help, make another PR and **target the master (legion) branch**.

**Comment by Shoxxo** [comment]
Master branch is NOT up2date with retail server. So no. If you will be up2date with 7.3.2 than okay! NWe have no sniffer, no source and no one updating it to latest retail.

**Comment by Aokromes** [comment]
@Wyreth master branch already suports 4 digits maps (since early 6.x commits)

**Comment by Wyreth** [comment]
@Aokromes yep I see now, nothing to do here :D

**Pull request closed without merging**
