### PR TITLE
Fix various crashes, also related to multithreading

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Tests performed:** Compiles

Fixed some crashes. When iterating groups we have to either do it not in multithreaded context (map updates) or start with checking maps (they are guaranteed to change in single thread update). Properly clear ComboPoint references on player remove and remove some possible references item may have when it is deleted during save. Also clear all hostile references when unit is removed from map.

### CODE REVIEW

**Comment by Rochet2** [comment]
Fixes a lot/most/all of https://github.com/TrinityCore/TrinityCore/issues/17838

**Comment by Aokromes** [comment]
/home/travis/build/TrinityCore/TrinityCore/src/server/game/Groups/Group.cpp:1388:54: fatal error: 
      '&&' within '||' [-Wlogical-op-parentheses]
  ...if (!player || allowedMap != nullptr && player->FindMap() != allowedMap)
                 ~~ ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/TrinityCore/TrinityCore/src/server/game/Groups/Group.cpp:1388:54: note: 
      place parentheses around the '&&' expression to silence this warning
  ...if (!player || allowedMap != nullptr && player->FindMap() != allowedMap)
                                          ^
                    (                                                       )

**Comment by Viste** [comment]
some times on restart after add commit have this http://pastebin.com/LDbh5YN0

**Comment by Aokromes** [comment]
Totaly unrelated to this PR, i have seen that crash since months ago.

**Comment by Viste** [comment]
@Aokromes I got it. Not much looking through the crash log, before the crash did not appear, therefore, I thought it had something to do with the commit, and not understanding loaded dump. sorry for bad eng(google translate)

**Comment by Aokromes** [comment]
Баг не относится к пулл реквесту. Он существует на чистой тринити по крайней мере с июля

**Comment by Viste** [comment]
@Aokromes, 'то я уже понял, просто не разбирался в краш логе, и до этого не ловил такой краш. Словил его сразу через 20 минут как обновил ядро и добавил этот пулл реквест. удаляю комменты. спасибо за ответ

**Pull request merged**
