### PR TITLE
[WIP] Core/AI: Pets musn't attack civilian NPC in aggressive mode

### LINKED ISSUE #23974: PetAI: Pets musn't attack civilian NPCs on sight when in aggressive mode
**Description:**
Ref: https://github.com/cmangos/mangos-wotlk/commit/0103bc21fc5a7015b0cbca10bffd07a5c179a433

Change required here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CoreAI/PetAI.cpp#L105

Something like : if (!nextTarget->IsCivilian())

**Branch(es):** Both

**TC rev. hash/commit:** rev. 091ff42064ba

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Implement changes regarding civilian NPC from patch 1.8.0. 

Changed grid notifier is only used by PetAI.

**Target branch(es):** 3.3.5/

**Issues addressed:** Closes #23974

**Tests performed:** Tested with warlock imp in camp. Pet attacked guards but ignored civilians.

~**Known issues and TODO list:**~

### CODE REVIEW

**Comment by ccrs** [comment]
that does not belong there.
it should be decided by the AI.

**Comment by Killyana** [comment]
@ccrs looks good?

**Comment by jackpoz** [comment]
that ignores players now

**Comment by Sorikoff** [comment]
Now should work with players. 
As far as I understand this function just validates pre-chosen target for attack, so the change should be made where _choosing_ happens (...GridNotifiers maybe?). Also this didn't happen to me (tested in Kharanos).

**Comment by jackpoz** [comment]
I honestly preferred the original commit, maybe with a bool allowCivilian. You'll have to ask ccrs what he had in mind about what was wrong with your initial solution. 

With the current solution if the closest target is a civilian then the pet will not attack anyone

**Comment by Sorikoff** [comment]
@ccrs, what's wrong with the first commit (idea) ^^?

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
