### PR TITLE
Core/Scripts: move forge_of_souls gossip to DB

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

Forge of Souls: Lady Jaina Proudmoore & Lady Sylvanas Windrunner
- remove 2 lines of hardcoded text from forge_of_souls.cpp
- remove the unused enum `GOSSIP_SPEECHINTRO`
- remove the `OnGossipHello()` hook from both NPC scripts
- replace the `OnGossipSelect()` hook with `sGossipSelect`
- remove the `DoAction` hook because of sGossipSelect
- move the actions into the `OnGossipSelect()` hook
- add Sylvanas' gossip option to the gossip_menu_option table

(gossip option text for Jaina is already in the DB table gossip_menu_option)

**Target branch(es):** 3.3.5 + 6.x

**Issues addressed:** Updates https://github.com/velinath/TrinityCore/issues/2 , [**Gossip migration from core scripts to SAI/DB ToDo List**](https://github.com/velinath/TrinityCore/issues/2)

**Tests performed:** (Does it build, tested in-game, etc) Builds without issues. Text modifications only.
Gossip tested in-game, still works as expected.

**Known issues and ToDo list:**
- [x] Remove `OnGossipHello()` 
- [x] Replace `OnGossipSelect()` with `sGossipSelect`

### CODE REVIEW

**Comment by joschiwald** [comment]
the whole ongossiphello stuff should be moved to db

**Comment by tkrokli** [comment]
OK, I thought it would be difficult to change that because of the instance script, but if that won't interfere, I will make those changes. Thanks for the suggestion. :+1:

**Comment by ccrs** [comment]
both scripts can be done with sai afaik

**Comment by tkrokli** [comment]
Very possible, let me push my latest change and then we can check which row of actions to use.

**Pull request merged**
