### PR TITLE
Core/Unit: send npcs home after fear runs out

### LINKED ISSUE #21106: Core/Movement: Feared NPCs do not return to their home position
**Description:** Feared NPCs do not return to their home position.

After you cast spell id 33815 (AoE fear) on any NPC in a crowd, they do not return home after the last fear move.
They keep standing at the last fear waypoint.

**Expected behaviour:**

They should return home.

**Steps to reproduce the problem:**

1. `./cast self 33815` on an NPC in a crowd
2. watch the NPC until it gets released from Fear

**Branch(es):** Both

**TC rev. hash/commit:**  b08280fcfee500acf8b951ec2c05e0760d4b9955

### PR DESCRIPTION
**Pull request by Jinnaix**
**Changes proposed:**

-  send creatures back to home position after fear

**Target branch(es):**

- [x] 3.3.5

**Issues addressed:**

Closes #21106

Also gets rid of problems around the Honor Hold fear event (#22362 #24218)

**Tests performed:**

- [x] Builds
- [x] Creature out of combat before being feared and out of combat after fear runs out -> returns home
- [x] Creature out of combat before being feared but taken into combat before fear runs out -> continue combat
- [x] Creature in combat before being feared but out of combat before fear runs out -> return home
- [x] Creature in combat before being feared and in combat when fear runs out -> continue combat

**Known issues and TODO list:**

none that im aware of

### CODE REVIEW

**Comment by Jildor** [comment]
could it affect controlled units?

**Comment by Jinnaix** [comment]
> could it affect controlled units or pets?

Can you give me a example that you would like to have tested with the expected result?

**Comment by Jildor** [comment]
Fear on pet and leave combat and see what happens when remove fear effect

I'm not sure if when you control a unit (by example mind control) and unit get fear effect, lose mind control or not, in case mind control continue, try leave combat and see what happens when remove fear effect.

**Comment by Jinnaix** [comment]
Both scenarios are very unlikely to happen, but here are the results:
A)
If you fear a pet and get out of combat, the pet will return home with its owner.
B)
If you mindcontrol a unit (this takes you in combat with this unit), and it gets feared, it will break your mind control, stay in combat with you and attack you after fear runs out.
If you mindcontrol a unit and that unit gets feared and you get ot of combat in this situation, the fear effect is removed immediately and the unit will return home.

**Comment by jackpoz** [comment]
is this PR ready to be merged ?

**Comment by Jinnaix** [comment]
I have nothing left to add here - all tests successful. 

I will create a new issue and try to solve https://github.com/TrinityCore/TrinityCore/issues/21106#issuecomment-491614049 afterwards since this is not related to fear but should be handled the same.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
