### PR TITLE
README.md grammar improvements

### PR DESCRIPTION
**Pull request by vickychenglau**
**Changes proposed:**

-  Grammar edits for correctness and clarity in README.md.

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
None.

**Tests performed:** (Does it build, tested in-game, etc.)
No code was changed, so testing was unnecessary.

**Known issues and TODO list:** (add/remove lines as needed)

- [x] None.

### CODE REVIEW

**Comment by Gooyeth** [comment]
This needs revision? :thinking:

**Comment by tkrokli** [comment]
Not really, it is more about when one of the team members finds it appropriate to commit it to the source.

**Comment by tkrokli** [comment]
I just checked [the commit list for master](https://github.com/TrinityCore/TrinityCore/commits/master) and found that Shauren made a commit less than 20 minutes ago. I prefer to see the checks for that core commit finish without any issues before adding a cosmetic change to that list.

**Comment by tkrokli** [comment]
Thank you for the contribution. 👍

**Pull request merged**
