### PR TITLE
Core/Map: Added Map::SetZoneOverrideLight std::chrono overload

### PR DESCRIPTION
**Pull request by HelloKitty**
**Changes proposed:**

-  Add new overload Map::SetZoneOverrideLight taking std::chrono milliseconds
- Replace existing usages with std::chrono literals using the new overload

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

Compiles

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Comment by Shauren** [comment]
If you are also switching existing uses to use chrono overload, is there any reason to keep the old one?

**Comment by HelloKitty** [comment]
Hmmm, I can delete it but wasn't sure if I should delete the existing API. Want me to delete?

**Comment by Shauren** [comment]
At no point in history we ever guaranteed api stability, go ahead and delete it

**Comment by HelloKitty** [comment]
Okie dokie, I've gone ahead and remove it.

**Pull request merged**
