### PR TITLE
Core/Conditions: Added CONDITION_SOURCE_TYPE_POINT_OF_INTEREST

### PR DESCRIPTION
**Pull request by meji46**
**Changes proposed:**

-  Added CONDITION_SOURCE_TYPE_POINT_OF_INTEREST

**Issues addressed:**
None

**Tests performed:**
Builds, tested in-game.

**Known issues and TODO list:** (add/remove lines as needed)
None

### CODE REVIEW

**Comment by mdX7** [comment]
arent those limited by conditions on gossip_menu_option? (just thinking about oribos guards atm)

**Comment by Shauren** [comment]
Honestly if its just 1 special case, I would just write a creature script and manually send the POI from OnGossipSelect

**Comment by meji46** [comment]
It's the only one I've found but I don't know if there are more in, for example, the Brewfest event (which has pois)

**Comment by Shauren** [comment]
Yep, should be scripted

**Pull request closed without merging**
