### PR TITLE
Scripts/BlackfathomDeeps: Morridune will now start his pathaction again.

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
**Changes proposed:**

-  https://github.com/TrinityCore/TrinityCore/issues/24291
-  Doing stuff in the constructor is bad. Updated that shit. Waypoint will start again.
-  

**Target branch(es):** 3.3.5/master

- 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
-  https://github.com/TrinityCore/TrinityCore/issues/24291

**Tests performed:** (Does it build, tested in-game, etc.)
yes

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] all fine
- [ ]

### CODE REVIEW

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Keader** [comment]
lul, i was clicking in merge when the button change hahaha

**Comment by Rushor** [comment]
should we recheck all kind of bosses where shit is handled in constructor? is there a way to check all script at once that have some stuff inside the constructor?

**Comment by illfated** [comment]
@Rushor : is that referenced in ticket #24294 (**Scripts: Scripts that Could have SetInCombatWith not working properly**)?

**Pull request merged**
