### PR TITLE
Core/conf: conf.dist typo & grammar corrections

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

- Typo and spelling corrections
- Grammar corrections, English grammar
- Minor adjustments in example code readability
- Capitalization adjustments to keep consistency
  with existing idioms, phrases and concepts

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)

None that I know of.

**Tests performed:** (Does it build, tested in-game, etc.)

Documentation & comment changes only, does not affect any settings or source code.

**Known issues and TODO list:** (add/remove lines as needed)

I may have missed some incorrect grammar, wording or phrasing. Less likely that spelling issues remain.
Even so, suggestions and additional requests for changes are more than welcome.

### CODE REVIEW

**Comment by illfated** [comment]
**To all TC users:** Feel free to be very nit-picky with this, both regarding my changes and also when it comes to suggesting more changes where I might have overlooked something in the descriptions that can be improved.

**To the TC team members & owners:** I am open to keeping this PR open (unmerged) for however much time you think will be practical to get more feedback, in case more feedback is useful in this case.

**Comment by jackpoz** [comment]
looks good, can I merge it ?

**Comment by illfated** [comment]
Sure, if you think it is more useful to merge it now than waiting for more feedback from others.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
