### PR TITLE
Fix delete statement

### PR DESCRIPTION
**Pull request by iTob191**
This is my first contribution, so I hope I did everything right^^

The fix itself should be self-explanatory..

### CODE REVIEW

**Comment by DDuarte** [comment]
Thanks for the PR!

I know this sounds silly however we usually do not change old SQLs unless we absolutely have to do that (i.e SQL is not syntatically valid) and this typo has been fixed in https://github.com/TrinityCore/TrinityCore/commit/d08d6d08ef1e77635f715033b10bc32e4b62bad1 (a new sql re-adding the deleted data was added).

**Comment by iTob191** [comment]
Mhh okay, I had some troubles importing the sql-updates as the "modify xp" has row already existed..

**Comment by DDuarte** [comment]
That can only happen because you either tried to reimport the same SQLs twice or due to custom stuff that created the same exact command :)

**Comment by iTob191** [comment]
Yep, probably the first one^^

**Pull request closed without merging**
