### PR TITLE
Core/Spells: implement spell queue

### PR DESCRIPTION
**Pull request by Ovahlord**
Players can now queue up their spell and item cast requests a couple of milliseconds before the global cooldown expires or previous spell cast launches which then gets executed right away

**Changes proposed:**

-  adding a queue to store a spell cast request that has been made before an ongoing cast or gcd has expired, offering a seamless and more responsive casting experience

**Tests performed:**
- builds, tested ingame, long-term tested on 4.x

**Known issues and TODO list:** (add/remove lines as needed)
- Pet casts are currently not supported as they are essentially using their own cast request bracket and since pet spell casts are kinda poorly implemented atm, it's not worth wasting time with them.

### CODE REVIEW

**Comment by Nyr97** [comment]
Why would we support this if this was made to prevent high-latency users from having a bad experience gameplay-wise? Locally we have no lag whatsoever, and if I recall correctly, you rejected this specific feature for 4.3.4 branch some time ago when someone else requested or tried to implement it themselves.

**Comment by heyitsbench** [comment]
Maybe embed it in a config? For development/personal servers/QoL, turn the system off, for the sake of accuracy turn it on?

**Comment by Ovahlord** [comment]
> Why would we support this if Blizzard implemented this feature to ONLY prevent high-latency users from having a bad experience gameplay-wise? Locally we have no lag whatsoever. Also, if I recall correctly, you rejected this specific feature for 4.3.4 branch some time ago when someone else requested or tried to implement it themselves for that same reason.

The Client supports it, so we do so as well. That's it.

**Comment by acidmanifesto** [comment]
> Also, if I recall correctly, you rejected this specific feature for 4.3.4 branch some time ago when someone else requested or tried to implement it themselves for that same reason.


Its been in tcpp for a good while.
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/4430863a1e9a787a3a702b58adaf4c7bb639fa29

**Comment by Ovahlord** [comment]
> Maybe embed it in a config? For development/personal servers/QoL, turn the system off, for the sake of accuracy turn it on?

There is no reason to turn it off at all because all it does is storing packet information until it can be used and canceling spell casts as well, as the /cancelqueuedspell macro can interrupt it.

**Comment by Nyr97** [comment]
> > Why would we support this if Blizzard implemented this feature to ONLY prevent high-latency users from having a bad experience gameplay-wise? Locally we have no lag whatsoever. Also, if I recall correctly, you rejected this specific feature for 4.3.4 branch some time ago when someone else requested or tried to implement it themselves for that same reason.
> 
> 
> 
> The Client supports it, so we do so as well. That's it.

Well,,, https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/224 this states otherwise 👀

**Comment by Ovahlord** [comment]
> > > Why would we support this if Blizzard implemented this feature to ONLY prevent high-latency users from having a bad experience gameplay-wise? Locally we have no lag whatsoever. Also, if I recall correctly, you rejected this specific feature for 4.3.4 branch some time ago when someone else requested or tried to implement it themselves for that same reason.
> > 
> > 
> > The Client supports it, so we do so as well. That's it.
> 
> Well,,, [The-Cataclysm-Preservation-Project/TrinityCore#224](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/224) this states otherwise 👀

are you here to keep bitching about it or do you want to contribute some actual feedback like testing this stuff?

**Comment by Nyr97** [comment]
Both of them are fitting, but the later I'm doing currently.

**Review by mdX7 — APPROVED** [review]

**Pull request merged**
