### PR TITLE
Core/GameObject/Spells: Cherry pick some lock & distance things from 3.3.5

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

-  Cherry pick https://github.com/TrinityCore/TrinityCore/commit/32e1de39a26628dcb64bc21ad415afb2ad938925 and https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7

**Target branch:**

- master

**Issues addressed:**

Closes: unknown. A lot of things can be affected by this. Think about bombs in Isle of Conquest (disarm),

**Tests performed:**

- Builds
- Tested with capture points

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] A lot of gameobjects / spells might be affected by this. Need to figure out if there is any wrong behaviour

### CODE REVIEW

**Comment by meji46** [comment]
Could be cherry-picked from https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7 ?

**Comment by Golrag** [comment]
I tried to cherry pick them, not sure if i made mistakes

**Comment by Ovahlord** [comment]
it will eventually get picked when they get there. until then no.

**Comment by Golrag** [comment]
So, i should close this pr and just wait for you guys to get the cherry picks done? :p

**Comment by Shauren** [comment]
Now cherry-picked

**Pull request closed without merging**
