### PR TITLE
Corrected execution time calculation for dst targets

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5

- [x] 3.3.5

**Tests performed:** Compiles

### CODE REVIEW

**Comment by joschiwald** [comment]
there are more places where this calculation is done

**Comment by xinef1** [comment]
This is the only place where that kind of calculation is done

**Comment by joschiwald** [comment]
Spell::AddUnitTarget
Spell::AddGOTarget

are also affected by caster size

**Comment by xinef1** [comment]
That is something else, this is delayTime calculation to destination point

**Comment by joschiwald** [comment]
why is the delay to destination not affected by caster size, while delay to units or gameobjects is?

**Comment by xinef1** [comment]
Because this matches clients animation (check Malleable Goo cast by Profesor Putricade)

**Comment by Treeston** [comment]
This is flat out incorrect for certain spells (Halion's Meteor Strike (74637) among others).

There is more to this than "hitbox size is not taken into account for ground targeting" (if only because that'd be really weird).

**Pull request merged**
