### PR TITLE
Core/Player: fix  crash in Legion & WoD Scenario locations

### LINKED ISSUE #18476: [master] Scenario locations of Legion & WoD crashes.
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Scenario locations of Legion unavailable and forces client/server crashes when you try to get there.

**Current behaviour:** Server and/or client crashes with "unknown opcodes" errors.

**Expected behaviour:** Sucsessiful loading, no errors server/clientside.

**Steps to reproduce the problem:**

1.  Start the server, create any character.
2.  Try to get into Broken Shore/Azsuna/Other scenario zones. For example: .go 84.3099 1942.78 14 1460 or .go 301.491 7320.21 149.96 1461 or I guess almost any other Legion scenario zone.
3.  You will get client or server crash after loading will be almost complete. Mostly client crashes.

**Branch(es):** master

**TC rev. hash/commit:**  bfa9a4c9597c748734836fa2293f1ccf9724dbba

**TDB version:**  703.00

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by ChipLeo**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Additional check in packet creation.

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [X] master

**Issues addressed:** 

- Closes #18476 

**Tests performed:**

- Tested in game on master branch.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ]

### CODE REVIEW

**Comment by Viste** [comment]
Wtf? master 3.3.5 any discription plz

**Comment by joschiwald** [comment]
provide a crashlog pls

**Comment by Ovahlord** [comment]
This change fixes the issue when you try to enter a map that has a scenario for example in the case of the master branch. Since scenario maps are considered a dungeon map the core tries to get a difficulty for the map. And since there is no difficulty the core simply crashes. This change will fix it.

**Comment by Eredar** [comment]
Can confirm that it works and solves Issue#18476. But need proper description by template.

**Comment by ChipLeo** [comment]
Confirm, that it works and solves #18476.

**Comment by ChipLeo** [comment]
CrashLog:

Revision: TrinityCore rev. e2ed6bb00171 2017-02-19 17:58:48 +0200 (master branch) (Win64, Debug, Static)
Date 24:2:2017. Time 22:30 
//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF6708378DD 01:0000000000CD68DD E:\Trinity7\worldserver.exe

Call stack:
Address   Frame     Function      SourceFile
00007FF6708378DD  0000005E5EFFD180  boost::optional_detail::optional_base<unsigned int>::construct<unsigned char const & __ptr64>+5D  c:\local\boost_1_59_0\boost\optional\optional.hpp line 618
00007FF6708372E3  0000005E5EFFD1B0  boost::optional_detail::optional_base<unsigned int>::assign_expr<unsigned char const & __ptr64,unsigned char>+73  c:\local\boost_1_59_0\boost\optional\optional.hpp line 440
00007FF6707FA746  0000005E5EFFD1F0  boost::optional<unsigned int>::operator=<unsigned char const & __ptr64>+56  c:\local\boost_1_59_0\boost\optional\optional.hpp line 894
00007FF6707627B9  0000005E5EFFD950  Player::SendInitialPacketsBeforeAddToMap+639  e:\wow\src\trinity\trinitycore\src\server\game\entities\player\player.cpp line 23260
00007FF671AE6CE8  0000005E5EFFE010  WorldSession::HandleMoveWorldportAck+998  e:\wow\src\trinity\trinitycore\src\server\game\handlers\movementhandler.cpp line 107
00007FF671AE633D  0000005E5EFFE040  WorldSession::HandleMoveWorldportAckOpcode+2D  e:\wow\src\trinity\trinitycore\src\server\game\handlers\movementhandler.cpp line 42
00007FF671887DD1  0000005E5EFFE0F0  PacketHandler<WorldPackets::Movement::WorldPortResponse,&WorldSession::HandleMoveWorldportAckOpcode>::Call+71  e:\wow\src\trinity\trinitycore\src\server\game\server\protocol\opcodes.cpp line 34
00007FF67071F439  0000005E5EFFE900  WorldSession::Update+599  e:\wow\src\trinity\trinitycore\src\server\game\server\worldsession.cpp line 396

**Comment by Eredar** [comment]
Summon @Krudor. Since sceanrio system is his work. Also scenarios entered without LFG system are not loading step information, but they should do it same way as instances, because all current legion scenarios except one (broken shore) were made for one player without lfg. Invasions not use lfg aswell. Also we need smooth loading implementation without screen, I saw few "preloaded maps" and "hide loading screen" strings in sniffs and it is also needed for garrisons, they use the same system.

**Comment by Eredar** [comment]
I sniffed whole battle on high seas scenario (alliance side) and put it into db, after it went there and there was no progress(step) info. First thought it was not linked at scenario table, but after few checks of map 1099, I found that they are there, and have proper scenario id (that I found in sniffs), so I thought the problem is that they were not implemented yet (or atleast not available without lfg).

**Comment by Krudor** [comment]
They are, you just can't enter scenarios in the proper difficulty.
You're probably ending up in the default difficulty, normal (1), when the scenario is registered to the real scenario difficulties, normal and heroic (11 and 12).
This is why you need LFG.
It is not possible to select scenario difficulty from the UI.

**Comment by Golrag** [comment]
On the PTR (7.2) when you use /console worlport mapid x y z, and you use a scenario as map, you get loading screen but you go quickly out of it without being teleported with an error message: "<selected difficulty> mode is not available for <scenario name>."'

ex:
/console worldport 1095 0 0 0
Normal difficulty is not available for Dagger in the Dark.

**Comment by Krudor** [comment]
Adding logic to default to difficulty 3 for instance type scenario makes all the sense in the world, but it's still not going to help the scenarios in MoP that doesn't have map difficulty entries.
Something in the LFG system is helping them launch properly.

**Comment by Eredar** [comment]
@Krudor I tried to change difficulty in db to 1, and progress still wasn't there. When you enter with .go command it is not creating "instance", so instanceID in .gps = 0. Maybe problem is scenarios not binded to instance manager? When you use .go to get in raid, you properly get an ID(lockout) for your instance same for 5 man dungeons, and in case of scenarios you don't get any. So looks like it is not coded properly.

**Comment by Krudor** [comment]
bool Instanceable() const { return InstanceType == MAP_INSTANCE || InstanceType == MAP_RAID || InstanceType == MAP_BATTLEGROUND || InstanceType == MAP_ARENA; }
No wonder

**Comment by Eredar** [comment]
Any news? Summon @Shauren

**Comment by ChipLeo** [comment]
This pull is wrong?

**Comment by Shauren** [comment]
You merged this really wrong and reverted the 7.2.5 update

**Comment by ChipLeo** [comment]
This pull need for 24461....

**Comment by Shauren** [comment]
Better fix incoming

**Pull request closed without merging**
