### PR TITLE
 Game/AI: Implement option to move a creature back to Homeposition on Evade.

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
…Evade.

* If ToHomePosition (action param 1) is 1 > Move to last stored position
* If ToHomePosition (action param 1) is 0 > Move to homeposition
* Ref: https://github.com/TrinityCore/TrinityCore/issues/24226

**Changes proposed:**

* If ToHomePosition (action param 1) is 1 > Move to last stored position
* If ToHomePosition (action param 1) is 0 > Move to homeposition
* Ref: TrinityCore#24226

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)

https://github.com/TrinityCore/TrinityCore/issues/24226
**Tests performed:** (Does it build, tested in-game, etc.)
yes

**Known issues and TODO list:** (add/remove lines as needed)

- [x] nothing
- [ ]

### CODE REVIEW

**Comment by Killyana** [comment]
Can you add an other param walk/run ?

**Comment by Rushor** [comment]
Why not adding it with the existing Action setwalk/run?

Should it run by default?

**Comment by Killyana** [comment]
Yes it must run by default, but as we will update existing SAI it's easier to just update the current line than adding an extra one for walk.

**Comment by Rushor** [comment]
okay cool, i will see if it is possible

**Comment by Rushor** [comment]
@Killyana added, if param walkmode 0 run by default

**Comment by Killyana** [comment]
I tested this issue https://github.com/TrinityCore/TrinityCore/issues/23917
The taunkas around Roanauk must evade to home position walking when the event ends.
But the just stay there:
image

``` sql
UPDATE `smart_scripts` SET action_param1=0, action_param2=1 WHERE `entryorguid` IN( -102327,-102329,-102326,-102330,-102328,-102341,-102333) AND action_type=24;

**Comment by Rushor** [comment]
@Killyana okay i think the homeposition was not stored here - and name was wrong.

what we want: if paramter is 0 > move creature to the spawnposition.

what i changed:

if action_param1 (ToRespawnPosition) = 0, store new homeposition from respawnposition and move to it.

**Comment by Killyana** [comment]
It works fine now, thanks.
I need to some tests for other situations to be sure nothing get broken.

**Comment by Killyana** [comment]
Npcs always run on evade whatever the value of action_param2

**Comment by Rushor** [comment]
hm i cannot see the reason why they always run

**Comment by jackpoz** [comment]
> hm i cannot see the reason why they always run

https://github.com/TrinityCore/TrinityCore/blob/dc7856644f48d6b313e973197fed69ef56d6b5e0/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp#L79

**Comment by jackpoz** [comment]
should the walk/run bit be ignored and merge the PR the way it is now ?

**Comment by illfated** [comment]
Could be a useful incentive to fix the mentioned walk/run issue if the current functionality becomes available to all. From what we have seen too often, testing does not take place until the code is published.

**Comment by Rushor** [comment]
hm yeah then let's merge that "remove to home" fix first. i will remove the option with walk/run again.

or i must copy the function of GetMotionMaster()->MoveTargetedHome(); and define the 

what would you suggest?

**Comment by Killyana** [comment]
In thins case make the npc return to home pos if there's no escort, and evades to the last point if it evades after a combat, no need to add an extra param

**Comment by jackpoz** [comment]
what's the status of this PR ?

**Comment by jackpoz** [comment]
>jackpoz commented on Jun 6
what's the status of this PR ?

2nd try: what's the status of this PR ?

**Comment by illfated** [comment]
Hello, @Rushor . Thanks for the code to the "Force of Neltharaku" PR which is merged now. 
I see you have been active about 2 days ago. 
Everything OK, I hope?

**Comment by jackpoz** [comment]
Setting the status of this PR back to Draft as there are still some things left to do. Please mark it as ready for review once they have been handled.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
