### PR TITLE
Scripts/Quest: Force of Neltharaku quest credit

### LINKED ISSUE #24796: Scripts/Quest: spell "Force of Neltharaku" gives double quest credit
**Description:**

- https://www.wowhead.com/quest=10854/the-force-of-neltharaku
- https://www.wowhead.com/npc=21722/enslaved-netherwing-drake
- https://www.wowhead.com/npc=22316/enslaved-netherwing-drake-kill-credit
- https://www.wowhead.com/npc=23187/enslaved-netherwing-drake
- https://www.wowhead.com/item=31652/enchanted-nethervine-crystal
- https://www.wowhead.com/spell=38762/force-of-neltharaku
- https://www.wowhead.com/spell=38775/force-of-neltharaku
- https://wow.gamepedia.com/Dragonmaw_Fortress
- https://wow.gamepedia.com/Netherwing_Fields

While doing the quest ["The Force of Neltharaku" (10854)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=10854), using the item ["Enchanted Nethervine Crystal" (31652)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=31652) on the [hostile Enslaved Netherwing Drake](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=21722) to turn them into the [friendly Enslaved Netherwing Drake](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=23187), I noticed that freeing 1 drake counted double for each release. After 1/5 drakes freed, I had received quest credit 2/5 and after freeing drake 2/5 I got 4/5 quest credit.

**Expected behaviour:**

The spell ["Force of Neltharaku" (38775)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=38775) should only give 1 quest kill credit. (Unfortunately, I did not think of checking the spell details before I left the game, so I did not notice if anything was wrong with the 15% Haste the spell is also supposed to cast on the player.)

**Steps to reproduce the problem:**

1. Use a level 70+ character with flying mount.
2. `.tele NetherwingFields`
3. `.quest add 10854`
4. Fly to and land in or nearby the Dragonmaw Fortress entrance area.
5. While being out of combat, use the item Enchanted Nethervine Crystal on any Enslaved Netherwing Drake, then kill any nearby Dragonmaw orcs fighting the friendly drake.
6. Wait a few seconds for the return spell from the drake to player.
7. Watch the quest credit displayed as double the number of drakes freed.

**Branch(es):**

Most likely both, because the quest is still available in retail. I just don't have the master branch client or server available for testing.

**TC rev. hash/commit:** 

TrinityCore rev. f2f4fc921ee8 2020-06-09 09:57:47 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
```
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80020
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-1016-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /build/data/maps. Total size: 251987687 bytes
vmaps directory located in /build/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /build/data/mmaps. Total size: 2010221346 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20051
```

**Operating system:** Windows 10 Version 2004 Home x64 on client computer.
Ubuntu(?) Linux/Unix on https://tcubuntu.northeurope.cloudapp.azure.com/

***
I don't know if there is anything wrong with how the spells are used in this script, but maybe it can help tracking where it happens or finding out where to look. 
I did not find anything in `spell_quest.cpp` related to this, so maybe these spells are only sourced from dbc data.

https://github.com/TrinityCore/TrinityCore/blob/e3b232fe0e5c21a87d3fe71813e9d750259823f1/src/server/scripts/Outland/zone_shadowmoon_valley.cpp#L337-L473

### PR DESCRIPTION
**Pull request by ghost**
**Description:**

Suggested solution to resolve the kill credit double cast issue in the quest "The Force of Neltharaku" (10854).

by Rushor

**Changes proposed:**

- Remove duplicate spell casts in the zone quest script
- Remove commented-out script section
- Set a couple of unit flags (anim/stand/hover)
- Move return new creature script override to end of script
- Move PlayerGUID, FlyTimer, and Tapped to Private
- Add DB flight movement control to Enslaved Netherwing Drake
- Add SpellMgr MaxAffectedTargets = 1 for spell 38762
- Add movement enum POINT_MOVE_UP
- Add missing enum for quest ID

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [X] master

**Issues addressed:** Closes #24796

**Tests performed:** (Does it build, tested in-game, etc.)

Builds fine, works as expected (and intended?) in-game. Issue #24796 is solved.

**Known issues and TODO list:** (add/remove lines as needed)

- [X] Open PR in draft mode until build is cleared
- [x] Compile and create local server
- [x] Test changes on local server

### CODE REVIEW

**Comment by jackpoz** [comment]
@Rushor was there anything else to do in this PR ?

**Comment by illfated** [comment]
Sorry for being late in building my local server environment for testing and confirming that it works as intended. It has been too hot during the last week (in Oslo) to do anything more than work as usual during daytime and wait for the heat to subside to sleep at night. Pushing my computer to build anything without turning off due to not enough cooling.

**Comment by jackpoz** [comment]
No hurry, I can put this pr on hold

**Comment by illfated** [comment]
- [X] MSVC build environment established.

**Comment by illfated** [comment]
- [X] All maps extracted and moved to new core. Ready for testing.

**Comment by illfated** [comment]
- [X] Tested in-game. Works a lot better now. I will even go so far as to say that it works as intended and expected. No complaints from me, I was getting the correct amount of quest credit.

**Comment by illfated** [comment]
BTW, you might want to set Rushor as author when merging.

**Comment by illfated** [comment]
@Rushor : Out of curiosity, do you know if this code is in use anywhere else, so you know others have confirmed it to be working?
I am merely thinking whether this PR needs more testing / confirmation besides my own testing.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Rushor** [comment]
sorry i totally did not saw this - yeah there was nothing to add on my side. maybe convert to sai in future. but all else seems stable.

**Comment by illfated** [comment]
> sorry i totally did not saw this - yeah there was nothing to add on my side. maybe convert to sai in future. but all else seems stable.

Good point, thanks for the feedback.

@offl : I guess you can add this to your list of potential future SAI conversions, right? 😉

**Comment by offl** [comment]
It should be converted but I'm not sure if it will be the same after conversion
If it will be not the same, I prefer leave CPP

**Comment by illfated** [comment]
Fair enough. If there are any doubts that the in-game will stay the same, it might just as good to leave it as it is for now, until someone finds a way to keep the functionality working through SAI.

**Pull request merged**
