### PR TITLE
DB/Azsuna: Remove trigger spell (not in sniff)

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

- This fix should be merged at the same time that https://github.com/TrinityCore/TrinityCore/issues/28570

### CODE REVIEW

**Comment by Ovahlord** [comment]
did you check if the spell is used anywhere else before breaking it entirely? It's a trigger missile spell so I highly doubt that they did that for no reason.

**Comment by aquadeus** [comment]
> did you check if the spell is used anywhere else before breaking it entirely? It's a trigger missile spell so I highly doubt that they did that for no reason.

yes, only used in azsuna, and the damage breaks the aura for this npc https://gyazo.com/0f7a129f0e32c9d9d57ec05eb3c02199

**Comment by Ovahlord** [comment]
check the sniff if there is a damage log packet dealing damage with the trigger spell. if yes, your suposed fix is a hack and what we have to fix here instead is the interruption of the aura which may be due to interrupt flags or evading

**Comment by Shauren** [comment]
181593 has TARGET_UNIT_NEARBY_ENTRY, meaning it should have data in conditions table - if your sniff doesnt have 181594 then that means no eligible target was present there

**Comment by aquadeus** [comment]
i put the conditions for the target unit nearby in the sql, and spell 181593 is in the sniff 

ServerToClient: SMSG_SPELL_START (0x2C3D) Length: 119 ConnIdx: 1 Time: 11/30/2022 23:19:03.194 Number: 4020
(Cast) CasterGUID: Full: 0x2016F49880596100000408000086D667 Creature/0 R1469/S1032 Map: 1220 (Broken Isles) Entry: 91524 (Cannon) Low: 8836711
(Cast) CasterUnit: Full: 0x2016F49880596100000408000086D667 Creature/0 R1469/S1032 Map: 1220 (Broken Isles) Entry: 91524 (Cannon) Low: 8836711
(Cast) CastID: Full: 0xBC16F49880B15643000408000807D6D7 Cast/3 R1469/S1032 Map: 1220 (Broken Isles) Low: 134731479
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: 181593 (Fire Cannon)
(Cast) (Visual) SpellXSpellVisualID: 81135
(Cast) (Visual) ScriptVisualID: 0
(Cast) CastFlags: 2
(Cast) CastFlagsEx: 1048576
(Cast) CastTime: 0
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) Ammo.DisplayID: 0
(Cast) DestLocSpellCastIndex: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) HitTargetsCount: 0
(Cast) MissTargetsCount: 0
(Cast) HitStatusCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) (Target) Flags: 0 (Self)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) hasMapID : False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(Cast) (Target) Name: 

ServerToClient: SMSG_SPELL_GO (0x2C3C) Length: 135 ConnIdx: 1 Time: 11/30/2022 23:19:03.194 Number: 4021
(Cast) CasterGUID: Full: 0x2016F49880596100000408000086D667 Creature/0 R1469/S1032 Map: 1220 (Broken Isles) Entry: 91524 (Cannon) Low: 8836711
(Cast) CasterUnit: Full: 0x2016F49880596100000408000086D667 Creature/0 R1469/S1032 Map: 1220 (Broken Isles) Entry: 91524 (Cannon) Low: 8836711
(Cast) CastID: Full: 0xBC16F49880B15643000408000807D6D7 Cast/3 R1469/S1032 Map: 1220 (Broken Isles) Low: 134731479
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: 181593 (Fire Cannon)
(Cast) (Visual) SpellXSpellVisualID: 81135
(Cast) (Visual) ScriptVisualID: 0
(Cast) CastFlags: 256
(Cast) CastFlagsEx: 1048592
(Cast) CastTime: 3399432277
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) Ammo.DisplayID: 0
(Cast) DestLocSpellCastIndex: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) HitTargetsCount: 1
(Cast) MissTargetsCount: 0
(Cast) HitStatusCount: 1
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) (Target) Flags: 0 (Self)
(Cast) (Target) HasSrcLocation: True
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) hasMapID : False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(SrcLocation) Transport: Full: 0x2016F4988057C700000408000006E931 Creature/0 R1469/S1032 Map: 1220 (Broken Isles) Entry: 89884 (Flog the Captain-Eater) Low: 452913

the triggered is not present

**Comment by Nyr97** [comment]
Any update on this? It's not the first time TARGET_UNIT_NEARBY_ENTRY is used while the given creature it is used for the given condition is not present, e.g. Toss Bomb (spellId 84467) which uses TARGET_DEST_NEARBY_ENTRY. Example: https://github.com/TrinityCore/TrinityCore/pull/28404

**Pull request merged**
