### PR TITLE
DB/Misc: Adding missing SAI scripts for mobs in Borean Tundra "part1"

### PR DESCRIPTION
**Pull request by HoustonCore**
**Changes proposed:**

-  Adding missing SAI scripts for mobs in Borean Tundra

**Target branch(es):** 3.3.5/master

- [√] 3.3.5

**Tests performed:**

- Tested in-game.
- Need feedback.

**P'S:**
- Information for spell i get in wowhead and my old scripts. If I'm wrong, correct me.

### CODE REVIEW

**Comment by Aokromes** [comment]
hi, for sql only fixes open a ticket instead.

**Comment by HoustonCore** [comment]
> hi, for sql only fixes open a ticket instead.

So I should open a ticket and not a pr?

**Comment by MaxtorCoder** [comment]
> 
> 
> > hi, for sql only fixes open a ticket instead.
> 
> So I should open a ticket and not a pr?

Well he said that, didn't he?

**Comment by illfated** [comment]
True, good point. For SQL-only fixes, those need to be posted in regular issue tickets. TC accepts Pull Requests only when you include C++ files, for example when you replace C++ scripts with SQL solutions (e.g. SAI).

@HoustonCore : Regarding a technical GitHub detail, when you edit your own PRs, please use a regular uppercase X instead of that square root symbol to mark a tick box as ticked, see example below:

- [X] 3.3.5

(MarkDown code block, to show what it looks like in plain text: )
```
- [X] 3.3.5
```

This may seem very cosmetic and nitpicky to you, but GitHub actually reads tick boxes and treats them as part of a task list, mostly in the main PR comment or in opening issue ticket comment, referenced in some side note in the right hand side details of the page (or sometimes in details referenced elsewhere on GitHub). Those references say something like "2 of 3 tasks completed".

**Comment by HoustonCore** [comment]
@illfated Well sorry, thanks for the info.  I will correct it next time)

**Comment by illfated** [comment]
Very well. Don't be too hard on yourself, things like that are to be expected by fairly new users on GitHub. That is one only of those things we all learn sooner or later. 😃

**Pull request closed without merging**
