### PR TITLE
Core/Creature: Fixed ForcedDespawn

### PR DESCRIPTION
**Pull request by ghost**
Existing code prevents forceRespawnTimer from being used to determine respawn time if creature is already dead before DespawnOrUnsummon is used.

### CODE REVIEW

**Comment by Shauren** [comment]
The `IsAlive()` check is there for a reason - you can't just expect everything will work if you call setDeathState(JUST_DIED) on a dead creature.
Just removing it is a wrong approach.

**Comment by malcrom** [comment]
I can't see what reason.

**Comment by malcrom** [comment]
I can change to:

    else
        if (IsAlive())
            setDeathState(JUST_DIED);

But the first setDeathState(JUST_DIED) must be there to update the respawn timer.

**Comment by malcrom** [comment]
This is working. I need this pushed.

**Pull request merged**
