### PR TITLE
[Scripting/Helper]: Implement FindNearestCreatureWithOptions

### PR DESCRIPTION
**Pull request by Seyden**
**Changes proposed:**

-  
-  
-  

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by mdX7** [comment]
#28410 there was a discussion about using lambda expressions for it, that would be more powerful than this approach

**Comment by Seyden** [comment]
> #28410 there was a discussion about using lambda expressions for it, that would be more powerful than this approach

it would indeed be but not everyone knows all the options regarding the core and also not every scripter knows how to write lambdas. Having predefined options, makes it easy for scripters to look for what they're looking for

**Comment by Nyr97** [comment]
we can add more options as time passes by though, that's the great part of this PR!

**Comment by ImmortalusDev** [comment]
> > #28410 there was a discussion about using lambda expressions for it, that would be more powerful than this approach
> 
> it would indeed be but not everyone knows all the options regarding the core and also not every scripter knows how to write lambdas. Having predefined options, makes it easy for scripters to look for what they're looking for

Warpten wrote there example, so anyone can use it

**Comment by Seyden** [comment]
I found a new issue regarding phasing.. CreatureLastSearcher and every GridNotifier Searcher Visit Check has a HasInPhase Check.. so i'm not quite sure why we're even checking 2 times if the object is in the certain phase:

1 time in the Visit function of the GridNotifier Searcher
1 time in the Visitor checker for each implementation which also checks for the phase

i have to implement a new gridnotifier searcher struct (without the phase check) and will then move my FindNearestCreatureWithOptions to this impl

**Comment by xvwyh** [comment]
A lambda could be added as an `std::function` field to FindCreatureOptions, killing two birds with one stone: both preserving the simplicity of common checks implemented as part of FindCreatureOptions, and adding the flexibility of custom checks via lambdas. Just depends on whether TC overlords will approve of the minor extra costs that comes with `std::function`.

**Pull request merged**
