### PR TITLE
Core/SAI: Fix the respawn event for GameObjects

### LINKED ISSUE #22612: Core/SAI: The SMART_EVENT_RESPAWN is no longer triggering with GameObjects
**Description:** The SMART_EVENT_RESPAWN is not triggering if used by a GameObject.

``` sql
-- Stone of Binding
UPDATE `gameobject_template` SET `AIName`="SmartGameObjectAI" WHERE `entry`=141812;
DELETE FROM `smart_scripts` WHERE `entryorguid`=141812 AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(141812,1,0,0,11,0,100,0,0,0,0,0,12,321,5,0,0,0,0,1,0,0,0,0,0,0,0,"Stone of Binding - On Respawn - Summon npc"),
(141812,1,1,0,60,0,100,0,5000,5000,5000,5000,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stone of Binding - On update  - despawn'");
```

**Steps to reproduce the problem:**

1. execute the SQL above
2. .go game 42469
3. Notice there's no npc 321
4. Once the gob despawn use .respawn (without target) to respawn it and notice there's no summoned npc, that means the SMART_EVENT_RESPAWN is not firing if used by gobs

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 7c003c568cdd

### PR DESCRIPTION
**Pull request by Killyana**
**Changes proposed:**
Fix the issue related to the respawn event not being triggered for GameObjects

**Target branch(es):** 
- [x] 3.3.5

**Issues addressed:** Closes #22612

**Tests performed:** Tested in-game
I'm not sure about the change related to "strcmp"

### CODE REVIEW

**Comment by Sorikoff** [comment]
I believe `strcmp` change is not needed. At least not related to this PR.

**Comment by Killyana** [comment]
Now the event SMART_EVENT_RESPAWN is triggred on evade for creature, we need to fix this.

**Comment by Killyana** [comment]
The issue wa caused: by https://github.com/TrinityCore/TrinityCore/commit/637b5f922d5849fa5b01d8ed28a826eddd3dc2cd#diff-703f1f16a955ae7ddc7caf673a75d85a

**Comment by Killyana** [comment]
We must choose to add the respawn on: SmartGameObjectAI::Reset()    or   SmartGameObjectAI::InitializeAI()

**Comment by Killyana** [comment]
I restored the respawn call on SmartGameObjectAI::InitializeAI(), and every thing works fine for all gobs that use this event: ` SELECT * FROM `smart_scripts` WHERE `event_type`=11 AND `source_type`=1;`

**Pull request merged**
