### PR TITLE
Core/ThreadManager: delete double include "TemporarySummon.h"

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
**Changes proposed:**
- Delete double include "TemporarySummon.h"

**Target branch(es):** 3.3.5/master
- [x] 3.3.5

### CODE REVIEW

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by illfated** [comment]
Wouldn't avoiding situations like this be more obvious if all the include lists were sorted Lexicographically (alphabetically) ascending?

**Comment by jackpoz** [comment]
@illfated the header was added when copying a commit from master and I didn't really check if the header was there already, I just checked if it built.

The order of headers follows a technical logic (linked header of the .cpp, TC headers, 3rd party headers, std headers), it's just not obvious at first sight.

**Comment by Aokromes** [comment]
> @illfated the header was added when copying a commit from master and I didn't really check if the header was there already, I just checked if it built.
> 
> The order of headers follows a technical logic (linked header of the .cpp, TC headers, 3rd party headers, std headers), it's just not obvious at first sight.

maybe tc headers, 3rd party headers and std headers must be separated by one empty row.

**Comment by illfated** [comment]
Thanks for the insight. I forgot that there is more than one sort order for the include lists.

**Pull request merged**
