### PR TITLE
Authserver cleanup phase 5 - removal of sha_pass_hash

### PR DESCRIPTION
**Pull request by Treeston**
_(This is part 5 of 5 in the deprecation process of `sha_pass_hash`, as outlined in #25157.)_
_(This pull request will be merged **September 6th, 2020**, thus completing the deprecation process of `sha_pass_hash`.)_

This pull request removes the config toggles introduced by #25138.

Additionally, it removes the legacy columns `sha_pass_hash`, `s`, and `v`, from the `account` table. It also removes all associated functionality from the core.

### CODE REVIEW

**Comment by ccrs** [comment]
bravo

**Comment by msoky** [comment]
👍

**Comment by LordWaycrest** [comment]
Can I ask, what is the session_key_bnet column in the accounts table for? :)

**Comment by Treeston** [comment]
You can run both legacy 3.3.5 and bnet-enabled branches from the same auth DB. `session_key_bnet` is what the latter branches use.

**Comment by illfated** [comment]
@LordWaycrest : See commit https://github.com/TrinityCore/TrinityCore/commit/22bad09c01c6f17eeb420076904fd5e88ad4de36 for the cherry-picking from master to 3.3.5 and its general description.

**Comment by LordWaycrest** [comment]
Thank you both.

> You can run both legacy 3.3.5 and bnet-enabled branches from the same auth DB. session_key_bnet is what the latter branches use.

Also can you explain more on that? Does sound interesting "bnet-enabled branches"

**Comment by Treeston** [comment]
Cataclysm/master branches and whatever other 4.x+ branches are floating around out there.

**Comment by LordWaycrest** [comment]
> Cataclysm/master branches and whatever other 4.x+ branches are floating around out there.

Brilliant, also keep getting this popup at  selection screen: https://imgur.com/a/WcAtLXc Never seen it before, I'll create an issue if needed.

**Comment by Treeston** [comment]
#25361 - if you can reliably reproduce it, turn on debug logs for Warden and post the checks + packet size sent before it happens.

**Comment by LordWaycrest** [comment]
> That sounds like #25361 - if you can reliably reproduce it, turn on debug logs for Warden and post the checks + packet size sent before it happens over there.

Ah I remember now, had with issue with cmangos which got fixed, if I can find the commit I'll post it here.

**Pull request merged**
