### PR TITLE
Core/Scripts: Implemented OnlyOnceAreaTriggerScript

### PR DESCRIPTION
**Pull request by Treeston**
Tagging #20287, #20306

To transition:
* Inherit from `OnlyOnceAreaTriggerScript` instead of `AreaTriggerScript`
* Rename `OnTrigger` to `_OnTrigger`

### CODE REVIEW

**Comment by Krudor** [comment]
I'm all for improving the scripting experience, but personally don't think manually storing/getting state from instancescript is that much of a hassle for the cases where you need to trigger once.

**Comment by Treeston** [comment]
Neither is adding a new implementing subclass (and it saves us from duplicating the same code 500 times).

**Comment by Krudor** [comment]
Yep, fully aware.
I like the idea, just don't like the implementation.

**Comment by Ovahlord** [comment]
This implementation is wrong anyways if it is not stored in the instance data. Cuz this would lead to an reset of all such areatriggers when the server crashes / gets restarted.
You should instead extend the exsiting area trigger class to add a "trigger once" variable and add a optional instance data overload to handle things automated.

**Comment by Treeston** [comment]
Greeting areatriggers are reset on instance reload on retail, too. This is intentional.

**Comment by Ovahlord** [comment]
What about areatriggers that are handling events that should not repeat, once they are done?

**Comment by ccrs** [comment]
I agree with Treeston, the less code duplication the better.
Though the option to save the state to DB should be available.

**Comment by Treeston** [comment]
@Ovahlord those already use boss states (see ICC events)

**Comment by ccrs** [comment]
And using boss states is completely wrong, Svala event for example. I'll commit a refactor/rewrite/we soon (TM). Dont use boss states to store event states.

**Comment by Keader** [comment]
Ok, PR is ready for feedbacks :)

**Comment by Keader** [comment]
@Treeston can be merged? :)

**Pull request merged**
