### PR TITLE
DB/Creatures: detach non-wdb data from creature_template part 1: difficulty entries

### PR DESCRIPTION
**Pull request by Ovahlord**
**Changes proposed:**
this marks the beginning of a long overdue task: relocating data which isn't sent in query packets for creatures into separate tables. This means that when this journey is over, we can call creature_template sacred so no user may touch the table ever again just like we do with gameobject_template.

**Tests performed:**
- none yet.

### CODE REVIEW

**Comment by Shauren** [comment]
I actually disagree with tiny splits like what you propose here for 1:1 relations, it makes dealing with tables very annoying

**Comment by Ovahlord** [comment]
Well, i'm currently thinking about migrating difficulty into creature_template_addon to get closer to what gameobject_template does  and only create a new table for stats instead

**Comment by CraftedRO** [comment]
why don't you port for example other stuffs like creature formations ?

**Comment by Nyr97** [comment]
isn't it best to move it into creature_template_difficulty instead? _addon table should resemble as much as master's, and master's difficulties are handled in _scaling table which is non-existent in wotlk branches

**Comment by funjoker** [comment]
IMO creature_template should only contain data from QUERY_RESPONSE and any other data taken from UFs or else should go to addon

**Pull request closed without merging**
