### PR TITLE
Core/Config: Fixed StartPlayLevels of DK, DH & RAF

### PR DESCRIPTION
**Pull request by RealLushen**
**Changes proposed:**

-  Modify the worldserver.conf so its up to date with 9.0.2

**Target branch(es):** 3.3.5/master

- master

**Issues addressed:**

- Console Errors due to wrong values

**Tests performed:**

- Yes it builds and works.

### CODE REVIEW

**Comment by Shauren** [comment]
Not that simple, allied race (and pandaren) DKs start at 10, other races at 8
For sql you need to make update file that does `ALTER TABLE`

**Comment by osleyder85** [comment]
Beware, the Death Knight Class player does not start at level 10, he starts at level 8 just like the Demon Hunter. This I just checked at Blizzard.

**Comment by Aokromes** [comment]
read what shauren said.

**Comment by illfated** [comment]
I assume that both the worldserver.conf settings and its matching core functions need to be updated to differentiate between (Allied Races + Pandaren) versus the Core Races, so this PR needs to be expanded to include extended core settings (pun intended).

**Pull request merged**
