### PR TITLE
[3.3.5] Core/Scripts: move npc_lunaclaw_spirit to SAI

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

This PR moves the core script `npc_lunaclaw_spirit` to SAI, removing hardcoded text.
The quests 6001 + 6002 are Druid class quests to get bear form, removed in patch 4.0.3a

**Quest name & IDs:**
- [Body and Heart (Alliance)](http://www.wowhead.com/quest=6001/body-and-heart): http://www.wowhead.com/quest=6001/body-and-heart
- [Body and Heart (Horde)](http://www.wowhead.com/quest=6002/body-and-heart): http://www.wowhead.com/quest=6002/body-and-heart

Changes in this PR:
- remove core script, including hardcoded text (with typo)
- add gossip_menu_option for both factions (Alliance & Horde)
- add SAI script to complete quest 6001 or 6002 based on conditions
- add gossip option conditions for team A (469) or team H (67)

**Target branch(es):** 3.3.5 (removed in patch 4.0.3a)

**Issues addressed:** Updates https://github.com/velinath/TrinityCore/issues/2 [**Gossip migration from core scripts to SAI/DB ToDo List**](https://github.com/velinath/TrinityCore/issues/2)

**Tests performed:** (Does it build, tested in-game, etc) Builds OK, script removal + SQL addition only.
Tests in-game in progress. Feedback requested for what to test (that I may have overlooked) to find errors.

**Known issues and TODO list:**
- [x] Test that the PR works to complete the correct quest ID and display correct gossip for Tauren Druid
- [x] Test that the PR works to complete the correct quest ID and display correct gossip for Night Elf Druid
- [x] Get feedback on how to test for possible bugs or what could possibly go wrong in the script

### CODE REVIEW

**Comment by jackpoz** [comment]
> Not yet tested in-game

it would be better to first test it ingame, then open the PR

**Comment by tkrokli** [comment]
I know, I just wanted feedback regarding the content or format of this PR so I would know if it will be accepted or not, even if the testing goes well. I also would like to know if there is anything I should consider changing in this PR if any of the methods are deprecated or don't meet the TC standards.

**Comment by tkrokli** [comment]
- [X] Changed the PR main comment ToDo list with test results (testing has begun and will be completed according to feedback for what more to test than just confirming that it works in its current form).

**Comment by tkrokli** [comment]
OK, so I tested both races again and found out that I had forgotten to add the quest incomplete condition for the gossip option. Added the missing condition and tested again, works exactly as intended.

**Review by SnapperRy — APPROVED** [review]
Looks good!

**Comment by tkrokli** [comment]
Closed in commit https://github.com/TrinityCore/TrinityCore/commit/3ad76dea7bdd889f016cce506833af7ed73d439d .

**Pull request closed without merging**
