### PR TITLE
Core/Pools: Attempt to workaround pools being broken since 2015

### LINKED ISSUE #21331: Core/Pools: Objects in the pool stop spawning
**Description:** Creatures (probably GameObjects too) that belong to a pool, will stop to respawn after some time. I can confirm this happens with Webbed Crusaders(30268 30273) and Serfex the Reaver(28083), for example.
I only monitored it for a few hours, but I think they won't respawn again until a server restart.

**Current behaviour:** After some number os respawns, the creature no longer spawn.

**Expected behaviour:** Creatures should keep respawning within the right time.

**Steps to reproduce the problem:**
To force it happen:
1. Execute: DELETE FROM characters.respawn;
                  UPDATE world.creature SET spawntimesecs = 3 where id IN (30273,30268);
2. Start server
3. .gm on
4. .go xyz 6394 229 395 571
5. .cast 44659
6. Repeat step 3 a few times, usally after the second/third time the Webbed Crusaders won't spawn anymore.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** e45d54d80e3f

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Attempt to workaround pools being broken since 2015

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #21331

**Tests performed:** (Does it build, tested in-game, etc.)
- Steps described in #21331

**Known issues and TODO list:** (add/remove lines as needed)

- This is not the most perfect fix of the universe that some want but 5 years of broken code is long enough to try fixing it.
- It attempts to fix only Creatures, it doesn't attempt to fix GameObjects

### CODE REVIEW

**Comment by Killyana** [comment]
I made some tests, and I managed to get 2 spawns from the same pool spawned at the same time:
image

What I did is just killing all creature in this room and restarted the server, upon login  SpawnID: 21318 was already spawned, after a while SpawnID: 86077 spawned with the 3 others.

``` sql
SELECT * FROM `creature` WHERE `guid` IN (21318,86077);
SELECT * FROM `pool_members` WHERE `SpawnID` IN (21318,86077);
SELECT * FROM `pool_template` WHERE `entry` IN (32493);

**Comment by Faq** [comment]
Wasnt better with #23603?

**Comment by jackpoz** [comment]
@Faq sure, just fix the merge conflicts and fix the remaining todo point then. Also do that with approval from the original author.

**Comment by Killyana** [comment]
So I figure out that if the unit that was chosen to respawn is different from the one that get killed, it will respawn instantly in sever restart, and the other unit will also respawn on top of it

**Comment by sirikfoll** [comment]
I can confirm this works as a fix for #21331. Even if only for creatures, still a huge improvement

**Comment by joshwhedon** [comment]
I am not convinced we need to do it via respawn. We don't want to respawn, we want to call Spawn1Object and not despawn it at the end of the process. Also doing so would fix gameobjects too.

**Comment by jackpoz** [comment]
@joshwhedon have you tried with Spawn1Object ?

**Comment by jackpoz** [comment]
I added a different attempt at https://github.com/TrinityCore/TrinityCore/pull/24949

**Comment by jackpoz** [comment]
Replaced by https://github.com/TrinityCore/TrinityCore/pull/24949

**Pull request closed without merging**
