### PR TITLE
Scripts/TrialOfTheChampion: add a note about Gossip - 3.3.5-trial_of_the_champion branch

### PR DESCRIPTION
**Pull request by ConradBunton**
-  Add note to take Gossip menu from DB
-  Don't forget that "dead" branch

### CODE REVIEW

**Comment by tkrokli** [comment]
You know, adding comments to those lines is not a solution TrinityCore wants to add.
If this had been a proper conversion to DB gossip, it would have been most wanted.

Unless you are willing to take the job of converting those hardcoded texts to DB gossip, I will vote for this PR to be closed or just put on hold for DB gossip conversion.

**Comment by Aokromes** [comment]
Like tkrokli said, proper conversion to db is needed here.

**Comment by tkrokli** [comment]
Also please note the already existing comments in

https://github.com/TrinityCore/TrinityCore/blob/6d8d0106478434e87fd7bdc8bfc4bb38e1303b0f/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp#L1248-L1256

Focus on moving the gossip to DB instead of adding more comments to the source -- it has got enough comments and bad code as it is.

**Comment by ConradBunton** [comment]
I made that commit to reactualise the branch. Everyone seem to give it up.

**Comment by tkrokli** [comment]
The main 3.3.5 branch has had updates for Crusaders Coliseum, except the hardcoded gossip. If you are able to convert the gossip to use DB text instead of hardcoded text in the script, it can be accepted into the `3.3.5-trial_of_the_champion` branch as well as modified to fit in the 3.3.5 branch (Keader & others updated TOC5 in the main 3.3.5 branch).

**Comment by ConradBunton** [comment]
Did you test that branch ? Only 3 fixes needed, no more.

**Comment by tkrokli** [comment]
I am talking about moving the text to DB, which means handling the tables `gossip_menu` , `gossip_menu_option` , `creature_text` and `creature_template` to make changes related to the gossip so the `#define` text lines can be removed and the C++ script gossip code can be altered so it handles DB gossip instead of hardcoded text. That means including a well written SQL file as well as changes to the C++ script.

**Comment by ConradBunton** [comment]
Gossip is just a minor fix. I made that commit to recall that branch in memories.
That scripts worked really good for TOC5.

**Comment by tkrokli** [comment]
Gossip is still something we want to get fixed in scripts, simply because we don't want hardcoded gossip or texts when it could be in DB instead. If you have got a solution for it, please share. That is the kind of PR we would like to see more of (see also https://github.com/velinath/TrinityCore/issues/7 and https://github.com/velinath/TrinityCore/issues/2 to get an idea of how long we have been working on it already. Any help with that kind of issue is appreciated.

**Pull request closed without merging**
