### PR TITLE
Update System.cpp

### PR DESCRIPTION
**Pull request by geshanet**
Ispralenie error when compiling map_extractor System.cpp

### CODE REVIEW

**Comment by Aokromes** [comment]
All TC branches are properly compiling, what compiler are you ussing to get error?

**Comment by geshanet** [comment]
I use what is written in .travis.yml
Ubuntu 14.04 LTS System Server 64


Суббота, 31 января 2015, 23:59 -08:00 от Aokromes <notifications@github.com>:

**Comment by jackpoz** [comment]
it's unclear what this Pull Request is supposed to fix, if it's supposed to fix a build error for the mapextractor project in the 3.3.5 branch please include the error in the pull request description.

I'm currently not experiencing any issue building mapextractor project on 3.3.5 on Windows x64 PCH

**Comment by geshanet** [comment]
here it will explain why this error when you compile it on Ubuntu 14.04.1 LTS X64:

/root/TrinityCore/src/tools/map_extractor/System.cpp: In function ‘void CreateDir(const string&)’:
/root/TrinityCore/src/tools/map_extractor/System.cpp:112:25: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             chdir("../");
                         ^

**Comment by geshanet** [comment]
windows not use

**Comment by DDuarte** [comment]
Am I allowed to shout? WARNINGS are not ERRORS.

**Comment by click** [comment]
@ geshanet : the "error" you refer to is a simple _warning_, nothing else. The code itself is even skipping that section, based on that it's not used.
If you have issues with compiling, include the part that says "error", not "warning".

**Comment by jackpoz** [comment]
This PR actually removes a required code portion, removing a functionality to fix a warning. It's much more important to keep existing features than fixing build warnings.

**Comment by geshanet** [comment]
On Windows, I did not compile. Say neither of which I can not. And removing the card on ubuntu everything works well and that without changing the code. But I was a little affected by this notice.

Отправлено с Samsung Mobile

-------- Исходное сообщение --------
От: jackpoz <notifications@github.com> 
Дата:02.02.2015  20:21  (GMT+07:00) 
Кому: TrinityCore/TrinityCore <TrinityCore@noreply.github.com> 
Копия: geshanet <ufo-x@mail.ru> 
Тема: Re: [TrinityCore] Update System.cpp (#14004) 

This PR actually removes a required code portion, removing a functionality to fix a warning. It's much more important to keep existing features than fixing build warnings.

**Pull request closed without merging**
