### PR TITLE
Core/Pet: Modified following speed and distance between owner and pet

### LINKED ISSUE #8924: [Core / Pet] Movement impairing effects on the Hunter also slow the pet
**Rev:** all (tested on fb3245d12533cde3fb0765b114a6132dde836119)

**Bug:**

When the Hunter is afflicted with a movement impairing effect, it causes the pet to walk until the effect wears off.

**Details:**

To test, try the following:

> 1. Cancel any buffs and put your pet on **stay**
> 2. Move several yards away and enter combat (without moving)
> 3. Click **follow** and notice the pet runs to where you are

Now repeat the above with the exception: **activate Aspect of the Cheetah**

> Notice your pet walks instead of runs while the Hunter is afflicted with the daze effect

**Notes:**

So far I have not been able to track this one down. It is similar to how when the Hunter switches from run to walk, the pet also switches to walk. I also don't think it is spell related because Hamstring and others also do this but who knows...

This is also **not** related to the speed fix I submitted, if you try this on a revision before that merge it will still happen.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/104249-core-pet-movement-impairing-effects-on-the-hunter-also-slow-the-pet?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10865: [Core / Pet] [Patch] Pets at rest are too far away
__Rev:__ All

__Bug:__

When pets are idle, they are too far away from their owner

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1412994-core-pet-patch-pets-at-rest-are-too-far-away?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #12817: [Fix][3.3.5] Creature's Pet always use run instead of walk when they follow the owner
db : up-to-date
core : 91053d557ca89c4b0c455366afae258835bd25f8

When a creature (A) summon another creature (B) as itself's pet, the pet (B) is always run to follow its owner (A). But most time, it should use walk. 

For example, the creature 3265 (which movementtype is 1) cast spell 6479 to summon creature 3939 as a pet. In game, you can see the the pet run a few steps, stop, run, stop. Not walk follow the owner.

TargetedMovementGenerator.cpp Line 111 change it to
```c++
	Unit * u = owner->GetCharmerOrOwner();
	if (u && 
		i_target->GetGUID() == u->GetGUID() && 
		u->GetTypeId() == TYPEID_UNIT &&
		i_target->ToCreature()->GetDefaultMovementType() == RANDOM_MOTION_TYPE) {
		init.SetWalk(true);
	} else {
		init.SetWalk(((D*)this)->EnableWalking());
	}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3650151-fix-3-3-5-creature-s-pet-always-use-run-instead-of-walk-when-they-follow-the-owner?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
Closes #8924
Closes #10865
Closes #12817

### CODE REVIEW

**Comment by Killyana** [comment]
It will fix this issue: https://github.com/TrinityCore/TrinityCore/issues/12817 ?

**Comment by peterbilt** [comment]
Now it closes #12817

**Comment by tkrokli** [comment]
Notice that your commits are not linked to a user account known by github.
Make sure your git client uses the same e-mail address as your github login.

**Comment by peterbilt** [comment]
> Notice that your commits are not linked to a user account known by github.
Make sure your git client uses the same e-mail address as your github login.

Fixed, thanks.

**Comment by Killyana** [comment]
Why this was closed?

**Comment by Aokromes** [comment]
Merge fuckup xD

**Comment by Killyana** [comment]
@peterbilt please reopen another PR, this ugly pets movements must be fixed.

**Comment by Kittnz** [comment]
Gonna try the changes this evening

**Comment by peterbilt** [comment]
Sorry about this mess. I'll open a new pull request.

**Comment by Kittnz** [comment]
Does not seem to change anything

**Pull request closed without merging**
