### PR TITLE
Fixed a typo in Map::GetHeight, causing invalid vmap height to be con…

### PR DESCRIPTION
**Pull request by kelno**
…sidered as valid

### CODE REVIEW

**Comment by tkrokli** [comment]
Pro tip: shorten your headline by moving the second half of it to the description line :
***
**Fixed a typo in Map::GetHeight**
Typo in Map::GetHeight caused invalid vmap height to be considered as valid.
`INVALID_HEIGHT => VMAP_INVALID_HEIGHT_VALUE`
***
use a back tick ( ` ) before and after the text you want to appear in grey (non-proportional font).

**Comment by DDuarte** [comment]
They are both equal to -10000.0f so this doesn't actually fix anything. However I still think this is a valid change to make the code clearer.

**Comment by tkrokli** [comment]
:smirk_cat: Before this commit gets pushed, consider shortening the title to **Fixed a typo in Map::GetHeight**.

**Comment by DDuarte** [comment]
@kelno: bump

**Comment by DDuarte** [comment]
@kelno: what issue does this fix? how to reproduce it?

**Comment by kelno** [comment]
Actually I did not encountered any issue, I just encoutered this while refactoring my code. Actually my commit message is wrong and this doesn't fix any runtime problem, since a map height set to VMAP_INVALID_HEIGHT_VALUE (-200000) is also excluded by the '> INVALID_HEIGHT' (-100000) check, I somehow inverted the values in my head.

**Comment by DDuarte** [comment]
After talking with the other guys we decided it's better not to change something that works. If there is indeed a real issue we'll look into this. Thanks.

**Pull request closed without merging**
