### PR TITLE
[3.3.5 only] Core/Conditions: Improved mergeability between branches

### PR DESCRIPTION
**Pull request by ariel-**
**Changes proposed**:
- Remove reuse of condition/source types used in other TC branches
- Added logging if this conditions/source types are accidentally used
- Extended logging for invalid condition type (if not extended condition type is not shown, useless log)

**Target branch(es)**: 335

**Issues addressed**: Improves merge capabilities and prevents further issues

**Tests performed**: (Does it build, tested in-game, etc) It builds correctly.

**Known issues and TODO list**:

### CODE REVIEW

**Comment by Shauren** [comment]
please, make no mention of 4.3.4 branch in the log message - we don't have it in this repository.

**Comment by ariel-** [comment]
Done, removed from other places as well

**Comment by Shauren** [comment]
Now if you could rename the SQL for todays date so I can click merge now

**Comment by tkrokli** [comment]
Yup. `2016_03_02_00_world.sql` is still available so far today. :+1:

**Pull request merged**
