### PR TITLE
Tools/MapExtractor: Fixed problem with DBFilesClient extraction for some locales.

### LINKED ISSUE #13359: [6.x.x]extractors problem (only mine?)
These are some of the messages of the console 

``` Unable to open file DBFilesClient\DeclinedWordCases.dbc in the archive for local
e itIT.
Unable to open file DBFilesClient\DeclinedWord.dbc in the archive for locale itI
T.
Unable to open file DBFilesClient\WMOAreaTable.dbc in the archive for locale itI
T.
Unable to open file DBFilesClient\Map.dbc in the archive for locale itIT.
Unable to open file DBFilesClient\AreaTable.dbc in the archive for locale itIT.
Extracted 385 files

Locale ptPT not installed.
Using locale: itIT
Extracting maps...
Read Map.dbc file... Fatal error: Cannot find Map.dbc in archive! ```

then it will automatically close..
This is because 
``` CascOpenFile(CascStorage, "DBFilesClient\\Map.dbc", CASC_LOCALE_ALL, 0, &dbcFile) ``` (line 265 - System.cpp) 

returns, obviously, FALSE because the file doesn't exist

### PR DESCRIPTION
**Pull request by et65**
Closes #13359

### CODE REVIEW

**Comment by DDuarte** [comment]
@Heihachi confirmed that this fixes dbc extracting problems for enUS

**Comment by zwj-2014** [comment]
zhCN work good.

504 files.

**Comment by danlapps** [comment]
Ill try FRFR tonight and let you know

**Comment by danlapps** [comment]
I can confirm this works for FRFR too, 504 files extracted

**Pull request merged**
