### PR TITLE
Core/PacketIO: updated SMSG_FEATURE_SYSTEM_STATUS

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

- update   SMSG_FEATURE_SYSTEM_STATUS to new packet class
-  define complaint status values

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.)
Build, tested in-game

### CODE REVIEW

**Comment by Faq** [comment]
Cherry picked from?

**Review by geektcp — COMMENTED** [review]
LGTM

**Comment by jackpoz** [comment]
is this a cherry-pick ?

**Comment by ForesterDev** [comment]
Partially, I've fixed refferences

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
