### PR TITLE
Scripts/ICC: update Sindragosa scripts to new model

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  update Sindragosa scripts to new model

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Tests performed:**

Build

### CODE REVIEW

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by jackpoz** [comment]
>D:\wow\TrinityCore\src\server\game\Scripting\ScriptMgr.cpp:793 in SpecializedScriptRegistry<class SpellScriptLoader,1>::AddScript ABORTED:
Script 'spell_sindragosa_ice_tomb' already assigned with the same script name, so the script can't work.

could it be this PR just killed worldserver ?

**Comment by jackpoz** [comment]
> **Tests performed:**
> 
> Build

Please next time start at least worldserver...

**Comment by jackpoz** [comment]
>Script named 'npc_rimefang' does not have a script name assigned in database.
ScriptName 'npc_rimefang_icc' exists in database, but no core script found!

**Comment by jackpoz** [comment]
this in the end was one of the most bugged PRs I ever merged. Next time I will put it back in draft if I don't see a Server.log attached clean of errors and an ingame video of the script still working correctly

**Comment by illfated** [comment]
Looks like there is no GitHub build check to pick up on the same type of error as DBErrors.log on a running server.

**Pull request merged**
