### PR TITLE
DB/Creature: ReActivate Creatures DeathState by using unit_flags3

### PR DESCRIPTION
**Pull request by JustZerooo**
**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [X] master

**Issues addressed:** Closes #  (insert issue tracker number)
- Creatures where was death was showing mana and life. This was incorrect and is now solved.
**Tests performed:** (Does it build, tested in-game, etc.)

Tests works fine and no problems with the death state anymore

**Known issues and TODO list:** (add/remove lines as needed)

Thanks to @Shauren who helped me ;)

### CODE REVIEW

**Comment by Aokromes** [comment]
thx but we don't use pull request for sql only fixes, plz open a ticket instead.

**Comment by TheNeoTV** [comment]
Sorry, i only use Pullrequests. Then it will not merged. Pullrequest is how Github works.

**Comment by Killyana** [comment]
This death state is generally handled by an aura, this aura apply the correct flags.

**Comment by TheNeoTV** [comment]
You are right but Blizzard has changed something. Shauren can tell you more. This is a NEEDED Update Statement to work correctly. Ask @Shauren

**Comment by Shauren** [comment]
@Killyana yes, but some creatures are done wrong and have the unit_flags2 & 1 in db, also aura script needs fix to apply this new flag

**Pull request closed without merging**
