### PR TITLE
Core/GameObject: don't allow non-consumable goobers to despawn on use

### LINKED ISSUE #15730: Core/Gameobject: Gameobjects despawn once clicked
Hello,

server: 8ff619ddc40fee1739125e91d20b519078c3f2fb
db all updates

The apple vat are to disappear when i loot the apple in the Helloween days for ca 3 min.

### PR DESCRIPTION
**Pull request by Wyrserth**
**Changes proposed:**

This PR fixes an issue where goober gameobjects ([Romantic Picnic Basket](https://www.wowhead.com/item=34480), the Naxxramas portals) would despawn after a player right-clicked on them.

They are goobers flagged as non-consumable (data3 == 0) so they should not despawn in any case unless they were summoned by a spell and they expired.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** closes #15730, updates #23451.

**Tests performed:** it works.

### CODE REVIEW

**Comment by Killyana** [comment]
There's 2 cases that must be checked:
1- https://woehead.way-of-elendil.fr/?item=34480/romantic-picnic-basket -- works fine
2- .go game 6166 Naxx portal -- works fine
3- .quest add 12069  & .go c id 26608  kill the npc -- Anub'et'kan's Carapace must not despawn upon looted, this was working correctly before this PR

**Comment by Wyrserth** [comment]
Forgot to keep the old behavior for summoned chests. Fixed both issues, thanks!

**Comment by Killyana** [comment]
Everything looks fine, it could be pushed one the restock is done.

**Comment by Wyrserth** [comment]
I made this PR to fix the major issue (goobers despawning) until we have enough data to understand how the restock timer works for gameobjects involved in quests.

BfA retail cannot be used as a reliable source because all the quest-related gameobjects are personal spawns and other players cannot affect it. From sniffs the only thing I could find out is that, after it is looted, the gameobject loses the interactable+sparkle dynamicflags to gain them in the next update tick. I don't yet know if this is just how it worked serverside back then or if it triggers a specific behavior clientside.

**Pull request merged**
