### PR TITLE
Scripts/Onyxia: Add AnimationTier::Ground

### PR DESCRIPTION
**Pull request by Faq**
Onyxia does not walk on the ground in third phase, she stays flying on the ground

**Changes proposed:**

-  Add AnimationTier::Ground

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**
https://github.com/TrinityCore/TrinityCore/pull/24875#issuecomment-692626339

**Tests performed:**

Builds, now after 2nd phase when she lands, not flying over ground but walks

### CODE REVIEW

**Comment by Ovahlord** [comment]
Actually you only need to correct the movement template data ( and extra flags of course )

**Comment by Faq** [comment]
-- Disable movement flag updates for Onyxia and let script handle them
```
UPDATE `creature_template` SET `flags_extra` = `flags_extra`| 0x200 WHERE `entry` IN (10184, 36538);
```

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/pull/25460#issuecomment-693520773 seems enough, tested ingame.
@offl I think can be pushed that sql ;)

**Comment by Faq** [comment]
yeah only sql is needed.

**Comment by Ovahlord** [comment]
`UPDATE `creature_template_movement` SET `Flight`= 1 WHERE `CreatureId` IN (10184, 36538);`

This not correct. Onyxia starts on the ground so give her Flight = 0 and Ground = 1.

**Comment by Faq** [comment]
It has in stock Ground = 1 and Flight= 1, so need only change Flight.

```
-- Disable movement flag updates for Onyxia and let script handle them
UPDATE `creature_template` SET `flags_extra` = `flags_extra`| 0x200 WHERE `entry` IN (10184, 36538);
UPDATE `creature_template_movement` SET `Flight`= 0 WHERE `CreatureId` IN (10184, 36538);
```

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/603844f67bcdd594ec4613ed10b674856b194159

**Pull request closed without merging**
