### PR TITLE
[3.3.5] Improve ticket system

### LINKED ISSUE #15655: [3.3.5] gm_ticket.closedBy has wrong value when closed by console
Branch: 3.3.5
Tested on revisions: ba009ea2e2d13c0aa8a76df5bfead6f757ccddc3, 774ea0b4bd1e

When you close a ticket via **console** using ```ticket close``` command, the ```gm_ticket.closedBy``` field value of that ticket is **16777215**.

According to the wiki, it should be **-1** instead.

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
This PR is about improving the ticket system.
- safely close ticket before character deletion (no matter of DeletedCharacterTicketTrace config, we need it in all cases)
- closes #15655
- allow to keep trace of delete characters tickets (configurable):

Currently all characters tickets are deleted on character deletion, this PR introduce a configurable feature to keep them in database.

```
#    DeletedCharacterTicketTrace
#        Description: Keep trace of tickets opened by deleted characters
#                     gm_ticket.playerGuid will be 0, old GUID and character name
#                     will be included in gm_ticket.comment
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

DeletedCharacterTicketTrace = 0

```
- TODO after merge:  update wiki

Thanks @Carbenium for help and suggestions

### CODE REVIEW

**Comment by tkrokli** [comment]
Maybe I am not interpreting the words correctly, but isn't the logic behind this .conf setting the opposite of what is ordinary? When I read the word `DeletedCharacterTicketTrace`, I read it as `Trace the ticket(s) of deleted characters` which makes me think 0=no, 1=yes, but that is the opposite of what is in the .conf setting. Maybe I am too used to settings being 0=disabled, 1=enabled. Also, when I read the description `Keep trace of tickets opened by deleted characters`, it also seems to tell me the opposite of what I would logically have chosen if I consider 0=no/disabled, 1=yes/enabled. If the name of the .conf setting had been `DeleteCharacterTicketTrace` (Deleted => Delete), the logic would be more apparent, at least when it comes to using ordinary everyday logic to know which setting is "no/disabled" and "yes/enabled".

**Comment by ShinDarth** [comment]
@tkrokli yes there is a typo, thanks for pointing it out

**Comment by tkrokli** [comment]
OK, good. I am glad my logic sense is still working. The .conf (and PR) description needs correction, then.

**Comment by Nelidon** [comment]
Ticket system has been removed from the client since 6.2 patch.

**Comment by tkrokli** [comment]
@Nelidon & @ShinDarth : maybe this PR needs to be tagged [3.3.5] specifically for that reason.

@ShinDarth : your `ShinDarth:tcket` branch is 123 commits behind `TrinityCore:3.3.5`.
Rebase your branch to keep it in sync (notice the "conflicts must be resolved" message).

**Comment by Carbenium** [comment]
The merge conflict is known and will be resolved when merging.

**Comment by Kittnz** [comment]
This branch has conflicts that must be resolved..

**Pull request closed without merging**
