### PR TITLE
Core/Opcodes: Fixed Spirit Healer opcodes

### PR DESCRIPTION
**Pull request by Goatform**
- CMSG_AREA_SPIRIT_HEALER_QUERY
- CMSG_AREA_SPIRIT_HEALER_QUEUE
- SMSG_AREA_SPIRIT_HEALER_TIME

TODO: convert it to new opcode style "void WorldSession::HandleAreaSpiritHealerQueueOpcode(WorldPackets::Misc::SpiritHealerQueue& packet)"

### CODE REVIEW

**Comment by Aokromes** [comment]
Failed  — The Travis CI build failed

**Comment by xerkoss** [comment]
WorldPackets::Misc?  I think those packages should be Battleground instead of Misc.

**Comment by jackpoz** [comment]
most of this PR seems to be variable renaming and code rearranging without much difference on the actual code behavior

**Comment by DDuarte** [comment]
Please re-open the pull requests once you have it converted to the new format. Thanks

**Pull request closed without merging**
