### PR TITLE
Scripts/Commands: add some missing checks for .guild create command

### LINKED ISSUE #23200: guild create command doesn't check max length
**Description:**

guild create command doesn't check max length

**Current behaviour:**

guild create command doesn't check max length, it outputs sql error on console
**Expected behaviour:**

command must check max guild name length

**Steps to reproduce the problem:**

1. .guild create aokromes "GMs trinitycore test server"

**Branch(es):**

all

**TC rev. hash/commit:** 

ALL N/R adbbd0eda

**Operating system:** N/R

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  add some missing checks

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #23200

**Tests performed:** (Does it build, tested in-game, etc.) Tested

**Known issues and TODO list:** (add/remove lines as needed)

- maybe add proper string for errors

### CODE REVIEW

**Comment by jackpoz** [comment]
does this fix this issue too ?
>SQL(p): INSERT INTO guild (guildid, name, leaderguid, info, motd, createdate, EmblemStyle, EmblemColor, BorderStyle, BorderColor, BackgroundColor, BankMoney) VALUES(1, 'GMs TrinityCore Test server', 2, '', 'No message set.', 1556004215, 0, 0, 0, 0, 0, 0)
 [ERROR]: [1406] Data too long for column 'name' at row 1

**Comment by jackpoz** [comment]
@ForesterDev is this ready to be merged ?

**Comment by ForesterDev** [comment]
I've nothing to add

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
