### PR TITLE
Update Object.h

### PR DESCRIPTION
**Pull request by lively158**
**Changes proposed**:
## 
## 
- 

**Target branch(es)**: 335

**Issues addressed**: N/A

**Tests performed**: (Does it build, tested in-game, etc) Tested , works like retail

Changed combat reach to be more blizzlike, instead of hitting pvp players from an insane distance.

### CODE REVIEW

**Comment by DDuarte** [comment]
Any source for those values?

**Comment by lively158** [comment]
Trial and error whilest comparing to retail servers I'm afriad, no access to sniff devices :(

**Comment by DDuarte** [comment]
I'm afraid we need something better than trial & error in this case. Those values have been there since ever and are quite a fundamental part of the combat system. I think sniffs wouldn't help that much anyway.

**Comment by jackpoz** [comment]
what happened to the PR description ?

**Comment by tkrokli** [comment]
Yes, the title should be more specific, something like
**[3.3.5] Core/Object: normalize Combat Reach distance**

... and then write details about the change in the expected paragraphs in the first PR post, like "Update the combat reach distance values in `Object.h` to realistic distances." or even more specific explanation in the top lines.

**Comment by Shauren** [comment]
Sorry but this is wrong. This is the sniffed value for player's combat reach
```
[0] UNIT_FIELD_COMBATREACH: 1069547520/1.5
```
As you see, it matches current value of DEFAULT_COMBAT_REACH. Next is range calculation itself - autoattacks have the same range as melee abilities that I very recently researched the formula for range where the current value of NOMINAL_MELEE_RANGE constant (5) is also correct and blizzlike.

Summing up, current range IS blizzlike.

**Pull request closed without merging**
