### PR TITLE
Core/Scripts: npc_grandmother gossip text moved to DB

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

Remove one more hardcoded text line from core scripts.
Also add correct gossip to the npc_grandmother script.

Gossip changes in this script:
- remove hardcoded text from core script
- use existing npc_text IDs in gossip enum
- add missing text rows to gossip_menu_option
- use values from gossip_menu_option in enum

**Target branch(es):** Both 3.3.5 and 6.x (src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp)

**Issues addressed:** Updates [**Gossip migration from core scripts to SAI/DB ToDo List**](https://github.com/velinath/TrinityCore/issues/2) https://github.com/velinath/TrinityCore/issues/2

**Tests performed**: (Does it build, tested in-game, etc)
Builds without issues in VS2013 Update 5 and here in travis-ci.

**Known issues and TODO list:**
No known issues, the script behaviour is kept unhanged.

### CODE REVIEW

**Comment by joschiwald** [comment]
remove stuff that is handled by db content

**Comment by tkrokli** [comment]
I tried to, but I find it difficult to convert `OnGossipSelect` to `sGossipSelect` because of the extra command to spawn `Creature* pBigBadWolf` and `creature->DespawnOrUnsummon();`. I made a couple of attemts to write sGossipSelect variants, but they fail:
First attempt: https://gist.githubusercontent.com/tkrokli/4e13f9791732a7bf5c8fbe3dff547df8/raw/7a561b8d06ecfe1b2e086ea8d2ed79d65c3ef31f/npc_grandmother.cpp
Errors: http://pastebin.com/raw/qY1AqHag

Second attempt: https://gist.githubusercontent.com/tkrokli/cbc44b4c0c311c77429c8abb5e837f67/raw/5d27298c0a66000e50715375f230bcc8740f4b97/npc_grandmother_gossip.cpp
Errors: http://pastebin.com/raw/g1CDEymT (Malcrom tried to help me, but I got no further.)

**Comment by joschiwald** [comment]
missing semicolon

```c++
struct npc_grandmotherAI : public ScriptedAI
{
...
};
```

**Comment by tkrokli** [comment]
Oh right. I will make another attempt, then. Should I use the one from my first or second attempt?

**Comment by joschiwald** [comment]
second looks better than the first one

**Comment by tkrokli** [comment]
I guess that is because `CreatureAI* GetAI()` is inside the struct instead of outside. OK, new attempt.

**Comment by joschiwald** [comment]
right

**Comment by tkrokli** [comment]
Retards if you wont merge it i will just close it so ye ur loss

**Comment by tkrokli** [comment]
Sorry about the noise. Should be resolved now.

**Pull request merged**
