### PR TITLE
Spell_Monk

### PR DESCRIPTION
**Pull request by ByJhonesDev**
Update Spell for Monk

### CODE REVIEW

**Comment by DDuarte** [comment]
Thanks for the PR.

Some thoughts before this is properly reviewed:
- Convert all tabs to 4 spaces
- Add the missing SQL assigning spells to scripts
- Are you the author of these 57 spell scripts?
- Why is some code commented out?

**Comment by soulfrost** [comment]
@DDuarte  main part of scripts ported from leaked pandashan core ( named as JadeCore and MistCore )

**Comment by AriDEV** [comment]
@soulfrost wasnt u the one who leaked core ?

**Comment by Noffearr** [comment]
This script monk, I got a source on the internet and updated it for the core has some cautions over to normally compile the source!

**Comment by DDuarte** [comment]
Okay, so you didn't write this... can you still do requested changes to the code?
Quick glance over the scripts and I found some hacks (i.e `spell_monk_elevation`, `spell_monk_renewing_mist`, `spell_monk_transcendence`) that definitely need a rewrite.

I don't know how you guys do in "other cores" but here we can't simply accept 3k lines of bad code from dubious sources.

**Comment by soulfrost** [comment]
main part of this scripts uselles for 6.0.3 ( i had update my own 548 core to 603 and see that 60% of scripts uselles shit )

**Comment by Noffearr** [comment]
I'll try to take all the mistakes, because for me so had only 03 warnings - will do everything possible to update these scripts today!

**Comment by DrEhsan** [comment]
https://github.com/soulfrost because you are an idiot u dont even know when u have to inverse a readbit when u dont have.... this scripts needs some little changes to make them to work.

**Comment by soulfrost** [comment]
yes, sure :)

**Comment by ottconnect** [comment]
i have an updated spell_monk.cpp from mop if that helps I can pull request a new one or add it here for someone to test it

**Comment by ottconnect** [comment]
Noffearr  message me when you get back

**Comment by ottconnect** [comment]
@DDuarte the code I posted was from 5.4.8 18414, but i'll take your advice and help @Noffearr  with the code hes already posted.

**Comment by DDuarte** [comment]
I know it's tiresome and a lot of work but since these scripts have multiple problems (were they even tested on 6.x?) it might be worth to open one PR per spell / group of spells.

**Comment by ottconnect** [comment]
yes I've tested them on 6xx already
and I don't have crash or issues, but i'll test it more

**Comment by ProjectcoreDevs** [comment]
add too in scriptloader.cpp for work + sql file + copyright on top...

**Comment by HerokDeV** [comment]
transcendence

someone can make this spell work is a very essential monk spell

https://www.wowhead.com/spell=101643/transcendence

**Pull request closed without merging**
