### PR TITLE
Core/Items: PvP item levels basic implementation

### PR DESCRIPTION
**Pull request by roc13x**
**Changes proposed:**
- Implement PvP item levels for PvP instances
- Fix heirloom min/max level

**Target branch(es):** 3.3.5/master
- [x] master

**Tests performed:** (Does it build, tested in-game, etc.)
- Compiled
- Tested in-game

### CODE REVIEW

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Item/Item.cpp

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/DataStores/DB2Stores.cpp
src/server/game/DataStores/DB2Stores.h

**Comment by soulfrost** [comment]
can be merged i think - all data right

**Comment by tkrokli** [comment]
@soulfrost : This branch has conflicts that must be resolved

**Conflicting files**
src/server/game/DataStores/DB2Stores.cpp
src/server/game/DataStores/DB2Stores.h
src/server/game/Entities/Unit/Unit.cpp

**Comment by tkrokli** [comment]
I took a chance doing this merge. I don't know if the change works 100% as intended.

**Comment by tkrokli** [comment]
Looks like the merge was successful. 2 additions from master and 1 typo fix (commit https://github.com/TrinityCore/TrinityCore/pull/20160/commits/8fa4ac620be136f1e3c9ca5e5c66d17ebf2b3218).

**Pull request merged**
