### PR TITLE
Darkkang master

### PR DESCRIPTION
**Pull request by pablobit94**
**Changes proposed:**

-  Gob move and turn fixed without reload server

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

// Sorry if I did some wrong for upload my commit and git and my fork, I'm new in this. But the file is working for me

### CODE REVIEW

**Comment by illfated** [comment]
Regarding the PR title: could you post link(s) to page(s) describing where you find "Darkkang master" before Mists of Pandaria? (3.3.5 / WotLK)

**Comment by pablorg94** [comment]
> Regarding the PR title: could you post link(s) to page(s) describing where you find "Darkkang master" before Mists of Pandaria? (3.3.5 / WotLK)

Hmm I don't have idea, I try it in master 7.3.5, but I think 3.3.5 have same problem, or no?

**Comment by Shauren** [comment]
Thanks for bringing the original failed cherry pick from master to 3.3.5 to my attention, I have redone it as discussed on IRC using `git cherry-pick -x e68ff4186e685de00362b12bc0b5084a4d6065dd`

**Comment by pablorg94** [comment]
> Thanks for bringing the original failed cherry pick from master to 3.3.5 to my attention, I have redone it as discussed on IRC using `git cherry-pick -x e68ff4186e685de00362b12bc0b5084a4d6065dd`

Ok sorry and thanks. I tried do this command in git but give me error.

**Comment by Shauren** [comment]
You needed to do it on a clean branch and then resolve conflicts using `git mergetool`

**Pull request closed without merging**
