### PR TITLE
(Core\Log) Adjust MonsterWhisper to Whisper 335

### PR DESCRIPTION
**Pull request by acidmanifesto**
MonsterWhisper was changed to Whisper a while ago.

**Changes proposed:**

-  Changes MonsterWhisper Log to show Whisper in the Logging for 335
- Essentially a cherry pick from my pr made on master. https://github.com/TrinityCore/TrinityCore/pull/27288

**Issues addressed:**

Closes # No Know Issue reported.

Tests performed:

(Does it build, tested in-game, etc.)

[x] Builds
[x] Runs

### CODE REVIEW

**Comment by jackpoz** [comment]
We usually use `git cherry-pick -x` for cherry-picks, is that something that you could do ? you could keep this PR by removing the 2 commits and adding the cherrypicked one (let me know if you need some help to do that)

**Comment by acidmanifesto** [comment]
> We usually use `git cherry-pick -x` for cherry-picks, is that something that you could do ? you could keep this PR by removing the 2 commits and adding the cherrypicked one (let me know if you need some help to do that)
In this particular case it would be the same thing wouldnt it?

**Comment by jackpoz** [comment]
Same thing from a code point of view, different from a git history point of view

**Comment by acidmanifesto** [comment]
> Same thing from a code point of view, different from a git history point of view

Im not home now. But when i get back i will see about looking that up.

**Comment by jackpoz** [comment]
Do you need help to cherry pick the commit ? I can do that if you want

**Comment by acidmanifesto** [comment]
you can if you want. just right now i am just pretty swapped with other projects at the moment.

**Pull request closed without merging**
