### PR TITLE
Draenor - Pandaria - Class Monk - Scenario

### PR DESCRIPTION
**Pull request by ByJhonesDev**
- Added only Scripts (Pandaria - Draenor - Scenario - Class Monk)

Make good use!

### CODE REVIEW

**Comment by Aokromes** [comment]
Also, better make multiple PRs to allow faster review for example one for each scenario, one for each draenor and pandaria zones.

**Comment by cemak** [comment]
very many hacks and copypaste

**Comment by MitchesD** [comment]
some of the scripts might be useful, create some separate PRs with some pandaren script for example

**Comment by carlos93** [comment]
Is the same script again and again and again.

**Comment by doriangray2** [comment]
thats what happens if you copy stuff from other peoples :D 
These scripts are mine and i just made them to test some stuff
Most of them are already fixxed at the moment

**Comment by dreinhardt89** [comment]
Maybe you can make some PR's?

**Pull request closed without merging**
