### PR TITLE
Update base character sql file

### PR DESCRIPTION
**Pull request by danlapps**

### CODE REVIEW

**Comment by tkrokli** [comment]
In previous PR you deleted the update file: sql/updates/characters/2014_10_28_00_characters.sql
Could it be that the file is missing in your local source now, or did you just forget it? :smirk_cat:

**Comment by danlapps** [comment]
its present, problem was exactly that I deleted it, needs to stay for those updating.  Will check after work what's wrong

**Comment by Aokromes** [comment]
Failed — The Travis CI build failed
ERROR 1100 (HY000) at line 1474: Table 'creature_respawn' was not locked with LOCK TABLES

**Comment by DDuarte** [comment]
characters_base should be generated by mysqldump, never by hand.

**Comment by danlapps** [comment]
Since I use french stuff for most, tried to keep code french free.  Forgot to replace 2 fields tho.

**Pull request merged**
