### PR TITLE
[Needs Feedback] Core/Spells: Store spellInfo from triggering spells

### LINKED ISSUE #15794: [3.3.5] [Spell][Hunter] Freezing Arrow(60192) is not working
The category of spell Freezing Arrow(60192) is 411, and the category of trigger spell 60202 is 411 too. So after 60192 casted, the trigger spell 60202 is in a cooldown.
After ver. 7dcddd90be6e49281ca04239de5839e757ef3f7a

### PR DESCRIPTION
**Pull request by ccrs**
closes #15794

I'd LOVE some active feedback on this from devs :)

### CODE REVIEW

**Comment by Demonid** [comment]
Damn son...

**Comment by LordUsagi** [comment]
Looks like it just adds support to fix that issue, rather then close it

**Comment by ccrs** [comment]
its a WIP ;)

**Comment by Keader** [comment]
travis dont like this xD https://travis-ci.org/TrinityCore/TrinityCore/builds/103178624#L726

**Comment by ccrs** [comment]
ofc, right now it's a complete mess xd

**Comment by jackpoz** [comment]
is there any useful change in this PR other than adding an new parameter to CastSpell and changing all places where it's called ? I might have missed the line.

A [WIP] PR with no description at all about what has been done so far and what's left to do is quite confusing.

**Comment by jackpoz** [comment]
Is there a case where triggeredByAura is passed not null and the new parameter is different than triggeredByAura->GetSpellInfo() ?

**Comment by streetrat** [comment]
if it only fixes that one spell's bug, why not just remove the triggered spell's category id? could be fixed in one line in LoadSpellInfoCorrections if you ask me

**Comment by Keader** [comment]
I believe this PR will close #15048 too

**Pull request closed without merging**
