### PR TITLE
Pools/GameObjects: Add DelayedRespawn PoolFlags

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

-  Add Flags to pool_template
-  Add and implement the DelayedRespawn Flag for gameobjects
-  Make traps poolable

**Issues addressed:**

Replaces: https://github.com/TrinityCore/TrinityCore/pull/28481
More info: https://github.com/TrinityCore/TrinityCore/discussions/28475

**Tests performed:**

- Builds
- Spawned buffs (traps) in arathi basin, put them in a pool with the new flag and they correctly waited for the respawn timer

**Known issues and TODO list:**

- None?

### CODE REVIEW

**Comment by Shauren** [comment]
Please let me know if 5f8cc1a120c72fbe355dd33f2757ae95c1f69b14 is enough

**Comment by Golrag** [comment]
Wont I need https://github.com/TrinityCore/TrinityCore/pull/28754/files#diff-b157588bb756d0f4688e1ddfdda15756e464b828a93157d41116f140f301cbc3R578 as well ? (allowing traps to be pooled)

**Comment by Shauren** [comment]
that entire gob tupe check can be removed

**Comment by Golrag** [comment]
@Shauren your commit seems to be enough. Thank you :) I will update this PR to remove the gob type check instead

**Pull request merged**
