### PR TITLE
[Core/Pet] Fix HP for summoned Pets

### PR DESCRIPTION
**Pull request by ghost**
Full hp for summoned, not active pets.
[link to Issues](https://github.com/TrinityCore/TrinityCore/issues/15030)

### CODE REVIEW

**Comment by DDuarte** [comment]
Fixes #15030

**Comment by DDuarte** [comment]
@PaulHellCore: Is this related to http://eu.battle.net/wow/en/forum/topic/1549391663?page=1 ?

**Comment by PaulHellCore** [comment]
No.

**Comment by jackpoz** [comment]
what's the effect of calling _LoadAuras() before map->AddToMap(this->ToCreature()) ? Did you debug the code to ensure everything works correctly ?

**Comment by tkrokli** [comment]
@jackpoz : I don't think the intention is to call `_LoadAuras()` before `map->AddToMap(this->ToCreature())` as such, I think the point here is to move the selected lines above `SetHealth()` and `SetPower()` (258-271). I am thinking about `InitTalentForLevel();` in particular, to have talents read correctly before setting the pet hp, in case of existing talent points affecting total creature hp. (I have not tested this PR yet.)

**Comment by jackpoz** [comment]
Intentional or not, the new code calls _LoadAuras() before map->AddToMap(this->ToCreature()) and either that's ok and this can be merged or that's not ok and this cannot be merged.

**Comment by tkrokli** [comment]
OK, I will test this in a branch of my own, just to see if I can find anything wrong happening, either during compile or during runtime. Feel free to suggest what I should be looking for. :)

**Comment by jackpoz** [comment]
As suggested in https://github.com/TrinityCore/TrinityCore/pull/15074#issuecomment-129190508
> Did you debug the code to ensure everything works correctly ?

**Comment by tkrokli** [comment]
Never mind. "Tistur" in #trinity convinced me that this is not a working solution for the issue. The real fix needs to be done in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L2975

BTW, had a dialog about it this evening: https://gist.github.com/tkrokli/ac5e69bc6c855e90d193

**Comment by PaulHellCore** [comment]
I had a decision on the other. Sorry for my English. 
[link to Gist] (https://gist.github.com/PaulHellCore/0526d0eccd63b851b221)

**Pull request closed without merging**
