### PR TITLE
Core/Spell: Reflection

### LINKED ISSUE #9745: [3.3.5][Warrior] Spell Reflection
1.Get a warrior with spell reflection.
2.Get a priest with penance and dispel magic.
3.Cast spell reflect, and let priest to cast penance or dispel magic to warrior.

Bug:
Spell reflection not reflecting penance tick or dispel magic.

Spell reflection should reflect the penance and dispel magic back to the priest.

rev: 2e1b1b8
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1413006-3-3-5-warrior-spell-reflection?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Aokromes**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

Spell reflection reflects the penance and dispel magic back to the priest. 
  

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
Closes #9745 by robinsch

[//]: # (**DEPRECATION NOTICE** Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE** If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

### CODE REVIEW

**Comment by Goatform** [comment]
Now **it reflects** shaman's spell **Purge**, but it **does not reflect: Dispel Magic and Penance**.

**Comment by Keader** [comment]
if i remember well, spells like penance and arcane missels should reflect first "damage" only

**Comment by Goatform** [comment]
Yes @Keader, you are right. But it still didn't fixed these spells for me. I can share hackfix which I made for my core with you guys but still, it is just a hackfix not something we should merge.

Basically, when it comes to reflecting spells such as Penance and Arcane Missiles, it should reflect 1 bolt but it is possible to reflect more than 1 bolt as well, it depends on time and range (it is already fixed in multi-reflection commit)

**Comment by robinsch** [comment]
@Goatform You need to allow Dispel Magic and Penance to be reflected. This doesn't work on default.

**Pull request closed without merging**
