### PR TITLE
fixed bronjahm and fixed Soul Power achievement

### PR DESCRIPTION
**Pull request by Grimton1337**
Did it correctly now, sorry for earlier.

### CODE REVIEW

**Comment by Grimton1337** [comment]
@jackpoz Sorry for not replying to earlier comments.

No, in fact, I can't re-do this thing, my friend and I started a project on our own game, so I can't really provide any help to you guys. Best of luck, though, maybe you guys can just convert my code into every branch? Sorry again.

**Comment by tkrokli** [comment]
Would you like me to give this PR a shot and fix the formatting? I am reasonably confident that I can handle the text formatting pretty well, as long as most of the code to be used is present and correct. :-)

**Comment by Aokromes** [comment]
Failed — The Travis CI build failed

**Comment by tkrokli** [comment]
> Failed — The Travis CI build failed

Yes, I noticed. Is it enough to clear the semicolon errors in the SQL file and remove the incorrect whitespace in the C++ file, then I am all up for fixing it. On the other hand, if there are other serious code errors, I need to collaborate with a coder to replace that code.

**Comment by Nyeriah** [comment]
This PR doesn't need any of these creature_text sqls. All of that data is already at database.

**Comment by tkrokli** [comment]
OK, thanks for the confirmation. Is it fair to say, then, that what is needed to complete this PR is to fix the codestyle of the file `src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp` ?

**Pull request closed without merging**
