### PR TITLE
Add quick events for easier event handling

### PR DESCRIPTION
**Pull request by jameyboor**
**Changes proposed:**
Add another container that plays nicely with lambdas to ease event development.

Instead of having to create a whole seperate class that derives from `BasicEvent` this addition will allow simple future actions to be added by just adding a lambda to the EventProcessor instead.

**Target branch(es):** 3.3.5

- [x] 3.3.5

### CODE REVIEW

**Comment by Ovahlord** [comment]
While you're at it add an 2nd header entry with std::chrono timers just like AddEventAtOffset does.

**Comment by Keader** [comment]
I love it

**Comment by jackpoz** [comment]
I see the way the m_quickEvents are iterated is totally different from m_events, would it make more sense to have the same for both ?

**Comment by Shauren** [comment]
Implemented differently in 813f693768ee94864b0d24423b9265bde2c9903d

**Comment by jameyboor** [comment]
@Shauren Oh you must be feeling really cool right now. HMMMMMMMMM

**Pull request closed without merging**
