### PR TITLE
Core/SAI: cherry pick player-only for SMART_EVENT_OOC_LOS and SMART_EVENT_IC_LOS 

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Cherry pick including adding playerOnly flag for SMART_EVENT_OOC_LOS and SMART_EVENT_IC_LOS 
- Cleanup in the same area
 
**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by illfated** [comment]
Just in case you are wondering about the AppVeyor error; it seems to be a connection closing before the artifacts can finish uploading to the AppVeyor site (not a build issue).

**Comment by matanshukry** [comment]
> Just in case you are wondering about the AppVeyor error; it seems to be a connection closing before the artifacts can finish uploading to the AppVeyor site (not a build issue).

Yeah I saw that. I just assumed it's fine and someone will ignore that and merge it.
If you want me to "fix" it I can commit a change and then revert it, causing the process to run again - just let me know.

**Comment by illfated** [comment]
Nah, it's just fine as is.

**Review by ghost — APPROVED** [review]

**Comment by Shauren** [comment]
77ee6dca456110336700460b25273a4de8061248 & 55931b0d924731e3dbbf939765343187f0c73720

**Pull request closed without merging**
