### PR TITLE
Core/Conditions: CONDITION_QUEST_OBJECTIVE_COMPLETE

### PR DESCRIPTION
**Pull request by benlbot**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

Following #19488 

**Changes proposed:**

- Ignore flag QUEST_OBJECTIVE_FLAG_OPTIONAL from quest_completion

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**  None

**Tests performed:** (Does it build, tested in-game, etc.)
- [x] Build
- [x] Tested In Game
- [ ] etc.

As mentioned in https://github.com/TrinityCore/TrinityCore/commit/ec83e3faf339be9e8129889859de464cfc47a1ed flag 0x04 is not required to complete the quest

### CODE REVIEW

**Comment by tkrokli** [comment]
Looks like one of the main devs will have to fix the build in the `master` branch
by changing something about `src/server/game/Entities/Unit/Unit.cpp:5144:12`.
(Don't worry, as long as it is not part of your PR, just wait for it to be fixed.)

**Comment by funjoker** [comment]
Logically this is wrong :/
Even an optional objective still can be complete.

What if ingame something happens when an optional objective is complete?
By returnin allways true for this the condition would be useless.

`IsQuestObjectiveComplete` only returns if the speficied objective is complete or not nothing else.
So you handling of flag might belong to objective quest status handling

**Comment by funjoker** [comment]
> "popup message from illidan"

nope :D

This is done by Scene Trigger Event: "CUEILLIDAN"

**Comment by Aokromes** [comment]
/home/travis/build/TrinityCore/TrinityCore/src/server/game/Entities/Unit/Unit.cpp:5144:12: fatal error: 
      unused variable 'triggerAmount' [-Wunused-variable]
    int32  triggerAmount = triggeredByAura->GetAmount();

**Comment by funjoker** [comment]
@Aokromes it's TC error not PR error

**Pull request merged**
