### PR TITLE
SmartScript: Added SetBossState support

### PR DESCRIPTION
**Pull request by ariel-**
**Changes proposed**:
- Adds Boss State capability to smart scripts, making it possible to fully script simple bosses using DB
- Still needs SetBossNumber set on instance .cpp, done this for DIre Maul, which has every boss with SmartAI

**Target branch(es)**: 335/6x

**Issues addressed**: Will help fixing DM tribute run (commit referenced)

**Tests performed**: (Does it build, tested in-game, etc)  Build correct

**Known issues and TODO list**: None as I know

### CODE REVIEW

**Comment by Shauren** [comment]
fkin hell... bosses arent supposed to be scripted in sai

**Comment by NorthStrider** [comment]
@Shauren  the newer complex one yes, but it looks to me that this can be used for old classic bosses since there seems to be some sort of client notification if a boss dies according to that boss state UI element.

**Comment by soulfrost** [comment]
@NorthStrider
```
some sort of client notification if a boss dies in WoD according to that boss state UI element.
```
made by SMSG_BOSS_KILL_CREDIT, and encounterID from by taken from DungeonEncounter.db2 - where row should be finded by creature_display_id

**Comment by Runico** [comment]
Please add an options for heroic attempts, like ToC

**Comment by ariel-** [comment]
Heroic attempts counter is handled by world states, this are the kind of instances that should be handled by a cpp script.

**Comment by joschiwald** [comment]
Dislike

**Comment by ariel-** [comment]
There are still some instances which don't have AIs in .cpp, but in SmartScript, like DIre Maul case, what should be done with those then? I think moving the (simple) scripts to cpp is overkill.

**Comment by Aokromes** [comment]
I don't see any reason to don't merge this for custom projects.

**Pull request merged**
