### PR TITLE
Fixes/3.3.5 aura infinite loop

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Core/Auras: Attempt to fix infinite loop with aura 18950 on map unload
-  Core/Auras: Log a detailed error and assert when failing to remove all auras after a few tries

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
Some crashes

**Tests performed:** (Does it build, tested in-game, etc.)
None

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by kelno** [comment]
Might be interesting:
I just had the same issue happen to me on my live server but in RemoveAllAurasOnDeath
Some aura was being re applied at each remove.

**Comment by jackpoz** [comment]
did you get a crashlog with some information about which unit/aura ?

**Comment by kelno** [comment]
I have rewritten bot airforce scripts which were causing this issue:

- The airforce bots put spell 38067 on players, which has aura effect SPELL_AURA_MOD_STALKED
- If players dies, he loses the aura, which triggers a visibility update (in HandleAuraModStalked handler), which triggered a new spell cast from the airforce bot MoveInLineOfSight
Infinite loop ensues just like in this pull request.

So, not currently an issue on TC, but super similar to this case and not hard to do in any script.

**Comment by sirikfoll** [comment]
Got the crash when unloading npc [Stonevault Cave Lurker](https://www.wowhead.com/npc=4850/stonevault-cave-lurker) in mapId 70 (Uldaman).
Npc had aura [22766](https://www.wowhead.com/spell=22766/sneak) (SPELL_AURA_MOD_STEALTH and SPELL_AURA_MOD_DECREASE_SPEED), didn't catch any extra logs :/

**Comment by jackpoz** [comment]
No crashlog or server log ?

**Comment by sirikfoll** [comment]
No, got this crash some time ago and just remembered to inform, will try to activate the logs, but it's a very very rare crash..

**Pull request merged**
