### PR TITLE
Misc: Removed unneeded info about character escaping from .conf.dist …

### PR DESCRIPTION
**Pull request by panaut0lordv**
…and improved example MotD

### CODE REVIEW

**Comment by jackpoz** [comment]
what's the deal with character escaping no longer needed ? the PR doesn't specify anything about it

**Comment by tkrokli** [comment]
The weird thing about using apostrophes in the MOTD message in Worldserver.conf is that for some people the backslash will be visible in-game, while for others it will work just as intended. My 3.3.5 compiles seem to work with the documented method, but I have not compared with 6.x yet.

**Comment by panaut0lordv** [comment]
In case your config needs commenting, please specify OS, architecture and boost lib version.

**Comment by jackpoz** [comment]
tried on Win 10 X64 and escaping the character \' displayed it like \' ingame so escaping is unneeded in this configuration

**Comment by jackpoz** [comment]
same behavior on Ubuntu 15.10 (335 branch at least)

**Pull request merged**
