### PR TITLE
Core: Implement "spell_script_names" reloading

### PR DESCRIPTION
**Pull request by Robingadko**
It is now possible to add scripts/templates without server restart
(based on and part of dc92d02678f23835375ca9b708bc9db6fe0a8ada)

**Changes proposed:**

Add reload spell_script_names command.

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

None.

**Tests performed:**

Built and tested in-game.

**Known issues and TODO list:** (add/remove lines as needed)

None.

### CODE REVIEW

**Comment by VincentVanclef** [comment]
nice 👍

**Comment by illfated** [comment]
Codestyle: `2020_12_16_01_reload_scripts_command.sql` is missing a NewLine at EOF (end-of-file). I would have commented in the SQL file if it wasn't for the fact that the missing NewLine does not show up here in the comments section.

**Comment by illfated** [comment]
Filename codestyle: your SQL files are named `2020_12_16_[...].sql` when they should be named using a date after the current files (2021_02_06_05_world.sql is the previous date content format).

**Comment by illfated** [comment]
Also: it is recommended to merge SQL content into 1 file before a merge with the existing source can be performed.

**Comment by Seyden** [comment]
The original PR was this here. Its not based on, its basically the original PR without the script removing part. https://github.com/TrinityCore/TrinityCore/pull/22846/

**Comment by illfated** [comment]
Thanks for the insight and link. Does this mean that the current PR owner is less likely to make required corrections to the current content?

**Comment by Shauren** [comment]
I don't see why would you open a PR with code made by someone else when the original one was also rejected?

**Pull request closed without merging**
