### PR TITLE
Build: Enable and require c++17

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Build: Enable and require c++17

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** None

**Tests performed:** (Does it build, tested in-game, etc.)
- Built, logged ingame

**Known issues and TODO list:** (add/remove lines as needed)

- [x] VS, GCC and Clang versions should be increased to whichever version has a working C++17 with no big known issues

### CODE REVIEW

**Comment by Aokromes** [comment]
Conflicting files
dep/argon2/CMakeLists.txt

**Comment by jackpoz** [comment]
Cleaned up the PR with only the changes required for C++17 after some CMake bits have been merged to 3.3.5 already

**Comment by jackpoz** [comment]
anyone against merging this PR ?

**Comment by illfated** [comment]
Maybe replace the label **[Feedback-FixOutdatedMissingWIP]** with **[Feedback-PatchFix]** before merging, just to signify its current state.

Otherwise, this PR has been available for quite a while, so if anybody with an opinion has not reviewed or tested this yet, they are unlikely to respond before this gets merged anyway.

**Comment by jackpoz** [comment]
This PR is planned to be merged this weekend. Speak before that if you don't want that (and maybe provide some valid reasons about it)

**Comment by Rushor** [comment]
so compiling with Microsoft Visual Studio/2017/Community/VC will still all wotk smooth?

**Comment by Aokromes** [comment]
> so compiling with Microsoft Visual Studio/2017/Community/VC will still all wotk smooth?

https://community.trinitycore.org/forum/2-releases-and-announcements/

**Comment by Rushor** [comment]
aok wrote: Since we are targeting C++17 compilers, GCC 6.3, clang 4 and Visual Studio 2017 under version 15.7 will become unsupported after summer 

perfect thanks!

**Comment by jackpoz** [comment]
@Rushor this PR raises VC++ required version to 19.16 which means VS 2017 15.9+ https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#-visual-studio-2017-version-1590 as previous VS 2017 versions had C++17 bugs.

I would suggest to update to latest VS 2017 or to latest VS 2019 to get latest fixes from the VS team.

**Comment by Rushor** [comment]
alright - thank you very much!

**Comment by Warpten** [comment]
Nitpick: also set Zc:__cplusplus on Windows to get proper value for the language version (it previously always reported as c++98)

**Comment by jackpoz** [comment]
I would prefer to change that flag in another PR, maybe removing _MSVC_VER checks, and testing it.

**Review by Shauren — APPROVED** [review]

**Comment by Warpten** [comment]
Aight go

**Pull request merged**
