### PR TITLE
Scripts/Thousand Needles: Kanati - Allow Attackability during Quest ' Protect Kanati Greycloud'

### LINKED ISSUE #11728: [ Quest ]  Protect Kanati Greycloud
It starts the quest but doesn't add npc's for the quest to protect him from

http://wotlk.openwow.com/quest=4966

Core 6c64fa8

TDB 335.52 + updates

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1617675-quest-protect-kanati-greycloud?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
closes #11728

### CODE REVIEW

**Comment by Rushor** [comment]
okay adding and removing this: me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC); does not work, probably an issue with the 
summoned->AI()->AttackStart(me); :/

**Comment by Rushor** [comment]
okay well i have no idea how to improve that, if someone has an idea, let me know, else i will close this shit in 2 days :D

**Comment by Kittnz** [comment]
Maybe it has somethign to do with rep? Him to become hostile?

**Comment by Rushor** [comment]
maybe in the future, closing for now

**Pull request closed without merging**
