### PR TITLE
Core/Movement: fix MovementInform scripts relying on WP_START or START_CLOSEST_WAYPOINT

### PR DESCRIPTION
**Pull request by tje3d**
**Description:**
This pr will fixes SmartScripts that have `event_type=MOVEMENTINFORM`, `event_param2=1`(pointid) and rely's on one of the `WP_START`, `START_CLOSEST_WAYPOINT` actions.

`WP_START` and `START_CLOSEST_WAYPOINT` uses `StartPath` -> `MovePath` -> `WaypointMovementGenerator` to move a creature, and the `WaypointMovementGenerator::OnArrived` currently pass the `_currentNode` ( which starts from 0 ) to `MovementInform`. As `smart_scripts`, `waypoints`, `pointid` starts from 1, Those `smart_scripts` with `event_type=34`, `event_param2=1` always fail to run.

Example: [QuestLink](https://wotlk.evowow.com/?quest=27364)

**Target branch(es):** 3.3.5

### CODE REVIEW

**Comment by Shauren** [comment]
Breaks all non-sai scripts

**Comment by tje3d** [comment]
Well, so `creature->AI()->MovementInform(WAYPOINT_MOTION_TYPE, creature->AI()->GetAIName() == "SmartAI" ? waypoint.id : _currentNode);` would do the job

**Comment by Shauren** [comment]
Almost, you should do _currentNode to point id translation inside SAI code, not in movement generator

**Comment by tje3d** [comment]
@Shauren much better now, thanks

**Pull request closed without merging**
