### PR TITLE
Scripts/Gameobject: Move Orb of Command script to SAI.

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
**Changes proposed:**

-  Move Orb of Command script to SAI.
-  
-  

**Target branch(es):** 3.3.5/master

- [X] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
- 

**Tests performed:** (Does it build, tested in-game, etc.)
- Yes all working

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Nothing
- [ ]

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Comment by Killyana** [comment]
There's 2 texts for this gossip:
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=6001;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=6001;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(15,6001,0,0,0,8,0,7761,0,0,0,0,0,"","Show gossip option if quest '7761' is rewarded"),
(14,6001,7155,0,0,8,0,7761,0,0,0,0,0,"","Show gossip text 7155 if quest '7761' rewarded");
DELETE FROM `gossip_menu` WHERE `MenuID`=6001 AND `TextID`=7155;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`) VALUES (6001,7155);
DELETE FROM `gossip_menu_option` WHERE `MenuID`=6001;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(6001,0,0,"<Place my hand on the orb.>" ,9859,1,1,0,0,0,0,"",0,0);

**Comment by Rushor** [comment]
o7

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
