### PR TITLE
g3d: remove and gate some x86-specific code 

### PR DESCRIPTION
**Pull request by Artox**
**Changes proposed:**

-  g3d: use compiler builtins for integer math on *all* platforms
-  g3d: build cpuid code only for x86

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

- Enhances #23231

**Tests performed:** (Does it build, tested in-game, etc.)

- master: built on Linux amd64, gcc
- master: login, create character, enter world
- 3.3.5: cherry-picked and built on Linux amd64, gcc

**Known issues and TODO list:** (add/remove lines as needed)

- needs testing on Windows and compilers other than gcc

### CODE REVIEW

**Comment by jackpoz** [comment]
I would say these https://github.com/TrinityCore/TrinityCore/tree/master/cmake/compiler are the compilers we support

**Comment by Artox** [comment]
> I would say these https://github.com/TrinityCore/TrinityCore/tree/master/cmake/compiler are the compilers we support

So those are gcc, icc, clang, msvc. Both icc and clang claim gcc compatiblity, and support the __sync_* atomic builtins.
And for msvc the Interlocked* are used.

**Comment by Shauren** [comment]
I would also say you definitely don't need to check that gcc version, we require 6.3 or newer for --std=c++14

**Comment by Warpten** [comment]
Since this is g3d, please include a patch diff in the directory tree for these changes

**Comment by Shauren** [comment]
Already supported in 3.3.5 - to be cherry-picked

**Pull request closed without merging**
