### PR TITLE
update (Core): add SubclassID to enforceDBCAttributes

### PR DESCRIPTION
**Pull request by acidmanifesto**
- Add SubclassID to enforceDBCAttributes
- SubclassIDis apart of the Item Entry dealing with the item.dbc but it is not apart of the enforceDBCAttributes https://github.com/TrinityCore/TrinityCore/blob/aeb4d18e20c444e828ecff0964013d3d8daf67d9/src/server/shared/DataStores/DBCStructure.h#L880-L890 
- currently prior to this pr it is only used in a switch case dealing with ammo display id and inventory type but not apart of any enforceDBCAttributes as with the rest of the enforceDBCAttributes.
- prior to this pr only: ClassID, SoundOverrideSubclassID, Material, DisplayInfoID, InventoryType, SheatheType is apart of the enforceDBCAttributes.
- subclass comparison to the dbc should prove helpful for logging to identify any wrong subclass with in the item template.
 
**Changes proposed:**

-  add a subclass check to the enforceDBCAttributes

**Issues addressed:**

Closes #  (insert issue tracker number) None Listed

**Tests performed:**

(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Shauren** [comment]
Uh... what can you say about this old removed code (and comment on it)

https://github.com/TrinityCore/TrinityCore/commit/a82654debd8fd00fec3f2024290876ab0d6dd175#diff-59e59afabb9e07b951f9cd43dc7ef08e8c894b2aa889ae394fc4ace2eef09242L2219-L2226

(image in case link doesnt open properly because of too large commit)
obraz

**Comment by acidmanifesto** [comment]
> Uh... what can you say about this old removed code (and comment on it)
> 
> https://github.com/TrinityCore/TrinityCore/commit/a82654debd8fd00fec3f2024290876ab0d6dd175#diff-59e59afabb9e07b951f9cd43dc7ef08e8c894b2aa889ae394fc4ace2eef09242L2219-L2226
> 
> (image in case link doesnt open properly because of too large commit)
> obraz
> 

Now that comment i was not aware from 15 yesrs ago. However, that brings up some questions. Is the dbc not to be fully trusted in this case? Why are we needing to rely on db? Is it because of sniffs being used to verified? If so when was the case of the dbc of the client not fully trusted or is this some unique case?

**Comment by Shauren** [comment]
I don't know, I was hoping you would answer that question by starting worldserver with this PR applied and checking if it produces error logs about subclass mismatch

**Comment by acidmanifesto** [comment]
> I don't know, I was hoping you would answer that question by starting worldserver with this PR applied and checking if it produces error logs about subclass mismatch

Some items were shown with errors. Mainly they were items cut from the game/ unobtainable items.
I can make a accompany sql later if u wish kater today that would align it to the dbc.

**Comment by acidmanifesto** [comment]
> I don't know, I was hoping you would answer that question by starting worldserver with this PR applied and checking if it produces error logs about subclass mismatch

sorry for the delay. been busy with newborn kid stuff.
At current we get this mismatch with the database when compared to the dbc.
Easily addressible with a sql patch.
```
Item (Entry: 17) does not have a correct subclass 1, must be 4 .
Item (Entry: 2556) does not have a correct subclass 0, must be 6 .
Item (Entry: 31802) does not have a correct subclass 10, must be 13 .
Item (Entry: 33080) does not have a correct subclass 0, must be 3 .
Item (Entry: 33604) does not have a correct subclass 0, must be 3 .
Item (Entry: 33604) has wrong Subclass value (3) for class 12
Item (Entry: 37445) does not have a correct subclass 0, must be 8 .
Item (Entry: 37445) has wrong Subclass value (8) for class 12
Item (Entry: 37677) does not have a correct subclass 0, must be 12 .
Item (Entry: 37677) has wrong Subclass value (12) for class 15
Item (Entry: 41749) does not have a correct subclass 0, must be 7 .
Item (Entry: 41749) has wrong Subclass value (7) for class 10
Item (Entry: 53048) does not have a correct subclass 0, must be 1 .
```

**Comment by acidmanifesto** [comment]
now do you want me to do a sql patch file seperately or do you want me to include on with this pr?

**Comment by CraftedRO** [comment]
I saw similar subclass errors when I tried to override our item db with [this one](https://github.com/CraftedRO/WoW.tools-3.4.0-Classic-WotLK-Tables/blob/main/converted.sql/item.sql) converted from wow tools, well just saying.

**Comment by CraftedRO** [comment]
I saw similar subclass errors when I tried to override our item db with [this one](https://github.com/CraftedRO/WoW.tools-3.4.0-Classic-WotLK-Tables/blob/main/original.csv/item.csv) converted from wow tools, well just saying.

**Comment by acidmanifesto** [comment]
> ```
> Item (Entry: 17) does not have a correct subclass 1, must be 4 .
> Item (Entry: 2556) does not have a correct subclass 0, must be 6 .
> Item (Entry: 31802) does not have a correct subclass 10, must be 13 .
> Item (Entry: 33080) does not have a correct subclass 0, must be 3 .
> Item (Entry: 33604) does not have a correct subclass 0, must be 3 .
> Item (Entry: 33604) has wrong Subclass value (3) for class 12
> Item (Entry: 37445) does not have a correct subclass 0, must be 8 .
> Item (Entry: 37445) has wrong Subclass value (8) for class 12
> Item (Entry: 37677) does not have a correct subclass 0, must be 12 .
> Item (Entry: 37677) has wrong Subclass value (12) for class 15
> Item (Entry: 41749) does not have a correct subclass 0, must be 7 .
> Item (Entry: 41749) has wrong Subclass value (7) for class 10
> Item (Entry: 53048) does not have a correct subclass 0, must be 1 .
> ```

```
-- Corrects subclass error messages
UPDATE `item_template` SET `subclass`=4 WHERE  `entry`=17;
UPDATE `item_template` SET `subclass`=6 WHERE  `entry`=2556;
UPDATE `item_template` SET `subclass`=13 WHERE  `entry`=31802;
UPDATE `item_template` SET `subclass`=3 WHERE  `entry`=33080;
UPDATE `item_template` SET `subclass`=3 WHERE  `entry`=33604;
UPDATE `item_template` SET `subclass`=8 WHERE  `entry`=37445;
UPDATE `item_template` SET `subclass`=12 WHERE  `entry`=37677;
UPDATE `item_template` SET `subclass`=7 WHERE  `entry`=41749;
UPDATE `item_template` SET `subclass`=1 WHERE  `entry`=53048;
```

**Comment by acidmanifesto** [comment]
@Shauren 
Now there is the error message
```
Item (Entry: 33604) has wrong Subclass value (3) for class 12
Item (Entry: 37445) has wrong Subclass value (8) for class 12
Item (Entry: 37677) has wrong Subclass value (12) for class 15
Item (Entry: 41749) has wrong Subclass value (7) for class 10
```
But  i am not entirely certain how that is wrong in this case as the subclass matches the dbc entirely.
That logging is from https://github.com/TrinityCore/TrinityCore/blob/afc6b9c1b805348ac727b21365a016f0366417de/src/server/game/Globals/ObjectMgr.cpp#L3131-L3135
I am curious if the logging may of been set up wrong here or if these items are specifically some sort of exception as they are all removed\cut\gm\unreleased items

**Comment by Shauren** [comment]
No, I guess thats the anomaly that the old commented out code was talking about, I would just restore the comment to prevent people in the future from trying to bring back the subclass check and not pursue this anymore

**Comment by acidmanifesto** [comment]
> No, I guess thats the anomaly that the old commented out code was talking about, I would just restore the comment to prevent people in the future from trying to bring back the subclass check and not pursue this anymore (look at ItemSubclass.dbc to confirm that these subclasses are indeed not valid for that class)

not a problem then. since we now have this discussion on the git. this can be used as reference for any further attempts.

**Comment by acidmanifesto** [comment]
Also just following up. The ItemSubclass.dbc does show it not matching up with class. So definately a unqiue situation. To call it a issue would be inaccurate imo. Most likely special case items that wont justify insane exception in the core.

**Pull request closed without merging**
