### PR TITLE
fix(Script/Quest) Last Rites

### LINKED ISSUE #19463: Last Rites quest broken
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
There are some minor issues with timing and perhaps some phasing issues regarding the quest [Last Rites](http://www.wowhead.com/quest=12019/last-rites).

After killing Valanar, Thassarian is only available for turn in for a few seconds before the followup event begins. I can't turn in the quest to [Thassarian ](http://www.wowhead.com/npc=26170/thassarian) after the event has ended because he and the other npc's disappeared.

While he and Leryssa are talking, their audible speech is not correctly lined up, they overlap through the conversation. Thassarian is supposed to walk over to Leryssa and kneel in front of her, instead sits down where he stands and does not move.

And finally, a few seconds after the event is over and they stop talking, everyone disappears as if there is a phase change and I cannot turn in the quest to Thassarian.

wowscrnshot_041517_001110

**Edit: A few minutes later, Thassarian reappears at his original spawn location sitting down.**

wowscrnshot_041517_002918

Here is a video from cata that appears to be from live: https://www.youtube.com/watch?v=BNfd1KWiLW0

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e478434146fd 2017-04-09 19:18:22 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Redo script to make quest work properly.

Closes #19463

**Tests performed:**

SQL inserts, Script compiles, Tested quest in game.

How to test:

.go c 101303
.quest add 12019

### CODE REVIEW

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19463 related

**Comment by CraftedRO** [comment]
0174e6ba8091 I tested this and seems blizzlike but I only have one doubt :
Shoudn't after Talbot transformes into [Prince Valanar](https://www.wowhead.com/wotlk/npc=25601) to change his npc id too , is this possible in TC ?

**Comment by malcrom** [comment]
> [0174e6b](https://github.com/TrinityCore/TrinityCore/commit/0174e6ba809172e29a0fc87962e1b88cd42d572a) I tested this and seems blizzlike but I only have one doubt : Shoudn't after Talbot transformes into [Prince Valanar](https://www.wowhead.com/wotlk/npc=25601) to change his npc id too , is this possible in TC ?

Change his entry?

**Comment by CraftedRO** [comment]
yea ? just askin'

**Comment by malcrom** [comment]
I could be wrong but to do that I think you would need a new spawn. In the sniff I made this from the the creature just transformed. I don't think it would improve on the script if it did change.

**Comment by CraftedRO** [comment]
well if others are fine with this , I love anyway how better looks now vs how bad it was before.

**Comment by CraftedRO** [comment]
btw shoudn't Thassarian dissapear too after hi's quest giver status is gone ?

**Comment by malcrom** [comment]
From what I remember it's timed.

**Comment by CraftedRO** [comment]
noice

**Pull request merged**
