### PR TITLE
Spells/Priest: don't keep players in combat via Vampiric Embrace

### PR DESCRIPTION
**Pull request by ghost**
by @P-Kito; posted in #15036

Vampiric Embrace should not keep PvP players in combat state.

Players can't drink or eat for extended periods of time in arena
because Vampiric Embrace aggro keeps them in combat.
These 3 lines inserted into SpellMgr.cpp should fix the issue.

### CODE REVIEW

**Comment by Goatform** [comment]
I think that you should add this as well:
```
spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_DONE_BONUS;

**Comment by tkrokli** [comment]
OK, good suggestion. I suppose @P-Kito forgot that part. ;)

**Comment by Goatform** [comment]
Or simply convert this PR with this one #15036 to get this:

``` diff
 @@ -3235,6 +3235,9 @@ void SpellMgr::LoadSpellInfoCorrections()
                 spellInfo->Effects[EFFECT_1].BasePoints = -6; // -5%
                 break;
             case 50526: // Wandering Plague
+            case 15290: // Vampiric Embrace
+                spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_DONE_BONUS;
+                spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_INITIAL_AGGRO;
+                break;
             case 63675: // Improved Devouring Plague
                 spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_DONE_BONUS;
                 break;

**Comment by tkrokli** [comment]
@Goatform : thanks, I see what you are saying. I did not want to mix the 2 PR solutions because of different PC class. Is your suggestion a more optimized solution than my current PR? :)

**Comment by P-Kito** [comment]
This is wrong. 
Vampiric Embrace doesn't need SPELL_ATTR3_NO_DONE_BONUS.

**Comment by Goatform** [comment]
@P-Kito, if I remember good I think that this aura has some issues about bonus with some auras.

**Comment by P-Kito** [comment]
If it's not in current TC, you will want to open another issue for that problem.
This PR is for the inCombat Problem

**Comment by tkrokli** [comment]
@P-Kito : OK, so I should revert that latest change, using only the original lines you posted in #15036?

**Comment by joschiwald** [comment]
@Goatform this problem was fixed some time ago (keyword SPELL_DAMAGE_CLASS_NONE)
@tkrokli remove SPELL_ATTR3_NO_DONE_BONUS

**Comment by Goatform** [comment]
Oh, then my bad. I apologise.

**Comment by tkrokli** [comment]
Made the requested changes and merged this PR into #15036 as requested. This PR is hereby closed.

**Pull request closed without merging**
