### PR TITLE
Core/Spells: Fix glyph of stars (druid)

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Fix glyph of stars

**Tests performed:**

Tested in-game

### CODE REVIEW

**Comment by Nyr97** [comment]
FYI: it is not possible to change a spell's raw value through a spellscript unless it's about damage calculations and so on. If you wish to change miscvalue, it must be done on Spellmgr.cpp 😿

**Comment by aquadeus** [comment]
Then is no other way to handle this spell

**Comment by Shauren** [comment]
Why aren't you hooking into `Unit::GetModelForForm`? All shapeshift customizations are scripted there

**Comment by aquadeus** [comment]
but this spell has no model id, it just removes the moonkin form

**Comment by Shauren** [comment]
Then make it return 0?

**Comment by aquadeus** [comment]
ok changed

**Pull request merged**
