### PR TITLE
Scripts/Borean Tundra: link gossip content for NPC Iruk from DB

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

- remove hardcoded text (deprecated method)
- add already existing DB gossip content to enum
- correct spell enum from `spell_creature_` to `spell_create_`
- replace case switch with if statement (only one boolean case)

Extra script file update:
- remove SD comment line 22 (outdated info, replaced by SAI)

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [X] master

**Issues addressed:** Replaces my old Pull Request #22847

Related to aletson#7 (**Migrate hardcoded gossip texts to database**)

**Tests performed:** (Does it build, tested in-game, etc.)

Tested in-game, builds and works as if nothing had been changed.

**Known issues and TODO list:** (add/remove lines as needed)

None that I know of. DB gossip linking is the main part here, not much else has changed.

### CODE REVIEW

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by illfated** [comment]
You're welcome. I simply find it necessary to follow up on that old script hardcoded text issue, reducing whenever possible.

**Comment by Aokromes** [comment]
if you are bored go fix [12:17:47] Disciple of Naralex says: This $n is a minion from Naralex's nightmare no doubt! :P

**Comment by illfated** [comment]
Haha, yeah. Will see if I can find a simple solution.
I have noticed it a lot, but always got distracted.
Thanks for the reminder. 👍

**Pull request merged**
