### PR TITLE
Core/Scripts: Remove useless SD2 error log

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

Another "removal" of hardcoded text in the outdated #define format.
This time it is not so much about removing the text as using the
preferred format and placing of the error log string in TC_LOG_ERROR.
- remove "#define ERROR_INST_DATA" (old format)
- move output string to the TC_LOG_ERROR command

**Target branch(es):** 3.3.5 + 6.x

**Issues addressed:** Updates https://github.com/velinath/TrinityCore/issues/2

**Tests performed:** (Does it build, tested in-game, etc)

Builds without issues, this is just deleting 1 label & moving a text string.

**Known issues and TODO list:**

None. This is only about moving a text string, no changes to the script code functionality.

### CODE REVIEW

**Comment by joschiwald** [comment]
useless log message

**Comment by tkrokli** [comment]
Sure, but do you have a suggestion for what to do instead? All I did was to remove the `#define` part and move the actual text string back to the actual log message. I am not introducing it, I am merely getting rid of the `#define` part.

I am open to suggestions on how to deal with that log message, but I don't have any ideas myself. Please, feel free to suggest any changes that would improve on what you see as useless about the logging part.

**Comment by sirikfoll** [comment]
Remove the define, the "else" and the log ^^

**Comment by tkrokli** [comment]
Thanks, that sounds like a good solution to me. **joschiwald**, do you concur with sirikfoll's suggestion?

**Comment by tkrokli** [comment]
If this commit is acceptable, I will rename the PR title to "Remove useless SD2 error log".

**Pull request merged**
