### PR TITLE
IsInAreaTriggerRadius overload based on areatrigger ID

### PR DESCRIPTION
**Pull request by Lopfest**
**Changes proposed:**
-  add overloaded method IsInAreaTriggerRadius with input areatrigger ID
-  in case there are multiple overlapping areatriggers, you can check with this method if you are within any of those areatriggers

**Target branch(es):** 3.3.5/master
- [x] master

**Issues addressed:** -

**Tests performed:** tested in-game

**Known issues and TODO list:** -

### CODE REVIEW

**Comment by Warpten** [comment]
You can check overlapping ATs with the entries just as well, so I don't get what this provided besides an helpful helper that should probably be inlined?

**Comment by Lopfest** [comment]
i wasnt able to find out any logic that would help me do [this](https://gist.github.com/Lopfest/ef8b87c7de96d23789ecb22dd8576c05) without requested method

**Comment by Shauren** [comment]
seriously? just pass `areaTrigger` there

**Comment by Shauren** [comment]
just use sAreaTriggerStore there

**Pull request closed without merging**
