### PR TITLE
[6.x] Core/SAI: added SMART_ACTION_UPDATE_INGAME_PHASES

### PR DESCRIPTION
**Pull request by Lopfest**
**Changes proposed**:
- implemented new SAI action to update targeted player's phases

**Target branch(es)**: 6x

**Tests performed**: tested in-game

### CODE REVIEW

**Comment by Rushor** [comment]
you can use spell_area instead

**Comment by Lopfest** [comment]
not in this quest: [The Missing Driver](http://www.wowhead.com/quest=29419)
on quest completion player phases are updated - phase 629 removed, phase 630 added.
immediately after that, phase 630 is removed, otherwise player would see NPC near cart and also his spawned copy simultaneously.
phases are updated again manually when player's spawned copy reaches his destination (cart).

**Comment by Killyana** [comment]
Do you have proof from sniffs, because this kind of stuff is generally handled by invisibility auras or phasing auras.

**Comment by Lopfest** [comment]
On quest completion:
```
Opcode: SMSG_QUEST_UPDATE_ADD_CREDIT (0x1D8A)
Time: 06:24:29.523
QuestID: 29419
ObjectID: 54855
Count: 1
Required: 1

Opcode: SMSG_PHASE_SHIFT_CHANGE (0x137C)
Time: 06:24:29.523
PhaseShiftFlags: 24
PhaseShiftCount: 3
[0] PhaseFlags: 1
[0] Id: 598
[1] PhaseFlags: 1
[1] Id: 630
[2] PhaseFlags: 1
[2] Id: 1323

Opcode: SMSG_PHASE_SHIFT_CHANGE (0x137C)
Time: 06:24:29.523
PhaseShiftFlags: 24
PhaseShiftCount: 2
[0] PhaseFlags: 1
[0] Id: 598
[1] PhaseFlags: 1
[1] Id: 1323
```
On waypoint reached:
```
Opcode: SMSG_PHASE_SHIFT_CHANGE (0x137C)
Time: 06:25:19.537
PhaseShiftFlags: 24
PhaseShiftCount: 3
[0] PhaseFlags: 1
[0] Id: 598
[1] PhaseFlags: 1
[1] Id: 630
[2] PhaseFlags: 1
[2] Id: 1323

SMSG_UPDATE_OBJECT (0x026B)
Time: 06:25:19.817
DestroyObjectsCount: 2
[0] Object GUID: Full: 0x1C39846B80372DC000003100002273CC Creature/0 R3681/S49 Map: 860 Entry: 56503 Low: 2257868 // player's spawned NPC
```
No spell for phase update were casted, only 2 quest invisibility spells, but those are not related to this NPC.

**Comment by Lopfest** [comment]
I know it can be done with SMART_ACTION_SET_INGAME_PHASE_ID, I thought this one could come in handy sometimes. If you think otherwise, feel free to close this PR.

**Comment by Killyana** [comment]
What's the difference between this new action and the actual actions?:
SMART_ACTION_SET_INGAME_PHASE_ID = 44, // PhaseId, apply
SMART_ACTION_SET_INGAME_PHASE_GROUP = 16, // phaseGroupId, apply

**Comment by Lopfest** [comment]
This new action updates phases defined by phase_area and their conditions. Same like spells with SPELL_EFFECT_UPDATE_PLAYER_PHASE.
Maybe it would be better to transfer all SAIs with SMART_ACTION_SET_INGAME_PHASE_ID that have phase conditions, to have less work with updating if blizzard comes up with some new phase system again or something similar.

**Pull request closed without merging**
