### PR TITLE
Revert "[3.3.5][master] Core/Movement: Smooth movement #13467 (#18020)"

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
This reverts commit 28050f338dfc66e0c40b6a3915bf96e38e0613e5.

Conflicts:
	src/server/game/AI/SmartScripts/SmartAI.cpp
	src/server/game/AI/SmartScripts/SmartScriptMgr.cpp

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Revert smooth movement because reasons.

**Target branch(es):** 3.3.5/master

- [X] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
- https://github.com/TrinityCore/TrinityCore/issues/18401

Reason to revert was discussed 100 times in IRC now.

short excerpt:

```sql
Rat_: how did that movement PR fuckup the sai pathing,  sai's pathing is like escortAI's, it sends the next wp as a GetMotionMaster()-:MovePoint(xyz)
Riztazz: it doesnt
Riztazz: escortAI sends entire paths too
Riztazz: till first delay
Riztazz: everything is handled by WaypointMovementGenerator
Rushor: you can read it here https://github.com/TrinityCore/TrinityCore/issues/18401
WardenX: TrinityCore/TrinityCore: Keader closed issue #18887: 2 Deathknight quests have some sort of pathing issue. https://github.com/TrinityCore/TrinityCore/issues/18887
Rat_: since the motionmaster update? 
Riztazz: i hardly touched motion master
Rat_: WaypointMovementGenerator was only used for the old pathing, wich is started from the creature table
Rushor: however every issue related to escort started with the smooth movement
Riztazz: every waypoint movement is handled by waypoint move gen now Rat_ 
Riztazz: imo movement could use major rewrite
Rat_: im on master 
Riztazz: motion slots and so on ;p
Riztazz: generators
Rushor: then you should not have that issue, since the commit wasn't merged to master right?
Malcrom_Android: Yeah that smoothing is incorrect
Malcrom_Android: It's like some fag wrote it.
Rushor: revert all for now, until movement was rewritten :)
Riztazz: Rushor: do it then
Rushor: do you refixed anything on it after first commit?
Riztazz: 19:55  Malcrom_Android: Yeah that smoothing is incorrect
Riztazz: why would i waste time if its incorrect
Malcrom_Android: Well the way you send all the waypoints for ground movement is wrong.
Malcrom_Android: Very faggy
Riztazz: Malcrom_Android: what you want
Riztazz: is impossible in current state
```

[//]: # (**DEPRECATION NOTICE** Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE** If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

### CODE REVIEW

**Comment by jackpoz** [comment]
summing up: @Riztazz opened a PR to fix something, it broke something else, he has no clue how to fix it ?
this will raise a red flag for future @Riztazz PRs then.

isn't there anything useful in the long issue discussion that could fix the current merged PR implementation ?

**Comment by Rushor** [comment]
> which issues will this PR add back that the PR was supposed to fix ? do you plan on fixing those too ?

easy. i will revert the option to add smooth movement. smooth movement should only be added once the motion master system in general was reworked. I'm not sure about the details, but i understood that his pr can only work once the complete motionmaster system was reworked. 

The revert will not add any issues (his pr only added a feature).

@jackpoz  Simply join IRC. ask about smooth movement, and Riztazz and malcrom will tell you why it should be reverted for now.

**Comment by Riztazz** [comment]
@Jackpoz apparently entire approach was wrong and blizzard sends one point a time for ground paths, there are few things that could be kept but otherwise entire thing has to be written from scartch

**Comment by jackpoz** [comment]
is this ready to be merged then, tested and such ?

**Comment by Rushor** [comment]
yes it works like before the pr

**Pull request merged**
