### PR TITLE
Scripts/Spells: Port Part of Druid Scripts to New Script Registration

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Port about ~half of spell_druid.cpp scripts to new script registration syntax (or system). _There are no changes in functionality._

**Target branch(es):** 3.3.5

~~**Issues addressed:**~~

**Tests performed:** It does build. I tested some random spells and items affected by these changes. Seems to be working.

~~**Known issues and TODO list:**~~

### CODE REVIEW

**Comment by Warpten** [comment]
You could probably write a script to automate that to be honest

**Comment by Sorikoff** [comment]
Yeah, had the same thoughts. In this case I used regexes, however.

**Comment by illfated** [comment]
Looks like you need to update (rebase) your PR content to be aligned with the TC 3.3.5 branch. travis-ci complains about content in `cs_go.cpp` which was recently solved.

**Comment by Sorikoff** [comment]
[Latest commit](https://travis-ci.org/TrinityCore/TrinityCore/builds/568808683?utm_source=github_status&utm_medium=notification) still contains an error.

**Comment by jackpoz** [comment]
Let's hope this doesn't add any new issue and it's impossible for me to review the changes in the PR (give it a try too, no way in hell one can tell if the code is the same or any typo was added)

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Sorikoff** [comment]
@jackpoz, have you tried diff in Split mode with whitespaces disabled? Looks better to me when it comes to review.

**Comment by illfated** [comment]
Good point, it looks easier to read like that. Anyway, it seems to be an improvement, although I am not a real coder, so I don't know much about any consequences of the code change.

**Pull request merged**
