### PR TITLE
Core/Spell Implement talent warrior level 110 anger management.

### PR DESCRIPTION
**Pull request by HannibalRoG**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Implement talent level 110 Anger Management.

**Target branch(es):** 3.3.5/master

- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

Compiled and tested

### CODE REVIEW

**Comment by Shauren** [comment]
This is not good at all, you need to track rage spent for all spells so casting a spell with 5 rage cost followed by another 5 rage would reduce the cooldown by 1 second
`SpellHistory::ModifyCooldown` does not need HasCooldown check before it
`CalcPowerCost` consumes spellmods with charges

**Comment by DoctorKraft** [comment]
A playerscript with function OnModifyPower is a better method ?

**Comment by HannibalRoG** [comment]
Let's deal with playerscript, we had doubts about that but his comments made it clear that we can use it, thank you.

**Comment by DoctorKraft** [comment]
i think, it's strange this proc on spell... but with your spellscript system i don't think we can do otherwise

**Comment by wonder2011** [comment]
I search for the playerscript event OnModifyPower or somethig like that but i don't find anything. I miss something here?

**Comment by wonder2011** [comment]
@Shauren if @HannibalRoG hold the spent rage and in case of 5 + 5 or similars, reduce the CD's, the PR then would be fine?

**Pull request closed without merging**
