### PR TITLE
[3.3.5/master] Core/Mechanic: Server client health desync

### PR DESCRIPTION
**Pull request by Krudor**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Eliminate one (common) scenario where spell damage was modified by an underlying function, but old unmodified damage value was sent to the client causing a client/server desync in health values.
- Semi unrelated change, prevent players from being able to kill themselves with self-inflicted damage with god mode cheat enabled.

**Target branch(es):** 3.3.5/master

**Tests performed:** Builds and appears to work as expected in-game

### CODE REVIEW

**Comment by Shauren** [comment]
Does this mean that UnitAI DamageDealt and DamageTaken modifications are reflected in values sent in client packets? If yes then this change is incorrect (see training dummies with 1 hp - but that is not the only case)

**Comment by Krudor** [comment]
This change is indeed incorrect after looking into it further.
I guess there's some missunderstanding regarding the rules of managing health.

If I understand it correct, you should NOT be allowed to modify creature damage taken server-side like DamageTaken and  DamageDealt is doing right now since it will lead to desync.

Related issue #16355

**Comment by Shauren** [comment]
No. Because doing it like that for creatures staying at any fixed health (and being unkillable) is blizzlike - and combat log keeps reporting unmodified damage as well (back to training dummies example, you need original unmodifed damage sent to measure your dps as thats the entire point of these dummies)

**Comment by Krudor** [comment]
Yes, but how do you support a creature staying at any fixed health, while still preserving original melee/spell damage when the damage info client package is the one telling the client whether or not a creature should take a visible chunk out of it's health?
Doesn't the damage deal packet tell the client both how much damage an ability did + it uses the same packet to remove health from the creature?
This is from what I've understood, please correct me if I'm wrong.

**Comment by Krudor** [comment]
Is there a single creature on retail that has a certain health locked, except the obvious case of 1 hp.

**Comment by Shauren** [comment]
http://www.wowhead.com/npc=97219/solsten this guy locks it at 2hp

**Comment by Krudor** [comment]
Indeed, then I'm out of ideas for fixing this desync issue :P
A flag for setting/unsetting a units ability to die would be nice though.
Lot's of

```
if (me->GetHealth() <= damage)
    damage = me->GetHealth() - 1;
```

code to specifically make a creature unkillable
Blizzard doesn't appear to be using damage taken hook too much when scheduling health % events, it seems to be more of a repeated time event checking for hp threshholds.
On TrinityCore bosses kind of instantly SNAP into their new phases once they hit a certain health through the DamageTaken hook, compared to live where it seems to be checked periodically.

**Pull request closed without merging**
