### PR TITLE
Core/Entities: add SellResult "You cannot sell items to this merchant" for Ethereal Soul-Trader

### PR DESCRIPTION
**Pull request by toto6**
**Changes proposed:**

-  Add SellResult "You cannot sell items to this merchant"
-  Use it for NPC Ethereal Soul-Trader 27914

**Target branch(es):** 3.3.5/master
- 3.3.5

### CODE REVIEW

**Comment by nawuko** [comment]
There is a good list of npc that you cannot sell to in WoW (altho its only 1 in 3.3.5 to my knowledge) Adding a check like this is bad practice. Maybe a custom flag or something would be better. @Shauren could give advise here.

**Comment by Faq** [comment]
Anyone has idea how this should be done? Scripted or with flag? @Shauren

**Comment by Shauren** [comment]
I think a flag on the vendor would work

**Comment by jackpoz** [comment]
anyone up to implement the flag ?

**Comment by ForesterDev** [comment]
I implement the feature this way

if (CreatureTemplate const* creatureInfo = creature->GetCreatureTemplate())
    {
        if (creatureInfo->type == CREATURE_TYPE_NON_COMBAT_PET)
        {
            _player->SendSellError(SELL_ERR_CANT_SELL_TO_THIS_MERCHANT, creature, itemguid, 0);
            return;
        }
    }

**Comment by Shauren** [comment]
That would break argent gruntling pet and would allow selling items to http://www.wowhead.com/npc=111737/celadine-the-fatekeeper

**Comment by ariel-** [comment]
Superseded by #21642

**Pull request closed without merging**
