### PR TITLE
[335] Scripts/EasternKingdoms: move Alchemist Arbington and Apothecary Dithers core script to DB

### PR DESCRIPTION
**Pull request by Wyreth**
**Changes proposed:**

Not much to say, just moving this to DB where it belongs, with some added conditions and correct texts from broadcast_text.

**Target branch(es):**

- [x] 3.3.5
- [ ] master

**Tests performed:** works fine.

### CODE REVIEW

**Comment by tkrokli** [comment]
Excellent move. I have been thinking about doing this before, but something always got in the way for me to even start figuring out the conversions.

BTW, either @velinath or I might add this PR into the list of C++ scripts migrated to SAI in https://github.com/velinath/TrinityCore/issues (https://github.com/velinath/TrinityCore/issues/2 , https://github.com/velinath/TrinityCore/issues/3 , https://github.com/velinath/TrinityCore/issues/7)

**Comment by Wyreth** [comment]
Hehe. I want to script the end event for the final quest in the Skeleton Key (Scholomance) quest chain (really, it's just the npc saying two things and casting a spell. I still don't know which one exactly), and adding it as a core script would be very ugly :P

**Comment by tkrokli** [comment]
Nice goal, I approve.

BTW, cosmetic detail: if I was to write the PR title & commit title, I would have written it as
**[3.3.5] Scripts/EasternKingdoms: move NPCs Dithers and Arbington to DB**
(based on the original core script `npcs_dithers_and_arbington` and its folder name).

What do you think? (I know, I care too much about cosmetic details. :-p )

**Comment by Wyreth** [comment]
Makes sense! Going to change it, thanks.

**Comment by velinath** [comment]
@tkrokli opened velinath/TrinityCore#8, which probably has relevance

**Comment by tkrokli** [comment]
@Wyreth : regarding the diff between what you suggest in your `gossip_menu_option` query and the data already in the DB, is it because the script is moved from core to DB, hence the option values can be simplified? Or was it just laziness on my part when I worked on that script almost 2 years ago, that I didn't see what could be used? (I also notice you have added some more gossip options, I presume those are part of the wider scope of the WPL quest progression.) Anyway, this is what is present in the TDB already:
```sql
SELECT * FROM `gossip_menu_option` WHERE `MenuID` IN (3223, 3224, 3225, 3226, 3227, 3228, 3229);
```
```
MenuID  OptionID  OptionIcon  OptionText                                              OptionBroadcastTextID  OptionType  OptionNpcFlag  ActionMenuID  ActionPoiID  BoxCoded  BoxMoney  BoxText  BoxBroadcastTextID  VerifiedBuild
------  --------  ----------  ------------------------------------------------------  ---------------------  ----------  -------------  ------------  -----------  --------  --------  -------  ------------------  -------------
  3223         0           0  What's needed for the cauldron at Felstone Field?                        6516           3            131             0            0         0         0                            0              0
  3223         1           0  What's needed for the cauldron at Dalson's Tears?                        6517           3            131             0            0         0         0                            0              0
  3223         2           0  What's needed for the cauldron at the Writhing Haunt?                    6518           3            131             0            0         0         0                            0              0
  3223         3           0  What's needed for the cauldron at Gahrron's Withering?                   6519           3            131             0            0         0         0                            0              0
  3228         0           0  What's needed for the cauldron at Felstone Field?                        6516           3            131             0            0         0         0                            0              0
  3228         1           0  What's needed for the cauldron at Dalson's Tears?                        6517           3            131             0            0         0         0                            0              0
  3228         2           0  What's needed for the cauldron at the Writhing Haunt?                    6518           3            131             0            0         0         0                            0              0
  3228         3           0  What's needed for the cauldron at Gahrron's Withering?                   6519           3            131             0            0         0         0                            0              0
  3229         0           0  I need a Vitreous Focuser.                                               6531           3            131             0            0         0         0                            0              0
```

**Comment by Wyreth** [comment]
I can use `UPDATE` queries to change the values to what I need for this to work, but that would result in long queries for no real benefit.

It might be just me, but I prefer to write "stand-alone" queries for non-trivial changes, so that anyone looking at it can know what is going on without needing to check DB for original values and then check again for what changes.

So I'd keep it like that instead of overcomplicating it. But if my approach is wrong, tell me and I'll change it :P

**Comment by tkrokli** [comment]
Very well. I need feedback from more experienced users like @Aokromes , @Killyana or @dr-j in that regard. Myself, I don't have an issue with it, but I am uncertain about the TC guidelines in this case,

**Pull request merged**
