### PR TITLE
[Fix] Bronjahm event & achievement Soul Power

### PR DESCRIPTION
**Pull request by ghost**
Based on PR #13606 - without SQL code

[Initialize all fields in the constructor] requested by @jackpoz in PR 13606
Solution delivered by @NorthStrider in PR #14036
`_soulFragmentsSpawned = 0;`
Added indentations suggested by @Nyeriah to keep codestyle intact.

### CODE REVIEW

**Comment by Aokromes** [comment]
Failed — The Travis CI build failed

**Comment by tkrokli** [comment]
Yes, this commit is useless too. I wonder why my first PR worked, but as soon as I started changing things, it went to pieces. I have to rethink the whole PR.

**Comment by MitchesD** [comment]
/home/travis/build/TrinityCore/TrinityCore/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp:97:17: fatal error:

use of undeclared identifier 'sCreatureTextMgr'

sCreatureTextMgr->SendSound(me, SOUND_DEATH, CHAT_MSG_MO...

**Comment by tkrokli** [comment]
Ah yes, of course. It was because I removed the declaration lines Nyeriah asked me to remove.

**Comment by tkrokli** [comment]
Truth be told, I don't find myself good enough to handle this many code challenges right now. I feel a bit down too because one of my major inspirations for almost 2 years in the emulation community decided to quit for good and I feel left alone to pick up the pieces in his forum. It makes today just a little bit more gray and challenging. He was one of the main reasons I even joined the TrinityCore forum as a user.

**Comment by jackpoz** [comment]
creating a new PR each time kind of breaks the point of a PR, that should list discussion and progress in a single page

**Comment by tkrokli** [comment]
Yes, I know. And I am sorry for being such a novice. I have to wait until I become more mentally stable and also (I hope) until my previous PR is merged (whenever that may be). I'm such a mess right now.

**Pull request closed without merging**
