### PR TITLE
Core/Spells: Use BonusAmount for periodic damage

### LINKED ISSUE #13887: Spell infest ( lich king ) not work
hi all my friends
i think after add stack rules by Trisjdc spell infest does not work true
this spell after each hit must get stack
i think code for this spell true 

		void OnPeriodic(AuraEffect const* /*aurEff*/)
		{
			if (GetUnitOwner()->HealthAbovePct(90))
			{
				PreventDefaultAction();
				Remove(AURA_REMOVE_BY_ENEMY_SPELL);
			}
		}

		void OnUpdate(AuraEffect* aurEff)
		{
			// multiply, starting from 2nd tick
			if (aurEff->GetTickNumber() == 1)
				return;
			aurEff->SetAmount(int32(aurEff->GetAmount() * 1.15f));
		}

		void Register() override
		{
			OnEffectPeriodic += AuraEffectPeriodicFn(spell_the_lich_king_infest_AuraScript::OnPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
			OnEffectUpdatePeriodic += AuraEffectUpdatePeriodicFn(spell_the_lich_king_infest_AuraScript::OnUpdate, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
		} 

but not worked my rev : 1ed339547b575b87832c89194b426824bb16831e

Thank you for your efforts.

### PR DESCRIPTION
**Pull request by LuqJensen**
Closes #13887

### CODE REVIEW

**Comment by cemak** [comment]
/home/travis/build/TrinityCore/TrinityCore/src/server/scripts/Spells/spell_hunter.cpp:212:53: fatal error: 
      no member named 'GetDamage' in 'AuraEffect'
                                basePoint = aurEff->GetDamage();

**Comment by Unholychick** [comment]
yes, i forgot a couple of files

**Comment by Frytiks** [comment]
Should this fix aggro problems with druid spell like maul and lacerate

**Comment by ccrs** [comment]
@Unholychick is this finished?

**Comment by Unholychick** [comment]
@Frytiks no.
@ccrs yes.

**Pull request merged**
