### PR TITLE
Core/AI: Imp should not do any melee attack when OOM

### LINKED ISSUE #301: [3.3.5][Warlock] Core/Pet: Imp Should not melee attack when OOM
1.) Create a warlock
2.) Learn Summon Imp
3.) Have Imp Attack until Out of Mana

Observed Result: Imp runs up to target and begins physical attack (melee) on target
Expected Result: Imp should stay by your side, and wait for mana to regen, then continue casting Firebolts.

Version: 3.3.5a (12340)
Core revision: Trinity Core 11032+
Ubuntu 64
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/66427-warlock-imp-should-not-melee-attack-when-oom?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
by @trickerer; closes #301 (issue & code source)

Warlock imp should not engage in melee combat when Out Of Mana.
The changes in this PR stops the imp from advancing to melee range.

Before this change, the imp would move into melee range, step by step,
from the very first fireball it casts towards the target NPC.

### CODE REVIEW

**Comment by ccrs** [comment]
hack, I think

**Comment by Goatform** [comment]
If I remember good that fix didn't worked on my 3.3.5 core.

**Comment by robinsch** [comment]
Hack.

**Comment by tkrokli** [comment]
Well, if trickerer's code is a hack, then I'm surprised Shauren didn't say so in #301. Would have saved me some time. Do you have a suggestion for what should be done instead?

**Comment by robinsch** [comment]
Maybe read #301? As stated in the issue using CLASS_MAGE is not a valid fix.

**Comment by MitchesD** [comment]
@tkrokli who told you to delete this PR? Some external guys who aren't on TC? Maybe they could share their fixes from their private servers instead of criticising. I realize that this code isn't good, but closing PR only because some people who aren't part of TC said it, is bad idea. To be honest, I also don't like your PRs, because it looks like you have no idea what its about and also it looks like untested, but UNTILL someone from TC devs closes it, don't do it only because of that people.

I don't have anything against you guys, but you could share your fixes instead of only saying: "its bad"

**Comment by Goatform** [comment]
First of all @MitchesD, none told him to close PR and don't be arrogant. If you are TC dev don't act like you're better than them. Second, everyone have permission to say what he/she thinks about this PR, doesn't matter if they will share some fix or not.

**Comment by MitchesD** [comment]
No, I am not arrogant, never said that I am better than someone else, but he wants merge PR to TC, so it makes sense that he should be directed by someone who have permission for that. My goal is following: there are many guys who have some private server and just takes our fixes to theirs repo but dont give us any of their fixes, okey they can since its free to use, BUT they do criticise some things because they already fixed that on their private servers but didnt share it, I don't know if this PR is that case, but we have seen it already, and if it got merged, they had to overwrite their changes. I didn't say anything against someone there, I am talking in general, because @tkrokli closed all his PRs.

**Pull request closed without merging**
