### PR TITLE
[7.x]: Core/Scripts: ICC - Deathbound Ward.

### PR DESCRIPTION
**Pull request by ghost**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Delete Attack Start hack.
-  Add Set Data 1 1 for start waypoint (feature).
-  

**Target branch(es):** 3.3.5/master
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
https://github.com/TrinityCore/TrinityCore/issues/12691

**Tests performed:** (Does it build, tested in-game, etc.)
Tested in game - not crashing!
**Known issues and TODO list:** (add/remove lines as needed)

- [x] Need add waypoints in database.

[//]: # (**DEPRECATION NOTICE** Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE** If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

Remove Attack Start hack. After activate - should start waypoint.

### CODE REVIEW

**Comment by Ulduar** [comment]
You can use path from:
https://github.com/unified-db/Database/blob/master/Updates/423_instance_icecrown_citadel.sql

**Comment by Unknown-1000** [comment]
Yes, ward cannot start attack, no need search nearest target, this is useless. Fixed. Thanks.

**Comment by Unknown-1000** [comment]
@Keader what's wrong?

**Comment by Ulduar** [comment]
@Unknown-1000 
He wants everything to be in C ++.
He thinks that your request is not correct and needs to close. Just to tell himself it did not want.

**Comment by Keader** [comment]
WTF ?
Please dont talk for me... You dont know me...
Btw i was confused with sql part that Ulduar link... I cant see the point...

**Comment by Ulduar** [comment]
@Keader 
https://github.com/unified-db/Database/blob/master/Updates/423_instance_icecrown_citadel.sql#L38
This? You can convert for waypoints.

**Comment by Keader** [comment]
But If i remember right... This npcs dont have waypoints in retail...
They start attack everyone when trap is active

**Comment by Ulduar** [comment]
@Keader  proof?

**Comment by Keader** [comment]
i can record a video today :)

**Comment by Rushor** [comment]
thx!

**Comment by Rushor** [comment]
alright found a old video that indicates the waypoints https://youtu.be/LYlXnPfD5J0?t=21

**Comment by Keader** [comment]
https://youtu.be/4ZMxuMUss1U

you are right btw, they have waypoints xD

**Pull request closed without merging**
