### PR TITLE
CMake/FindBoost: Fix policy CMP0054 warning (added in 3.1)

### PR DESCRIPTION
**Pull request by ghost**
(cherry picked from commit 7e6dadf)

### CODE REVIEW

**Comment by Nyeriah** [comment]
I heard once upon a time we would just merge 335 into 434

**Comment by tkrokli** [comment]
I guess that was before they ran into all the problems with phasing issues.

**Comment by jackpoz** [comment]
does this apply to 335 or was it already applied to 335 ? if so, this pr will be rejected

**Comment by DDuarte** [comment]
Already in 3.3.5 and 6.x, our target branches.

**Pull request closed without merging**
