### PR TITLE
DB: Fix a DB error.

### PR DESCRIPTION
**Pull request by ghost**
Error correction, if wrong to cancel.

### CODE REVIEW

**Comment by MitchesD** [comment]
I don't see anything wrong, it's normal actionlist

**Comment by Killyana** [comment]
What's the DBerror?

**Comment by DevRival** [comment]
Why are we then use entryorguid = 2229300?

**Comment by Aokromes** [comment]
we don't edit existing sql files unless they can't be applied, also, we don't use pull requests for sql only fixes.

**Comment by MitchesD** [comment]
because it's actionlist? it means entry * 100

**Comment by DevRival** [comment]
Oh God, I did not see( excuse the stupidity(

**Pull request closed without merging**
