### PR TITLE
3 3 5

### PR DESCRIPTION
**Pull request by Kinkiller-Uchiha**

### CODE REVIEW

**Comment by DDuarte** [comment]
@Angel5224: this is the 3rd time you opened a bogus PR, today. I don't know what you are trying to do but please stop click the wrong buttons.

**Comment by tkrokli** [comment]
My first suspicion here is that he does not know how to fork the TC repository to his own repo and tries to populate it by pushing the files to his own repo instead. I don't understand where he picks the files to create these unnecessary Pull Requests, though.

**Comment by Angel5224** [comment]
apologize for my curiosity
the truth I am very new using GitHub and that was why I made these mistakes
I hope you have not causing anything bad
thousand apology sorry

**Comment by tkrokli** [comment]
Apology accepted. Just make sure that you read more about those settings before posting something that doesn't belong in the TrinityCore repository or issue tracker before you know what it does.

**Pull request closed without merging**
