### PR TITLE
Scripts/Spells: Hunter's Chimera Shot - Serpent damage

### PR DESCRIPTION
**Pull request by robinsch**
Hunter's Chimera Shot - Serpent (ID: 53353) damage should be increase by Improved Stings talent.

### CODE REVIEW

**Comment by LuqJensen** [comment]
source? it should get its scaling indirectly through the increase serpent sting receives

**Comment by Keader** [comment]
"Instantly deals 40% of the damage done by your Serpent Sting"
All other talents of all classes with similar mechanical increase the direct damage according to the damage of the DoT that are based

**Comment by LuqJensen** [comment]
Not sure how if i understand you correct Keader, but i suppose what youre saying is essentially the same as I do. Given serpent sting with damage 100, the calculation for the damage of chimera shot - serpent with improved stings talent is
``100*5*1.3*0.4``
Serpent stings duration is by default 15 sec and ticks once per 3 sec (does not scale with haste). 100 for the base (for this example) 15/3 = 5 ticks, + 30% from the improved stings talent and 40% of that...
What this commit appears to do is add another 30% to the direct damage.
``100*5*1.3*0.4*1.3`` 
which is not blizzlike. It would make chimera shot - serpent deal damage equivalent to 52% of serpent sting...

**Comment by Keader** [comment]
Nop, the calculation is just right after applying the fix.
Take a look at the issue, I think you can see my test there #14958

**Pull request merged**
