### PR TITLE
Core/PacketIO: Updated CMSG_DISMISS_CRITTER

### PR DESCRIPTION
**Pull request by Faq**
**Changes proposed:**

- based on cherry-pick 6fbfc61de1931f1e70aee80249535436e368c113

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
none

**Tests performed:** (Does it build, tested in-game, etc.)
Builds

### CODE REVIEW

**Comment by illfated** [comment]
Some of the files show the additional UNIX file mode change `100644 → 100755` ... is this intended, or a coincidental required update from GitHub to these files?

**Comment by Faq** [comment]
Thnx, not intended.

**Comment by illfated** [comment]
Good job. I was wondering why that single file with no changes appeared in the list, but that was due to the mode change. Happy to see it resolved. 👍

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
