### PR TITLE
Scripts/Outland: Quest 10911 "Fire at will"

### LINKED ISSUE #6828: [Quest] Fire at Will
The quest Fire at Will (http://old.wowhead.com/quest=10911) in Blade Edge Mountains is bugged.

How it should work :

Use the naturalised amunition to take control over a Fel Cannon to destroy south and north warp gate.

Use the Fel Cannon ability to attack the warp gate, the warp gate will be destroyed once you shot 7 times with your fel canon ability, in the meantime imps and hounds should be summoned out of the warp-gate.

How it does work :

You can take control of a Fel Cannon but it does not attack the warp gate when the skill is used, neither summons appears from the warp gate.

On rev : 7b5bdc2+ and TDB 11.47+

### PR DESCRIPTION
**Pull request by ghost**
Quest 10911 "Fire at will"

**Changes proposed:**

-  
-  
-  

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #6828

**Tests performed:**

Builds and works correctly

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Will need to add SAI to imps for Anti-Demon Flame Thrower Spell 39222
- [ ]

### CODE REVIEW

**Review by MaxtorCoder — CHANGES_REQUESTED** [review]
Not sure what I think off the SummonGameobject lines. Maybe someone else has a better idea.

**Review by mdX7 — COMMENTED** [review]
cool pr! :)

**Comment by malcrom** [comment]
I have no idea why this is failing test. It works fine on my system. Someone else can figure it out.

**Review by Seyden — CHANGES_REQUESTED** [review]

**Comment by jackpoz** [comment]
There are some comments from different people in this PR, please check them and reply to them

**Comment by jackpoz** [comment]
what happened to this PR ?

**Comment by CraftedRO** [comment]
maybe one day, Malcrom will resume work on this one

**Comment by Aokromes** [comment]
anyone can takeover this? or maybe it can be splited on pieces to push?

**Pull request closed without merging**
