### PR TITLE
[3.3.5] Core/Scripts: move npc_locksmith to DB/SAI 

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed**:

Move 9 lines of hardcoded text from the core script `npc_locksmith` to DB.
- remove npc_locksmith from npcs_special.cpp
- move the gossip handling to the database
- move conditions to the DB table `conditions`
- use the correct gossip text from broadcast_text
- remove options not existing in broadcast_text
- add Key to Searing Gorge option (related spell)
- add The Eye of Haramad option (related spell)

**Target branch(es)**: 3.3.5 (Keys + achievement "The Keymaster" removed in patch 4.0.3a / 4.2.0)

**Issues addressed**: Updates https://github.com/velinath/TrinityCore/issues/2

**Tests performed**: (Does it build, tested in-game, etc)

Builds OK in VS2013 Update 5, works as intended in-game. Tested on 2 characters like this:

```
.go creature 117456 || .go Pazik_"The_Pick"_Prylock
.go creature 202844 || .go Benik_Boltshear
.go creature 202845 || .go Walter_Soref

.quest add 5505 // Scholomance (A)
.quest complete 5505
.quest reward 5505 // reward: Skeleton Key
(and then destroy the key manually from the keyring)

.quest add 5511 // Scholomance (H)
.quest complete 5505
.quest reward 5505 // reward: Skeleton Key
(and then destroy the key manually from the keyring)

Quest: Scholomance (A)                 =  5505 (Skeleton Key)
Quest: Scholomance (H)                 =  5511 (Skeleton Key)
Quest: How To Break In To The Arcatraz = 10704 (Key to The Arcatraz)
Quest: Hotter Than Hell (A)            = 10758 (Key to The Shattered Halls)
Quest: Hotter Than Hell (H)            = 10764 (Key to The Shattered Halls)
Quest: At Last!                        =  3201 (Key to Searing Gorge)
Quest: Dark Iron Legacy                =  3802 (Shadowforge Key)
Quest: Return To Khagdar               =  9837 (Master's Key)
Quest: The Eye of Haramad              = 10982 (The Eye of Haramad)
Quest: Containment (Violet Hold)       = 13159 (The Violet Hold Key)
Quest: Eternal Vigilance (Druid quest) = 11011 (Essence-Infused Moonstone)
```

**Known issues and TODO list**:
- [X] Added `npcflag = 1` to NPC 29728 (Walter Soref in Undercity), because gossip was not available.
- [X] Removed the gossip options for the "Key to the Focusing Iris" / "Heroic Key to the Focusing Iris" because the only available `broadcast_text` in TDB 335.61 for those 2 items are:

```
Oh great Queen of the Dragons, I have somehow misplaced my Key to the Focusing Iris. Can you find it for me?
Oh great Queen of the Dragons, I have somehow misplaced my Heroic Key to the Focusing Iris. Can you find it for me?
```

I am pretty sure those texts are meant to be used only by `Alexstrasza the Life-Binder` and that she is the correct source for replacing a lost `Key to the Focusing Iris`. Maybe this needs source documentation.

If someone objects to the removal of those 2 options and the addition of the other 2 keys, I ask that one of the TC devs provides me with advice on which keys are to be kept in the script and which ones need to be removed. The added options are related lines from `broadcast_text` and can be looked up like this:

``` sql
SELECT * FROM `broadcast_text` WHERE `ID` BETWEEN 30314 AND 30321 OR `ID` in (20969,35500);
```

```
    ID  Language  MaleText                                                       FemaleText                                                     EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild
------  --------  -------------------------------------------------------------  -------------------------------------------------------------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  -------------
 30314         0  Hey $c, if you've lost a key I might be able to help you out.  Hey $c, if you've lost a key I might be able to help you out.         1         0         0            0            0            0        0       0       1          18019
 30315         0  I've lost my key to Scholomance.                               I've lost my key to Scholomance.                                      0         0         0            0            0            0        0       0       1          18019
 30316         0  I've lost my key to The Arcatraz.                              I've lost my key to The Arcatraz.                                     0         0         0            0            0            0        0       0       1          18019
 30317         0  I've lost my key to The Shattered Halls.                       I've lost my key to The Shattered Halls.                              0         0         0            0            0            0        0       0       1          18019
 30318         0  I've lost my key to Searing Gorge.                             I've lost my key to Searing Gorge.                                    0         0         0            0            0            0        0       0       1          18019
 30319         0  I've lost my Shadowforge Key.                                  I've lost my Shadowforge Key.                                         0         0         0            0            0            0        0       0       1          18019
 30320         0  I've lost The Eye of Haramad.                                  I've lost The Eye of Haramad.                                         0         0         0            0            0            0        0       0       1          18019
 30321         0  I've lost my key to Karazhan.                                  I've lost my key to Karazhan.                                         0         0         0            0            0            0        0       0       1          18019
 35500         0  I've lost my key to the Violet Hold.                           I've lost my key to the Violet Hold.                                  0         0         0            0            0            0        0       0       1          18019
 20969         0  I've lost my Essence-Infused Moonstone. Can you replace it?    I've lost my Essence-Infused Moonstone. Can you replace it?           0         0         0            0            0            0        0       0       1          18019
```

### CODE REVIEW

**Comment by tkrokli** [comment]
D'oh. Looks like Travis got a really big hiccup. 41x `fatal error: file '/usr/include/` (etc.)
Will try to fix it by synchronizing the PR again.

**Comment by tkrokli** [comment]
Suggestion: maybe add the label [3.3.5] because this content was removed in patch 4.0.3a / 4.2.0 ?

**Comment by Aokromes** [comment]
Any reason to don't merge this?

**Comment by tkrokli** [comment]
No objections from me, I was hoping for feedback from TC devs if they approve of the changes.
The changes should be well documented, but it would be nice to have some constructive criticism.

**Comment by tkrokli** [comment]
OK, now I have moved the entire script to DB & SAI. It should be easier to provide some feedback now.

**Comment by Aokromes** [comment]
/home/travis/build/TrinityCore/TrinityCore/src/server/scripts/World/npcs_special.cpp:2448:9: fatal error: 
      unknown type name 'npc_locksmith'
    new npc_locksmith();

**Comment by tkrokli** [comment]
Oh. Right. I forgot to remove the scriptname link at the bottom of the .cpp file. My bad. Fix incoming ASAP.

**Comment by tkrokli** [comment]
D'oh! Travis failed to start the build... Oh well. I will just restart it with a push refresh.

**Comment by tkrokli** [comment]
Travis does not seem to like me tonight...
```
--2016-05-31 19:58:59--  http://llvm.org/apt/llvm-snapshot.gpg.key
Resolving llvm.org (llvm.org)... 192.17.58.186
Connecting to llvm.org (llvm.org)|192.17.58.186|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-05-31 19:58:59 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

The command "wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -" failed and exited with 2 during .

Your build has been stopped.
```

**Pull request merged**
