### PR TITLE
Require Visual Studio 2019 16.4 or greater

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Requires Visual Studio 2019 16.4 or greater to avoid any VS 2017 compiler bug. Latest VS 2019 version at the time of writing is 16.4.5 (and everyone should update often)
- Add appveyor.yml with the AppVeyor configuration

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**
None

**Tests performed:**
I use latest version of Visual Studio as soon as it's released.

**Known issues and TODO list:** (add/remove lines as needed)
None

### CODE REVIEW

**Comment by jackpoz** [comment]
To Do: manually remove BOOST_ROOT env variable from online appveyor configuration

**Comment by Faq** [comment]
ref. #22779

**Comment by NoRRt** [comment]
Add New Ver Microsoft Visual Studio 2019 16.5.0 For Support the TrinityCore

**Comment by jackpoz** [comment]
> Add New Ver Microsoft Visual Studio 2019 16.5.0 For Support the TrinityCore

that's already supported

**Comment by NoRRt** [comment]
> > Add New Ver Microsoft Visual Studio 2019 16.5.0 For Support the TrinityCore
> 
> that's already supported

Support Branch Master

**Comment by Shauren** [comment]
> 
> 
> > > Add New Ver Microsoft Visual Studio 2019 16.5.0 For Support the TrinityCore
> > 
> > 
> > that's already supported
> 
> Update for Branch Master

It's already supported.

**Comment by illfated** [comment]
> To Do: manually remove BOOST_ROOT env variable from online appveyor configuration

cosmetic/formal, I know, but maybe add this to the TODO list in the main PR comment?

**Pull request merged**
