### PR TITLE
Core/Spells: Implement OnEffectAbsorbHeal and AfterEffectAbsorbHeal hooks

### PR DESCRIPTION
**Pull request by Nyr97**
We're missing proper implementation of basic absorb heal hooks for spellscripts. Credits to @Seyden for providing the base code for the implementation.

**Changes proposed:**

- Implement OnEffectAbsorbHeal aura hook.
- Implement AfterEffectAbsorbHeal aura hook.

**Issues addressed:**

None.

**Tests performed:**

It builds and it was tested in-game.

**Known issues and TODO list:** (add/remove lines as needed)

None.

### CODE REVIEW

**Comment by Ovahlord** [comment]
how about not just restricting this to heal but insead to all kinds of absorb?

**Comment by Nyr97** [comment]
there is an existent hook for absorb damage, I too thought it would be more efficient to add support to it for healing rather than splitting them, but I don't know the implications it would have and the final decision is @Shauren

**Comment by Seyden** [comment]
So like what? You both know that healing has HealInfo and Damage Absorb does have DamageInfo?

**Comment by Shauren** [comment]
ignore him

**Pull request merged**
