### PR TITLE
Scripts/Misc:Fix locale text not load from db.

### PR DESCRIPTION
**Pull request by leelf00**
**Changes proposed:**
Fix gossip option not load from db.
- [x] ZulAman
- [x] Quest Chasing the Moonstone (11194)
- [x] Quest Cairne's Hoofprint (925)
- [x] Magisters Terrace

  
updates https://github.com/TrinityCore/TrinityCore/issues/22696

**Tests performed:**

build and tested with zhTW client in game.

### CODE REVIEW

**Comment by Aokromes** [comment]
looks good to me.

**Comment by offl** [comment]
Pls migrate changes for npc_professions to separate PR

**Comment by leelf00** [comment]
ok,I will separate it

**Comment by leelf00** [comment]
updated

**Pull request merged**
