### PR TITLE
Core/PacketIO: Duel Opcodes

### PR DESCRIPTION
**Pull request by xerkoss**
no tabs anymore ;)

### CODE REVIEW

**Comment by VirusEntertainment** [comment]
great update :D

**Comment by Carbenium** [comment]
We can’t automatically merge this pull request.
Just remove the opcode value changes.

**Comment by xerkoss** [comment]
@Carbenium  remove opcodes values?  all to unhandled?

**Comment by Carbenium** [comment]
For now yes please. We'll activate them, when we're done with the WPP sync.

**Comment by Carbenium** [comment]
@xerkoss: Any news?

**Pull request closed without merging**
