### PR TITLE
Core/Structure for CMSG_SET_ACTIONBAR_TOGGLES and activate SMSG_MOVE_SET...

### LINKED ISSUE #14008: [6.x] fly speed problems
Rev. https://github.com/TrinityCore/TrinityCore/commit/68d026709b92197123a1b9ada71c30f4eda88073
Tested GM speeds and mount speeds, opcodes:
CMSG_MOVE_SET_FLY
CMSG_MOVE_CAN_FLY
spams errors
On grounf speed are working fine, but if try flying - speed is very slow, even GM commands doesnt helps. Only if teleporting in other location - then works only gm - speed

P.S Sorry for my bad English.

### PR DESCRIPTION
**Pull request by ProjectcoreDevs**
..._FLIGHT_SPEED

SMSG_MOVE_SET_FLIGHT_SPEED resolve #14008 

One problem with CMSG_SET_ACTIONBAR_TOGGLES.
It' save in the DB but for load it after disconnect, he don't load correcly (wrong field 58?)

### CODE REVIEW

**Comment by msoky** [comment]
i am waiting for this :)

**Comment by Naios** [comment]
:+1:

**Comment by DDuarte** [comment]
@ProjectcoreDevs: This looks okay however ActionBar should be called Mask: https://gist.github.com/DDuarte/61a11138e8a359d62159#file-structs_601_18179-cs-L10736

@xerkoss:

> “We are all born ignorant, but one must work hard to remain stupid.” 
― Benjamin Franklin

**Comment by Takenbacon** [comment]
The PLAYER_FIELD_BYTES offset needs to be changed to 1 to fix the actionbar loading.

**Comment by msoky** [comment]
any news?

**Pull request merged**
