### PR TITLE
Core/Defines: define faction templates and replace magic numbers from scripts

### PR DESCRIPTION
**Pull request by ForesterDev**
… scripts

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Tests performed:** (Does it build, tested in-game, etc.)

Build

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Comment by Keader** [comment]
Nice work

**Review by Shauren — APPROVED** [review]
seems legit

**Comment by ccrs** [comment]
any way to use ````sFactionTemplateStore```` on this?

**Comment by Shauren** [comment]
Why/how? These are ids exactly for sFactionTemplateStore

**Review by Keader — APPROVED** [review]

**Comment by ccrs** [comment]
thats why I asked, more like a thought than a suggestion

**Pull request merged**
