### PR TITLE
Core/ScriptedAI: skip STATE_ESCORT_NONE in EscortAI::JustAppeared()

### PR DESCRIPTION
**Pull request by tje3d**
**Target branch(es):** 3.3.5

**Issues addressed:** #21291 #21042 ( It may also solve some other issues )

Fixed one the problem listed in: #20310

### CODE REVIEW

**Comment by tkrokli** [comment]
Interesting solution as well as the simplicity of it.
Have you checked that nothing breaks because of this change?

**Comment by ccrs** [comment]
wrong, look at the related "discussion" in other issues, whats needed to be done is already known

**Comment by tje3d** [comment]
It works and didn't break anything else, so i count it as a good temporary fix

**Comment by tkrokli** [comment]
No, just wait until the weekend, need some more feedback first.

**Comment by tje3d** [comment]
closed e4e6e22

**Pull request closed without merging**
