### PR TITLE
Fix player extra flags not saved.

### PR DESCRIPTION
**Pull request by ryancheung**
**Changes proposed:**

Save player extra flags when saving player.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)

Player extra flags not saved after logout.

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by jackpoz** [comment]
what does this actually change ingame ?

**Comment by ryancheung** [comment]
Nothing ingame. I just fix the worldserver conf `GM.LoginState` option 2 (last save state) for GM characters.

**Comment by illfated** [comment]
Looks like you need to include commit https://github.com/TrinityCore/TrinityCore/commit/37ffdc05b23f079af3e22d7042f6ffe240e69cd5 in your PR branch to avoid the error (warning) message from AppVeyor.

**Comment by ccrs** [comment]
seems like a nice catch

**Comment by ryancheung** [comment]
Rebased latest 3.3.5 branch now.

**Comment by Shauren** [comment]
This is wrong. All of the functions called in the block of code under `GetSession()->HasPermission(rbac::RBAC_PERM_RESTORE_SAVED_GM_STATE)` modify m_ExtraFlags.

3.3.5 code:
Player constructor: Set m_ExtraFlags = 0;
DB extra_flags = 1
sWorld->getIntConfig(CONFIG_GM_LOGIN_STATE) = 2
LoadFromDB:  if (DB extra_flags & 1) SetGameMaster(true); // this modifies m_ExtraFlags
RESULT: m_ExtraFlags = 1 after db load, expected 1

Your version:
Player constructor: Set m_ExtraFlags = 0;
DB extra_flags = 1
sWorld->getIntConfig(CONFIG_GM_LOGIN_STATE) = 0 // meaning .gm off
LoadFromDB: config hits case 0, does nothing
RESULT: m_ExtraFlags = 1, expected 0

**Comment by ryancheung** [comment]
`m_ExtraFlags` would never get save to DB but it was loaded from DB on player login. Is it intentional?

**Comment by Shauren** [comment]
No, it is saved just fine. https://github.com/TrinityCore/TrinityCore/blob/37ffdc05b23f079af3e22d7042f6ffe240e69cd5/src/server/game/Entities/Player/Player.cpp#L19330

**Comment by ryancheung** [comment]
That should be the on character create save

**Comment by Shauren** [comment]
Well, wrong line, same code
https://github.com/TrinityCore/TrinityCore/blob/37ffdc05b23f079af3e22d7042f6ffe240e69cd5/src/server/game/Entities/Player/Player.cpp#L19455

**Comment by ryancheung** [comment]
I was confused by the (last save state) conf option yesterday. Sorry for the wrong PR.

**Comment by illfated** [comment]
Fair enough. That is a learning experience too.

**Pull request closed without merging**
