### PR TITLE
Fixed power consume Issue

### LINKED ISSUE #24315: Unlimited mana / rage / etc
**Description:**

Paladin has unlimited mana, mana not being diminished when using Flash Heal

**Current behavior:**

Created a new Blood Elf Paladin.  When using Flash Heal (on self or others), mana never gets used, and thus I can spam Flash Heal forever and not run out of mana

**Expected behavior:** Flash Heal uses mana, mana gets used and must be regenerated

**Steps to reproduce the problem:**  Use Flash Heal on yourself or others, will see that mana is unlimited

----------

**Branch(es):** master

**TC rev. hash/commit:**  569f1c9

**Operating System:** Windows 10

### PR DESCRIPTION
**Pull request by DuelistRag3**
**Changes proposed:**

-  Fixed power consume Issue
-  Powers will be used now
-  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [ x] master

**Issues addressed:** Closes #24315  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

Tested Building
Tested Ingame

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by dio85** [comment]
Calculation not full correct. But now use the powers...

**Comment by DuelistRag3** [comment]
At least it do it :D

**Comment by dio85** [comment]
:D i write this at 6 day ago, where need to fix and what, but nobody can read... :D

**Comment by DuelistRag3** [comment]
better make a pull request, reading all things on discord, can be hard tho

**Comment by dio85** [comment]
i hate make pr's always just flame all ppl.

**Comment by Shauren** [comment]
flaaaaaaaaaame

**Pull request merged**
