### PR TITLE
Core/Conditions: implement CONDITION_GAMEMASTER

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  implement CONDITION_GAMEMASTER - check if player is gamemaster or can be gamemaster

**Target branch(es):**

- [x] 3.3.5

**Tests performed:** build, tested in game

### CODE REVIEW

**Comment by IllInuz** [comment]
Looks promising.

**Comment by Shauren** [comment]
I don't question the implementation (its so simple) but what would the use cases for this be?

**Comment by ForesterDev** [comment]
@Shauren f.e. I want to use this in ICC for make posibility for GMs activate Lich King or Deathbringer encounters without completing previous. It's too tiring every time to kill all the bosses to start Lich King for tests.

**Comment by Aokromes** [comment]
iirc you can use set data with gm commands.

**Comment by ForesterDev** [comment]
@Aokromes , yes, but this is more simple way. And this can be used in other situations, f.e. to pass level, class restrictions, quest requirements for GMs

**Comment by Killyana** [comment]
How we are suppose to test level, class restrictions, quest requirements without a GM character?

**Comment by ForesterDev** [comment]
@Killyana just use .gm off or don't use this condition)

**Comment by Gooyeth** [comment]
> 
> 
> @Shauren f.e. I want to use this in ICC for make posibility for GMs activate Lich King or Deathbringer encounters without completing previous. It's too tiring every time to kill all the bosses to start Lich King for tests.

There is an RBAC for it: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Accounts/RBAC.h#L66

**Comment by jackpoz** [comment]
althought this might not be so useful, merging it anyway

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
