### PR TITLE
Fixed issue #17884: make broadcast_text_locale work.

### LINKED ISSUE #17884: hotfixes.broadcast_text_locale doesn't work
**Description**:
I added a entry in hotfixes.broadcast_text_locale but server still refer to the text in table hotfixes.broadcast_text for gossip_menu_option.

**Current behaviour**: Tell us what happens
server doesn't get the text from table hotfixes.broadcast_text_locale for gossip_menu_option.

**Expected behaviour**: Tell us what should happen instead
get the localized text from hotfixes.broadcast_text_locale for gossip_menu

**Steps to reproduce the problem**:

1. chat with any city guard.
2. 
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x

**TC hash/commit**:  
 59fe9087447dc58c3f41fb6f647bc2b50a95b9b5

**TDB version**:  
6.04

**Operating system**:  
Windows.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

### PR DESCRIPTION
**Pull request by Druson**
**Changes proposed:**
## 

**Target branch(es): 6.x

**Issues addressed:** Closes #17884

**Tests performed: yes, tested in game.

**Known issues and TODO list:**
- [none ] 
- [ ]

### CODE REVIEW

**Comment by Shauren** [comment]
This is just a bad workaround, locale data should be loaded through `DB2DatabaseLoader::LoadStrings`

**Comment by Druson** [comment]
@Shauren  I don't think this is a bad workaround. I have checked that ther is no locale data  loaded.  You may take a look at the table layout of hotfixes.broadcast_text, there is no locale column in the table now, the locale columns have been moved to table hotfixes.broadcast_text_locale.

**Comment by Shauren** [comment]
You are missing the point, all DB2 stores should load their locale data with the code already in place
Loaded from here https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/DataStores/DB2Stores.cpp#L263

**Comment by Druson** [comment]
@Shauren Checked the code in DB2Stores.cpp,  seems the bug is in https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/DataStores/DB2Stores.cpp#L256

I changed "defaultLocale == i" to "DEFAULT_LOCALE == i", and it works now.

**Pull request closed without merging**
