### PR TITLE
Core/DB: Valley of Trials quest fixes

### PR DESCRIPTION
**Pull request by Taaboy**
**Changes proposed:**
To Fix quest starters and enders for Valley of Trials Start (Orc) and Quest Chain Follow order to retail version.
Fix Durotar.cpp to remove obselete quest from script and added new quest for Lazy Peon 37446
http://www.wowhead.com/quest=37446/lazy-peons

**Target branch(es):** 
master

**Issues addressed:**

**Tests performed:** 
Yes Compiles and tested in game

**Known issues and TODO list:**

### CODE REVIEW

**Comment by Aokromes** [comment]
if all the c++ changes is the quest id, plz open a ticket with the sql fixes.

**Comment by Taaboy** [comment]
The changes for sql are there above the script fix, really this sucks did all requested from the guide with sql and cpp fix so it would be easy push and now i have to go thru another ticket process. which i will do , but not bothering with future fixs i have 5 more zones and quest chains. Let others do it now.
@Taaboy	Fix Valley of Trial Quest Chains and Quest to Retail			4147f98

**Comment by Shauren** [comment]
@Taaboy Please look carefully on the diff you submitted on github - the entire file is marked as changed (you fucked up and commited it with windows line endings)

**Comment by Taaboy** [comment]
Thank you Shauren ,, Thats all i need to know i fucked up, tell me where and i will fix it next time . If i am not told that it was fucked up how was i to know. First time Pull Request was putting it off for 3 months now. So do compare on the file and only submit the diff , Now i know.  window line ending that i don't know and may need to be shown where to read about it , or short explanation .

**Comment by Shauren** [comment]
Google for `core.autocrlf`

**Pull request closed without merging**
