### PR TITLE
Scripts/Quest: Fix Kindness (#27688)

### LINKED ISSUE #27688: Core/GameObject: Mature Netherwing Drake
### Description

**After feeding. The dragon doesn't fly away. And there is no dialog box (Belan shi karkun).**

WoWScrnShot_013022_014335

### Expected behaviour

https://www.youtube.com/watch?v=MY1yU4fDNkk

### Steps to reproduce the problem

**Location**
Netherwing Fields in [Shadowmoon Valley](https://tbc.wowhead.com/outland-shadowmoon-valley)
 `X: -4049.340576 Y: 721.523254 Z: 1.619745 Map: 530 (Outland) Area: 3758 (Netherwing Fields) Zone: Shadowmoon Valley`

**Faction Netherwing**
[faction=1015](https://tbc.wowhead.com/faction=1015/netherwing)

**First quest**
[quest=10804](https://tbc.wowhead.com/quest=10804/kindness)

**NPC quest**
[npc=22113](https://tbc.wowhead.com/npc=22113/mordenai)

**NPC drake**
[npc=21648](https://tbc.wowhead.com/npc=21648/mature-netherwing-drake)

**Item quest**
[item=31372](https://tbc.wowhead.com/item=31372/rocknail-flayer-carcass)

**src/server/scripts/Outland/zone_shadowmoon_valley.cpp**

[View git blame](https://github.com/TrinityCore/TrinityCore/blame/50178650b2d1c123c40aa4d7ed3ecf3d7fefa00d/src/server/scripts/Outland/zone_shadowmoon_valley.cpp#L199)

### Branch

3.3.5

### TC rev. hash/commit

4c2986c6b16fac13554d8eb290caa28e863c8361

### Operating system

Ubuntu 20.04.3 LTS

### Custom changes

None

### PR DESCRIPTION
**Pull request by anzz1**
**Changes proposed:**

-  Fix Quest 'Kindness' (quest id [10804](https://wotlkdb.com/?quest=10804))
-  Fix NPC 'Mature Netherwing Drake' (npc id [21648](https://wotlkdb.com/?npc=21648))
-  Remove npc script from 21648, reimplement script in SAI

**Issues addressed:**

Closes #27688

**Tests performed:**

Builds, tested in-game. I used the TBC Classic video from the issue #27688 as a reference and the current implementation looks spot on and true to the original.

**Known issues and TODO list:**

- [ ] Drake chooses the closest carcass, which is not necessarily the same that player has set on ground if an uneaten but not yet despawned carcass happens to be closer (edge case)
- [ ] [Has Eaten Recently](https://wotlkdb.com/?spell=38502) gets reset when the creature does, so the current implementation is setting it again on reset in a certain event phase (2 or 4). This SQL line can be removed if a better implementation can be figured out, like disallowing the debuff be removed on creature reset.
```sql
(21648, 0, 6, 0, 25, 10, 100, 0, 0, 0, 0, 0, 0, 11, 38502, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mature Netherwing Drake - On Reset - Cast \'Has Eaten Recently\' (Phase 2 & 4)'),
```
- [ ] [Netherbreath](https://wotlkdb.com/?spell=38467) values are taken from old script, it means casting every 5 secs with 100% chance in combat, this might not be right.
- [ ] [Intangible Presence](https://wotlkdb.com/?spell=36513) should also be used by Mature Netherwing Drake, but is missing.
- [x] If you start combat with the drake while the OOC script (timed action list) is running, it will pause execution but continue after combat ends. This means that it will give the quest credit and say 'Belan shi karkun' from air if you engaged it before it talked. 

Note: This needs PR #27733 to be applied to work correctly.

### CODE REVIEW

**Comment by anzz1** [comment]
I'm leaving my "notes" here for posterity from when I first tried to fix this by editing the original script but it ending up ugly and decided to rewrite this in SAI:
<details markdown=1><summary markdown="span">Old mess</summary>

```cpp
/*#####
# npc_mature_netherwing_drake
#####*/

enum MatureNetherwing
{
    SAY_JUST_EATEN              = 0,

    SPELL_PLACE_CARCASS         = 38439,
    SPELL_JUST_EATEN            = 38502,
    SPELL_NETHER_BREATH         = 38467,
    POINT_EAT_ID                = 1,

    GO_CARCASS                  = 185155,

    QUEST_KINDNESS              = 10804,
    NPC_EVENT_PINGER            = 22131
    // drake npcid = 21648
    // carcass itemid = 31372
};

class npc_mature_netherwing_drake : public CreatureScript
{
public:
    npc_mature_netherwing_drake() : CreatureScript("npc_mature_netherwing_drake") { }

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_mature_netherwing_drakeAI(creature);
    }

    struct npc_mature_netherwing_drakeAI : public ScriptedAI
    {
        npc_mature_netherwing_drakeAI(Creature* creature) : ScriptedAI(creature)
        {
            Initialize();
        }

        void Initialize()
        {
            uiPlayerGUID.Clear();

            bCanEat = false;
            bIsEating = false;
            bEatAnimPlayed = false;
            bDelayedReset = false;
            bTakeoff = false;

            EatTimer = 5000;
            CastTimer = 5000;
            ResetTimer = 7000;

            me->SetCanFly(true);
            me->SetDisableGravity(true);

            me->GetMotionMaster()->Clear();
            me->GetMotionMaster()->InitializeDefault();

            //if (me->GetMotionMaster()->GetCurrentMovementGenerator(MOTION_SLOT_DEFAULT)->HasFlag(MOVEMENTGENERATOR_FLAG_PAUSED)) {
            //    me->GetMotionMaster()->GetCurrentMovementGenerator(MOTION_SLOT_DEFAULT)->Resume(0);
            //    printf("resume\n");
            //}
        }

        ObjectGuid uiPlayerGUID;

        bool bCanEat;
        bool bIsEating;
        bool bEatAnimPlayed;
        bool bDelayedReset;
        bool bTakeoff;

        uint32 EatTimer;
        uint32 CastTimer;
        uint32 ResetTimer;

        Position currentNode;

        void Reset() override
        {
            printf("reset\n");
            Initialize();
        }

        void SpellHit(WorldObject* caster, SpellInfo const* spellInfo) override
        {
            if (bCanEat || bIsEating)
                return;

            if (caster->GetTypeId() == TYPEID_PLAYER && spellInfo->Id == SPELL_PLACE_CARCASS && !me->HasAura(SPELL_JUST_EATEN))
            {
                uiPlayerGUID = caster->GetGUID();
                bCanEat = true;
            }
        }

        void MovementInform(uint32 type, uint32 id) override
        {
            if (type != POINT_MOTION_TYPE)
                return;

            if (id == POINT_EAT_ID)
            {
                printf("eat reached\n");
                bIsEating = true;
                bEatAnimPlayed = false;
                bDelayedReset = true;
                ResetTimer = 7000;
                EatTimer = 7000;
                //Position pos;
                //pos.Relocate(me);
                //pos.m_positionZ += 50.0f;
                //me->SetHomePosition(pos);
                //me->SetCanFly(true);
                //me->SetDisableGravity(true);
            }
        }

        void EnterEvadeMode(EvadeReason why) override
        {
            if (!_EnterEvadeMode(why))
                return;

            TC_LOG_DEBUG("scripts.ai", "npc_mature_netherwing_drakeAI::EnterEvadeMode: entering evade mode (why: %u) (%s)", why, me->GetGUID().ToString().c_str());

            me->SetCanFly(true);
            me->SetDisableGravity(true);
            bDelayedReset = true;
            bTakeoff = false;
            ResetTimer = 5000;
        }

        void UpdateAI(uint32 diff) override
        {
            if (UpdateVictim())
            {
                if (CastTimer <= diff)
                {
                    DoCastVictim(SPELL_NETHER_BREATH);
                    CastTimer = 5000;
                }
                else
                    CastTimer -= diff;

                DoMeleeAttackIfReady();
                bIsEating = false;
                bCanEat = false;
            }
            else
            {
                if (bCanEat || bIsEating)
                {
                    if (EatTimer <= diff)
                    {
                        if (bCanEat && !bIsEating)
                        {
                            if (Unit* unit = ObjectAccessor::GetUnit(*me, uiPlayerGUID))
                            {
                                if (GameObject* go = unit->FindNearestGameObject(GO_CARCASS, 10))
                                {
                                    //me->GetMotionMaster()->MoveIdle();
                                    //me->StopMoving();
                                    me->GetMotionMaster()->GetCurrentMovementGenerator(MOTION_SLOT_DEFAULT)->Pause(0);
                                    me->SetCanFly(true);
                                    me->SetDisableGravity(true);
                                    me->GetMotionMaster()->MovePoint(POINT_EAT_ID, go->GetPositionX(), go->GetPositionY(), go->GetPositionZ());
                                }
                            }
                            bCanEat = false;
                        }
                        else if (bIsEating)
                        {
                            if (GameObject* go = me->FindNearestGameObject(GO_CARCASS, 10))
                                go->Delete();

                            if (Player* player = ObjectAccessor::GetPlayer(*me, uiPlayerGUID))
                            {
                                player->KilledMonsterCredit(NPC_EVENT_PINGER);
                                me->SetFacingToObject(player);
                            }
                            DoCast(me, SPELL_JUST_EATEN);
                            Talk(SAY_JUST_EATEN);

                            bIsEating = false;
                            bTakeoff = false;

                            //me->SetCanFly(true);
                            //me->SetDisableGravity(true);

                            //me->SetCanFly(true);
                            //me->SetDisableGravity(true);
                            //me->GetMotionMaster()->Clear();
                            //me->GetMotionMaster()->MovePoint(POINT_RESET_ID, currentNode[0], currentNode[1], currentNode[2]);
                        }
                    }
                    else
                    {
                        if (bIsEating && !bEatAnimPlayed && EatTimer <= 6000)
                        {
                            me->HandleEmoteCommand(EMOTE_ONESHOT_ATTACK_UNARMED);
                            bEatAnimPlayed = true;
                        }
                        EatTimer -= diff;
                    }
                }
                else if(bDelayedReset)
                {
                    if (ResetTimer <= diff)
                    {
                        Reset();
                    }
                    else
                    {
                        if (!bTakeoff && ResetTimer <= 4000)
                        {
                            Position pos;
                            pos.Relocate(me);
                            pos.m_positionZ += 1.0f;
                            pos.m_positionX += cos(pos.GetOrientation()) * 1.001f;
                            pos.m_positionY += sin(pos.GetOrientation()) * 1.001f;
                            me->SetCanFly(true);
                            me->SetDisableGravity(true);
                            me->GetMotionMaster()->MoveTakeoff(0, pos);
                            bTakeoff = true;
                        }
                        ResetTimer -= diff;
                    }
                }
            }
        }
    };
};
```
</details>

**Comment by anzz1** [comment]
To the TODO point "If you start combat ...":  

I don't know whether it's possible to "cancel" a timed action list, I guess it could be overridden with a dummy script but that doesn't seem "clean", what do you think? In SmartScriptMgr.h at definition of `SMART_ACTION_CALL_TIMED_ACTIONLIST` there was an old comment which specified a "stop after combat 0/1" parameter but that does not exist (anymore?).

**Comment by offl** [comment]
>I don't know whether it's possible to cancel a timed action list, I guess it could be overridden with a dummy script but that doesn't seem "clean", what do you think?

Yes, it's not "clean"

>In SmartScriptMgr.h at definition of SMART_ACTION_CALL_TIMED_ACTIONLIST there was an old comment which specified a "stop after combat 0/1" parameter but that does not exist (anymore?).

It probably never existed

>Currently you can specify it to run only OOC, but then it continues from where it was left after the combat is over (and evade is over, creature reached home).

It shouldn't?

**Comment by anzz1** [comment]
> It shouldn't?  

Well I think the script should stop (not pause) execution on combat. I mean intuitively if you attack the creature while feeding it, it should not thank you after killing you. :smile: 

Then again I don't know whether stopping or continuing the script after combat is the right blizzlike behaviour. I only had that video to go by when implementing this. Maybe someone with a TBC PTR sub could go and check against live?

**Comment by offl** [comment]
They may not expect that and can't support everything because their scripting system has limitations

**Comment by Alastro-Kraken** [comment]
The current implementation of removing buffs/debuffs on evade is wrong, at least for normal NPCs and regarding buffs. Example, if you're a priest and buff a town guard or a NPC you're escorting, it shouldn't lose all the buffs once it evades.

About debuffs, I couldn't manage to get a NPC to evade while it had a debuff cast from me - it kept attacking me regardless of how far I got from the spawn point even with a non-damaging debuff like Faerie Fire. But when I debuff a mob and it kills me, it loses all the debuffs I cast (DoT and not).

**Comment by anzz1** [comment]
Maybe only auras with `AURA_INTERRUPT_FLAG_LEAVE_COMBAT` 0x80000000 should be removed?  

Or all 'negative' auras? There seems to be a lot of different things related to whether an aura is "negative" or "harmful",  

SpellCustomAttributes has `SPELL_ATTR0_CU_NEGATIVE` (SPELL_ATTR0_CU_NEGATIVE_EFF0 | SPELL_ATTR0_CU_NEGATIVE_EFF1 | SPELL_ATTR0_CU_NEGATIVE_EFF2)  

AURA_FLAGS has `AFLAG_POSITIVE` 0x10 but also `AFLAG_NEGATIVE` 0x80  

And maybe even more that I missed.

**Comment by offl** [comment]
Forgot to leave the link https://github.com/TrinityCore/TrinityCore/issues/23890#issuecomment-1030850811
Pls copy https://github.com/TrinityCore/TrinityCore/pull/27735#issuecomment-1030915502 there

**Pull request closed without merging**
