### PR TITLE
CMake: Prepare for target_precompile_headers

### PR DESCRIPTION
**Pull request by Carbenium**
**Changes proposed:**

-  Cleanup CMake policies
-  Use target_precompile_headers instead of cotire with CMake >= 3.16.0

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Tests performed:** compile

### CODE REVIEW

**Comment by Shauren** [comment]
CMP0043 can be set to NEW when not using cotire

**Comment by jackpoz** [comment]
335 has https://github.com/TrinityCore/TrinityCore/commit/18cc36bc67023dc9ca58e77733c2b8c74655cf86 so maybe cherry-pick that and have this PR focus only on pch ?

**Comment by jackpoz** [comment]
Just for info the only CI that has CMake >= 3.16 for master branch is AppVeyor (3.3.5 has Circle CI with CMake >= 3.16 too)

**Comment by jackpoz** [comment]
@Carbenium would you like to cherry-pick this to 335 ?

**Pull request merged**
