### PR TITLE
Core/Spells: Implemented personal summons (#19231)

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  cherry pick commit b7bb5e6a98119512702519adecf559ecedc20743

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

None

**Tests performed:**

None

**Known issues and TODO list:** (add/remove lines as needed)

- Let CI check the build

### CODE REVIEW

**Comment by jackpoz** [comment]
@Treeston could you compare https://github.com/TrinityCore/TrinityCore/commit/b7bb5e6a98119512702519adecf559ecedc20743#diff-0e95a31f2d0f9af5b93027cf1c8eddd47d5678cf344be4eecdc54df3ef410700 with https://github.com/TrinityCore/TrinityCore/pull/25765/files#diff-0e95a31f2d0f9af5b93027cf1c8eddd47d5678cf344be4eecdc54df3ef410700 and see if I ported the changes correctly for ThreatManager ?

It doesn't have to be the best solution etc, I just need to know if it's a similar place as the original author. If the code needs improvements, it could be improved in another PR (as this is supposed to only be a cherry-pick with the least amount of changes to allow any improvements to be ported back to master branch too)

**Comment by Treeston** [comment]
Taking a look. Do I understand the check correctly - if the threatening unit is a tempsummon that is only visible to its summoner, unless the threatened unit is also a tempsummon that is only visible to that same summoner, it redirects all threat to that summoner instead?

**Comment by Treeston** [comment]
Move that entire check further up, just before/after the vehicle check that starts on line 315. Use the same logic it uses if the check passes.

**Comment by Treeston** [comment]
(You can't really keep the original structure from `master`, it abuses redirect logic which wouldn't work in `3.3.5`, our redirect system is different because it supports multiple redirections.)

**Comment by jackpoz** [comment]
I moved the code above and copied the behavior of Vehicle with setting the threat to 0 after redirecting it. Please let me know if now it's ok

**Comment by Treeston** [comment]
Looks reasonable as a cherry pick.

(I have my doubts whether it is _correct_ in its behavior, though.)

**Comment by funjoker** [comment]
There are probably small tweaks which can be adjusted in future. It’s basic support.

**Comment by jackpoz** [comment]
And it works:
image

**Comment by Treeston** [comment]
Neat.

**Comment by jackpoz** [comment]
PvP doesn't seem to work that good as the summon killed an enemy player with the enemey player being clueless
image

**Comment by Treeston** [comment]
That was kind of what I was alluding to above. All the current threat logic is doing is preventing the summon from threatening other units.

I think this should go in one of the CanEnterCombat (or whatever it's called, it's the big static check function on combatmanager). Actual behavior would need to be determined (it should be (I guess?) able to fight creatures, but not other players?)

**Comment by jackpoz** [comment]
I think it should fit in WorldObject::CanSeeOrDetect() even, the personal summon should never target an enemy player.

**Comment by Treeston** [comment]
That sounds reasonable, yes.

**Pull request merged**
