### PR TITLE
Scripts/ICC: Lord Marrowgar - Coldflame Resistance

### PR DESCRIPTION
**Pull request by Demonid**
**Changes proposed:**

-  Fix Resistance for Coldflame

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes https://github.com/TrinityCore/TrinityCore/issues/13240

### CODE REVIEW

**Comment by Keader** [comment]
Sources? i'm not sure if issue is valid.

**Comment by offl** [comment]
> The second ability is an ability called Cold Flame. Lord Marrowgar will shoot out the Cold Flame against a target and the Cold Flame will go in a straight line until gone. If you stand in the fire you take 6000 frost damage every second for three seconds. The Cold Flame will start at Lord Marrowgar and go towards it’s target, so melee need to be careful with the flame as it may start right on them even if it’s going for another target. **It’s adviced to use Frost Resistance Aura or Frost Resistance Totem**. 

[Source](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/273775-icecrown-citadel-instance-tactics-explanation-etc-questions-allowed.html). But i'm not sure if it is a good source.

**Comment by Demonid** [comment]
In this guide from 2009 from Tankspot: the video says that is a good idea to run frost resistance:

https://www.youtube.com/watch?v=RSbBt9NHsXE&feature=youtu.be&t=1m54s

In this other video from 2009, you can see the tank getting hit multiple times from Coldflame on MSBT, it clearly shows part of the damage being resisted.

https://www.youtube.com/watch?v=YUlvH8n_Zwg

**Comment by Shauren** [comment]
Yep, definitely getting resited there on these videos

**Pull request merged**
