### PR TITLE
Game/SmartScripts: SMART_EVENT_POWER_PCT + SMART_EVENT_TARGET_POWER_PCT

### LINKED ISSUE #14788: Request - New SMART_EVENT_ENERGY_PCT.
https://github.com/TrinityCore/TrinityCore/commit/cc3ddf23cef54aea652ba45acf8f24c2fbd517d1
Add new event. One example: http://www.wowhead.com/npc=57159/earthen-soldier#abilities
And abilities:
http://www.wowhead.com/spell=107872/twilight-rage
If Has 100 Energy - should cast buff on self Twilight rage and reset full energy.
Maybe Pandaria and Draenor npc also need event.

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
AUTOR: @robinsch
closes #14788

### CODE REVIEW

**Comment by Rushor** [comment]
kay tested this for:

```sql
-- Razormane Thornweaver SAI
SET @ENTRY := 3268;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,80,1,0,0,4000,4000,11,6950,0,0,0,0,0,2,0,0,0,0,0,0,0,"Razormane Thornweaver - In Combat - Cast 'Faerie Fire' (No Repeat)"),
(@ENTRY,0,1,0,4,0,100,1,0,0,0,0,11,467,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormane Thornweaver - On Aggro - Cast 'Thorns' (No Repeat)"),
(@ENTRY,0,2,0,3,0,100,0,0,80,0,0,51,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Razormane Thornweaver - Between 0-80% Mana - Kill Target");

-- Gymer SAI
SET @ENTRY := 29884;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,27,0,100,1,0,0,0,0,1,8,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - On Passenger Boarded - Say Line 8 (No Repeat)"),
(@ENTRY,0,1,0,61,0,100,0,0,0,0,0,1,9,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - On Passenger Boarded - Say Line 9 (No Repeat)"),
(@ENTRY,0,2,0,28,0,100,1,0,0,0,0,1,10,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - On Passenger Removed - Say Line 10 (No Repeat)"),
(@ENTRY,0,3,0,54,0,100,1,0,0,0,0,11,55461,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - On Just Summoned - Cast 'Storm's Fury' (No Repeat)"),
(@ENTRY,0,4,0,54,0,100,0,0,0,0,0,8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - On Just Summoned - Set Reactstate Passive"),
(@ENTRY,0,5,0,54,0,100,0,0,0,0,0,44,256,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - On Just Summoned - Set Phase 256"),
(@ENTRY,0,6,0,73,0,100,0,0,0,0,0,11,46598,0,0,0,0,0,7,0,0,0,0,0,0,0,"Gymer - On Spellclick - Cast 'Ride Vehicle Hardcoded'"),
(@ENTRY,0,7,0,0,0,100,0,6000,10000,6000,10000,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - In Combat - Say Line 1"),
(@ENTRY,0,8,0,3,0,100,0,0,80,0,0,51,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gymer - Between 0-80% Mana - Kill Target");
```

deathaction works for Razormane Thornweaver, but not for Gymer, maybe vehiclerelated issue?

**Comment by DDuarte** [comment]
"deathaction works for Razormane Thornweaver" seems unrelated to this PR. Can I merge this?

**Comment by Rushor** [comment]
no i only tested the Action (51) while using the Eventtype (3).
The result was that it works for creatures like 'Razormane Thornweaver' which are using mana, but it's not working for creatures like 'Gymer' which are using energy.

Also i couldn't found any creature in the world which generates rage to test the eventtype which sourcetype rage

**Comment by Rushor** [comment]
so eee just tested this with a engergy creature:

```sql
-- Jotunheim Rapid-Fire Harpoon SAI
SET @ENTRY := 30337;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,3,0,100,0,100,100,5000,5000,44,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jotunheim Rapid-Fire Harpoon - Between 100-100% Mana - Set Phase 2");
```

no change at all with this script - dunno what i'm doing wrong

**Comment by jackpoz** [comment]
If I apply the patch, execute the SQL script and use http://www.wowhead.com/npc=30337/jotunheim-rapid-fire-harpoon it ejects me after a few seconds and it disappears.
This is the callstack:
>>	worldserver.exe!Unit::SetPhaseMask(unsigned int newPhaseMask, bool update) Line 16434	C++
 	worldserver.exe!SmartScript::ProcessAction(SmartScriptHolder & e, Unit * unit, unsigned int var0, unsigned int var1, bool bvar, const SpellInfo * spell, GameObject * gob) Line 1059	C++
 	worldserver.exe!SmartScript::ProcessTimedAction(SmartScriptHolder & e, const unsigned int & min, const unsigned int & max, Unit * unit, unsigned int var0, unsigned int var1, bool bvar, const SpellInfo * spell, GameObject * gob) Line 2328	C++
 	worldserver.exe!SmartScript::ProcessEvent(SmartScriptHolder & e, Unit * unit, unsigned int var0, unsigned int var1, bool bvar, const SpellInfo * spell, GameObject * gob) Line 2786	C++
 	worldserver.exe!SmartScript::UpdateTimer(SmartScriptHolder & e, const unsigned int diff) Line 3347	C++
 	worldserver.exe!SmartScript::OnUpdate(const unsigned int diff) Line 3392	C++
 	worldserver.exe!SmartAI::UpdateAI(unsigned int diff) Line 328	C++
 	worldserver.exe!Creature::Update(unsigned int diff) Line 582	C++


Does this mean this PR works fine and it can be merged ?

**Comment by tkrokli** [comment]
jackpoz commented 2015-11-22, 15:01 CET:
> Does this mean this PR works fine and it can be merged ?

I would not think so when looking at your call stack, but then again, maybe your question is rhetorical?

**Comment by jackpoz** [comment]
I'm not sure what Rushor expected as result, we'll wait for him to reply

**Comment by MitchesD** [comment]
@Rushor: any news?

**Comment by Rushor** [comment]
hmm i didn't recognised the message 16 days ago, i will try the script with some other creates

**Comment by jackpoz** [comment]
any update about this pr ? is it working correctly ?

**Comment by jackpoz** [comment]
still no feedback since the 22nd November

**Comment by tkrokli** [comment]
... or 8th December, if you count the quick reply about going to try the script with some other creatures.

**Comment by jackpoz** [comment]
Please ask a TrinityCore member to reopen this Pull Request once you provide the requested feedback. There is no need to open a new Pull Request with the same changes.

**Comment by Rushor** [comment]
thx :)

**Pull request closed without merging**
