### PR TITLE
Script/ScarletEnclave: Eye of acherus now rooted at spawn

### LINKED ISSUE #24272: Creature/Movement: Eye of acherus initial root
**Description:** When Eye of Acherus (the vehicle) spawn it get the aura https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51860 it must root it, but for some reason the player is still able to move the vehicle until the wp start.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L440

This issue is not related to the recent charm commit as I reverted it and I reproduced the issue.
.list aura show the vehicle has spell=51860

**Steps to reproduce the problem:**

1. .quest add 12641
2. .go c id 25462
3. click the gob to summon the eye
4. move the eye

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 49e77d7c9e4c

### PR DESCRIPTION
**Pull request by Faq**
**Changes proposed:**

-  With JustAppeared() didnt work, long live InitializeAI().

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #24272 

**Tests performed:** (Does it build, tested in-game, etc.)
compiles,event works like it should.

### CODE REVIEW

**Comment by jackpoz** [comment]
what about Reset() ? what about InitializeAI() ? which ones did you try ?

as a rule of thumb, the AI constructor but used ONLY to initialize local class member fields.

**Comment by Faq** [comment]
Retested, and ye works, thnx.

**Comment by Ovahlord** [comment]
This is weird because it makes no sense to cast it on AI initialization unless there is another fucked up function that resets movement flags on adding a creature to world

**Comment by jackpoz** [comment]
@Ovahlord do you want to investigate the "makes no sense" part or should I just merge the PR ?

**Comment by Ovahlord** [comment]
@Faq can you do me a favor and do a .list aura  on the eye whithout this PR when you should be rooted?

**Comment by Faq** [comment]
Sure:
```
Target unit has 2 auras:
id: 51860 [Root Self] effmask: 1 charges: 0 stack: 1 slot 1 duration: 5078 maxduration: 10000   caster: creature guid: 1756
id: 51892 [Eye of Acherus Visual] effmask: 1 charges: 0 stack: 1 slot 0 duration: -1 maxduration: -1   caster: creature guid: 1756
Target unit has 1 auras of type 4:
id: 51892 eff: 0 amount: 0
Target unit has 1 auras of type 26:
id: 51860 eff: 0 amount: 0
```

**Comment by jackpoz** [comment]
@Ovahlord anything else to check ?

**Comment by jackpoz** [comment]
Merging this. @Ovahlord you can continue your investigation when you find the time to do it.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
