### PR TITLE
[3.3.5] Core/Logs: English text corrections

### PR DESCRIPTION
**Pull request by ghost**
This is an attempt to proofread standard error messages and system messages
from both core and DB. The corrections span typos, grammar and punctuation.

Because some of these messages can have multiple meanings depending on context,
this PR will stay in "WIP" status until the corrections have been validated and approved.

You are welcome to suggest improvements and files not yet included in this list.

Thanks to @Kinzcool for suggesting this line of work. :)

---

Update: removed the SQL changes after jackpoz' request in https://github.com/TrinityCore/TrinityCore/pull/16038#issuecomment-170291767

### CODE REVIEW

**Comment by tkrokli** [comment]
If you want me to post a link to a diff page with the contents in `trinity_string` compared from before and after the SQL is used, feel free to suggest a recommended page or site with a diff tool with options to save the diff for at least as long as this PR will stay open.

**Comment by jackpoz** [comment]
is this the result of some kind of tool or manual work ?

**Comment by ShinDarth** [comment]
great idea

**Comment by tkrokli** [comment]
@jackpoz : it is pure manual labor, I just used my English knowledge/skills. @ShinDarth : thanks. :)

**Comment by mthsena** [comment]
Would nice a cleanup like this in the ```world.commands.help```

**Comment by tkrokli** [comment]
OK, good suggestion. I presume you are talking about the result from this SQL query:
```sql
SELECT * FROM `command` ORDER BY `permission`;
```

**Comment by Keader** [comment]
nice work Tk :+1:

**Comment by ShinDarth** [comment]
@tkrokli any news with this?

**Comment by Ascathor** [comment]
Hm. Could we place loadup messages into something like Trinity_Loadup ? I imagine it being easier if there are certain changes required to be done, e.g. localization (if someone bothers to do them).

**Comment by tkrokli** [comment]
@ShinDarth : sorry for not making any updates recently, I was not feeling well enough to do anything.
I was going to check out @mthsena's suggestion to find out how much the `command`.`help` text needs cleaning up and to be added to this PR, but that could also be done in a separate PR if needed. It is more or less a question whether it is more important to include it in this PR than to do it separately, I don't know. I was also hoping for some feedback if there is anything already in this PR that needs fixing or not.

**Comment by ShinDarth** [comment]
@tkrokli got it, I hope you are feeling better now!

**Comment by tkrokli** [comment]
@Ascathor : in `trinity_string` there already are 8 localization columns: `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, so I don't quite see how it would help to change the table name.
Maybe I misunderstood what your point is and how it would look in practice.

@ShinDarth : thanks, I feel better, though I need another day to get back to normal.

**Comment by jackpoz** [comment]
the SQL part is quite a pain to review, it would be easier if you could separate the C++ part from the SQL part in 2 different PRs, maybe keeping the C++ part in this one.

We were also wondering about adding grammar codestyle to https://trinitycore.atlassian.net/wiki/pages/viewpage.action?pageId=2130103 , i.e. "could not" instead of "can't/cannot/can not/couldn't" and similar things. I'll notify you once we sort out the guidelines.

**Comment by tkrokli** [comment]
OK, I can see that it would make a better overview if I remove the SQL part from this PR. To post the SQL part separately means that I only create a new issue post for the SQL, according to TC standards.

**Comment by jackpoz** [comment]
btw it seems your PR missed https://github.com/tkrokli/TrinityCore/blob/grammar_and_spelling_corrections_335/src/tools/mmaps_generator/MapBuilder.cpp#L713

**Comment by tkrokli** [comment]
Good catch. Like I mentioned earlier, this is manual work, so there may still be other typos or non-English/ "engrish" cases that I may have missed. I just picked the obvious ones that I could find. I will add that L713 from MapBuilder.cpp to this PR. Should I move the SQL to a separte issue too, while I'm at it?

**Comment by jackpoz** [comment]
Watch out for other occurrences of fialed.

https://trinitycore.atlassian.net/wiki/pages/viewpage.action?pageId=2130103 still doesn't contain any rule about "could not" instead of "can't/cannot/can not/couldn't" and similar things, poke someone around to add them so you can go on working on this PR.

**Comment by tkrokli** [comment]
Updated the PR:
- moved 2015_12_17_18_world335.sql out of the PR for use in a regular issue
- added 2 corrections to MapBuilder.cpp (L 702 and L713)

No other occurrences of the spelling "FIAL" or "fial" found except in the name Fialla Sweetberry.

**Comment by tkrokli** [comment]
As I wrote in the update comment in the PR description, SQL fixes will now be posted separately.

**Comment by tkrokli** [comment]
Wow, nice. Thanks for the merge. I will be so pleased to see less poorly written system messsages in the console from now on. The only messages I have not been able to decide more changes for, are those SpellMgr-related Log messages ending in `[ ... ], and then ...` (I did not know that there would be a need for TC_LOG messages to end in `, and then ...` before my last review of this PR. But thanks.

**Pull request merged**
