### PR TITLE
AuctionHouse: Deposit - Fixed config value of 0 being ignored.

### PR DESCRIPTION
**Pull request by lucas-wb**
Please talk slowly I'm a little dull

-- Realized I used tabs instead of spaces as per the coding standards, added another commit. Enlighten me if there is a better way to do so

### CODE REVIEW

**Comment by DDuarte** [comment]
`GetAuctionDeposit` returns `AH_MINIMUM_DEPOSIT` (100) if the deposit is lower than that. Why shouldn't that be the case for 0?

**Comment by Tomatodev** [comment]
That's the problem, in the world config you put in a multiplier for the deposit cost. If you put 0 into the config, indicating you want there to be no deposit, it multiplies the deposit by 0, but then immediately sets it to AH_MINIMUM_DEPOSIT since its < (100).

**Comment by jackpoz** [comment]
This PR looks ok, could you squash the commits so it can be merged ?

**Comment by StormBytePP** [comment]
@Tomatodev why close without reason?

**Comment by Tomatodev** [comment]
Had problems squashing, deleted the wrong source repo. Was going to resubmit with a new source repo

**Comment by StormBytePP** [comment]
but you can undelete it, re-clone, and try squash again :)

**Comment by jackpoz** [comment]
@Tomatodev there's no hurry, take your time to learn how to squash. you need to learn it only once, after than it's gonna be easier :)

**Pull request closed without merging**
