### PR TITLE
Core/Scripts: Tom Hegger must target player in Say text

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

Make NPC 25827, Tom Hegger, say his aggro text while targeting player to use $c correctly.

File: [zone_borean_tundra.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_borean_tundra.cpp)
Script: [npc_hidden_cultist](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_borean_tundra.cpp#L2200)
Quest: The Hunt is On, 11794 (http://www.wowhead.com/quest=11794/the-hunt-is-on)
NPC:  [Tom Hegger, 25827](http://www.wowhead.com/npc=25827/tom-hegger)

Before this change, Tom Hegger does not target player when saying his
aggro text "You don't know who you're messing with, $c!   Death beckons!"
and hence the text $c will be shown instead of the player class.

**Target branch(es):** 3.3.5 (I do not know if this issue exists in 6.x)

**Issues addressed**: Updates #16133 [[3.3.5] DB/Quest: The Hunt is On (11794)](https://github.com/TrinityCore/TrinityCore/issues/16133)

**Tests performed**: (Does it build, tested in-game, etc)

Builds without issues, works as intended/expected in-game. :+1:

**Known issues and TODO list**:

No known issues with this script modification, it compiles and works in-game.
The added line is identical to another line used in the same script (reused code).

### CODE REVIEW

**Comment by Naios** [comment]
If this doesn't happen aleady, maybe we can log an error when the formatter fails to deduce the playername.

**Comment by Shauren** [comment]
@Naios formatting happens clientside.

**Comment by Naios** [comment]
We could also check against that.

**Comment by DDuarte** [comment]
String search for $C, $G and so on and if no target error log?

**Comment by Naios** [comment]
Yep, better precheck all strings on startup.

**Pull request merged**
