### PR TITLE
Core/Spells: Fix DK Death rune selection

### LINKED ISSUE #14796: [3.3.5] Core/Spells: DK Death rune usage wrong
When a DK casts a spell costing a Frost rune, the current version of TrinityCore has this priority:
* Find a Frost rune
* Use any Death rune

WOTLK had a small and subtle difference in the prioritization, but it was one that makes certain rotations much easier:
* Find a Frost rune
* Find a Death rune that was originally a Frost rune
* Use any Death rune
 
Tested on 62ebd002d990. Fix in progress.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18618351-3-3-5-core-spells-dk-death-rune-usage-wrong?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by czw**
Fixes #14796.

### CODE REVIEW

**Comment by Shauren** [comment]
Source for this mechanic?

**Comment by czw** [comment]
No documented source. Played DK extensively in WOTLK and started experimenting with one again. Noticed that a few muscle memory rotations didn't work due to the wrong runes being on cooldown.

**Comment by gigatotem** [comment]
"Regular Blood, Frost, or Unholy runes have priority over other runes marked as Death runes. For example, using an ability that costs 1 Frost rune will consume:

the active Frost rune, if you have 1 Death rune and at least 1 Frost rune active;
an active Death rune, if you do not have any Frost runes active."


http://www.icy-veins.com/wow/runes-and-runic-power-a-death-knight-resource-system-guide

**Comment by tkrokli** [comment]
@gigatotem: Your post looks relevant to me. Useful piece of documentation on the subject of this PR.

**Comment by Frytiks** [comment]
Thanks for this, i'm using it, work's very well. Finally get fixed Death Rune

**Comment by czw** [comment]
Not my video, but it demonstrates the behaviour that my patch is enabling.
https://www.youtube.com/watch?v=my9wslCEfl8
- 2:50 - Starts with two Blood runes, two Death/Frost, two Death/Unholy
- 2:56 - Icy Touch cast, a Death/Frost rune is used and
- 2:58 - Plague Strike cast, a Death/Unholy rune is used

If the same is done without my patch on a TrinityCore server, the two Death/Unholy runes are used. Also shows that if two Death runes are used by an ability that generates them, they remain Death runes. Something I will try to patch as well later on.

**Pull request merged**
