### PR TITLE
Create spell_monk.cpp

### PR DESCRIPTION
**Pull request by ottconnect**

### CODE REVIEW

**Comment by soulfrost** [comment]
best code style... rofl

**Comment by ottconnect** [comment]
I know it will probably need a bit of work, but I had no issue with compile on it.

**Comment by DDuarte** [comment]
This suffers from the same problems as #13953 (and a couple more, like incomplete scripts and placeholders).
Please try to work with @Noffearr on #13953 to fix the existing issues. Thanks.

**Comment by ottconnect** [comment]
no problem, I sent him the code for him to look at it

**Comment by Roxtedy** [comment]
lol

**Pull request closed without merging**
