### PR TITLE
DB/Item: Solace of the Fallen

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/TrinityCore/TrinityCore/issues/1896

### CODE REVIEW

**Comment by DDuarte** [comment]
Thanks for the pull request but please use Issues to submit SQL-only fixes.

**Comment by Skyepup** [comment]
So what do I do to get this in the main branch? This fix is already on a issue.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/1896#issuecomment-11885803

**Comment by Skyepup** [comment]
So then I updated the issue with the fix that was already on there. Tested working, do I just wait for one of the contributers to actually update trinity core?

**Comment by Aokromes** [comment]
You need to read the comment i linked.

**Pull request closed without merging**
