### PR TITLE
Scripts/The Barrens: Beaten Corpse

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Move script from C++ to SAI.

**Target branch(es):** 3.3.5

~**Issues addressed:**~

**Tests performed:** Works as intended.

~**Known issues and TODO list:**~

### CODE REVIEW

**Comment by illfated** [comment]
Congrats. I did not see that one coming, especially not as easily solved as that.
I was convinced that we would have to create a SAI version of `player->TalkedToCreature()`
and I never thought it would be as easy as saying `On Gossip Select - Credit Quest`.

If you continue like this, you will soon eradicate the traces of my contributions... ;-)

**Comment by Sorikoff** [comment]
It's for the best ;D

**Comment by Killyana** [comment]
This can be pushed.

**Comment by illfated** [comment]
I concur with that assessment.

Just as a footnote, I now think that this quest must have been the easiest quest Blizzard ever created (dialogue-wise), except for the autocomplete quests.
I also think that this is one of the top 10 (if not one of the top 5) quests in the entire game to create the most live in-game chat activity (or "noise" - remember The Barrens chat?), especially if you include related forum posts on wowhead and elsewhere.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
