### PR TITLE
Scripts/MoltenCore: Implement Garr's Firesworn Separation Anxiety mec…

### PR DESCRIPTION
**Pull request by ghost**
…hanic and fix wrong spell id

- The previous (wrong) spell ID used mana, so it was never cast because Firesworns aren't mana users

**Changes proposed:**

-  Implement Garr's Firesworn's Separation Anxiety mechanic - adds enrage when pulled 20 yards away from boss.
-  Fix wrong spell id being used by Firesworns. Previous (wrong) ID used mana so it was never cast. Firesworns got no mana.

**Target branch(es):** 3.3.5/master

- [ X] 3.3.5
- [ X] master

**Tests performed:** (Does it build, tested in-game, etc.)
Builds, works...

### CODE REVIEW

**Comment by ccrs** [comment]
would you please update the script to the new ```RegisterCreatureAI``` macro?

**Comment by illfated** [comment]
(cosmetic) - maybe the detail under "Target branch(es): " in the PR description is intentional, but if you remove the space before X inside the [ ] brackets, those will be shown as tick boxes.

**Comment by Nyeriah** [comment]
@ccrs !hola! anything else?

**Comment by ccrs** [comment]
¡Hola!* 😄 

Not really, ty!

**Pull request merged**
