### PR TITLE
Fixed logic error in instance loading, simplified instance id recycling

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5

- [x] 3.3.5

**Issues addressed:** Partially #15780

**Tests performed:** Compiles

This patch simplifies instance id recycling and fixes logic error. If max(instanceId) in db was dividable by 32 without rest the _instanceIds vector was improperly resized.

### CODE REVIEW

**Comment by Demonid** [comment]
5 months without activity, @Aokromes

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15780#issuecomment-269040472

**Comment by ccrs** [comment]
@xinef1 is this tested or debugged or anything?

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Maps/MapManager.cpp

**Comment by sirikfoll** [comment]
Is this still needed after https://github.com/TrinityCore/TrinityCore/commit/2639056071597edfdf74b31a16ce644610a1b6d9 ?

**Comment by Aokromes** [comment]
Yes, now it's even worse. But again i prefer https://github.com/TrinityCore/TrinityCore/issues/15780

**Comment by Shauren** [comment]
No, this and the other recycling PR are not needed - something else is now broken

**Pull request closed without merging**
