### PR TITLE
Core/Phases: Ported new phasing from 4.x branch

### PR DESCRIPTION
**Pull request by streetrat**
Ported my and Subv's phasing system from 4.x to 6.x
Also fixed some map swap issues

### CODE REVIEW

**Comment by streetrat** [comment]
there is phase.dbc and phasegroup.dbc, or what are their names...
to use multiple phases you have to set a phase group from that dbc

**Comment by msoky** [comment]
thx :+1:

**Comment by Naios** [comment]
I still don't get it why you removed the old PhaseMgr, it worked well and you could have changed it easily to use ids instead of masks.
The acutal problem of those phases is that you need to take care of phasing auras to be removed if a player doesn't meet a special criteria anymore, and `spell_area` is just not enough to handle it.

**Comment by Exodius** [comment]
Does this mean that [phasing intended for 4.3.4 branch](https://github.com/TrinityCore/TrinityCore/tree/phases) is functional? And if answer is positive, why isn't it merged into the 4.3.4 branch?

**Comment by Aokromes** [comment]
You need to read, this is port of the work done on 4.x merged from phases branch.

**Comment by Exodius** [comment]
I did read. streetrat wrote that he ported "his and subv's phasing system from 4.x to 6.x and that he fixed some map swap issues" however nowhere is mentioned that this is still work in progress and that it is incomplete. I just assumed that "phasing" branch is working (maybe not as Blizzlike) and only fine tunes are needed.

**Comment by streetrat** [comment]
it should handle phasing auras currectly (+terrain swaps if set in db)

**Comment by msoky** [comment]
i cant wait for this :+1:  please merge :)

**Comment by msoky** [comment]
can we merge it?

**Comment by MitchesD** [comment]
it will be merged when it's finished

**Comment by msoky** [comment]
is it necessary for 3.3.5 DK zone too?

**Comment by Aokromes** [comment]
No, this phasing thing is 4.x and 6.x only

**Pull request merged**
