### PR TITLE
[7.x] Legion stats

### LINKED ISSUE #17647: [7.x] Legion player_levelstats
Complete player_levelstats level 1-110 (incl Demon Hunter)
Clean table. (Removed 'spi' column due to remove of spirit in Legion)

All race-offsets are included.

DB: future TDB7

https://gist.github.com/funjoker/d4d4133538a49d6394a2940e825f3e22
Last Edit: 22.07.2016

### PR DESCRIPTION
**Pull request by funjoker**
**Changes proposed**:
- Removed spirit loading from core
- Added stats for legion

**Target branch(es)**: 6x/7x

**Issues addressed**: Closes #17647

**Tests performed**: Builds and starts

### CODE REVIEW

**Comment by frozen4** [comment]
good work . but the table creature_classlevelstats is still missing data can anyone add it?

**Comment by funjoker** [comment]
Well i have no mana datas so i want to wait for Release

**Comment by frozen4** [comment]
do you have armor and  damage data?

**Comment by funjoker** [comment]
Damage is given by db2 Files.
Yes i have armors 101-123

**Pull request merged**
