### PR TITLE
Named CREATURE_TYPE_FLAG_2_UNK8.

### PR DESCRIPTION
**Pull request by Macsimka**
**Changes proposed:**
Client function: CGUnit_C::IsUnconsciousOnDeath.
Verified by sniff and game test. NPC for example Garrosh Hellscream - 71865.
https://i.imgur.com/8T4ozvH.png
https://i.imgur.com/1oDABqV.jpg
https://youtu.be/R3O380GONuY?t=977

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Selenium** [comment]
Illidan in BT encounter have the same behaviour and don't die

**Comment by meji46** [comment]
Can you check if it isn't really because of UNIT_FLAG3_UNCONSCIOUS_ON_DEATH (https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Unit/UnitDefines.h#L228)

**Comment by Macsimka** [comment]
> Can you check if it isn't really because of UNIT_FLAG3_UNCONSCIOUS_ON_DEATH? (https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Unit/UnitDefines.h#L228)

UNIT_FLAGS_3 its draenor (or legion, I don't remember)+ feature. On mop (5.4.8) and below we doesn't have this.
In new patches creatures have UNIT_FLAG3_UNCONSCIOUS_ON_DEATH + type flag in template.

`[0] (ObjectData) EntryID: 71865 (71865)`
`[0] (UnitData) Flags: 33088 (Unk6, ImmunePC, CanSwim)`
`[0] (UnitData) Flags2: 4194304 (GiganticAoi)`
`[0] (UnitData) Flags3: 2 (Unconscious)`

`ServerToClient: SMSG_QUERY_CREATURE_RESPONSE (0x2914) Length: 158 ConnIdx: 0 Time: 11/28/2022 18:06:11.766 Number: 128839`
`Entry: 71865`
`CreatureTypeFlags2: 128 (CREATURE_TYPEFLAGS_2_UNK8)`

**Comment by mdX7** [comment]
```sql
SELECT * FROM `creature_template` WHERE `type_flags2` & 0x80 <> 0 ORDER BY `VerifiedBuild` DESC;
```
when executing this query i get quite a lot of results, especially wailing caverns and naxxramas bosses have those flags set, and im 100% sure that those creatures actually die

**Comment by Macsimka** [comment]
Checked on 5.4.8 and shadowlands clients. For mop its 100% CREATURE_TYPE_FLAG_2_UNCONSCIOUS_ON_DEATH, but not for shadowlands. Looks like the flag has been reassigned in new patches.

**Pull request closed without merging**
