### PR TITLE
[3.3.5] Core/Scripts: zone_thousand_needles.cpp cleanup

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed**:

1 more text line removed in the ongoing series: "Remove hardcoded text from core scripts".

Core script for "Plucky" Johnson :
- move the actual gossip handling to DB
- create new gossip_menu_option entry
- link the option to gossip_menu.text_id
- add correct default gossip to the NPC
- create SAI script with alternate emotes
- add condition check for quest taken
- remove the script from zone script
- extra enum cleanup in zone script

**Target branch(es)**: 3.3.5 (quest 1950 "Get the Scoop" was removed in patch 4.0.3a)
http://www.wowhead.com/quest=1950/get-the-scoop
http://wow.gamepedia.com/Quest:Get_the_Scoop

**Issues addressed**: Removes (and corrects) the hardcoded text line
`#define GOSSIP_P    "Please tell me the Phrase.."` from the script in `zone_thousand_needles.cpp`.
The correct gossip_menu_option from `broadcast_text`.`ID` 2707 is:
`"Tell me the phrase to Tirth's lockbox."`

Added the correct default gossip to NPC 6266 ("Plucky" Johnson), which is :
`Hey!  Are you on an errand for Tirth?  If I were you I'd get as far away from him as I could!  His mind's been pickled from too much drink but his magic's as strong as ever!`
(This gossip is shown both with and without the quest.)

Updates https://github.com/velinath/TrinityCore/issues/2

**Tests performed**: (Does it build, tested in-game, etc)
Builds without problems in VS2013 Update 5, works as intended in-game.
Tested multiple times both with and without the quest in the character's quest log.

**Known issues and ToDo list**:

None, the script functionality is improved and working.

### CODE REVIEW

**Comment by tkrokli** [comment]
D'oh. For some reason I forgot to remove the unwanted `#define` text line. Fixed now. :-P

**Comment by tkrokli** [comment]
Suggestion: maybe add the labels  [Comp-C++Script] + [Comp-Database] to this PR?

**Comment by tkrokli** [comment]
I have made a new attempt this time to use SAI instead of the core script. Still untested.

**Comment by tkrokli** [comment]
I kept the old script commit in this PR in case moving the script to SAI does not work as intended.

**Comment by tkrokli** [comment]
Edited the main PR comment post to reflect the SAI changes instead of core script changes.

**Comment by joschiwald** [comment]
looks good

**Pull request merged**
