### PR TITLE
Core/BattlePets: BattlePetError enum class

### PR DESCRIPTION
**Pull request by meji46**
**Changes proposed:**

-  Defined BattlePetError enum class.

**Issues addressed:**
None

**Tests performed:**
Builds, tested in-game.

**Known issues and TODO list:** (add/remove lines as needed)
None

### CODE REVIEW

**Comment by Shauren** [comment]
SMSG_BATTLE_PET_REVOKED and SMSG_BATTLE_PET_RESTORED are never going to be used - don't implement (used on retail for store pets when you get a refund)

**Comment by meji46** [comment]
> SMSG_BATTLE_PET_REVOKED and SMSG_BATTLE_PET_RESTORED are never going to be used - don't implement (used on retail for store pets when you get a refund)

Done

**Comment by mdX7** [comment]
> 
> 
> SMSG_BATTLE_PET_REVOKED and SMSG_BATTLE_PET_RESTORED are never going to be used - don't implement (used on retail for store pets when you get a refund)

can we actually document that anywhere?

**Comment by funjoker** [comment]
> > SMSG_BATTLE_PET_REVOKED and SMSG_BATTLE_PET_RESTORED are never going to be used - don't implement (used on retail for store pets when you get a refund)
> 
> can we actually document that anywhere?

Maybe add a comment to the Opcode in core ? :D

**Pull request merged**
