### PR TITLE
[WIP] Scripts/Pandaria: Script loader and more

### PR DESCRIPTION
**Pull request by JustZerooo**
**Changes proposed:**

- Add the forgotten script loader for pandaria files.  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [X] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Build works.

**Known issues and TODO list:** (add/remove lines as needed)

Someone have to add some scripts. Later or never whatever.

### CODE REVIEW

**Comment by Shoxxo** [comment]
Do not close this Pullrequest, i will start fill it with content. Thanks.

**Comment by tkrokli** [comment]
Very well. I presume you are aware of the partial overlap with the PR **[WIP] Scripts/Pandaria: The Wandering Isle** https://github.com/TrinityCore/TrinityCore/pull/17021 (`src/server/scripts/Pandaria/pandaria_script_loader.cpp`).

**Comment by Aokromes** [comment]
```code
[16:50:42] <Shauren> iMZ: mangos does something we dont do - they add empty placeholder files for all possible bosses

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/17011

**Pull request closed without merging**
