### PR TITLE
[3.3.5] Core/Spells: Fix incorrect Seal of Righteousness calculation.

### PR DESCRIPTION
**Pull request by Eliminationzx**
Source http://wowwiki.wikia.com/wiki/Spell_power_coefficient
Closes https://github.com/TrinityCore/TrinityCore/issues/14446

### CODE REVIEW

**Comment by Treeston** [comment]
[WoWwiki history agrees](http://wowwiki.wikia.com/wiki/Spell_power_coefficient?oldid=2193140).

**Comment by c9240709-b07d-4439-9212-94f05f7a3212** [comment]
:+1:

**Comment by ariel-** [comment]
No, 35.5% of SP and 22.5% of AP is the coefficient for the JUDGEMENT part of this spell, not for the "extra holy attack" part. This PR mixes coefficients.

The "by 1" off issue (#14446) is caused by int32/uint32 casting of floats, wich truncates the decimal part, std::lroundf should be used instead, as explained in https://github.com/TrinityCore/TrinityCore/issues/14446#issuecomment-91328897 (but maybe only in the calculation part of this spell, not in the SpellEffectInfo, which maybe will break something else)

**Comment by c9240709-b07d-4439-9212-94f05f7a3212** [comment]
@ariel- You might be wrong:

Here is the spell info http://wotlk.openwow.com/spell=21084.
_Fills the Paladin with holy spirit for 30 min, granting each melee attack **[MWS*(0.022*AP+0.044*SPH)]** additional Holy damage. Only one Seal can be active on the Paladin at any one time. Unleashing this Seal's energy will cause **[1+0.2*AP+0.32*SPH]** Holy damage to an enemy._

The first part is before patch 3.3.0 (mistake on openwow) as it might be seen here on patch 3.2.0: http://www.wowhead.com/forums&topic=113856/sor-vs-socom-some-math. It was lately changed to the spell coefficient stated on WoWWiki ([Seal of Righteousness] (judgement) 35.5% 22.5% Patch 3.3), but that _(judgement)_ might be a mistake from WoWWiki as this spell was upgraded during years as now deals also damage on a area of 8 yards.

We should use _lroundf_ (as stated in your sugestion https://github.com/TrinityCore/TrinityCore/issues/14446#issuecomment-91328897) also on this formula (**which this PR updated it to patch 3.3.0**) but also on the tooltip (if it can be modified).

**Pull request merged**
