### PR TITLE
Scripts/Tanaris: move Aquementas to SAI & improve related event

### LINKED ISSUE #11668: DB/Quest: Aquementas
TrinityCore rev. 847bb11299a9 2014-03-02 23:15:55 -0500 (master branch)

http://www.wowhead.com/quest=4005/aquementas

Use the Book of Aquor to summon Aquementas.- Works

After killing Aquamentas you're supposed to recieve http://www.wowhead.com/item=11522

You don't receive the item needed to complete the quest.
http://www.wowhead.com/item=11522

The Item is in the database.

### PR DESCRIPTION
**Pull request by Wyreth**
**Changes proposed:**

Original script by @dr-j.

Made some adjustments to waypoints, script and conditions to make it works more close to the few sources we have for this quest.

**Target branch(es):**

- [x] 3.3.5

**Issues addressed:** closes #11668

**Tests performed:** works fine.

**What's missing**:

- [ ] Aquementas should be immune to frost damage and spell effects. Not sure how to accomplish that in DB. Any insight?

### CODE REVIEW

**Comment by tkrokli** [comment]
Pro tip: When you create the first local commit in a PR and you want it to close an existing issue automatically via GitHub when the PR gets merged, you can add a separate Commit comment text line a couple of lines below the title line, saying `Closes #11668` (using this PR as an example). I don't know if it will work to add it to the existing PR. Maybe it could work if you add it to the first commit while also merging the existing commits into one _and also do a force push to the PR branch_, but I am uncertain if it works as expected after the PR has been created. (I haven't tested this enough on my own PRs in the past to know this for sure.) It is practical to know this for future Pull Requests, though. :-)

**Comment by Wyreth** [comment]
Good tip, I'll try it now :D thanks!

**Comment by tkrokli** [comment]
Looks correct to me. Crossing my fingers for it to work as expected upon merge. 👍

**Comment by tkrokli** [comment]
I see you have added the  comment
> Aquementas should be immune to frost damage and spell effects. Not sure how to accomplish that in DB. Any insight?

in the PR description. For the sake of keeping the PR open a bit longer to see if someone has got a suggestion on how to solve that piece of the puzzle, I will set this PR as [Feedback-FixOutdatedMissingWIP] until that part has been discussed (and hopefully answered). My initial thought is that maybe this could be accomplished with a flag of some sort in `creature_template` -- need to check to see if any of them can fit the bill, though. I am also uncertain if the current DB entry is 100% correct or not, so we have to wait and see if that can be answered by someone who knows more about it.

**Comment by Wyreth** [comment]
About frost immunity, [this spell](http://www.wowhead.com/spell=7940) could be useful.

There's one for every spell school that mobs can be immune to - can we add that even without confirmation from sniffs (which will probably never come, since the mob was removed in Cataclysm)?

**Comment by offl** [comment]
> Aquementas should be immune to frost damage and spell effects. Not sure how to accomplish that in DB. Any insight?

By a aura(hack) or you can implement(or import) immunities in creature_template -_-

**Comment by Wyreth** [comment]
That would probably be useful, yep :P

**Comment by offl** [comment]
Here's a list of NPCs with immunities for vannila/tbc, but I think it can be used for 3.3.5
```sql
(12457,16491,18099,18100,18101,18102); -- Holy
(2760,4036,4037,4038,4676,5850,5852,7137,7664,7734,7735,9016,9017,9026,9816,9878,9879,11502,11666,11667,11668,12056,12143,12457,16491,18099,18100,18101,18102,19203,19973,20703,21706,22323,25001); -- Fire
(92,2258,2592,2735,2736,2752,2762,2791,4499,11321,11744,11777,11778,11779,11783,11784,12201,12237,12457,14435,14455,16491,17085,17154,17156,17157,17158,17159,17160,18062,18099,18100,18101,18102,18181,21707,22036,23029); -- Nature
(691,2761,3917,5461,5462,7079,7132,7428,7429,7664,7734,7735,9453,10642,10756,10757,12457,13280,16491,17153,17155,17167,17207,17358,18099,18100,18101,18102,19204,20704,21428,21728,22009,22035,22309,25740,25755,25756,25757,25865,26116,26178,26204,26214,26215,26216,26338,26339,26340,26341,26342); -- Frost
(703,7664,12457,16491,18099,18100,18101,18102,19206,20705,21032); -- Shadow
(7734,7735,10202,10662,10663,10664,11480,11483,12457,16488,16491,16530,16854,18099,18100,18101,18102,18864,18865,18866,18867,19205,20516,20702,21032,22310); -- Arcane

**Comment by tkrokli** [comment]
I did a quick compare in `creature_template` for all those listed on your line 4 (`-- Frost`) and found that Aquementas has got 54 in `resistance1` through `resistance6` (all resistance groups). Regarding `mechanic_immune_mask`, I noticed that only `Ahune <The Frost Lord>` and `Frozen Core` has got 617299839 listed (from those on line 4), which consists of:
```
536870912 -- MECHANIC_SAPPED
 67108864 -- MECHANIC_DAZE
  8388608 -- MECHANIC_HORROR
  4194304 -- MECHANIC_TURN
   524288 -- MECHANIC_SHACKLE
   131072 -- MECHANIC_BANISH
    65536 -- MECHANIC_POLYMORPH
     8192 -- MECHANIC_KNOCKOUT
     4096 -- MECHANIC_FREEZE
     2048 -- MECHANIC_STUN
     1024 -- MECHANIC_SNARE
      512 -- MECHANIC_SLEEP
      256 -- MECHANIC_SILENCE
       64 -- MECHANIC_ROOT
       32 -- MECHANIC_GRIP
       16 -- MECHANIC_FEAR
        8 -- MECHANIC_DISTRACT
        4 -- MECHANIC_DISARM
        2 -- MECHANIC_DISORIENTED
        1 -- MECHANIC_CHARM
```
Maybe @sirikfoll has got any ideas, since he knows quite a bit about `Ahune <The Frost Lord>` ? :-)

**Comment by offl** [comment]
> I did a quick compare in creature_template for all those listed on your line 4 (-- Frost) and found that Aquementas has got 54 in resistance1 through resistance6 (all resistance groups).

Some NPCs already have resistances, but I don't know how and why they were added -_- Some of them should not have any resistance.

> I am also thinking about what you mentioned about http://www.wowhead.com/spell=7940/immunity-frost and that it is considered a hack to use auras. Is that regardless of whether the aura is added in creature_template_addon or as a script command?

No matter. Auras like this implemented only for some NPCs(so they shouldn't be used for other).

**Comment by tkrokli** [comment]
> No matter. Auras like this implemented only for some NPCs(so they shouldn't be used for other).

Yes, that is correct in most cases, AFAIK. There are some cases, though, like where the page about spell 7940 `Immunity: Frost` does not say which creature(s) it is used by, so I thought it could be a more general spell and therefore maybe used in scripts more than as an ability or static spell. Isn't it so that auras (more often than not) don't show up in sniffs and therefore need to be discovered visually like in videos or (for existing creatures) verified on retail servers? Anyway, I can't say for sure, so I will leave the decision to others with more experience and knowledge than me.

**Comment by offl** [comment]
7940 used by [Evolving Ectoplasm](https://github.com/TrinityCore/TrinityCore/blob/15b1aaff4189df291fc28e3607ed2b0e4d297341/sql/old/7/world/00_2017_04_18/2017_03_13_00_world.sql#L833).

> Isn't it so that auras (more often than not) don't show up in sniffs and therefore need to be discovered visually like in videos or (for existing creatures) verified on retail servers?

Seems like today all auras are shown up in sniffs. But prior to wotlk for some reason only hidden auras which trigger spells were not shown in sniffs or were deleted from c_t_a :/

**Comment by Wyreth** [comment]
Would it be all right to create a new bitmask field in creature_template_addon to control elemental immunity?

I was thinking something along the lines of "negative value in creature_template's resistanceX fields), but I guess those values are sniffed/parsed from somewhere?

This can be merged as it is, anyway. The resistance immunity is a broader issue to be solved indipendently from this.

**Comment by offl** [comment]
> I was thinking something along the lines of "negative value in creature_template's resistanceX fields", but I guess those values are sniffed/parsed from somewhere?

I'm not sure, but I think immunities cannot be sniffed.
Here's two variants how to implement this: https://github.com/sergeev/hgroundcore/commit/2bd30ae1cfcdc7412fee1ad666eb6a61b243a273 https://github.com/cmangos/mangos-tbc/commit/cb0fca1b377dff0181c29e6e3e5e92d32797eaec

**Comment by Aokromes** [comment]
@Wyreth ref resistance to elements creature_template:

  `resistance1` smallint(6) NOT NULL DEFAULT '0',
  `resistance2` smallint(6) NOT NULL DEFAULT '0',
  `resistance3` smallint(6) NOT NULL DEFAULT '0',
  `resistance4` smallint(6) NOT NULL DEFAULT '0',
  `resistance5` smallint(6) NOT NULL DEFAULT '0',
  `resistance6` smallint(6) NOT NULL DEFAULT '0',

**Comment by tkrokli** [comment]
Ref. https://github.com/TrinityCore/TrinityCore/pull/20464#issuecomment-333299969
> Aquementas has got **54** in `resistance1` through `resistance6` (all resistance groups).

So what would a reasonable value be to make Aquementas resist any frost spells, regardless of power?
I also thought the existing `creature_template` values were sniffed, but maybe I forgot something?

**Comment by Wyreth** [comment]
There's no value that can make it immune as far as I know. #20709 takes care of the immunity part, if it gets approved :P

**Comment by offl** [comment]
> This can be merged as it is, anyway. The resistance immunity is a broader issue to be solved indipendently from this.

**Pull request merged**
