### PR TITLE
Remove extra online update query when login in world on character

### PR DESCRIPTION
**Pull request by CraftedRO**
**Changes proposed:**

-  Remove extra update query when login in world on character since is there already one sent when you enter credentials

**Issues addressed:**

Closes https://github.com/TrinityCore/TrinityCore/issues/26923

**Tests performed:**

(Does it build, tested in-game, tested on db side.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ]

### CODE REVIEW

**Comment by Shauren** [comment]
This is neccessary in case you have multiple realms running and one of them is restarted, it will clear online flag on its restart

**Comment by CraftedRO** [comment]
it will clear online flag on worldserver restart with this too anyway

**Comment by Shauren** [comment]
Yes but at least this code will set it back to 1 if you change characters

**Comment by CraftedRO** [comment]
it will set back to 1 in AUTH db that's not supposed to be a character online status but rather account, meh anyway I don't know why I even care

**Pull request closed without merging**
