### PR TITLE
Scripts/Ebon Hold: How To Win Friends And Influence Enemies

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Move script from C++ to SAI (and improve it).

**Target branch(es):** 3.3.5

~**Issues addressed:**~

**Tests performed:** Mostly works as intended.

~**Known issues and TODO list:**~

### CODE REVIEW

**Comment by jackpoz** [comment]
are the known issues/todo happening in the C++ script too ?

**Comment by Sorikoff** [comment]
Text bubbles work normally when C++ is used.

**Comment by jackpoz** [comment]
Then we can't merge a PR that adds new issues

**Comment by Killyana** [comment]
I'm doing some changes, the text issue is fixed.

**Comment by Aokromes** [comment]
@Sorikoff jump into irc :)

**Comment by Sorikoff** [comment]
Thanks, @Killyana! What was the issue with bubbles?

**Comment by Killyana** [comment]
No Idea, it's just don't happen for me

**Comment by Sorikoff** [comment]
Hmm, updated SQL isn't working for me (manually casting `52781`).

**Comment by Killyana** [comment]
I changed the condition update again.

**Comment by Sorikoff** [comment]
Now seems to be good.

**Comment by Killyana** [comment]
Is there a script or something that changes the proc of 52781 ?

**Comment by Sorikoff** [comment]
```
mysql> SELECT `spellppmRate_1` FROM item_template WHERE entry=39371;
+----------------+
| spellppmRate_1 |
+----------------+
| 1.0            |
+----------------+
1 row in set
```

**Comment by Killyana** [comment]
The spell has 10 secs cooldown, so probably because of this it doesn't proc too much, anyway I updated the SQL with the final version.

**Comment by Killyana** [comment]
@Sorikoff I forget to do the reset properly, I updated the script with the final final version and the SAI is even shorter.

**Comment by Shauren** [comment]
Proc rate on retail is terrible too...

**Comment by Warpten** [comment]
Cooldown has nothing to do with proc rate

**Comment by Sorikoff** [comment]
Isn't ppm too low though?

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
