### PR TITLE
Build: Set CMake policy CMP0144 to NEW

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Set CMake policy CMP0144 to NEW
-  (similar to commit 4d7bf20 on master)
- Notable diff: extra documentation in comments

**Issues addressed:**

Only affects users with Cmake version 3.27 and newer (3.28 and soon to be released 3.29)
Cmake manual page: https://cmake.org/cmake/help/v3.27/policy/CMP0144.html

**Tests performed:**

Builds just fine, removes a warning in Cmake when using new versions 3.27 and above.
I have used this cherry-picked commit for several months now to avoid the old warning.

**Known issues and TODO list:** (add/remove lines as needed)

No known issues, this is basically the same content as commit 4d7bf20 on master.

### CODE REVIEW

**Comment by Shauren** [comment]
Closing, ported together with many other build related commits

**Comment by Legoso** [comment]
> Closing, ported together with many other build related commits

Fair enough. I was worried it would take another half year to see the cherry-pick.

**Comment by CraftedRO** [comment]
half year it is still reasonable, I wonder if we have to create a dummy cherry pick to force a real cherry pick for each unmerged thing 😅

**Comment by Legoso** [comment]
Problem solved ... for now. ^^

**Pull request closed without merging**
