### PR TITLE
Core/Unit: SpellDamagePctDone +15% for DK diseases

### PR DESCRIPTION
**Pull request by ghost**
by @P-Kito; retrieved from #15027.

Deathknight diseases should make 15% more damage after patch 3.2.0

Adding the 15 pct damage via SpellFamilyFlags[1] 0x6000000 & 0x800.

### CODE REVIEW

**Comment by joschiwald** [comment]
i don't think this is right
i guess blizz increased dmg by changing dbcs

**Comment by P-Kito** [comment]
no.  there is already the   * 1.15 in the tooltip.
so therefore: why didn't they change it then?

**Comment by LuqJensen** [comment]
I have applied a similar fix elsewhere before. Iirc the "source" was Dr. Damage addon reporting values 15% higher than recount/combat log. I think blizzard just changed the damage in serverside dbcs

**Comment by P-Kito** [comment]
DBCs say:  [..] * 1.15
I am not sure whether it's already in or not, but I GUESS not.

**Comment by jackpoz** [comment]
@joschiwald any other feedback about this PR ?

**Comment by tkrokli** [comment]
I suppose this is not a valid fix, so I will close and remove this PR.

**Pull request closed without merging**
