### PR TITLE
Core/MMaps: Fix charge underwater/falling

### LINKED ISSUE #22253: Warrior Charge Underwater Facing the Wrong Way
**Description:**

Warrior charge underwater causes the warrior to charge at the mob but faces the wrong way.

**Current behaviour:**

When your underwater fighting turtles for instance and you use charge the charge works but when you stop at the mob you are facing the wrong way.

**Expected behaviour:**

You should be able to use the charge underwater and stop right in front of the mob so you can instantly attack without having to move around to get the mob in front of you.

**Steps to reproduce the problem:**

1. Go anywhere where there is deep water and mobs
2. Cast charge on any mob and your toon will run at them.
3. Then you are greeted by the error that you are facing the wrong way.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6726126664db+

**Operating system:** 

Windows Server 2012

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

- Fix charge sometimes returning "no path available" when swimming/underwater.
- Fix charge sometimes returning "no path available" when falling, now it allows to charge downwards.
- Fix charge selecting a destination point 4 yards above swimming/underwater targets.
- Disabled raycast charge as that seems to be unblizzlike. This might fix some falling underground issues.
- Removed the Z 4 yards offset that never made any sense to me.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #22253 , #23326 , #24011 , maybe #11526

**Tests performed:** (Does it build, tested in-game, etc.)
Performed the tests described at https://github.com/TrinityCore/TrinityCore/issues/22253#issuecomment-465990651 

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] More tries should be done in water (shallow and deep)
- [ ] Any try should be done with flying caster/targets

### CODE REVIEW

**Comment by Killyana** [comment]
This fix both issues, I noticed if you are falling you cannot charge, it returns no path available, but it's not relate to this PR

**Comment by jackpoz** [comment]
Fixed charge not working when falling, now it allows to charge downwards

**Comment by jackpoz** [comment]
Disabled raycast charge as that seems to be unblizzlike

**Comment by Killyana** [comment]
Charge in water, and when the player is falling are fixed.

**Comment by jackpoz** [comment]
any chance it fixed the falling underground also ?

**Comment by Killyana** [comment]
Yes I cannot reproduce an undermap issue, also it's better to remove: https://github.com/TrinityCore/TrinityCore/pull/24010/files#diff-952c711803610aa78110e4f92ff2516aR5515-R5516 this 4 yards are now useless, thy just cause a weird jump at the end of the charge

**Comment by jackpoz** [comment]
Removed the Z 4 yards offset that never made any sense to me

**Pull request merged**
