### PR TITLE
Core: whitespace cleanup, reduce double blank line to single

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
**Changes proposed:**
- Delete double empty line

**Target branch(es):**
- [x] 3.3.5

### CODE REVIEW

**Comment by illfated** [comment]
PR title suggestion (in case you find it useful):

**Core: whitespace cleanup, reduce double blank line to single**

(alternative phrasing can also be useful)

**Comment by Winfidonarleyan** [comment]
@illfated I agree

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by jackpoz** [comment]
I will probably add to https://github.com/TrinityCore/TrinityCore/blob/3.3.5/contrib/check_codestyle.sh a check for "\n\n\n" to get a warning when someone adds back a double empty line

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ed975ef4c0e614addc069785f23c1b7f522f3b8e check added

**Comment by Winfidonarleyan** [comment]
Okay, I'll check in a bit later

**Pull request merged**
