### PR TITLE
Core/Character: Fix crash by delete charachter

### PR DESCRIPTION
**Pull request by Luzifix**
hey,

i found a bug in the character delete funktion.

### CODE REVIEW

**Comment by tkrokli** [comment]
OK, this version looks clean and nice, keeping it in line with the existing spacing. Good job. :+1:

**Comment by Luzifix** [comment]
Thx :)

**Comment by joschiwald** [comment]
reguid stuff for DTT_CURRENCY in PlayerDumpReader::LoadDump missing
loading dump will trigger `TC_LOG_ERROR("misc", "Unknown dump table type: %u", type);`

**Comment by Luzifix** [comment]
@johnholiver Sorry, but i dont really understand what you try to say to me :(

**Comment by tkrokli** [comment]
@Luzifix : joschiwald meant to tell you (in code) that your fix will trigger a Log Error (`TC_LOG_ERROR`).
It means that this fix needs a little more work.

**Comment by joschiwald** [comment]
after reviewing pdump tool, i noticed that pdump loader is very broken, mostly related to new guid format

**Comment by Luzifix** [comment]
Emmm ok...i dont wented to add the last 2 commit in this PR. >.<
I think i try to fix smaller bugs and close this PR =/

**Comment by joschiwald** [comment]
create one branch for each pull request to avoid such thing

**Comment by joschiwald** [comment]
you don't need to create a new pull request for this one, i'm already working on this

**Pull request closed without merging**
