### PR TITLE
Core/PacketIO Update and enable SMSG_SPELL_ENERGIZE_LOG

### PR DESCRIPTION
**Pull request by brecky**

### CODE REVIEW

**Comment by Carbenium** [comment]
@brecky: those last commits doesn't really belong here...

**Comment by DJScias** [comment]
@brecky As @Carbenium says it's best to -only- include commits that are related to the structure update.

Other code that is not related to the PR should be refrained from getting pushed on the same branch you're trying to PR into Trinity Core.

**Comment by Carbenium** [comment]
@brecky : we can't merge this PR if you don't clean up your branch

**Comment by Carbenium** [comment]
@brecky: I'll close this PR now. Please open a new one containing *only* your proposed fix.

**Pull request closed without merging**
