### PR TITLE
Modernize codebase with Clang-Tidy range based loops, part 4

### PR DESCRIPTION
**Pull request by Lillecarl**
**Changes proposed:**
-  Range based loops everywhere

**Target branch(es):**
- [x] 3.3.5
- [ ] master

**Issues addressed:** 
Keeping TrinityCore up2date with the C++ standards

**Tests performed:**
Builds locally with clang

**Known issues and TODO list:** (add/remove lines as needed)
- [ ] Finish the rest

### CODE REVIEW

**Comment by soulfrost** [comment]
u can use smthn like `::value_type`, google it,

bad, but example:
```c++
    for (PlayerSpellMap::value_type const& spell : m_spells)
    {
        if (spell.second->state == PLAYERSPELL_REMOVED)
            continue;

        if (!spell.second->active || spell.second->disabled)
            continue;

        knownSpells.KnownSpells.push_back(spell.first);
    }
```

other way, use c++17 features:
```c++
    for (auto const& [spellId, spellInfo] : m_spells)
    {
        if (spellInfo->state == PLAYERSPELL_REMOVED)
            continue;

        if (!spellInfo->active || spellInfo->disabled)
            continue;

        knownSpells.KnownSpells.push_back(spellId);
    }
```

**Comment by Lillecarl** [comment]
@soulfrost Second example isn't legal in TC, but oi thanks for that, that's bloody useful, cheers!

I'll go over this again later, cba right now. Going to sleep :p

**Comment by Faq** [comment]
@Lillecarl we miss you :)

**Comment by Lillecarl** [comment]
@Faq Thanks buddy, I kinda hit some mental barrier and just couldn't be fucked sadly, I've still got the github convo in my mail as todo to finish. I got a tip regarding using the "iterator pair" instead of manually typing it out too, so i need to revisit my previous PR's before i continue with these (Because i only want the defacto best shit that i know going into TC) :)

**Comment by jackpoz** [comment]
should we leave this open or should we close it ?

**Comment by jackpoz** [comment]
was this ready to be merged ?

**Comment by jackpoz** [comment]
Closing this PR as it seems abandoned. Feel free to ask here to reopen it if anyone would like to work on it.
If it's ready to be merged just let me know and I can merge it.

**Pull request closed without merging**
