### PR TITLE
Core/Movement: Allow using walk when chasing

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Allow passing additional parameter to Chase Movement Generator in order to determine whether unit should walk. Currently it looks like that: 
```c
me->GetMotionMaster()->MoveChase(horse, {}, {}, true);
```

**Target branch(es):** 3.3.5

**Tests performed:** Does build, works-in-game

### CODE REVIEW

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Killyana** [comment]
If we have a creature that always use walk when chasing the target, how can we do that without a cpp?

**Comment by Sorikoff** [comment]
Which creature we are talking about?

**Comment by jackpoz** [comment]
@Killyana I would add a new column somewhere in the DB "chase_walk_mode" with:
- 0 always run, default, current behavior, doesn't break any script
- 1 respect current SetWalk() state
- 2 always walk, might not be needed but while at it we can implement it

**Comment by ccrs** [comment]
noooo, just add a unitflagextraorhowheveritscalled and you will cover all cases

**Comment by Killyana** [comment]
https://www.wowhead.com/npc=37881/wretched-ghoul related to The Sacred and the Corrupt quest, use always walk.

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Creature/CreatureData.h#L35

that

**Comment by Sorikoff** [comment]
`CREATURE_FLAG_EXTRA_UNUSED_13` is free? Or may be I could alter `creature_template_movement`?

**Comment by Shauren** [comment]
You have a table dedicated to movement, why would you even suggest shoving it into extra flags?

**Comment by ccrs** [comment]
that is actually true, I forgot about it, much better 👍

**Pull request merged**
