### PR TITLE
Core/Spells: fixed root behaivior of creatures that are being rooted via movement template while getting a root aura removed

### PR DESCRIPTION
**Pull request by Ovahlord**
-  fixing a small issue that was allowing creatures to bypass their root movement state set in creature_movement_template when a root aura has been removed from that creature.

### CODE REVIEW

**Comment by ccrs** [comment]
this is valid 👍 
Although, I have in mind some more changes regarding root impl, stall this PR for a time please
I actually think I have the spare time to do it tomorrow 💃

**Comment by jackpoz** [comment]
@ccrs could you fix movement generators too while at it :D ?

**Comment by Ovahlord** [comment]
@ccrs that's a pretty long "tomorrow" don't you think so too? What's the state on this one?

**Comment by ccrs** [comment]
awfully busy IRL, will try to deliver soon ™️

**Comment by Aokromes** [comment]
this can be merged?

**Comment by Aokromes** [comment]
this can be merged?

**Comment by Aokromes** [comment]
this can be merged?

**Comment by Wyrserth** [comment]
I'd say yes :P it works fine and prevents the bug as described.

**Comment by ccrs** [comment]
No, dont merge

**Comment by jackpoz** [comment]
@ccrs what about merging it and then you revert it in your PR/commit ?

**Comment by jackpoz** [comment]
@ccrs I'm going to merge this as I don't see any other fix on sight coming anytime soon

**Comment by jackpoz** [comment]
> @ccrs what about merging it and then you revert it in your PR/commit ?
> @ccrs I'm going to merge this as I don't see any other fix on sight coming anytime soon

Anything wrong with this @ccrs ?

**Comment by ccrs** [comment]
On it

**Comment by jackpoz** [comment]
merging this, @ccrs you can revert it with your code when you will finish your local changes

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
