### PR TITLE
Core/Spells: Handle auras 328 & 396 (SPELL_AURA_TRIGGER_SPELL_ON_POWER_*)

### PR DESCRIPTION
**Pull request by Robingadko**
(cherry picked from 37bb37b8d4a0f932df2a80dbb205067ac8625821 and extended)

**Changes proposed:**

-  Add hadlers for `SPELL_AURA_TRIGGER_SPELL_ON_POWER_PCT `and `SPELL_AURA_TRIGGER_SPELL_ON_POWER_AMOUNT`
-  Add `Unit::CheckPowerProc` method to decide when auras should proc

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

None

**Tests performed:**

Built and tested in-game with https://wowhead.com/spell=190488/fulmination-controller

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Comment by Ovahlord** [comment]
I think the old naming  SPELL_AURA_PROC_ON_POWER_AMOUNT is describing the behaivior much more accurately as it's a real proc that's only firing off when meeting the criteria of the aura effect. I'm also a bit surprised that master doesn't have its implementation anymore as it's present in 4.x already and iirc it was a official implementation

**Comment by Traesh** [comment]
First Shauren point is handled in the original code (no removal)

Second point is handled in both original and PR code, as we check for old amount value here : https://github.com/TrinityCore/TrinityCore/pull/26188/files#diff-b4a23722c5b449d326b1c0e5a75f3b51de931e42e688793fd9f1d233536a02c6R10037

For example on 190427 if you go from 0 to 1 you'll trigger the proc because oldValue < 1 && newValue >= 1
If you go from 1 to 2 newValue is indeed >= 1 but oldValue is not < 1 then first effect is not triggered.

**Comment by Shauren** [comment]
Then what are those lines doing here? https://github.com/TrinityCore/TrinityCore/pull/26188/files#diff-b4a23722c5b449d326b1c0e5a75f3b51de931e42e688793fd9f1d233536a02c6R10040-R10041

**Comment by Shauren** [comment]
Closing in favor of me manually redoing the cherry-pick
If you are going to do it, at least don't break the original (and correct) logic

56e9560661adca81fc1e9a297cb6823cf7a6cb22

**Pull request closed without merging**
