### PR TITLE
Core/Creature: Added possibility to give creatures multiple gossip menu ids and control them via conditions

### PR DESCRIPTION
**Pull request by mdX7**
**Changes proposed:**

-  move gossip_menu_id field from creature_template to separate table
-  allow conditions on menu ids
-  

**Tests performed:**

(Does it build, tested in-game, etc.)
built, tested with (just random gossips/conditions, not from retail):
```sql
DELETE FROM `creature_template_gossip` WHERE `CreatureID`=918 AND `MenuID`=4004;
INSERT INTO `creature_template_gossip` (`CreatureID`, `MenuID`, `VerifiedBuild`) VALUES
(918, 4004, 0);

DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 14) AND (`SourceGroup` IN (4004, 4502));
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `Comment`) VALUES
(14, 4004, 0, 0, 0, 9, 0, 176, 0, 0, 0, 'Player has quest WANTED:  "Hogger" (176) active'),
(14, 4502, 0, 0, 0, 9, 0, 176, 0, 0, 1, 'Player has not quest WANTED:  "Hogger" (176) active');

```

### CODE REVIEW

**Comment by offl** [comment]
It can be used to show different gossip when C'Thun is defeated https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15380
But for guids I think they just changes gossip to another in guid-script using their Unit(s) become a gossip https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=19481, same with Pusillin https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=14354

**Comment by mdX7** [comment]
its used for several npcs in shadowlands, e.g. every class trainers (showing different menuid when you aren't the related class) or also some other classic stuff e.g. onyxias/nefarians head quest related npcs

**Comment by offl** [comment]
Yeah, their action changes default menu which is sent to all players

**Comment by Lordron** [comment]
Same for https://www.wowhead.com/npc=69226/skumblade-seadragon and other skumblades, Each have 5-10 different gossips. Creature pick one on spawn and use it

**Comment by mdX7** [comment]
so that means we additionally require something to override the menu id for the lifetime of the creature? pr was mostly for the classtrainers based on info by @Naddley

**Comment by Lordron** [comment]
> > Same for https://www.wowhead.com/npc=69226/skumblade-seadragon and other skumblades, Each have 5-10 different gossips. Creature pick one on spawn and use it
> 
> so that means we additionally require something to override the menu id for the lifetime of the creature? pr was mostly for the classtrainers based on info by @Naddley

Yeah, we can cache menuId at spawn and then return in GetGossipMenuForSource. Then re-cache on condtition change.

**Comment by mdX7** [comment]
> > > Same for https://www.wowhead.com/npc=69226/skumblade-seadragon and other skumblades, Each have 5-10 different gossips. Creature pick one on spawn and use it
> > 
> > 
> > so that means we additionally require something to override the menu id for the lifetime of the creature? pr was mostly for the classtrainers based on info by @Naddley
> 
> Yeah, we can cache menuId at spawn and then return in GetGossipMenuForSource. Then re-cache on condtition change.

i think we can just do that via script. I don't know of any other npcs besides the Skumblades which show this behavior. So we are talking about 10ish npcs with a random menu id which is "defined" on spawn

**Comment by Shauren** [comment]
Is this still required after 09568736134372ec1a79b936a248eec30f071c8d?

**Comment by mdX7** [comment]
Yes, as its required to check several conditions on the player and the resulting menu id is also per player

**Review by meji46 — APPROVED** [review]

**Pull request merged**
