### PR TITLE
Core/Wintergrasp: Implement worldstates for Archavon's log

### LINKED ISSUE #16880: [3.3.5] DB/GO: Archavon's Log - Missing Counter
**Description**:
http://www.wowhead.com/object=194356/archavons-log#comments
Archavon's Log should shows the number of:
Horde:  
 Keep Defended: $4024w
 Keep Captured: $4022w

Alliance:
 Keep Defended: $4025w
 Keep Captured: $4023w

**Current behaviour**: Tell us what happens
if you open Archavon's Log the result will be:
```sql
Horde:  
 Keep Defended: 0
 Keep Captured: 0

Alliance:
 Keep Defended: 0
 Keep Captured: 0
```
even if you just won/loose a couple of games/wintergraps

**Expected behaviour**: Tell us what should happen instead
If you open open the book, there should be the number of all won/loosed matches of wintergrasp for the horde and for the alliance.

**Steps to reproduce the problem**:
.go object 87581
.bf start 1
.bf stop 1
open book > see that there will be no change at all

**Branch(es)**: 335 (6.x not tested)

**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/8d992a888c6618737e5324b4c424f0a5e324b531

**TDB version**:
DB 335.60

**Operating system**: 
Windows 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### PR DESCRIPTION
**Pull request by Gerhood**
**Changes proposed:**

Send and update worldstates for Archavon's log

**Target branch(es):** 3.3.5/6.x

**Issues addressed:** Closes #16880

### CODE REVIEW

**Comment by ariel-** [comment]
I had this work on hold, currently updating BG scripts:

https://github.com/ariel-/TrinityCore/commit/af37d1c6d2219e43c4856a51eeefb23db1a6b88f

**Comment by tkrokli** [comment]
@Gerhood : your files are probably conflicting with the commit ariel- just pushed.
You need to either merge or rebase your PR source and push again, unless this is duplicate work.

**Comment by Expecto** [comment]
worldstates 4022 not in WorldStateUI.dbc

**Comment by Gerhood** [comment]
Yeah whatever

**Pull request closed without merging**
