### PR TITLE
Core/Scripts: make "The Crone" in Karazhan attackable to players

### LINKED ISSUE #15426: [3.3.5a]The Crone doesn't become attackable during the Opera Event
Revision: 2bcd9c543f1f

After killing Roar, Dorothee, Tinhead, Strawman and Tito, The Crone correctly spawns, but does not become attackable. You drop combat, and if you teleport out of the instance and come back you can start up another event. The Crone will still be present during the new encounter.

### PR DESCRIPTION
**Pull request by dubitabam**
fixes #15426 

second approach :)

### CODE REVIEW

**Comment by MitchesD** [comment]
this isn't correct way, these flags are removed when EnterCombat, so I am not sure if that issue is really valid

**Comment by Killyana** [comment]
The problem is EnterCombat is never triggered due to UNIT_FLAG_IMMUNE_TO_PC. BTW it's the only boss in bosses_opera.cpp  that use EnterCombat to remove this flags, the others are using MoveInLineOfSight to remove UNIT_FLAG_NON_ATTACKABLE

**Comment by tkrokli** [comment]
@daevidpreis : Please update this page to use the correct NPC name in the title and your commit:
"The Crone" - http://www.wowhead.com/npc=18168/the-crone

Since you need to edit the title anyway, I suggest the following wording based on TC standards:
**Core/Scripts: remove UNIT_FLAG_IMMUNE_TO_PC from "The Crone" (Karazhan)**

**Comment by tkrokli** [comment]
@daevidpreis : I checked with the devs in #trinity and verified that @Expecto's  suggestion is correct.

**Comment by daevidpreis** [comment]
@tkrokli ok changed that and the one in line 704 `EnterCombat` too

**Comment by MitchesD** [comment]
As I said before, it's wrong, removing flag in constructor is nonsense, if so, then this flag will be removed for all time, then its useless to remove it in EnterCombat, I think proper way is remove it in MoveLineInSight, or when event starts, but I am sure, that in constructor it's WRONG.

**Comment by daevidpreis** [comment]
@MitchesD advise taken. you think this is the correct way?

**Comment by MitchesD** [comment]
@daevidpreis no, that's not correct, the result is the same, removing flag on spawn. I think correct way is removing on attack start or on move, but for sure not on spawn.

**Comment by daevidpreis** [comment]
i think attack start will never happen as long as the flag is set. i tried it in MoveInLineOfSight, but then players can drop combat and regenerate before engaging her.

**Comment by MitchesD** [comment]
this is still wrong, if you are still interested in, find a better way.

**Comment by Rushor** [comment]
sadly @daevidpreis no longer has time for anything related to tc :/

**Pull request closed without merging**
