### PR TITLE
a script for implementing TrinityCore

### PR DESCRIPTION
**Pull request by alzee**
**Changes proposed:**
-  add a bash script for implementing TrinityCore 6.x or 3.3.5

**Target branch(es):** 3.3.5/6.x

**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc)

**Known issues and TODO list:**

tcinit is a script for Redhat derivative to implement TrinityCore 3.3.5 or 6.x
Including requirements installation, clone repo, cmake, make, sql import, maps extraction and more.
All you need to do is download the TDB_full_*.7z from https://github.com/TrinityCore/TrinityCore/releases and put it into directory where tcinit at, tcinit --init will do the rest.

### CODE REVIEW

**Comment by DDuarte** [comment]
Thanks but the forums might be a better place for scripts like this.

**Comment by Dotcra** [comment]
yeah, I think so. But I got stuck in registration by 'What color are tree leaves?', no idea.

**Comment by DDuarte** [comment]
We ask that?! Try green.

**Comment by tkrokli** [comment]
@Dotcra : been a while since you have been outdoors and seen what nature looks like? ;-)

**Comment by Dotcra** [comment]
oh yeah, green just passed, how stupid I am

**Comment by KingPin** [comment]
thats a stupid question.... the forum admin who made that should be beaten with two sticks.

**Pull request closed without merging**
