### PR TITLE
Core/Creature: equipment_id field on creature table is not working co…

### PR DESCRIPTION
**Pull request by Aokromes**
…rrectly, if it's set to 0 the npc still spawn with the equipement.

By Malcrom
Closes TrinityCore#16416

### CODE REVIEW

**Comment by Killyana** [comment]
Tested and works as intended.
For DB spawns:
If equipment_id=0 no equipment loaded
If equipment_id=n>0  equipment=n is loaded
If equipment_id=-1 a random equipment is loaded

For a summoned npc: the first equipment in the DB will be loaded

For npcs that use scripts to load equipments it works fine.

**Comment by malcrom** [comment]
But why would a summoned npc have an equipment 2 and no equipment 1?

**Comment by Killyana** [comment]
Maybe there's no equipment=1

**Comment by malcrom** [comment]
Shouldn't 2 be changed to 1 then? These are not sniffed values.

**Comment by Killyana** [comment]
Yes we can change this cases, in 3.3.5 there's only 2

**Comment by malcrom** [comment]
UPDATE `creature_equip_template` SET `ID` = 1 WHERE `CreatureID`=23784;

**Comment by Killyana** [comment]
It' not a summoned npc so it doen't matter

**Comment by jackpoz** [comment]
If this PR requires some SQL scripts, please include those in the PR.
By git blaming the modified code, it seems like it went through quite many changes in the past, so please check how this will affect other creatures too, not just the one reported in https://github.com/TrinityCore/TrinityCore/issues/16416

**Comment by Killyana** [comment]
I already tested all cases, every thing works correctly, I will not provide any sql before this pr is merged as it requires lots time, and it looks this pr is refused.

**Comment by jackpoz** [comment]
But "as it requires lots of time" means that if we merge it now, 335 will be broken until you decide to push whatever SQL is required. While if this PR gets compete properly, it can be merged.

**Comment by malcrom** [comment]
Update creature SET equipment_id=1 WHERE equipment_id=0 AND  id = (SELECT CreatureID  FROM creature_equip_template WHERE ID=1);

**Comment by Killyana** [comment]
Push the PR, if all equipments are not fixed in both branchs until tomorrow, revert it.

**Comment by illfated** [comment]
Do we have a known list of NPCs not wearing/using/wielding equipment, but should be able to do so after this PR gets merged? Or will we need to apply DB changes (SQL files) after this PR is merged to see actual changes? (At the moment, the only NPC I can remember not using his intended tool/weapon is [Awilo Lon'gomba `<Grand Master Cooking Trainer>`](https://woehead.way-of-elendil.fr/?npc=29631) (NPC ID 29631) in Dalaran.)

**Comment by malcrom** [comment]
ATM there are npcs with equipment that shouldn't have it. This along with Kilyanas SQL will put it at the same state but give us the ability to fix the NPCs that shouldn't have equipment.

**Pull request merged**
