### PR TITLE
Core/Pools: Fixed a bug in explicitly + equally chanced pools

### PR DESCRIPTION
**Pull request by lachtanek**
Fixed a bug introduced in https://github.com/TrinityCore/TrinityCore/commit/de80cd2e0de470522a734e8e7a65e81b82bfc5fb (https://github.com/TrinityCore/TrinityCore/issues/21032).
@Killyana, can you please test it?
I can't do it right now, but I think this is simple enough fix to not need any extensive testing.

### CODE REVIEW

**Comment by Treeston** [comment]
Please explain what the PR does and how it achieves it.

**Comment by lachtanek** [comment]
In my first PR, I fixed a bug in pools which resulted in less and less objects being spawned the more were respawned basically. Sadly, I misunderstood one part of the pooling system (explained here https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130271/pool+gameobject#pool_gameobject-chance) and broke this. there was apparently a bug that triggering object couldn't spawn (https://github.com/TrinityCore/TrinityCore/pull/20949#issuecomment-350083960), fixed that one aswell.
This PR should fix bugs.
Sorry for not clarifying this in original post.

**Comment by Killyana** [comment]
No change, this gobs still not spawned.

**Comment by lachtanek** [comment]
Okay, thanks, will look into that probably tomorrow

**Comment by lachtanek** [comment]
Should be fixed now, tested on pool 311, spawned ok after server start and respawned after 1st loot.

**Comment by Killyana** [comment]
Yes this fix the issue #21032 but #19257 still happen, probably not related to this PR.

**Comment by lachtanek** [comment]
What exactly is a problem there? I can't seem to understand it from the comments, they seem to be talking about multiple different issues.

**Comment by Killyana** [comment]
It's pretty simple: .go c 86075
You will see 4 mobs in this pit, everyone has a pool at the exact same position it could be Entry: 4131or Entry: 4133
Kill and respawn this 4 npcs many times, you will notice at some point they will not respawn.

**Comment by lachtanek** [comment]
The issue is that the creature is part of new spawning system.
What happened before was that when PoolMgr::SpawnObject was called, the creature was already in world (called here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Creature/Creature.cpp#L2066) and pool system either selected it and left it spawned, or not and despawned it.
What happens with new spawning system, old creature is deleted and a new one is spawned. The problem is, if Map::CheckRespawn finds out that it is pooled creature, it doesn't do anything and leaves the respawn on pool system. Same thing will probably happen to GOs.

One solution is for map to respawn the creature anyway and pool system might despawn it right away, if it feels that way (or if it is not rolled), which feels hacky (same kind of hacky as current system).
Other solution is to somehow pass the info about whether creature is dynamically spawned or not to pool system, or let it find out somehow, which doesn't feel right either.
Third solution may be to wait for new pool system -_-
Should I try to fix it regardless?

**Comment by offl** [comment]
> The issue is that the creature is part of new spawning system.

This bug was here since the pool implementation. This bug occurs on other mangos-based projects(vanilla, for example).

> Should I try to fix it regardless?

It's a different issue, maybe in a new PR?

**Comment by Killyana** [comment]
I tried to reproduce it in an older revision without dynamic spawn, and the issue never happen, it's definitively related to dynamic spawns, maybe @r00ty-tc can help with that.

**Comment by Shauren** [comment]
Since this PR is confirmed to fix #21032 and does not even attempt to fix #19257 then its good to go

**Comment by shamage** [comment]
Hi, two days ago I went to the repair - see the attachment, and I did a new compilation of the DB, but now after the update I will not start the server and write the error (see the picture in the attachment). Do you know how to fix me? Thank you for your advice!

**Comment by tkrokli** [comment]
This is not a forum. Please use the TrinityCore forum pages for questions about personal configuration, or ask in the **#trinity** help channel on IRC (see https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC for details).

**Pull request merged**
