### PR TITLE
Core/Scripts: Correction to Uncontrollable Frenzy, Queen Lana'thel

### PR DESCRIPTION
**Pull request by mik1893**
**Target branch**: 335/6x
**Issues addressed**: Prevents queen lana'thel to cast frenzy effects on  herself increasing life by 300%
**Tests performed**: Tested in game
**Known issues and TODO list**: none

### CODE REVIEW

**Comment by Shauren** [comment]
And how would that even happen in the first place?
Also never delete by spell_id, always by ScriptName

**Comment by mik1893** [comment]
the spell 70924 has TARGET_UNIT_CASTER
it happens many times that she casts the frenzy effect on herself, as it's using the spell_linked_spell stuff. 

Spell 70924
 Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 300
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 133 (SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT), value = 300, misc = 0 (0), miscB = 0, periodic = 0

**Comment by tkrokli** [comment]
Cosmetic adjustments to your SQL, add back ticks to the column names like this:
```sql
--
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`= 70923 and `spell_effect`= 70924;
DELETE FROM `spell_script_names` WHERE `ScriptName`='spell_blood_queen_uncontrollable_frenzy';
INSERT INTO `spell_script_names` VALUES (70923,'spell_blood_queen_uncontrollable_frenzy');
```
For DB merging, it is practical to add a comment marker on top of the SQL, like in this example.

**Comment by mik1893** [comment]
thanks @tkrokli i was quite sure you were going to do that for me :dancer:

**Pull request closed without merging**
