### PR TITLE
[3.3.5] Core/Spell: Chain heal won't bounce on 100% hp targets 

### PR DESCRIPTION
**Pull request by PolarCookie**
**Changes proposed:**
Chain heal should not bounce on targets with 100% hp, rather stop early, or not bounce at all if cast in a fully healed raid.
It's been a while since I fixed this issue, so I don't have any reference videos anymore.
This matters as rshamans get incorrect procs of Improved Water Shield.

The condition I removed translates to "pick the first target in the list, no matter what", while now it's picking the highest hp deficit target every bounce.

**Target branch(es):**
- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.)
Builds and works in-game

### CODE REVIEW

**Comment by pedroevil51** [comment]
Tested on https://github.com/TrinityCore/TrinityCore/commit/c48a596c66c075c876c860a7d5c036d033de0b9d

**Review by klister803 — APPROVED** [review]
Working on latest commit

**Comment by pedroevil51** [comment]
@Keader Will record soon as possible

**Comment by PolarCookie** [comment]
@pedroevil51 I think he meant proof of blizzard behavior.

@Keader 
I don't have the original video I worked from, it's been a while, but found
https://youtu.be/fHWBIwHfuNE?t=3m5s
There's several examples throughout the video, but it's hard do tell sometimes.
That timestamp shows the tank getting a CH that doesn't bounce when everyone is full, shortly after the aoe happens and usual bounces happen.

https://youtu.be/TsiDglz4L5s?t=1m54s
I counted 6 no-bounce chain heals in that fight

https://youtu.be/KcslDMFyL_8?t=2m30s.
Check also the first trash pack in the video, sequence of some CH-with-bounce then a CH-no-bounce on the iceblocked mage.

Also casting a shaman pentagram should be possible (first video probably from TBC, second definetly cata+).
https://www.youtube.com/watch?v=8p0y185dE30
https://www.youtube.com/watch?v=AY25zV96pnA

**Comment by PolarCookie** [comment]
By happy coincidence; found this.
https://forum.gamer-district.org/topic/43125-chain-heal-jumping/

By Fluffybully
> **Name of issue:**
>
> It jumps off ppl who're at 100% HP.
> 
> **How it should work:**
> 
> Chain heal shouldn't jump on full health players. This means that when you CH a player and everyone around this player is full, the CH should stop jumping.
> 
> You can see that on https://www.youtube.com/watch?v=RSeVCw3hVgQ (patch 3.3 movie on retail, lich king world first kill), at 5.10.
> You can see this happening a lot more in https://www.youtube.com/watch?v=Pf4MAONG1vs (patch 3.1 movie on retail, world first yogg saron normal mode) for example at 9.52
> If you watch https://www.youtube.com/watch?v=EW4W21KMQWU (retail patch 4.3) you can notice that it's still the same thing : CH doesn't bounce on full HP players. For example at 2.56 when everyone around the shaman is shielded and full, He casted CH on himself and it didnt jump. You can also see that at 24.47. And again at 25.15. However this doesn't happen a lot because the shaman is playing quite well.
>  
> 
> https://web.archive.org/web/20100807233504/http://elitistjerks.com/f47/t99442-shaman_restoration/
> CH part : "Jumps to 3 targets (or 4 with a glyph). Jumps are based on who is missing the most health (by absolute value). If there are no targets in range below 100% it will not jump. The heal can jump back to the shaman if they have taken damage."
> 
>  
> 
> p.s am ready for the hate xD
>

**Comment by illfated** [comment]
Cosmetic details, but still; improvement suggestion for the PR title:
**[3.3.5] Core/Spells: Chain Heal should not bounce on targets with 100% hp**

Also, to any of the TC members with access to changing labels:
replace **[Comp-C++Script]** with **[Comp-Core]** (src/server/game/Spells/Spell.cpp)

**Pull request merged**
