### PR TITLE
Core/SAI: Fix SMART_EVENT_FLAG_NOT_REPEATABLE flag being ignored when specifying a chance (and other SMART_ACTION_CAST fixes)

### LINKED ISSUE #25209: Core/SAI: SMART_EVENT_UPDATE_OOC seems to ignore %-chance
**Description:**

While i was messing around with [Scarshield Portal](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=9707#abilities) script by removing the despawn, i noticed that OOC completly ignores the percentage chance for casts. The Burning Felguards have been summoned in every lifetime of the portal.
Might be the case that it completely ignores event conditions.

**Expected behaviour:**

Non 100% chances should be recognized by SMART_EVENT_UPDATE_OOC

**Steps to reproduce the problem:**

1. 
```sql
DELETE FROM `smart_scripts` WHERE (`entryorguid` = 9707) AND (`source_type` = 0) AND (`id` IN (3));
``` 
This is to prevent the Portal form despawn itself after 10 seconds
2. go c id 9257 and get in combat with the warlocks
3. Watch

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

174ac958009222aeef83520101a28963f8c63b0e

**Operating system:** Win10

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

- Fix SMART_EVENT_FLAG_NOT_REPEATABLE flag being ignored when specifying a chance, always making the action trigger.
- Fix SMART_ACTION_CAST with SMART_EVENT_FLAG_NOT_REPEATABLE not casting the spell at all if rolled chance was successful but creature couldn't cast the spell
- Prevent linked actions if SMART_ACTION_CAST couldn't be completed and will be retried later

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #25209

**Tests performed:**

.npc add temp 18037

image

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Fix more SAI stuff that @offl wants
- [ ] Test again all the cases

### CODE REVIEW

**Comment by jackpoz** [comment]
Added "Fix SMART_ACTION_CAST with SMART_EVENT_FLAG_NOT_REPEATABLE not casting the spell at all if rolled chance wasn't successful" fix

**Comment by jackpoz** [comment]
Added "Prevent linked actions if SMART_ACTION_CAST couldn't be completed and will be retried later"

**Comment by illfated** [comment]
Pretty neat to have that circleci codestyle_and_sql check for all PRs to notice forgotten redundant whitespace.

**Comment by jackpoz** [comment]
btw if anyone could write a SAI script for each case and write what to expect, I could test it and debug to see if there are issues.

**Comment by offl** [comment]
> Fix SMART_EVENT_FLAG_NOT_REPEATABLE flag being ignored when specifying a chance, always making the action trigger.

Seems like you already tested this

> Added "Fix SMART_ACTION_CAST with SMART_EVENT_FLAG_NOT_REPEATABLE not casting the spell at all if rolled chance wasn't successful" fix

Don't understand what was the issue. It's non-repeatable, chance roll wasn't sucessful, why we should try again?

> Prevent linked actions if SMART_ACTION_CAST couldn't be completed and will be retried later

Can't reproduce without fix right now, will try again when I'll have time

**Comment by offl** [comment]
> Prevent linked actions if SMART_ACTION_CAST couldn't be completed and will be retried later

```sql
DELETE FROM `smart_scripts` WHERE `entryorguid` =36478;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES('36478','0','0','0','0','0','50','0','0','10000','16000','20000','0','11','69056','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Soulguard Watchman - In Combat - Cast \'Shroud of Runes\'');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES('36478','0','1','2','0','0','100','0','8000','16000','32000','40000','0','11','69053','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Soulguard Watchman - In Combat - Cast \'Unholy Rage\' (Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES('36478','0','2','0','61','0','100','0','0','0','0','0','0','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Soulguard Watchman - In Combat - Say Line 0 (Dungeon)');
```

.npc add temp 36478
aggro it
target and .cast back 25900
wait
tested right now and got 100 emotes in 3 seconds

**Comment by offl** [comment]
If related to fix №2

.npc add temp 22105
aggro it
target and .cast back 25900
.dam 5000

Creature performs emote, no cast (creature is stunned)

.unaura all

no cast

**Comment by jackpoz** [comment]
>Fix SMART_ACTION_CAST with SMART_EVENT_FLAG_NOT_REPEATABLE not casting the spell at all if rolled chance was successful but creature couldn't cast the spell

Updated the description, it was written wrong

**Comment by jackpoz** [comment]
> tested right now and got 100 emotes in 3 seconds

I tested this with this PR and it did the emote only after I did ".unaura all" . were the 100 remotes without this PR or ?

**Comment by offl** [comment]
>> tested right now and got 100 emotes in 3 seconds
>
>I tested this with this PR and it did the emote only after I did ".unaura all" . were the 100 remotes without this PR or ?

100 emotes without PR, I didn't tested something with PR

> is there anything else to test/fix before merging this PR ?

Seems everything is good

**Review by offl — APPROVED** [review]

**Pull request merged**
