### PR TITLE
DB/Account: update account_access table

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

- rename fields id -> AccountID, gmlevel -> SecurityLevel
- add Comment field
- rename command .acc set gmlevel to .acc set seclevel

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Tests performed:** (Does it build, tested in-game, etc.)
Tested, build

### CODE REVIEW

**Comment by jackpoz** [comment]
A concern from the user point of view: after years and years of using .account set gmlevel , it will feel puzzling to get a "command not found". We might have to announce the change on the forum so more people will be aware of the change.

It should be possible to define both commands in cs_account.cpp with same permissions and handler so that for some time they both work. Could you please check this ?

**Comment by ForesterDev** [comment]
@jackpoz, done :)

**Comment by jackpoz** [comment]
@ForesterDev could you please merge 3.3.5 into this PR to fix the merge conflicts ? thanks 😃

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by tsarevpp** [comment]
Hey, for me the SHA1 hash for the `2020_06_20_00_au
th.sql` file is `19917cc5ed99eceba626351dfeca01258227fc01`. Could you please check if that is the correct hash?

**Comment by jackpoz** [comment]
I cannot reproduce the issue:
- MySQL 8 on Ubuntu 20.04
image
image

- MySQL 5.7 on Windows 10
image

**Pull request merged**
