### PR TITLE
[3.3.5] Core/Spells: break Stealth and modify Stand State

### LINKED ISSUE #14819: [3.3.5] harmful spell hit with stand state and stealth
Currently (562da2e) only harmful CC spells will break stealth and modify the unit stand state.

This behaviour is wrong. All harmful spell hit should break stealth and modify the stand state. There are a few exception for the stealth break mechanic such as:
* Mass Dispel (http://wowwiki.wikia.com/Mass_Dispel - Patch 2.2.0 (25-Sep-2007): Has a chance to be resisted when dispelling immunity effects. This will be displayed in the combat log. In addition, it will no longer cause rogues and druids in Cat Form to lose Stealth. The flashing area graphic has been removed.)
* Earthbind Totem (Pulse) (http://wowwiki.wikia.com/Earthbind_Totem - Patch 2.2.0 (25-Sep-2007): Earthbind Totem no longer breaks stealth.)
* Distract (http://www.wowhead.com/spell=1725/distract#comments:id=814676 - It doesn't break stealth. But for instance if it's a rogue on rogue fight distract can actually cost him enough time such that you will be able to pull off a cheapshot on him.)
We don't have a spellAttr that states that spells should not break stealth on harmful spell hits. I also can't find them having something common.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/19173168-3-3-5-harmful-spell-hit-with-stand-state-and-stealth?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
by @robinsch; closes #14819

Currently (562da2e), only harmful CC spells will break stealth and modify the unit stand state.
This behaviour is wrong. All harmful spell hits should break stealth and modify the stand state.

There are a few exceptions for this mechanic, such as:
- Mass Dispel (priest spell ID 32375, 32592, 39897)
- Earthbind Totem (Pulse) (spell ID 3600)
- Distract (rogue spell ID 1725)

### CODE REVIEW

**Comment by robinsch** [comment]
Update. All harmful spells should modify the stand state.
```diff
My bad, all harmful spells should modify the stand state. It was common to break enemys drinking with mass dispel or distract in arena.

```diff
From 3e95e84a76926d1de7fe18f9bcc7c3ee1b68cd01 Mon Sep 17 00:00:00 2001
From: robinsch <robin.schriever.hude@web.de>
Date: Mon, 1 Jun 2015 12:28:19 +0200
Subject: [PATCH] #14819

---
 src/server/game/Spells/Spell.cpp    |  9 ++++-----
 src/server/game/Spells/SpellInfo.h  |  2 +-
 src/server/game/Spells/SpellMgr.cpp | 24 ------------------------
 3 files changed, 5 insertions(+), 30 deletions(-)

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 3c78540..4a9cc33 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -2425,9 +2425,8 @@ void Spell::DoAllEffectOnTarget(TargetInfo* target)
     {
         m_caster->CombatStart(unit, !m_spellInfo->HasAttribute(SPELL_ATTR3_NO_INITIAL_AGGRO));
 
-        if (m_spellInfo->HasAttribute(SPELL_ATTR0_CU_AURA_CC))
-            if (!unit->IsStandState())
-                unit->SetStandState(UNIT_STAND_STATE_STAND);
+        if (!unit->IsStandState())
+            unit->SetStandState(UNIT_STAND_STATE_STAND);
     }
 
     if (spellHitTarget)
@@ -2511,8 +2510,8 @@ SpellMissInfo Spell::DoSpellHitOnUnit(Unit* unit, uint32 effectMask, bool scaleA
         if (m_caster->_IsValidAttackTarget(unit, m_spellInfo))
         {
             unit->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_HITBYSPELL);
-            /// @todo This is a hack. But we do not know what types of stealth should be interrupted by CC
-            if (m_spellInfo->HasAttribute(SPELL_ATTR0_CU_AURA_CC) && unit->IsControlledByPlayer())
+
+            if (!m_spellInfo->HasAttribute(SPELL_ATTR0_CU_DONT_BREAK_STEALTH))
                 unit->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);
         }
         else if (m_caster->IsFriendlyTo(unit))
diff --git a/src/server/game/Spells/SpellInfo.h b/src/server/game/Spells/SpellInfo.h
index f2808a0..1c3f9af 100644
--- a/src/server/game/Spells/SpellInfo.h
+++ b/src/server/game/Spells/SpellInfo.h
@@ -176,7 +176,7 @@ enum SpellCustomAttributes
     SPELL_ATTR0_CU_CONE_LINE                     = 0x00000004,
     SPELL_ATTR0_CU_SHARE_DAMAGE                  = 0x00000008,
     SPELL_ATTR0_CU_NO_INITIAL_THREAT             = 0x00000010,
-    SPELL_ATTR0_CU_AURA_CC                       = 0x00000040,
+    SPELL_ATTR0_CU_DONT_BREAK_STEALTH            = 0x00000040,
     SPELL_ATTR0_CU_DIRECT_DAMAGE                 = 0x00000100,
     SPELL_ATTR0_CU_CHARGE                        = 0x00000200,
     SPELL_ATTR0_CU_PICKPOCKET                    = 0x00000400,
diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 1c79e34..91903c3 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -2801,14 +2801,6 @@ void SpellMgr::LoadSpellInfoCustomAttributes()
         {
             switch (spellInfo->Effects[j].ApplyAuraName)
             {
-                case SPELL_AURA_MOD_POSSESS:
-                case SPELL_AURA_MOD_CONFUSE:
-                case SPELL_AURA_MOD_CHARM:
-                case SPELL_AURA_AOE_CHARM:
-                case SPELL_AURA_MOD_FEAR:
-                case SPELL_AURA_MOD_STUN:
-                    spellInfo->AttributesCu |= SPELL_ATTR0_CU_AURA_CC;
-                    break;
                 case SPELL_AURA_PERIODIC_HEAL:
                 case SPELL_AURA_PERIODIC_DAMAGE:
                 case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
@@ -2901,22 +2893,6 @@ void SpellMgr::LoadSpellInfoCustomAttributes()
         if (spellInfo->SpellVisual[0] == 3879)
             spellInfo->AttributesCu |= SPELL_ATTR0_CU_CONE_BACK;
 
-        switch (spellInfo->SpellFamilyName)
-        {
-            case SPELLFAMILY_WARRIOR:
-                // Shout
-                if (spellInfo->SpellFamilyFlags[0] & 0x20000 || spellInfo->SpellFamilyFlags[1] & 0x20)
-                    spellInfo->AttributesCu |= SPELL_ATTR0_CU_AURA_CC;
-                break;
-            case SPELLFAMILY_DRUID:
-                // Roar
-                if (spellInfo->SpellFamilyFlags[0] & 0x8)
-                    spellInfo->AttributesCu |= SPELL_ATTR0_CU_AURA_CC;
-                break;
-            default:
-                break;
-        }
-
         spellInfo->_InitializeExplicitTargetMask();
     }
 
-- 
1.9.5.msysgit.1

```

**Comment by tkrokli** [comment]
OK, let me see if I get this. Remove the SQL file and only apply the changes above to the original files?

**Comment by robinsch** [comment]
Keep the SQL file and only apply changed from above.

**Comment by tkrokli** [comment]
"only apply changed from above." ... to the existing Pull Request files? OK, I will do that.

**Comment by robinsch** [comment]
The only diff is that I renamed the ATTR and removed it from the check above unit->SetStandState(UNIT_STAND_STATE_STAND);.

**Comment by tkrokli** [comment]
OK, thanks for confirming. :+1:

**Comment by Drektharroz** [comment]
@Aokromes Why not accepted yet?

**Comment by tkrokli** [comment]
Thanks for commenting, @Drektharroz, I wasn't sure either. I don't know if this fix isn't important enough or if there is something wrong about it. I just don't know. There are no comments to go from.

**Comment by mik1893** [comment]
is this working as intended?

**Comment by Rushor** [comment]
+ didn't found any complication

you may can add hunters mark + mage invis linked spell  to the spell_custom_attr list

**Comment by mik1893** [comment]
@tkrokli please add the stuff @Rushor is asking for

**Comment by Rushor** [comment]
aka these ones:
```sql
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (1130, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (32592, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (39897, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (3600, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (1725, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (14323, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (14324, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (14325, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (53338, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (35009, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (32375, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (42650, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (43264, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (58833, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (58832, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (58831, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (43263, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (58834, 64);
REPLACE INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (58838, 64);
```

**Comment by tkrokli** [comment]
Oh, right. I'm :on: it. I almost had "a day off" from checking my PRs, thanks for the feedback! :+1:

**Comment by robinsch** [comment]
It's a server side spell, spell_dbc.

**Comment by tkrokli** [comment]
OK, thanks a lot for the info. Looked it up in DB and found the comment: `Invisibility - Reducing threat`
http://wow-mania.com/armory/?spell=35009 (Serverside - Invisibility - Reducing threat)
http://www.wowhead.com/spell=66/invisibility (naming Spell #35009, but linked page removed)

Adding it back to the list and updating the PR in a few minutes. :)

**Comment by tkrokli** [comment]
Just a detail about the commit message in this PR: should I add the other spells to the message list?

**Comment by w5860363** [comment]
DB Spell_dbc 35009 Laugh effect
remove effect Disappear

**Comment by jackpoz** [comment]
this PR modifies same lines as https://github.com/TrinityCore/TrinityCore/pull/14765

**Comment by robinsch** [comment]
#14765 is a workaround and doesn't cover the intended mechanic used in this PR.

**Comment by Aokromes** [comment]
So, close #14765 ?

**Comment by tkrokli** [comment]
@Aokromes : pjasicek's account page does not show any activity after 2015-05-31, so I think it will be difficult to get a comment from him regarding his PR. As you noticed, robinsch is available for comment. You can of course check with any of the main TC devs for confirmation on which changes are preferred.

**Comment by robinsch** [comment]
Yes close #14765

**Comment by jackpoz** [comment]
Just a note: 35009 was added in the DELETE statement of the SQL script. I'll modify it locally and then merge the PR.

**Comment by tkrokli** [comment]
Good observation, thanks for fixing that missing entry. :+1:

**Pull request merged**
