### PR TITLE
Core/Spells: Fix wrong totem placement

### PR DESCRIPTION
**Pull request by Eliminationzx**

### CODE REVIEW

**Comment by Rushor** [comment]
thanks fpr the pr :)

**Comment by Kittnz** [comment]
You should fix these commits, you added 3 more commits in this PR.

**Comment by Rushor** [comment]
@Eliminationzx : are you going to push a new fresh pr? :)

**Comment by Eliminationzx** [comment]
Yes. Sorry for that mistake.

**Comment by Keader** [comment]
why you dont use squash? '-'

**Pull request closed without merging**
