### PR TITLE
Core/Scripts: update warrior Charge to 7.1.5

### PR DESCRIPTION
**Pull request by HannibalRoG**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Update Warrior charge to 7.1.5

**Target branch(es):** 3.3.5/master

- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
I dont find any

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled and tested looks blizzard to us.

### CODE REVIEW

**Comment by Eredar** [comment]
Charge movement need to be rewritten, I managed to get under textures few times. Easiest way to reproduce it is to charge to Orc starting location training dummies. If you use it behind the rock with dummie as target you will fall down under the ground.

**Comment by HannibalRoG** [comment]
I can confirm that happend to me as you said the first 2 times I used the charge, the rest the worst thing was to cross the graph but it came correctly to the target, I attached an image to see if it is from there that happens.
Anyway it seems to me that this has nothing to do with the script as such.
If I am wrong correct me.

charge

**Comment by funjoker** [comment]
Well the Charge itself is broken i think. So not the spell.. The SPELL_EFFECT_CHARGE

**Comment by HannibalRoG** [comment]
What happened to Travis?

**Comment by Aokromes** [comment]
```code
/home/travis/build/TrinityCore/TrinityCore/src/server/game/Movement/Spline/MoveSplineInit.cpp:92:35: fatal error: 
      '&' within '|' [-Wbitwise-op-parentheses]
            moveFlags = moveFlags & ~(MOVEMENTFLAG_BACKWARD) | MOVEMENTF...
                        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~ ~
/home/travis/build/TrinityCore/TrinityCore/src/server/game/Movement/Spline/MoveSplineInit.cpp:92:35: note: 
      place parentheses around the '&' expression to silence this warning
            moveFlags = moveFlags & ~(MOVEMENTFLAG_BACKWARD) | MOVEMENTF...
                                  ^
                        (                                   )

**Comment by Shauren** [comment]
Thats an error from master branch, ignore

**Comment by P-Kito** [comment]
Can you charge while rooted or does it give you an error?

**Comment by HannibalRoG** [comment]
When charging while being rooted or frozen does not evaluate the target but applies all other effects. Does this have to do with the problem of the charge commented for @Eredar or is our script that is incomplete?

**Comment by funjoker** [comment]
This is a Problem of the Script. Actually He needs to make 2 Scripts.
One must be added to the Charge spell itself.

Making debuff applied to target OnHit.

**Comment by Shauren** [comment]
@funjoker are you sure about that? iirc charge applies root on cast to make sure you are on target when you arrive

**Comment by funjoker** [comment]
Gonna check that :D .
If not he needs to apply a check if not rooted.

**Comment by funjoker** [comment]
Okay. @Shauren you are right.
So adding a check before cast.

**Comment by P-Kito** [comment]
Wrong. Charge now applies effects on arrival. Was changed last patch/hotfix.

image

**Comment by Golrag** [comment]
That's a 7.2 PTR change, on 7.1.5 it does not do any damage and the debuffs (root (105771) and slow (236027)) are applied to the target before you reach them

**Comment by P-Kito** [comment]
Woops. You are right. Lul.

**Comment by wonder2011** [comment]
So a code like this would be fine here ?

`GetCaster()->ToPlayer()->RemoveMovementImpairingAuras();`

**Comment by Seyden** [comment]
Well something is missing..

The new charge has SpellEffectExtraData

```
Effect 0: Id 96 (SPELL_EFFECT_CHARGE) DIFFICULTY_NONE
BasePoints = 0
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
EffectMiscValueB = 45080
```

look at the MiscValue.. actually charge isn't finished when he doesn't use the misc..

**Comment by HannibalRoG** [comment]
This is the actual effect for charge in 7.1.5 spell id 100

Effect 0: Id 3 (SPELL_EFFECT_DUMMY) DIFFICULTY_NONE
BasePoints = 0
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)

Effect 1: Id 30 (SPELL_EFFECT_ENERGIZE) DIFFICULTY_NONE
BasePoints = 200
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
EffectMiscValueA = 1

There that you mention is not for 7.1.5

**Comment by Seyden** [comment]
@HannibalRoG do you even know your own script?

the effects from spell id 100 doesn't have any charge effect.. and in your script, you're casting the spell id 218104 which has the spell effect SPELL_EFFECT_CHARGE like i said.

So the spell isn't updated at all :D

**Comment by HannibalRoG** [comment]
@Seyden You're right, but we do not know how to use EffectMiscValueB = 45080
If you want you can contribute to offer us a light.

**Comment by DoctorKraft** [comment]
> EffectMiscValueB = 45080

You know what that value is? SpellxSpellVisual?

**Comment by HannibalRoG** [comment]
@DoctorKraft and that question is for...??

**Comment by wonder2011** [comment]
@Seyden you are saying that @HannibalRoG will need to implement a seccond spell, the spell `218104` and his CHARGE_EFFECT?, and in the other hand, what is the EffectMiscValueB?. I try to find this with Spell Work and is clear that is not a spell (visual for example).

**Comment by DoctorKraft** [comment]
Yeah @wonder2011, my question is a same. I search spell for visual but nothing, i don't have a dbc viewers for look if spellxspellvisualid is correct with sniff (spellwork give only a visualid not spellxspellvisualid) But in sniff you have only 3 spells (run, slow, root)

**Comment by HannibalRoG** [comment]
Currently the script does everything the spell says it should do, I do not know why @Seyden says it's outdated.

Todo:
Fix SPELL_EFFECT_CHARGE as @funjoker say

**Comment by DoctorKraft** [comment]
@HannibalRoG No you have one spell missing 105771 (for root) and we speaking about the visual.
Look this video https://www.youtube.com/watch?v=lGsOf7vspHA 7sec to 11sec and compare with TC (no visual)

**Comment by Shauren** [comment]
ignore visual, i fixed it for all SPELL_EFFECT_CHARGE

**Comment by HannibalRoG** [comment]
OMG what such of stupid i am, we found the effect, it will be implemented soon.
One question, does the effect (105771) apply from the initial moment of charge or once the warrior reaches his target?

**Comment by DoctorKraft** [comment]
Nice ! Actually on retail 105771 is casted in same time before your charge (you can simply add castspell 105771 with your other cast)

**Comment by HannibalRoG** [comment]
It looks amazing now.
I think there is still a small problem with the charge and it is that the npc of the orc starting area that are on a hill should not be possible to charge them, at least not on the side of the hill that can not climb.
Try charge to the npc Northwatch Scout on top of the hill.

**Comment by HannibalRoG** [comment]
That Travis its not my fault ;)

**Comment by HannibalRoG** [comment]
UPS, thats Travis is not my fault.

**Comment by Eredar** [comment]
@HannibalRoG On retail charge still exectuted if used on that position, but movement path bypass it around, not in a straight line. Straight movement used only while charge executed in the air. If it is used on the ground it even can look like a slalom. Problem is in MovementGenerator, ChargeMovement, I guess. Worng waypoints calculation.

**Comment by HannibalRoG** [comment]
Thanks @Eredar for your explanation.

**Comment by wonder2011** [comment]
I test this PR and looks very nice, working like on retail. Thanks to @HannibalRoG for this work.

**Comment by DoctorKraft** [comment]
"Slalom" is generated with mmaps no ?

**Comment by Seyden** [comment]
@DoctorKraft yes generated with mmaps

**Comment by HannibalRoG** [comment]
What about this PR?

**Comment by Aokromes** [comment]
Conflicting files
src/server/scripts/Spells/spell_warrior.cpp

**Pull request closed without merging**
