### PR TITLE
Scripts: Fix crossfaction combat issue

### LINKED ISSUE #23795: creatures ignores * UNIT_FLAG_IMMUNE_TO_PC (0x100) on mixed groups
**Description:**

creatures ignores * UNIT_FLAG_IMMUNE_TO_PC (0x100) on mixed groups

**Expected behaviour:**

creatures don't agroes people when having * UNIT_FLAG_IMMUNE_TO_PC (0x100)

**Steps to reproduce the problem:**

1. (for faster repo, and save completing quests) login with one horde and one aliance gm
2. make a group with both
3. .go gameobject 151101
4. enter pit of saron with aliance gm, turn gm off / enter forge of souls
5. with the horde gm enter pit of saron / forge of souls, gm off, go c id 36494 / 36502. 
6. dam 1000000
7. you will see you have got agro from aliance quest giver.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

215a6cee2489

**Operating system:** debian 10 x64 ubuntu 19.10 x64

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**
Fix crossfaction combat issues in these cases:
- Fix Martin Victus attacking players in crossfaction groups because it was spawned as summon of the boss, triggering DoCombatInZone()
- Fix Devourer of Souls guardians attacking players in crossfaction groups because they were spawned as summons of the boss, triggering DoZoneInCombat()

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #23795

**Tests performed:** (Does it build, tested in-game, etc.)
#23795 doesn't happen anymore

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Check other instances with the same issue

### CODE REVIEW

**Comment by Aokromes** [comment]
working as intended

**Comment by illfated** [comment]
I guess that the nopch error indicates that we need to include something like this in `instance_pit_of_saron.cpp`:
```cpp
#include "Object.h"
```

**Comment by Shauren** [comment]
no, its `TemporarySummon.h`

**Comment by jackpoz** [comment]
can I just
```cpp
#include "All.h"
```
:) ?

**Comment by Shauren** [comment]
No, I kill for bloating includes

**Comment by illfated** [comment]
Cosmetic: Please change "DoCombatInZone()" to `DoZoneInCombat()` -- which is the actual name of the function/call -- in the PR comment.

Suggestion: if you want to, you can edit the PR title to **Scripts/Frozen Halls: Fix crossfaction combat issue**
(unless you plan to include more files later)

**Comment by ckegg** [comment]
The group of alliance NPC standing next to Muradin at platform in front of Deathbringer Saurfang after gunship battle will do the same thing.

**Pull request merged**
