### PR TITLE
Core/Loot: Allow master looter to see all quest items

### LINKED ISSUE #24230: [3.3.5] Core/Item: Master Looter Item visibility problem
**Description:**

Master Looter cant see items that provide Quests.
Original Issue #16653
PR and commit that should have fixed this issue : #23410 -> e6ad9b1

[Image 1](https://cdn.discordapp.com/attachments/682994561177747515/683959390340251659/WoWScrnShot_030220_094911.jpg)

[Image 2](https://cdn.discordapp.com/attachments/682994561177747515/683959394412920870/WoWScrnShot_030220_094918.jpg)

**Current behaviour:**

ML cant see Quest Items.

**Expected behaviour:**

ML should be able to see and assign Quest Items.

**Steps to reproduce the problem:**

Create a Raid with at least 2 Characters.
Set Lootrules to ML.
.go c 49678
kill and loot

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ce449f6

**Operating system:** 

Windows 10

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Core/Loot: Allow master looter to see all quest items

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #24230

**Tests performed:**

None

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Comment by Jinnaix** [comment]
Works like a charm. With PR:

WoWScrnShot_060721_111109

Without PR:

WoWScrnShot_060721_111844
WoWScrnShot_060721_111843

**Comment by jackpoz** [comment]
and you still get all the required errors if the destination player cannot receive the quest item, right ? like, is there any regression test we have to do or can this be merged ?

**Comment by Jinnaix** [comment]
I have never been Masterlooter in retail, so im not 100% sure how it should look like:

WoWScrnShot_061321_142131

Player Monson already completed the quest given by Heart of Hakkar -> Cant assign the item to him, he also correctly does not see the item as a drop when checking the corpse
Player Lesandra alredy has the Heart of Hakkar in her inventory from a previous run -> Cant assign the item to her, she also correctly does not see the item as a drop when checking the corpse
Luciah and Boing both see the item when checking the corpse, while only Luciah is eligible to obtain it (Boing is Masterlooter but already has the item), assigning it to Luciah works as intended.

**Comment by jackpoz** [comment]
Thanks @Jinnaix for the long test done for this PR 🚀

**Pull request merged**
