### PR TITLE
Core/UnitAI: #17309 follow-up

### PR DESCRIPTION
**Pull request by ccrs**

### CODE REVIEW

**Comment by ccrs** [comment]
found it some days ago, didnt know u were about to merge (finally)

**Comment by Aokromes** [comment]
@ccrs review the other prs where i poked you :P

**Comment by ccrs** [comment]
should review and merge this fast, the crash is pretty common in bosses

**Comment by jackpoz** [comment]
> the crash

which crash ?

**Comment by jackpoz** [comment]
> No description provided.

what happened to the PR description ?

**Comment by tkrokli** [comment]
The PR description should at least include the commit message from the first commit:
```
Set CurrentVictim as first element on targetList if necessary,
which is then filled with the threatlist elements that satisfy the predicate.
```
But it should also contain as much info as possible as suggested by the TC Pull Request template:
- https://raw.githubusercontent.com/TrinityCore/TrinityCore/3.3.5/pull_request_template.md

**Comment by ccrs** [comment]
its a fucking follow up without logic changes to fix a crash

**Comment by tkrokli** [comment]
OK, I just tried to be helpful by suggesting what to do to follow up joschiwald's questions.
You might want to at least put that comment and the issue number (as a link) in the description.

**Comment by jackpoz** [comment]
> its a fucking

nice choice of words

**Pull request merged**
