### PR TITLE
Scripts/Wailing Caverns: make Disciple of Naralex say Mutanus, not $n

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

- Disciple of Naralex should say
"This Mutanus the Devourer is a minion from Naralex's nightmare no doubt!"
instead of using $n caused by a missing target in the `Talk() `script command.

-  Target name was not defined in this part of the script, so I had to find the creature and its name somehow.

-  I haven't used this type of function before to look up a creature for `Talk()` arguments, so it took me a day to find a working solution. I got some inspiration from `zone_silithus.cpp`:
https://github.com/TrinityCore/TrinityCore/blob/995aabe4bbbe17233376e7ee84a2ae52a82b424b/src/server/scripts/Kalimdor/zone_silithus.cpp#L372-L375
https://github.com/TrinityCore/TrinityCore/blob/995aabe4bbbe17233376e7ee84a2ae52a82b424b/src/server/scripts/Kalimdor/zone_silithus.cpp#L386
https://github.com/TrinityCore/TrinityCore/blob/995aabe4bbbe17233376e7ee84a2ae52a82b424b/src/server/scripts/Kalimdor/zone_silithus.cpp#L460

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [X] master (Wailing Caverns is supposed to be completely different after Cataclysm, but TC source has not been changed yet as far as I can tell)

**Issues addressed:**

None that I could find in the TC issue tracker, but recently requested by Aokromes in my PR #23118 .

**Tests performed:** (Does it build, tested in-game, etc.)

Builds just fine in Visual Studio 2017, RelWithDebInfo. See image (Details) below for in-game details:

<details>

WoWScrnShot_031819_220027

</details>

**Known issues and TODO list:** (add/remove lines as needed)

- [x] The added code has potential for simplification or improvements, but I need feedback from real coders to learn more.
- [x] "WIP" added in the PR title to indicate that feedback is needed because the improvement potential. Remove the "WIP" part when all changes are approved, before merge.

### CODE REVIEW

**Comment by jackpoz** [comment]
me->SummonCreature() returns already what you are looking for (or NULL if it failed). Use the usual if (Creature* moradus = me->SummonCreature(...)) Talk(..., moradus);

**Comment by illfated** [comment]
OK, maybe I have had trouble seeing that solution because to me it sort of looks like the summon runs again. 🏃 🐂 
Will your suggested solution need all the same arguments as the original ones?

**Comment by jackpoz** [comment]
You don't need to call SummonCreature() twice, change the call that is already in the sources to be like the code I pasted above, then you can use the return value in Talk() function

**Comment by mdX7** [comment]
```c
if (Creature* mutantus = me->SummonCreature(NPC_MUTANUS_THE_DEVOURER, 150.872f, 262.905f, -103.503f, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 300000))
    Talk(SAY_MUTANUS_THE_DEVOURER, mutanus);
```
it's this basicly

**Comment by illfated** [comment]
Thanks to both of you. It is obvious that I have not spent enough time coding to know this kind of coding myself.

**Comment by illfated** [comment]
The failed circleci nopch test worries me a bit.
Got any suggestions on how to correct (improve) that error?
```cpp
/home/circleci/project/src/server/scripts/Kalimdor/WailingCaverns/wailing_caverns.cpp:247:47: fatal error: cannot initialize a variable of type 'Creature *' with an rvalue of type 'TempSummon *'
                                if (Creature* mutanus = me->SummonCreature(NPC_MUTANUS_THE_DEVOURER, 150.872f, 262.905f, -103.503f, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 300000))
                                              ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
src/server/scripts/CMakeFiles/scripts_kalimdor.dir/build.make:2198: recipe for target 'src/server/scripts/CMakeFiles/scripts_kalimdor.dir/Kalimdor/WailingCaverns/wailing_caverns.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts_kalimdor.dir/Kalimdor/WailingCaverns/wailing_caverns.cpp.o] Error 1
```

**Comment by Shauren** [comment]
Add #include "TemporarySummon.h"

**Comment by jackpoz** [comment]
Is this ready to be merged ? Were the last changes tested too? Then we can merge it

**Comment by illfated** [comment]
Very well, I will run a test on the changes later today. 
That is the only hurdle left before merge.

**Comment by illfated** [comment]
Sorry for the delay, yesterday I fell asleep on the couch while waiting for my local build to complete.
Anyway, I tested it now and it works just as issue-free as the previous content (see image (Details) below):

<details>

WoWScrnShot_032119_191258

</details>

**Comment by illfated** [comment]
The only thing I am pondering now is what changes should be made to the commit text.
Could you merge the comment text from all 3 PR commits, making the last one read
"Thanks to Shauren for the nopch build fix recommendation." - or would you like me to merge them?

**Comment by jackpoz** [comment]
we can give @Shauren a /hug out of the commit message and he will be happy about it anyway :)

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by illfated** [comment]
You are very welcome. I am just happy to be of any kind of help with this source since all the working parts of it gives me hours of entertainment when I can't come up with something else to entertain me. 😃

**Pull request merged**
