### PR TITLE
[WIP] Add docker support for travis-ci

### PR DESCRIPTION
**Pull request by greenbagels**
Adds support for faster, sudo-less docker containers on travis-ci.

_Note that this file contains "experimental" code that has yet to be pulled to Travis-CI, so it will not work as everything stands._

Specifically, the kalakris-cmake alias is nonexistent for the whitelisted apt sources at this point (travis-ci/travis-ci#3722), as well as the specific boost packages although the source is whitelisted (travis-ci/travis-ci#3759).

I'm just leaving this here for convenience for when it can later function properly.

### CODE REVIEW

**Comment by Naios** [comment]
```
CMake 2.8.9 or higher is required.  You are running version 2.8.7
```

**Comment by DDuarte** [comment]
Re-open this once @travis-ci whitelists the packages.

**Comment by greenbagels** [comment]
Both whitelists have been merged. Docker support *should* work now.

**Comment by greenbagels** [comment]
The docker travis ci builds are taking roughly 20 minutes to complete, as cmake is running unusually slow for some odd reason. As per @DDuarte's recommendation, I'm closing this PR, but I'll post more info in a gist or forum post.

**Comment by Naios** [comment]
There is also the possibility to [run docker with preconfigured containers](https://github.com/lukecyca/travis-docker-example/blob/master/.travis.yml) inside the travis legacy stack.

**Comment by DDuarte** [comment]
Just to make it clear, under Travis' docker, setup runs faster (60 seconds vs <40 seconds) however actual build (**make**, not cmake) runs a lot slower (20 minutes vs 5 or 6 seconds).

**Comment by DDuarte** [comment]
@jackpoz: tried enabling ccache but it seems Travis doesn't like it:
https://travis-ci.org/TrinityCore/TrinityCore/builds/71487069#L1718-L1722

> The command "make -j 10" exited with 0.
cache.2
store build cache
1.26schanges detected, packing new archive
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
uploading archive
failed to upload cache
curl: Can't open '/home/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
Done. Your build exited with 0.

**Pull request closed without merging**
