### PR TITLE
DB/World: Added model info for Imp model.

### PR DESCRIPTION
**Pull request by Sar777**
New imp model. path 6.2.0

### CODE REVIEW

**Comment by Aokromes** [comment]
We don't use PRs for sql only fixes, because they aren't usualy merged on the same day they are made and it will make 3 commits for a simple fix.

**Comment by DDuarte** [comment]
Thanks for the fix but please post it in a new issue since it's a SQL only PR

https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md#creating-pull-requests
> For SQL only fixes, please create a ticket. Since it's very unlikely that your Pull Request will be merged on the day that you open it, please name the files with an impossible date to avoid merging issues ie: 2015_13_32_00_world.sql

**Comment by MitchesD** [comment]
also don't put ' ' around numbers

**Comment by MitchesD** [comment]
create issue for that fix please

**Pull request closed without merging**
