### PR TITLE
Core/SAI: Prevent loading invalid smart_scripts entry

### PR DESCRIPTION
**Pull request by robinsch**
**Changes proposed:**

-  Don't load smart_scripts with entryorguid 0

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:**
Fixed an issue where invalid data was loaded, this invalid data would be used by all summoned creature replacing their "existing" SAI

Closes #  (insert issue tracker number)
-

**Tests performed:**
builds, won't load SAI
(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by jackpoz** [comment]
does this get triggered on current TDB ? just to know if there are some existing cases already

**Comment by robinsch** [comment]
No.

**Comment by ccrs** [comment]
looking good

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
