### PR TITLE
[Legion] Update MAX_LEVEL & DEFAULT_MAX_LEVEL

### PR DESCRIPTION
**Pull request by funjoker**
**Changes proposed**:
- Update MAX_LEVEL to 110
- Update DEFAULT_MAX_LEVEL to 110

**Target branch(es)**: 7x Only necessary for Legion

**Tests performed**: 
- Enables the player_levelstats for 101-110

### CODE REVIEW

**Comment by funjoker** [comment]
Not Sure if both need to be 123 =/

**Comment by funjoker** [comment]
I think now it fits ... i hope ^^

**Comment by Shauren** [comment]
Well this is interesting, both should be 110 btw (why do we even keep 2 separate defines for this when NONE of them is used for gt code)

**Comment by funjoker** [comment]
yeah tell me why :D
so better 110 ? ^^
Description says we need to check what the max level in gt is so i did :P

**Pull request merged**
