### PR TITLE
DB/Loot: Rework Level 1 - 5 loot to be blizzlike

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**
-  Add extra primary keys to creature_loot_template to allow proper loot.
- Redo loot for all starting areas

Added for testing on TC.

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
Make an issue for sql fixes.

**Comment by offl** [comment]
Why you think same reference is assigned twice to same creature?

**Comment by malcrom** [comment]
Because I'm smarter than you.

**Comment by malcrom** [comment]
This is here for anyone who is interested to test. I know Shauren and Awful will have issues with it because they are assholes.

**Comment by Teppic1** [comment]
It's quite common to see in classic mobs dropping items from the same reference template a second time, and things are certainly separated out by mob type (like boars vs humans). The templates are definitely different between TBC and vanilla 1-20 zones too. Something that'd be more difficult to emulate is how many mobs will drop a single item or a bunch of items from the same templates, but usually nothing in between, though it's not a big issue.

**Comment by Shauren** [comment]
> It's quite common to see in classic mobs dropping items from the same reference template a second time, and things are certainly separated out by mob type (like boars vs humans). The templates are definitely different between TBC and vanilla 1-20 zones too. Something that'd be more difficult to emulate is how many mobs will drop a single item or a bunch of items from the same templates, but usually nothing in between, though it's not a big issue.

That is where you simply change *Count columns to roll another item from the same reference. There is no need to do a silly thing like modifying primary key of the table and inserting the reference twice.

**Comment by malcrom** [comment]
> It's quite common to see in classic mobs dropping items from the same reference template a second time, and things are certainly separated out by mob type (like boars vs humans). The templates are definitely different between TBC and vanilla 1-20 zones too. Something that'd be more difficult to emulate is how many mobs will drop a single item or a bunch of items from the same templates, but usually nothing in between, though it's not a big issue.

This is the only way you can make it work blizzlike. Some here think they know everything without testing and are completely wrong and delete comments.

**Pull request closed without merging**
