### PR TITLE
[BFA] DB2 and Gt updates

### PR DESCRIPTION
**Pull request by Palabola**
**Changes proposed:**
-  New DB2 files added (+62 DB2) and removed which is not exist anymore.

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [ *] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by ReyDonovan** [comment]
DB2 and Gt updates + Initial work on BFA 

https://github.com/ws-motive/TrinityCore/pull/1/files

**Comment by funjoker** [comment]
Azerite GTs missin

**Comment by Palabola** [comment]
@funjoker  Thx, updated!

**Comment by Palabola** [comment]
Moved to bfa branch.

**Pull request closed without merging**
