### PR TITLE
Added updates to translations, in the try to remove cataclysm changes…

### PR DESCRIPTION
**Pull request by StormBytePP**
… that got merged in the translations (only the spanish ones).

At least, this is an attempt to not be confused anymore for the changed quests, changed locations, and so, as many of the quests changed also the finish location it tells under its
objectives.

See notes in the beginning of the archive.

### CODE REVIEW

**Comment by Rushor** [comment]
usually we don't accept prs with db changes only, could you open up a new issue with the whole changes
in the 
```
```sql
UPDATE XXX

format? thanks for your pr :)

**Comment by Killyana** [comment]
This must be done for all locales not only Spanish.

**Comment by Rushor** [comment]
will be hard to get all old locales before the change from 31.03.2014 :/

**Comment by Killyana** [comment]
If only 245 quests must be updated it will take time but it can be done, @StormBytePP are you sure only this quests are affected?

**Comment by StormBytePP** [comment]
@Rushor I will do that
@Killyana I know, but I can only speak english and spanish, and definitelly I need to compare stored english version with source (the translation that we have) with destination (the translation from esWoW2 project). As a note, esWoW2 is what I used before trinity merged translations into TDB, not perfect, but I found that some of current translations contains explanation about "Cataclysm" in description so definitelly it must be reviewed.

Furthermore, this work is a VERY tedious work, it costed me about 5 hours, to manually review each translation.

Moreover, there are more than 245 quests to translate, but as I placed in notes, I only translated the ones which have actually data: For example, I skipped translations which contains NULL in description fields and so as that is useless anyway.

Finally, yes, I will open a new ticket, and I will also explain the process I did to compare, insert data in a temp table, and so, as it will ease a lot the process (I even used a little PHP script to output sql updates), but let me some time as I am currently busy on my own work, but will definitelly do.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0b49726a5f745993a74ab40b2954fc6a39ca26bb

**Pull request closed without merging**
