### PR TITLE
Core/Creature: Implemented sparring with max health percent thresholds 

### LINKED ISSUE #18576: [DEV] Core: Monster sparring
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Initial support for monster sparring was implemented here https://github.com/TrinityCore/TrinityCore/pull/17673

Only melee attack are working now, spells still deal damage, Also some mechanism like deal damage only until health% is not implemented.

Old issue: https://github.com/TrinityCore/TrinityCore/issues/13258

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  rev. 3e51583e6cde

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by mdX7**
**Changes proposed:**

-  Core/Creature: Implemented sparring with max health percent thresholds 

**Issues addressed:**

Closes #18576  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)
built, tested ingame in Sentinel Hill with: 
```sql
UPDATE `creature_template_addon` SET `noNPCDamageBelowHealthPct`=85 WHERE entry IN(54372, 54373, 54371, 42407);
```

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Drop `Unit::ShouldSparWith` & `Unit::FakeAttackerStateUpdate`
- [x] Fix overridden data of existing creatures

### CODE REVIEW

**Comment by Nyr97** [comment]
I don't know if you've taken into consideration several spells that may contain SPELL_EFFECT_INSTAKILL when used on sparring creatures. Since this system (excluding the whole CreatureDifficulty.dbc flags) is very similar to Cataclysm branch's sparring system, I'm inclined to think the sparring will ignore such effect, which is also the case on that branch.

**Comment by mdX7** [comment]
> I don't know if you've taken into consideration several spells that may contain SPELL_EFFECT_INSTAKILL when used on sparring creatures. Since this system (excluding the whole CreatureDifficulty.db2 flags) is very similar to Cataclysm branch's sparring system, I'm inclined to think the sparring will ignore such effect, which is also the case on that branch.

will be fixed with #27316

**Comment by offl** [comment]
Just in case https://docs.google.com/spreadsheets/d/1Wh1e1ZXYM-sw3wWrY9dGZ2ngK8oa3PA2XIftQJuf5R0/edit#gid=740715654&range=B455:B458
Check params

**Comment by ReyDonovan** [comment]
if the NPC is a quest target, then you have to remove the hotfixesDB flag from it
example hack
https://www.wowhead.com/npc=80775
```sql
 DELETE FROM `creature_difficulty` WHERE `ID`=78511;
INSERT INTO `creature_difficulty` VALUES
(78511,5,90,90,14,178,-1870135296,72,16777216,67584,16777216,0,0,80775, 28153);

**Comment by Nyr97** [comment]
Any news on this PR?

**Review by meji46 — APPROVED** [review]

**Comment by Nyr97** [comment]
Merge, merge time!

**Comment by Nyr97** [comment]
yayyy

**Comment by CraftedRO** [comment]
the issue was targeting 3.3.5 branch too so I guess someone shoud cherry this

**Pull request merged**
