### PR TITLE
Core/SAI: Warn when an unused parameter is set in the database

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Warn when an unused parameter is set in the database as all unused parameters are supposed to be set to 0

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Lot of SAI scripts with parameters set by mistake in the wrong columns.

**Tests performed:**

Started, some errors are logged

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Finish the mapping for events
- [x] Finish the mapping for actions
- [x] Finish the mapping for targets

### CODE REVIEW

**Comment by jackpoz** [comment]
Some errors reported for now:
>SmartAIMgr: Entry 31279 SourceType 0 Event 5 Action 11 has unused event_param5 with value 14000, it must be 0, skipped.
SmartAIMgr: Entry 32800 SourceType 0 Event 5 Action 11 has unused event_param5 with value 14000, it must be 0, skipped.

**Comment by jackpoz** [comment]
Finished validating events, this is the list of current errors:
>SmartAIMgr: Entry 27727 SourceType 0 Event 2 Action 11 has unused event_param4 with value 17000, it must be 0, skipped.
SmartAIMgr: Entry 27727 SourceType 0 Event 3 Action 11 has unused event_param4 with value 11000, it must be 0, skipped.
SmartAIMgr: Entry 31279 SourceType 0 Event 5 Action 11 has unused event_param5 with value 14000, it must be 0, skipped.
SmartAIMgr: Entry 31702 SourceType 0 Event 5 Action 86 has unused event_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 32800 SourceType 0 Event 5 Action 11 has unused event_param5 with value 14000, it must be 0, skipped.
SmartAIMgr: Entry 37230 SourceType 0 Event 1 Action 47 has unused event_param5 with value 1, it must be 0, skipped.

@offl if you have time please fix these and push the fix to 3.3.5 , I will continue with validating actions and targets

**Comment by jackpoz** [comment]
Finished validating actions, this is the list of errors:
>SmartAIMgr: Entry -78644 SourceType 0 Event 5 Action 54 has unused action_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 3821 SourceType 0 Event 0 Action 75 has unused action_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 7079 SourceType 0 Event 0 Action 75 has unused action_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 9543 SourceType 0 Event 3 Action 45 has unused action_param3 with value 5000, it must be 0, skipped.
SmartAIMgr: Entry 11832 SourceType 0 Event 32 Action 66 has unused action_param1 with value 3, it must be 0, skipped.
SmartAIMgr: Entry 11832 SourceType 0 Event 35 Action 66 has unused action_param1 with value 3, it must be 0, skipped.
SmartAIMgr: Entry 11832 SourceType 0 Event 44 Action 66 has unused action_param1 with value 3, it must be 0, skipped.
SmartAIMgr: Entry 13196 SourceType 0 Event 3 Action 31 has unused action_param3 with value 8, it must be 0, skipped.
SmartAIMgr: Entry 13196 SourceType 0 Event 3 Action 31 has unused action_param4 with value 16, it must be 0, skipped.
SmartAIMgr: Entry 16222 SourceType 0 Event 2 Action 5 has unused action_param6 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 16222 SourceType 0 Event 5 Action 5 has unused action_param6 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 16222 SourceType 0 Event 8 Action 5 has unused action_param6 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 16222 SourceType 0 Event 11 Action 5 has unused action_param6 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 16222 SourceType 0 Event 14 Action 5 has unused action_param6 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 16222 SourceType 0 Event 16 Action 66 has unused action_param6 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 16833 SourceType 0 Event 1 Action 66 has unused action_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 21657 SourceType 0 Event 0 Action 26 has unused action_param3 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 23995 SourceType 0 Event 4 Action 66 has unused action_param1 with value 23995, it must be 0, skipped.
SmartAIMgr: Entry 24539 SourceType 0 Event 6 Action 72 has unused action_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 25808 SourceType 0 Event 1 Action 49 has unused action_param1 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 26405 SourceType 0 Event 1 Action 75 has unused action_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 26780 SourceType 0 Event 9 Action 22 has unused action_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 27909 SourceType 0 Event 3 Action 103 has unused action_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 29210 SourceType 0 Event 1 Action 49 has unused action_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 29627 SourceType 0 Event 0 Action 75 has unused action_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 29747 SourceType 0 Event 2 Action 75 has unused action_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 30393 SourceType 0 Event 1 Action 18 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 30945 SourceType 0 Event 9 Action 5 has unused action_param2 with value 10000, it must be 0, skipped.
SmartAIMgr: Entry 30993 SourceType 0 Event 10 Action 89 has unused action_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 1 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 2 Action 69 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 3 Action 81 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 6 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 11 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 16 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 21 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 31135 SourceType 0 Event 28 Action 69 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 779000 SourceType 9 Event 2 Action 15 has unused action_param6 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 1059900 SourceType 9 Event 2 Action 114 has unused action_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 1060000 SourceType 9 Event 2 Action 114 has unused action_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2297900 SourceType 9 Event 3 Action 37 has unused action_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2778800 SourceType 9 Event 3 Action 64 has unused action_param3 with value 27714, it must be 0, skipped.
SmartAIMgr: Entry 2972400 SourceType 9 Event 1 Action 66 has unused action_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3040300 SourceType 9 Event 3 Action 107 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3040300 SourceType 9 Event 4 Action 107 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3040300 SourceType 9 Event 5 Action 107 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3040300 SourceType 9 Event 6 Action 107 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3040500 SourceType 9 Event 16 Action 66 has unused action_param1 with value 3, it must be 0, skipped.
SmartAIMgr: Entry 3040800 SourceType 9 Event 2 Action 66 has unused action_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3041100 SourceType 9 Event 3 Action 66 has unused action_param1 with value 5, it must be 0, skipped.
SmartAIMgr: Entry 3113506 SourceType 9 Event 0 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3113506 SourceType 9 Event 3 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3113506 SourceType 9 Event 4 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3122200 SourceType 9 Event 1 Action 1 has unused action_param5 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 18842200 SourceType 9 Event 1 Action 99 has unused action_param2 with value 2, it must be 0, skipped.

As usual, it might be the checks are wrong so double check.

**Comment by Faq** [comment]
- [x] Finish the mapping for actions

**Comment by jackpoz** [comment]
image

should we validate that x,y,z,o are 0 when they are not supposed to be used ?

**Comment by offl** [comment]
It's same thing as params
It's up to you

**Comment by jackpoz** [comment]
Errors about SMART_TARGET. As usual, don't blindly trust these logs but please check if they are correct:

>SmartAIMgr: Entry -75734 SourceType 0 Event 0 Action 11 has unused target_param1 with value 21709, it must be 0, skipped.
SmartAIMgr: Entry -75106 SourceType 0 Event 0 Action 11 has unused target_param1 with value 21416, it must be 0, skipped.
SmartAIMgr: Entry -75105 SourceType 0 Event 0 Action 11 has unused target_param1 with value 21416, it must be 0, skipped.
SmartAIMgr: Entry -75104 SourceType 0 Event 0 Action 11 has unused target_param1 with value 21416, it must be 0, skipped.
SmartAIMgr: Entry 6557 SourceType 0 Event 3 Action 47 has unused target_param2 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 10043 SourceType 0 Event 5 Action 11 has unused target_param1 with value 32, it must be 0, skipped.
SmartAIMgr: Entry 17826 SourceType 0 Event 13 Action 133 has unused target_param3 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 18399 SourceType 0 Event 7 Action 41 has unused target_param3 with value 100, it must be 0, skipped.
SmartAIMgr: Entry 18955 SourceType 0 Event 1 Action 85 has unused target_param1 with value 10, it must be 0, skipped.
SmartAIMgr: Entry 27229 SourceType 0 Event 0 Action 85 has unused target_param1 with value 10, it must be 0, skipped.
SmartAIMgr: Entry 28948 SourceType 0 Event 6 Action 1 has unused target_param2 with value 10, it must be 0, skipped.
SmartAIMgr: Entry 30630 SourceType 0 Event 0 Action 85 has unused target_param1 with value 30630, it must be 0, skipped.
SmartAIMgr: Entry 30830 SourceType 0 Event 4 Action 11 has unused target_param2 with value 2, it must be 0, skipped.
SmartAIMgr: Entry 328900 SourceType 9 Event 1 Action 5 has unused target_param1 with value 2000, it must be 0, skipped.
SmartAIMgr: Entry 328900 SourceType 9 Event 1 Action 5 has unused target_param2 with value 2000, it must be 0, skipped.
SmartAIMgr: Entry 369201 SourceType 9 Event 2 Action 1 has unused target_param1 with value 3, it must be 0, skipped.
SmartAIMgr: Entry 479200 SourceType 9 Event 2 Action 12 has unused target_param1 with value 23869, it must be 0, skipped.
SmartAIMgr: Entry 2361600 SourceType 9 Event 0 Action 54 has unused target_param1 with value 186265, it must be 0, skipped.
SmartAIMgr: Entry 2361600 SourceType 9 Event 0 Action 54 has unused target_param2 with value 50, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 0 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 1 Action 11 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 2 Action 11 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 3 Action 28 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 4 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 5 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471000 SourceType 9 Event 6 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 0 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 1 Action 11 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 2 Action 11 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 3 Action 28 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 4 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 5 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2471100 SourceType 9 Event 6 Action 1 has unused target_param1 with value 7, it must be 0, skipped.
SmartAIMgr: Entry 2483500 SourceType 9 Event 1 Action 1 has unused target_param2 with value 40, it must be 0, skipped.
SmartAIMgr: Entry 2719901 SourceType 9 Event 7 Action 41 has unused target_param1 with value 1, it must be 0, skipped.
SmartAIMgr: Entry 3784600 SourceType 9 Event 2 Action 1 has unused target_param3 with value 20, it must be 0, skipped.
SmartAIMgr: Entry 3784600 SourceType 9 Event 3 Action 11 has unused target_param3 with value 20, it must be 0, skipped.
SmartAIMgr: Entry 3784600 SourceType 9 Event 6 Action 1 has unused target_param3 with value 20, it must be 0, skipped.
SmartAIMgr: Entry 3784600 SourceType 9 Event 7 Action 1 has unused target_param3 with value 20, it must be 0, skipped.

**Comment by jackpoz** [comment]
I don't get any error anymore with latest fixes from 335

**Pull request merged**
