### PR TITLE
[3.3.5] Core/config: add MonsterSight setting to worldserver.conf.dist

### PR DESCRIPTION
**Pull request by JustZerooo**
**Changes proposed:**

-  Add the setting `MonsterSight = 50.000000` to worldserver.conf.dist
    - Limits the maximum distance that a creature can see regardless of level difference (through CreatureAI::IsVisible).
    - Increase CONFIG_SIGHT_MONSTER to 50 yards. Used to be 20 yards.

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
updates #20125

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Aokromes** [comment]
find real meaning of that.

**Comment by Shoxxo** [comment]
Specifies the visibility of the monsters.

Looked ad google translator and the definition. That seems be what we need to say!

**Comment by tkrokli** [comment]
Suggestion from my comment in https://github.com/TrinityCore/TrinityCore/issues/16859#issuecomment-321225880 :
> Limits the maximum distance that a creature can see regardless of level difference (through CreatureAI::IsVisible).
Increase CONFIG_SIGHT_MONSTER to 50 yards. Used to be 20 yards.

**Comment by Shoxxo** [comment]
Okay i will change the Description if i am home

**Comment by tkrokli** [comment]
I believe your original location in the `CREATURE SETTINGS` section was a better choice for this setting.
I also would like to see the documentation more complete and detailed, so here is a suggestion from me:
```diff
diff --git a/src/server/worldserver/worldserver.conf.dist b/src/server/worldserver/worldserver.conf.dist
index a703b7ff55..b806c7bb64 100644
--- a/src/server/worldserver/worldserver.conf.dist
+++ b/src/server/worldserver/worldserver.conf.dist
@@ -1707,16 +1707,25 @@ ListenRange.Yell = 300
 #    Creature.MovingStopTimeForPlayer
 #        Description: Time (in milliseconds) during which creature will not move after
 #                     interaction with player.
 #        Default: 180000
 
 Creature.MovingStopTimeForPlayer = 180000
 
 #
+#    MonsterSight
+#        Description: The maximum distance in yards that a "monster" creature can see
+#                     regardless of level difference (through CreatureAI::IsVisible).
+#                     Increases CONFIG_SIGHT_MONSTER to 50 yards. Used to be 20 yards.
+#        Default:     50.000000
+
+MonsterSight = 50.000000
+
+#
 ###################################################################################################
 
 ###################################################################################################
 # SPAWN/RESPAWN SETTINGS
 #
 #    Respawn.MinCheckIntervalMS
 #        Description: Minimum time that needs to pass between respawn checks for any given map.
 #        Default:     5000 - 5 seconds
```
Feedback & insight is appreciated, especially from any of the main TC developers.

**Comment by tkrokli** [comment]
Time for comments from the other TC team members.

**Pull request merged**
