### PR TITLE
Core/Auras:  Don't save special liquid auras

### PR DESCRIPTION
**Pull request by Demonid**
Fixes: https://github.com/TrinityCore/TrinityCore/issues/14506 and some others auras.

### CODE REVIEW

**Comment by joschiwald** [comment]
i don't like this solution

what about unapply the liquid aura when unit gets removed from map while in liquid?

**Comment by MitchesD** [comment]
@Demonid please could you change it as joschiwald requested?

**Comment by MitchesD** [comment]
well, it looks like original author isn't going to update this PR as we requested, closing

**Comment by Demonid** [comment]
@joschiwald Im to noob to do something like that, but you could do it if you want :+1:

**Pull request closed without merging**
