### PR TITLE
[3.3.5] OpenSSL version 3.0 support

### PR DESCRIPTION
**Pull request by damaex**
**Changes proposed:**

- OpenSSL version 3.0 support
- MariaDB support for Ubuntu 22.04

**Issues addressed:**

- Ubuntu 22.04 unsupported

**Tests performed:**

- [x] builds on 20.04/22.04
- [x] run, login and 5min gameplay on 22.04

**Known issues and TODO list:**

- [x] none

### CODE REVIEW

**Comment by Shauren** [comment]
Ill have to reject this PR, outside of RC4 (because it doesnt exist there anymore), openssl 3.0 support is done in master branch and should just be ported

**Comment by Shauren** [comment]
bc87f7b337154e683369a3790ee8fd1a7d4cba98 and aa6a0f24312ce6132e55a9aed677362a3b1dc8a9

**Comment by damaex** [comment]
RC4 still exists in the openssl 3.0 legacy provider `OSSL_PROVIDER_load(_libctx, "legacy");`
So, you want me to update the `master`-branch for OpenSSL 3.0 and port it back?

**Comment by Shauren** [comment]
No, master branch is already updated (see commits i linked), all that remains is porting it to 3.3.5

**Comment by damaex** [comment]
Okay, I have seen those and will do my updates accordingly.

Is HMAC used in the master branch??
Because:
https://github.com/TrinityCore/TrinityCore/blob/daafe1c181c47111b30b1ca4f3c3bfc628d1f207/src/common/Cryptography/HMAC.h#L121
Should be: `size_t length = DIGEST_LENGTH;`
According to: https://www.openssl.org/docs/man3.0/man3/EVP_DigestSignFinal.html

> EVP_DigestSign() signs tbslen bytes of data at tbs and places the signature in sig and its length in siglen in a similar way to EVP_DigestSignFinal(). In the event of a failure EVP_DigestSign() cannot be called again without reinitialising the EVP_MD_CTX. If sig is NULL before the call then siglen will be populated with the required size for the sig buffer. If sig is non-NULL before the call then siglen should contain the length of the sig buffer.

**Comment by Shauren** [comment]
Yes, its used and that code works with both 1.1 and 3.0

**Comment by damaex** [comment]
> Yes, its used and that code works with both 1.1 and 3.0

Interestingly this didn't work on my tests and i had to change it.

**Pull request closed without merging**
