### PR TITLE
Added missing ruRU localization, fixed incorrect translation

### PR DESCRIPTION
**Pull request by EWHile-EWK**
**Changes proposed:**

-  Added missing ruRu localization for Quests (Night Elf Start Zone)
-  Fixed incorect translation

**Target branch(es):** 3.3.5

- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.)
Tested in-game.
Works properly

### CODE REVIEW

**Comment by joschiwald** [comment]
use update or insert queries instead of replace queries

**Comment by Aokromes** [comment]
Thx but we don't use PRs for SQL only fixes, plz open a ticket instead, and like joschiwald said, use only update or delete+insert.

**Comment by EWHile-EWK** [comment]
Thank you, I understood, I will soon fix it.

**Comment by EWHile-EWK** [comment]
I will make more changes to the localization and create a new pool request

**Comment by EWHile-EWK** [comment]
okey?

**Comment by Jildor** [comment]
For sql fix you should create a issue

**Comment by EWHile-EWK** [comment]
okey thx

**Comment by EWHile-EWK** [comment]
and attach the SQL file?

**Comment by tkrokli** [comment]
When you open a new ticket, post the SQL code in a code block (use ```sql on a blank line above the top of the SQL code) either at the end of the ticket post or put it in a new comment after creating the new issue ticket. Also follow and use the existing issue template when creating the ticket to add the necessary description and information about what the changes are in your suggested solution. Look up some of the SQL issue tickets posted during the last month to see how it should be posted, where the text **Suggested solution:** is written before the SQL code block.

**Pull request closed without merging**
