### PR TITLE
Scripts/Commands: Avoid copies of RBACCommandData 

### PR DESCRIPTION
**Pull request by Carbenium**
**Changes proposed:**

-  Scripts/Commands: Avoid copies of RBACCommandData 
**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Should fix a V1002 warning reported by PVS-Studio

**Tests performed:**
Commands in-game + console under Valgrind

### CODE REVIEW

**Comment by Faq** [comment]
PVS reported "The 'RBACCommandData' class, containing pointers, constructor and destructor, is copied by the automatically generated copy constructor."

**Comment by jackpoz** [comment]
> PVS reported "The 'RBACCommandData' class, containing pointers, constructor and destructor, is copied by the automatically generated copy constructor."

that's where we got the report to start looking into this 😃

**Comment by jackpoz** [comment]
@Carbenium are you going to update the PR with what Shauren suggested about just deleting copy ctor ?

**Comment by Faq** [comment]
@jackpoz just posted actual error msg, so it is more obvious.

**Review by Shauren — APPROVED** [review]

**Pull request merged**
