### PR TITLE
Sorted contributors list of THANKS file and converted to utf-8

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Easier to locate duplicate names and to maintain
- UTF 8
- I did **NOT** update the list, just sorted the old one

### CODE REVIEW

**Comment by Naios** [comment]
We could update it too, the last sync is 3 years old...

**Comment by ShinDarth** [comment]
Yeah, and also remove the duplicate names

**Comment by Naios** [comment]
Also there are some contributors who only contributed db fixes in tickets and are mentioned through @, which we could parse too.

**Comment by ShinDarth** [comment]
@Naios I agree

**Pull request merged**
