### PR TITLE
DB/Spawn all creature & gameobject in Wizard's Sanctum

### PR DESCRIPTION
**Pull request by shamage**
**Changes proposed:**

-  DB/Spawn all creature & gameobject in Wizard's Sanctum
-  
-  

**Issues addressed:**

Closes #  (insert issue tracker number)

#27464
**Tests performed:**

Tests performed in the game
(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
Make an issue for sql fixes please.

**Comment by shamage** [comment]
> Make an issue for sql fixes please.

It´s existed ==> this link #27464

**Comment by mdX7** [comment]
> > Make an issue for sql fixes please.
> 
> It´s existed ==> this link #27464

just update the gist you posted in there, sql only fixes are not supposed to be done as pull request :)

**Comment by shamage** [comment]
I don't know how to do it :(

**Comment by mdX7** [comment]
image
theres an edit button in the top right corner if you click on your gist link, just remove all the code in there and put your new code in there - or create an entire new gist and link that in the issue

**Pull request closed without merging**
