### PR TITLE
Fix(Script/SAI) Quest "Aces High!"

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Replace Corastrasza script with SAI

**Tests performed:**

SQL inserts.
Compiles
Tested mounting dragons in game. 

This can be tested by just inserting SQL.
.go c 121495
.quest add 13413
.quest add 13414
Open gossip with Corastrasza and test both gossip options.

### CODE REVIEW

**Review by Shauren — APPROVED** [review]

**Comment by CraftedRO** [comment]
c0758ae6f320 Im testing this atm but I may found few issues 
major ones: 
1.[Scalesworn Elite](https://www.wowhead.com/wotlk/npc=32534/scalesworn-elite) are kinda too op and almost one shot our  Wyrmrest skytalon with [Arcane Surge](https://www.wowhead.com/wotlk/spell=61272/arcane-surge)
2.Atm you can click on that gossip 3 times and spawn 3 skytalons
WoWScrnShot_100222_133600

minor one : Corastrasza gossip shoud be : "I...I think so..." - [video](https://youtu.be/zNviZrJ9er8?t=5) instead of "I am ready, Lady Corastrasza."

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c0758ae6f3201cf9584fa43304aee041a6c4ffff Im testing this atm but I may found few issues:

1.[Scalesworn Elite](https://www.wowhead.com/wotlk/npc=32534/scalesworn-elite) are kinda too op and almost one shot our Wyrmrest skytalon with [Arcane Surge](https://www.wowhead.com/wotlk/spell=61272/arcane-surge)
2.Atm you can click on that gossip 3 times and spawn 3 skytalons or even more.

WoWScrnShot_100222_134511

**Comment by CraftedRO** [comment]
Found another you get dismounted from Wyrmrest Skytalon around those coordinates.
.go xyz 3812.752930 6834.860352 600.692627

**Comment by CraftedRO** [comment]
Found another you get dismounted from Wyrmrest Skytalon around those coordinates.
.go xyz 3812.752930 6834.860352 600.692627


https://user-images.githubusercontent.com/24683355/193450952-3b53249c-23c4-4f65-9ec0-be55c2fac300.mp4

**Comment by Shauren** [comment]
@CraftedRO those issues arent introduced by this PR and this PR doesn't attempt to fix them

**Comment by CraftedRO** [comment]
ah ok my bad , then its fine as it is.

**Pull request merged**
