### PR TITLE
CharBaseInfo Hotfix

### LINKED ISSUE #21855: [Master] CharBaseInfo hotfix table
Not there in TrinityCore rev. 11c3c456b7e1 2018-04-18 20:27:45 +0300 (master branch) (Win64, RelWithDebInfo, Static). Will it be added?

### PR DESCRIPTION
**Pull request by Smerdokryl**
**Changes proposed:**

-  Allows hotfixing the CharBaseInfo table, which is responsible for Race/Class combinations

**Target branch(es):** master

- [√] master

**Issues addressed:** Closes #21855

**Tests performed:** Builds, game client recognises hotfix and shows the new classes as enabled

### CODE REVIEW

**Comment by funjoker** [comment]
Does the core use this DB2?

HotfixBlob sends all hotfixes unhandled by Core.
So of core does not need it, then no need of this.

**Comment by Smerdokryl** [comment]
@funjoker This is for potential custom edits

**Comment by funjoker** [comment]
> This is for potential custom edits

Then all DB2 would need to be added LUL
The question is: Does TC need it?

**Comment by Wyrserth** [comment]
To be fair this looks like one of those interesting and quirky things that could justify a few lines of code :)

**Comment by Shauren** [comment]
While few lines might not seem like a big deal, adding it to TC means supporting all future structure changes made to that file - I am saying this for every request to add new .db2

**Comment by Smerdokryl** [comment]
@Shauren Well, since this is a non-priority addition based on, practically, my own request, I don't think anyone reasonable would suggest that the TC team is responsible for updating the structure. Besides, if there are changes, I'm sure someone utilising this functionality (most likely I) would do a PR to update it.

**Comment by Shauren** [comment]
Sadly thats not how it works, when a new patch changes the structure, this changes https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/DataStores/DB2Metadata.h#L1686 (this file is autogenerated). If what is written in DB2LoadInfo.h (this file is autogenerated from DB2Structure.h) does not match DB2Metadata.h, **worldserver will not start**

**Comment by Ascathor** [comment]
What is the status on this, though ? Yes or no ?

**Comment by Shauren** [comment]
Been a "no" ever since my last comment

**Pull request closed without merging**
