### PR TITLE
Core: Replace unchecked Unit::GetVictim calls with Unit::EnsureVictim

### PR DESCRIPTION
**Pull request by HelloKitty**
**Changes proposed:**

- Use Unit::EnsureVictim everywhere Unit::GetVictim is referenced but not checked for nullptr

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

Compiles

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

**Comment by Ovahlord** [comment]
I don't know what you mean that they are not checked for nullptr because in all your changed lines there literally IS a pointer check right before the action is being called.

**Comment by HelloKitty** [comment]
@Ovahlord That's reasonable, but assumes that the calling code has complete knowledge of the implementation of Unit::GetVictim while I don't think it should be written with that assumption. If you're not going to assign the returned Unit pointer to a local variable then calling the asserting version of GetVictim should be preferred imo.

I am aware that the behavior does not actually change in these cases but this seems the better way.

**Comment by Ovahlord** [comment]
I dunno, to me it seems like wasted performance and inconsistent code using two different helpers with one calling a macro that's completely useless in that scenario.

**Comment by Shauren** [comment]
No. EnsureVictim only exists to shut up static analysis tools, you absolutely do not need it in places where GetVictim was already checked for nullptr

**Comment by HelloKitty** [comment]
I disagree, the calling could should not have the assumption that it knows the exact implementation of Unit::GetVictim. It should not assume it returns the same exact Unit pointer even though we do know that it will. But I guess it really is a trivial matter and I don't care much about pursuing the matter further so I'll delete the branch.

**Pull request closed without merging**
