### PR TITLE
removes UNIT_FLAG_IMMUNE_TO_PC from "The Crone (Karazhan)"

### LINKED ISSUE #15426: [3.3.5a]The Crone doesn't become attackable during the Opera Event
Revision: 2bcd9c543f1f

After killing Roar, Dorothee, Tinhead, Strawman and Tito, The Crone correctly spawns, but does not become attackable. You drop combat, and if you teleport out of the instance and come back you can start up another event. The Crone will still be present during the new encounter.

### PR DESCRIPTION
**Pull request by dubitabam**
fixes #15426

### CODE REVIEW

**Comment by Killyana** [comment]
The Flag is supposed to be removed here: https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp#L705
Maybe  EnterCombat never happen as immune to pc make it passif
``` cpp
        void EnterCombat(Unit* /*who*/) override
        {
            Talk(SAY_CRONE_AGGRO);
            me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
            me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
        }

**Comment by Aokromes** [comment]
We don't use PRs as sql only fixes, if something is broken c++ side must be fixed.

**Comment by daevidpreis** [comment]
Sorry didn't know that. As I'm pretty new to Trinity. But it worked on my development machine.
Maybe you can send me a personal message or a hint how you handle sql only request?

**Comment by DDuarte** [comment]
You can put SQL only fixes in an issue however this specific one probably should be done with C++

**Comment by daevidpreis** [comment]
Woooow you are really fast :D
As I said, I'm pretty (absolutely) new to Trinity. I'll make myself more familiar with Trinity before sending any other PR!

**Comment by DDuarte** [comment]
No problem, set yourself comfortable and thanks for the fixes :)

**Comment by Treeston** [comment]
Yeah, unless you make an NPC aggro her, she'll never hit EnterCombat with that flag set.

**Comment by Aokromes** [comment]
@daevidpreis you can jump into irc if you need more real time comunication.
irc.rizon.net #trinity

**Pull request closed without merging**
