### PR TITLE
[3.3.5] Fix strings for Dwarven and Troll Dices

### PR DESCRIPTION
**Pull request by Magnifikator**
TextEmote() starts already with the playername. No need to add it once more.

### CODE REVIEW

**Comment by Aokromes** [comment]
Plz, convert this to creature_text

**Comment by Magnifikator** [comment]
It's a player emote not a creature.

**Comment by DDuarte** [comment]
I think this PR is fine as it is and it can be merged.
If you'd still like to move the text to the DB, the merge can wait.

**Comment by Magnifikator** [comment]
I can only tell how to do it:

Add in trinity_string something like this:
```
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('10500','%s rubs %s [Decahedral Dwarven Dice] between %s hands and rolls. One %u and one %u.',NULL,NULL,'schüttelt %s [Zehnseitige Zwergenwürfel] zwischen %sn Händen und würfelt. Eine %u und eine %u.',NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('10501','%s causually tosses %s [Worn Troll Dice]. One %u and one %u.',NULL,NULL,'wirft locker %s [Abgenutzte Trollwürfel]. Eine %u und eine %u.',NULL,NULL,NULL,NULL,NULL);
```

Add in language.h:
``` 
LANG_DWARVEN_DICE = 10500,
LANG_TROLL_DICE = 10501,
```
and in SpellEffects it must be like this:
```sprintf(buf, m_caster->ToPlayer()->GetSession()->GetTrinityString(LANG_DWARVEN_DICE), gender, gender, urand(1, 10), urand(1, 10));```

and

```sprintf(buf, m_caster->ToPlayer()->GetSession()->GetTrinityString(LANG_TROLL_DICE), gender, urand(1, 6), urand(1, 6));```

Don't know what is a proper number in language.h.

**Comment by joschiwald** [comment]
are there some sources that this string is correct? (sniff, guides, videos, comments on wowhead or something else)

i'm sure blizzard constructs this string in another way

**Comment by Magnifikator** [comment]
no

**Comment by joschiwald** [comment]
i'm not talking about localization, i think the string is completly wrong (old mangos code)

**Comment by joschiwald** [comment]
found something: broadcasttext 26147 and 26152

WotLK Patch 3.1.1 (2009-04-21): The dice now trigger a standard /roll command when used.

    <Name> rubs <his/her> [Decahedral Dwarven Dice] between <his/her> hands and rolls.
    <Name> rolls <1-100> (1-100) 

from http://wow.gamepedia.com

**Comment by Magnifikator** [comment]
Another try:   (Feel free to change text and text ID)

```
replace into `trinity_string` (`entry`, `content_default`, `content_loc3`) values('10500','rubs his |cffffffff|Hitem:36863:0:0:0:0:0:0:0|h[Decahedral Dwarven Dice]|h|r between his hands and rolls. One %u and one %u.','schüttelt seine |cffffffff|Hitem:36863:0:0:0:0:0:0:0|h[Zehnseitige Zwergenwürfel]|h|r zwischen seinen Händen und würfelt. Eine %u und eine %u.');
replace into `trinity_string` (`entry`, `content_default`, `content_loc3`) values('10501','rubs her |cffffffff|Hitem:36863:0:0:0:0:0:0:0|h[Decahedral Dwarven Dice]|h|r between her hands and rolls. One %u and one %u.','schüttelt ihre |cffffffff|Hitem:36863:0:0:0:0:0:0:0|h[Zehnseitige Zwergenwürfel]|h|r zwischen ihren Händen und würfelt. Eine %u und eine %u.');
replace into `trinity_string` (`entry`, `content_default`, `content_loc3`) values('10502','casually tosses his |cffffffff|Hitem:36862:0:0:0:0:0:0:0|h[Worn Troll Dice]|h|r. One %u and one %u.','wirft locker seine |cffffffff|Hitem:36862:0:0:0:0:0:0:0|h[Abgenutzte Trollwürfel]|h|r. Eine %u und eine %u.');
replace into `trinity_string` (`entry`, `content_default`, `content_loc3`) values('10503','casually tosses her |cffffffff|Hitem:36862:0:0:0:0:0:0:0|h[Worn Troll Dice]|h|r. One %u and one %u.','wirft locker ihre |cffffffff|Hitem:36862:0:0:0:0:0:0:0|h[Abgenutzte Trollwürfel]|h|r. Eine %u und eine %u.');
```

Language.h:
```
    LANG_DWARVEN_DICE_MALE   = 10500,
    LANG_DWARVEN_DICE_FEMALE = 10501,
    LANG_TROLL_DICE_MALE     = 10502,
    LANG_TROLL_DICE_FEMALE   = 10503,
```

SpellEffects.cpp
```
               // Roll Dice - Decahedral Dwarven Dice
                case 47770:
                {
                    char buf[512];
					const char *genderText = m_caster->ToPlayer()->GetSession()->GetTrinityString(LANG_DWARVEN_DICE_MALE);
					if (m_caster->getGender() > 0)
						genderText = m_caster->ToPlayer()->GetSession()->GetTrinityString(LANG_DWARVEN_DICE_FEMALE);
					
                    sprintf(buf, genderText, urand(1, 10), urand(1, 10));
                    m_caster->TextEmote(buf);
                    break;
                }
                // Roll 'dem Bones - Worn Troll Dice
                case 47776:
                {
                    char buf[512];
                    const char *gender = "seine";
					const char *genderText = m_caster->ToPlayer()->GetSession()->GetTrinityString(LANG_TROLL_DICE_MALE);
					if (m_caster->getGender() > 0)
						genderText = m_caster->ToPlayer()->GetSession()->GetTrinityString(LANG_TROLL_DICE_FEMALE);
					
                    sprintf(buf, genderText, urand(1, 6), urand(1, 6));
                    m_caster->TextEmote(buf);
                    break;
                }

```

**Comment by Magnifikator** [comment]
@joschiwald 
> `<Name> rubs <his/her> [Decahedral Dwarven Dice] between <his/her> hands and rolls.`
> `<Name> rolls <1-100> (1-100) `

To make things simple I would change it into: 
`<Name> rubs <his/her> [Decahedral Dwarven Dice] between <his/her> hands and rolls. <He/Her> rolls <1-100> (1-100) `

Could be change easily in the DB now.

**Comment by joschiwald** [comment]
we don't accept new trinity strings, use right broadcasttexts instead

**Comment by Magnifikator** [comment]
Broadcasttexts are for creatures, aren't they ?

**Comment by Aokromes** [comment]
No, broadcasttexts contains all blizzlike texts, even non-creature ones.

**Comment by joschiwald** [comment]
yes

**Comment by joschiwald** [comment]
try this
```c++
enum RollDice
{
    TEXT_DECAHEDRAL_DWARVEN_DICE = 26147,
    TEXT_WORN_TROLL_DICE         = 26152
};

// 47770 - Roll Dice
class spell_item_decahedral_dwarven_dice : public SpellScriptLoader
{
    public:
        spell_item_decahedral_dwarven_dice() : SpellScriptLoader("spell_item_decahedral_dwarven_dice") { }

        class spell_item_decahedral_dwarven_dice_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_item_decahedral_dwarven_dice_SpellScript);

            bool Validate(SpellInfo const* spellInfo) override
            {
                if (!sObjectMgr->GetBroadcastText(TEXT_DECAHEDRAL_DWARVEN_DICE))
                    return false;
                return true;
            }

            bool Load() override
            {
                return GetCaster()->GetTypeId() == TYPEID_PLAYER;
            }

            void HandleScript(SpellEffIndex /*effIndex*/)
            {
                GetCaster()->TextEmote(TEXT_DECAHEDRAL_DWARVEN_DICE, GetHitUnit());

                Player* player = GetCaster()->ToPlayer();
                uint32 minimum = 1;
                uint32 maximum = 100;
                uint32 roll = urand(minimum, maximum);

                WorldPacket data(MSG_RANDOM_ROLL, 4 + 4 + 4 + 8);
                data << uint32(minimum);
                data << uint32(maximum);
                data << uint32(roll);
                data << uint64(player->GetGUID());
                if (Group* group = player->GetGroup())
                    group->BroadcastPacket(&data, false);
                else
                    player->SendDirectMessage(&data);
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_item_decahedral_dwarven_dice_SpellScript::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_item_decahedral_dwarven_dice_SpellScript();
        }
};

// 47776 - Roll 'dem Bones
class spell_item_worn_troll_dice : public SpellScriptLoader
{
    public:
        spell_item_worn_troll_dice(char const* scriptName, uint32 roll, uint32 textId) : SpellScriptLoader("spell_item_worn_troll_dice") { }

        class spell_item_worn_troll_dice_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_item_worn_troll_dice_SpellScript);

            bool Validate(SpellInfo const* spellInfo) override
            {
                if (!sObjectMgr->GetBroadcastText(TEXT_WORN_TROLL_DICE))
                    return false;
                return true;
            }

            bool Load() override
            {
                return GetCaster()->GetTypeId() == TYPEID_PLAYER;
            }

            void HandleScript(SpellEffIndex /*effIndex*/)
            {
                GetCaster()->TextEmote(TEXT_WORN_TROLL_DICE, GetHitUnit());

                Player* player = GetCaster()->ToPlayer();
                uint32 minimum = 1;
                uint32 maximum = 6;

                for (uint8 i = 0; i < 2; ++i)
                {
                    uint32 roll = urand(minimum, maximum);

                    WorldPacket data(MSG_RANDOM_ROLL, 4 + 4 + 4 + 8);
                    data << uint32(minimum);
                    data << uint32(maximum);
                    data << uint32(roll);
                    data << uint64(player->GetGUID());
                    if (Group* group = player->GetGroup())
                        group->BroadcastPacket(&data, false);
                    else
                        player->SendDirectMessage(&data);
                }
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_item_worn_troll_dice_SpellScript::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_item_worn_troll_dice_SpellScript();
        }
};
```

**Comment by Nawuko** [comment]
maybe put the MSG_RANDOM_ROLL in its own function. Something like this: http://pastebin.com/Q8BbmvcZ

**Comment by Ascathor** [comment]
@Nawuko referenced a decent piece of code, though. Something along that line seems fairly accurate.

**Comment by Aokromes** [comment]
0295273

**Pull request closed without merging**
