### PR TITLE
Core/Racial:Auto learn Apprentice Riding and Running wild for worgens th...

### PR DESCRIPTION
**Pull request by Loukie**
...at reach level 20

### CODE REVIEW

**Comment by Shauren** [comment]
hack

**Comment by Loukie** [comment]
how come?

**Comment by Loukie** [comment]
I dont see a nother way of doing this and Worgens does auto learn these to spells when the reach level 20 so explain to me way you would say that this is hack?

**Comment by Rushor** [comment]
if the person, who nearly invented the whole core for tc, say that it's a hack, it's a hack. probably ask him on irv for more infos :D

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c927acf1f47e2cb80062042e172aeff17df862be

**Comment by DDuarte** [comment]
Compare @Loukie's proposed solution (https://github.com/TrinityCore/TrinityCore/pull/14305/files) and Shauren's fix addressing the same issue: https://github.com/TrinityCore/TrinityCore/commit/c927acf1f47e2cb80062042e172aeff17df862be

Hardcoded IDs and very specific checks are usually a Bad Ideia™

**Pull request closed without merging**
