### PR TITLE
[6.x] Update worldserver.conf.dist

### PR DESCRIPTION
**Pull request by alexandre433**
**Target branch(es):** 6.x

**Tests performed:** It builds and it was tested (Does it build, tested in-game, etc)

Change of some errors which give on the server.log for not beeing there.

I don't really know some descriptions thus them beeing "None"

### CODE REVIEW

**Comment by tkrokli** [comment]
Regarding `MonsterSight` and `GuarderSight`: those options will not be added to Worldserver.conf without a proper description of what they are / what they do. See also [**Undocumented config options**](16859) #16859 for previous discussion on this topic.

**Comment by alexandre433** [comment]
So should I edit the description from what I understand what the names of those options do?

**Comment by tkrokli** [comment]
If you have got correct information about what the options do, it would definitely be an improvement. :)

**Comment by Shauren** [comment]
Adding these values with no description serves no purpose

**Pull request closed without merging**
