### PR TITLE
Scripts/Spells: Runic Healing Injector

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Migrate spell `Runic Healing Injector` to spell scripts system.

**Target branch(es):** 3.3.5

~~**Issues addressed:**~~

**Tests performed:** Works!

~~**Known issues and TODO list:**~~

### CODE REVIEW

**Comment by illfated** [comment]
Same here, rebasing your PR branch on TC 3.3.5 will remove the travis-ci error.

**Comment by jackpoz** [comment]
I think this PR got mixed up with https://github.com/TrinityCore/TrinityCore/pull/23691

**Comment by Sorikoff** [comment]
Looks fine now.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
