### PR TITLE
Scripts/Commands: implement reload lfg_dungeon_template command

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  implement reload lfg_dungeon_template command

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

### CODE REVIEW

**Comment by Treeston** [comment]
Conflicted RBACs, please rebase.

**Comment by Shauren** [comment]
Doesn't reloading break random dungeon?
See https://github.com/TrinityCore/TrinityCore/blob/4b6351e6a5a2e2c986f3c0ea8e25bc76055c5b2c/src/server/game/DungeonFinding/LFGMgr.cpp#L256

**Comment by Aokromes** [comment]
Conflicting files
sql/base/auth_database.sql
src/server/scripts/Commands/cs_reload.cpp

**Comment by Shauren** [comment]
Still waiting for test if this doesnt break random queue

**Comment by jackpoz** [comment]
@ForesterDev could you take a look at the question/test above about breaking random queue ?

**Pull request closed without merging**
