### PR TITLE
Core/SmartAI: Allow setting orientation for SMART_ACTION_MOVE_TO_POS

### PR DESCRIPTION
**Pull request by Sorikoff**
**Changes proposed:**
Pass orientation to MotionMaster when raw coordinates in SMART_ACTION_MOVE_TO_POS are given.

**Target branch(es):** 3.3.5

**Issues addressed:** Ref #22975

**Tests performed:** Does build, tested with custom SQL

~**Known issues and TODO list:**~

### CODE REVIEW

**Comment by Killyana** [comment]
Can you add : action_param5=movement_type=0/1 (run/walk)

**Comment by Sorikoff** [comment]
In separate PR.

**Comment by Ovahlord** [comment]
I'm still  not a fan of shoving orientation into move commands because blizzlike approaches would be creating a 2nd move call after reaching the desired destination. So IF you want to do both in one function call, make sure to call two splines. one to move to the position and one to face to the desired direction. That's how blizz does it.

**Comment by Sorikoff** [comment]
Could you please clarify then why orientation can even be passed to MoveGen if it is not blizzlike approach?

**Comment by Ovahlord** [comment]
Because someone probably thought that this is a nice way to do while it's actually wrong. As far as I have seen movement packets in sniffs, facing with orientation values are never being sent together with a destination. There is only one case where facing is being used together and that's chase movement. But even in this face the chase movement does not use facing angles but a facing target guid.

**Comment by Sorikoff** [comment]
Thanks for clarification.

**Pull request closed without merging**
