### PR TITLE
Fixed load taxi nodes.

### PR DESCRIPTION
**Pull request by SeTM**
Spell nodes not have prices.
to #12832

### CODE REVIEW

**Comment by jackpoz** [comment]
Which flypaths does this change affect ?

**Comment by SeTM** [comment]
All fly paths from refrenced issue (The Exodar, Blood Watch, Bloodmyst Isle - 508, 509) and others spell path (select effectmiscvalue1+1 from spell_dbc where effect1 = 123;) that used in normal flight.

**Comment by jackpoz** [comment]
With "which flypaths" I mean a list of flypaths.

Anyway, here's the list of the affected spells:
- 29376
- 29377
- 31752
- http://wotlk.openwow.com/spell=34578
- http://wotlk.openwow.com/spell=47851

**Comment by Aokromes** [comment]
SeTM you don't have got your bounty no? :)

**Comment by SeTM** [comment]
No I did not receive it

**Comment by Aokromes** [comment]
you must ask for it on bs.

**Pull request merged**
