### PR TITLE
Fix other make program e.g. ninja/nmake in windows

### PR DESCRIPTION
**Pull request by ryancheung**
Fix other make program e.g. ninja/nmake in windows by upgrading cotire and updating cmake auth/world server conf file install command

**Changes proposed:**

-  Upgrade cmake pch module cotire to fix compile with ninja(or other make  program than msbuild) in windows
-  Fix auth/world server conf install cmake command when building with ninja(or other make  program than msbuild)

**Without these changes, build with ninja in cmake would raise the following build error:**

```
[build] Launching build
[proc] Execute command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/WoWEmulators/TrinityCore/build --config RelWithDebInfo --target all -- -j 14
[build] ninja: error: 'PrecompiledHeaders/commonPCH.h', needed by 'src/common/CMakeFiles/common.dir/Banner.cpp.obj', missing and no known rule to make it
[build] build completed，exit code is 1
```

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
-

**Tests performed:** (Does it build, tested in-game, etc.)
Tested in local build with ninja and cmake in vscode.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by ryancheung** [comment]
Developing, building, and one-button-click debugging the core with vscode without even opening VS 2017 is really awesome.

**Review by Shauren — CHANGES_REQUESTED** [review]
This reverts all our custom changes to cotire, including a fix for garbage cotire behavior that forces a complete full rebuild when any source file is changed if PCH is enabled (not just if a header that is included in PCH header gets changed)

Cannot accept

**Comment by ryancheung** [comment]
Oh, I didn't know that. I didn't know much about cotire and i can't give more changes of cotire. 
I'll create a issue instead of this PR.

**Comment by jackpoz** [comment]
Maybe we can merge latest cotire with our custom changes (even if cotire project is dead and we should replace it)

**Comment by ryancheung** [comment]
Yeah, just looked the cotrie readme and noticed cotire would be replaced with cmake PCH features of version 3.16+. Maybe we should replace cotire with that.

**Comment by Aokromes** [comment]
@Naios The functionality provided by cotire has been superseded by features added to [CMake 3.16][cmkr].
:P

**Comment by ryancheung** [comment]
It should be pretty easy to replace `add_cxx_pch` with `target_precompile_headers`, like: 
```
target_precompile_headers(game PRIVATE ${PRIVATE_PCH_HEADER})
```

Not sure how UNITY_BUILD works for now.

**Comment by Naios** [comment]
@Aokromes  The question is more whether you want to introduce CMake 3.16 as dependency.

I personally would recommend to do it since upgrading CMake is super easy in general.

**Comment by jackpoz** [comment]
- Latest CMake on latest Ubuntu 19.10 is 3.13.4 https://packages.ubuntu.com/eoan/cmake
- Latest CMake on latest Debian Buster is 3.13.4 https://packages.debian.org/buster/cmake

**Comment by ryancheung** [comment]
It is not a problem. You can download the bash script provided by cmake to install any version.

**Pull request closed without merging**
