### PR TITLE
Core/Scripts: set correct unit_flags on npc_scarlet_miner_cart

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

After recent changes to the source, `npc_scarlet_miner_cart` gets attacked
right after player enters the GO/NPC to be towed down to Light's Point.
This PR fixes the issue by making it non-attackable for NPCs.
- remove the `UNIT_FLAG_IMMUNE_TO_PC` line used in this script.
- add correct `unit_flags` to the DB entry/NPC ID 28817 Mine Car

Based on the information provided by r00ty-tc in https://github.com/TrinityCore/TrinityCore/issues/17816#issuecomment-241528244 :

```
[1] UpdateType: CreateObject1
[1] GUID: Full: 0xF1507091001852C8 Type: Vehicle Entry: 28817 Low: 1594056
[1] Object Type: Unit (3) (0x0003)
[1] Update Flags: Living, StationaryObject, Vehicle (224) (0x00E0)
[1] Movement Flags: None (0) (0x0000)
[1] Extra Movement Flags: None (0) (0x0000)
.........
[1] UNIT_FIELD_FLAGS: 520/7.286752E-43
[1] UNIT_FIELD_FLAGS_2: 2048/2.869859E-42
```

From https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-unit_flags :

| Flag | Hex | Name | Comment |
| --- | --- | :-- | :-- |
| 8 | 0x0008 | UNIT_FLAG_PVP_ATTACKABLE | Allows to apply PvP rules to attackable state in addition to faction dependent state |
| 512 | 0x0200 | UNIT_FLAG_IMMUNE_TO_NPC | Disables combat/assistance with NonPlayerCharacters (NPC) |

Combined, this makes the `unit_flags` value 520 instead of 512 as I first suggested.

**Target branch(es):** 3.3.5 and 6.x

**Issues addressed:** Closes issue  #17816 (Core/Scripts/Quest: Massacre at Light's Point)

**Tests performed:** (Does it build, tested in-game, etc) Builds OK, tested by the issue participants.

**Known issues and ToDo list:**
- [X] remove wrong flag set in the core script
- [X] set correct correct `unit_flags` on the DB entry/NPC ID 28817 'Mine Car'

### CODE REVIEW

**Comment by joschiwald** [comment]
the correct unitflag should go into db, the script stuff can be removed

**Comment by tkrokli** [comment]
OK, I have updated issue #17816 with the SQL fix, so I hereby close this PR (SQL-only fixes don't use PRs).

**Comment by tkrokli** [comment]
Sorry, I totally forgot the core script lines interfering with the UNIT_FLAGS. Reopening to correct it.

**Comment by ariel-** [comment]
According to sniff, faction field is wrong too:

```[2] OBJECT_FIELD_ENTRY: 28817/4.038122E-41
[2] OBJECT_FIELD_SCALE_X: 1065353216/1
[2] UNIT_FIELD_CREATEDBY: 72737522/2.514224E-36
[2] UNIT_FIELD_CREATEDBY + 1: 100663296/2.407412E-35
[2] UNIT_FIELD_BYTES_0: 16908544/2.387795E-38
[2] UNIT_FIELD_HEALTH: 2699/3.782105E-42
[2] UNIT_FIELD_MAXHEALTH: 2699/3.782105E-42
[2] UNIT_FIELD_LEVEL: 56/7.847271E-44
[2] UNIT_FIELD_FACTIONTEMPLATE: 1610/2.256091E-42```

**Comment by Shauren** [comment]
@ariel- isn't 1610 the player blood elf faction? some vehicles do inherit its passenger faction

**Comment by tkrokli** [comment]
Yes, according to https://trinitycore.atlassian.net/wiki/display/tc/FactionTemplate 1610 = PLAYER, Blood Elf

**Comment by DDuarte** [comment]
Since summoned creatures and vehicle inherit the faction of their masters, WPP sort of ignores factions of players in creatures: https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParser/SQL/Builders/WDBTemplates.cs#L96

**Comment by ariel-** [comment]
Weird, I got this on a CreateObject packet, maybe it was already in use by other player. Gotta recheck.

**Pull request merged**
