### PR TITLE
Core/Movement: fixed taxi pathings getting finalized earlier than intended

### PR DESCRIPTION
**Pull request by Ovahlord**
**Changes proposed:**

-  followup fix for cf3277c641bd877b9fa1939da5da7cde1778561b discussed in https://github.com/TrinityCore/TrinityCore/issues/23829

**Target branch(es):** 3.3.5/master
- [x] 3.3.5

### CODE REVIEW

**Comment by jackpoz** [comment]
Tested ingame etc ?

**Comment by Ovahlord** [comment]
Kilyana tested it and said it seems to be fine.

**Comment by jackpoz** [comment]
does https://github.com/TrinityCore/TrinityCore/pull/23830/files#diff-d0720ce3f8edece58e8e6e5483a786beR126 need to be changed too ? or why did the array range check change to _currentNode < _path.size() - 1 ?

**Comment by Ovahlord** [comment]
Since we now deal with a path that is 1 point larger than intended we also have adapt the path.size changes accordingly so the checks will remain intact otherwise we risk getting out of range errors

**Comment by jackpoz** [comment]
If _currentNode is used as index of path,  it doesn't matter how you got it,  with or without the additional start point, < path.size() condition will always stop all out of range cases

**Comment by Ovahlord** [comment]
yes, and with the new spline point _currentNode will be incremented also when we pass the first spline point that is not a actual taxi path point which leads to the problem that we trigger the finalization earlier than intended and all the incremental path size checks also need to be changed accordingly what I just did. Example: prior to my addition we had 13 path points and now since we consider the player position, we have 14 instead. So path.size() - 1 is covering that problem up so all checks will do their old job again.

**Comment by jackpoz** [comment]
so this is ready to be merged, latest version tested too ?

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
