### PR TITLE
[WIP] [3.3.5] Pet hit rating inheritance

### PR DESCRIPTION
**Pull request by PolarCookie**
**Changes proposed:**
Warlock (and hunter) pets do not inherit hit from their owners.
This used to be done through scaling auras, but these seem to have been deprecated in favour of the StatSystem (right?)
Only, StatSystem includes everything for pets but combat ratings, so here's a fix for hit.

This fix feels kinda "tacked on", any thoughts on this @ariel-? you wrote most of the StatSystem, right?

**Target branch(es):**
- [x] 3.3.5

**Issues addressed:** Closes probably many that I don't remember...

**Tests performed:**
Tested for Felhunter, was using Instructor Razuvious on 25 man as my dummy.

Here is the current situation, hit rating was 368 (14.03%)

This PR at 145 hit rating (5.53%), with 3/3 suppression.

This PR at 368 (14.03%), with 3/3 suppression.

### CODE REVIEW

**Comment by Shauren** [comment]
No, doing it with auras is the preferred way, it was supposed to be done with auras but never properly implemented

**Comment by PolarCookie** [comment]
well, until they work, this will do for now.

**Comment by robinsch** [comment]
You simply prevent mistakes by implementing the auras, for example Ghoul should not get owners hit scaling (they don't have an aura for it).

**Comment by PolarCookie** [comment]
What is the problem with the scaling auras then? why do they not work/what needs to be fixed?

**Comment by Keader** [comment]
They dont have a "base point", you need set amount by scripts :)
hard part is: know how much

**Comment by robinsch** [comment]
@PolarCookie  Base points / talent scaling etc.

**Pull request closed without merging**
