### PR TITLE
Core/Gossip: Update GossipOptionIcon to latest 9.1.0 values

### PR DESCRIPTION
**Pull request by MaxtorCoder**
**Changes proposed:**

-  Update GossipOptionIcon enum to latest values

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Tests performed:**
- Builds
- Tested ingame

### CODE REVIEW

**Comment by Faq** [comment]
Some work is done here https://github.com/TrinityCore/TrinityCore/pull/26906

**Comment by MaxtorCoder** [comment]
> Some work is done here #26906

I see, thanks! This was just merely for updating the values real quick so it worked :D Will close it.

**Comment by meji46** [comment]
@MaxtorCoder do you mind if I add the latest enum values to my PR?

**Comment by MaxtorCoder** [comment]
> @MaxtorCoder do you mind if I add the latest enum values to my PR?

Go for it 😄

**Pull request closed without merging**
