### PR TITLE
[WIP] Scripts/Mardum: Mardum, the Shattered Abyss

### PR DESCRIPTION
**Pull request by osleyder85**
**Changes proposed:**

Complete work of Mardum zone, including spawns, phases, quests, waypoints...

- Funtions
    - [x] Add funtion OnUpdate and OnPlayerUpdate in ScriptMgr.

- Spawns
    - [x] Add missing spawn in area 7705 - Mardum, the Shattered Abyss.

- Scenes
    - [x] Add scene Start Demon Hunters.

- Conversations
    - [x] Add conversation Start Demon Hunters.

- Path:
    - [x] Add path for Dread Felbat.
    - [x] Add path for Legion Command Center.

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by funjoker** [comment]
The scene is bit triggered via own hook you implemented.

it’s actually an aura which interrupts on move.
OnRemove it triggeres conversation.

You can actually create DH, move and see conversation logout and do it again.
First login log is not needed.

**Comment by osleyder85** [comment]
@funjoker  I have created a DH on the official server and I have seen the scene and the conversation only once, every time I go back in the npc already appear.

**Comment by MaxtorCoder** [comment]
If you copy from AshamaneCore at least copy it properly. Changing a few thing here and there doesn't help.

**Comment by illfated** [comment]
> I also don't call this a complete rework if the scripts didn't even exist before this PR.

Fair enough, what should be used instead? "implement" is mostly used when adding new spells, functions or methods.

**Comment by illfated** [comment]
@osleyder85 : Cosmetic/codestyle suggestion for your SQL file; remove the blank comment lines (except for line 1) unless you have planned to add more comment content in those subsequent lines.

**Comment by illfated** [comment]
> If you copy from AshamaneCore at least copy it properly.

If any parts or all of the PR content stems from AshamaneCore, this PR should display some form of acknowledgement to the source, according to Open Source rules.

**Comment by funjoker** [comment]
Will check again, but it is 100% interrupt flag of aura.

**Comment by osleyder85** [comment]
> 
> If you copy from AshamaneCore at least copy it properly. Changing a few thing here and there doesn't help.

If you look closely, I have only used what I think is correct. You haven't even verified if it works or not. Please when you go to comment on any of my arrangements speak with arguments.

**Comment by osleyder85** [comment]
> 
> 
> Will check again, but it is 100% interrupt flag of aura.

That you recommend me to put an areatrigger or spell_area. The conversation and the scene exit when player-> GetPositionY () <3281.f is reached. Nor is there anything in Conditions that allows me to ask, that only happens when you log in for the first time and get to the point.2

**Comment by jackpoz** [comment]
is this still WIP (as the title says [WIP]) ? Is so please change the PR status to draft, it makes it easier to know if a PR is ready to be merged or not.

**Comment by funjoker** [comment]
Ok i digged my old stuff:

- The start scene is triggered by a serverside spell
  - SpellID: 196030 Name: Start: Quest Invis
  - Data must be filled manually:
    spell_interrupts -> AuraInterruptFlags1 = 40 (Move and Jump)
    spell_interrupts -> InterruptFlags = 23 
    spell_misc -> some fitting attributes and ranges etc...
    spell_effect -> Effect = 6 Aura = 4 ImplicitTarget1 = 1
- This spell is linked to the scene play spell
  - SpellID: 193525 Name: Start: Demon Hunters - Play Scene
    ```
    INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `comment`) VALUES 
    (-196030, 193525, '');
    ```
- Spell 193525 is linked to Update Phase Spell
    ```
    INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `comment`) VALUES 
    (-193525, 82238, 'Update Phase');
    ```
- To track completion of actions, blizzard mostly uses quests or objectives, in this case they do too!
  - QuestID: 40076 Name: Start Demon Hunter Tracking Event
- Simply use spell_area to handle where aura is used and link it to the tracking quest
  ```
  INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, 
  `quest_start_status`, `quest_end_status`) VALUES 
  (196030, 7705, 0, 40076, 0, 0, 2, 1, 64, 1);
  ```

All this DB stuff makes the scene start on move or jump when you created a Demon Hunter
To make it only 1 time only, we have to apply a SceneScrip, for examplet:

```
enum SceneQuests
{
    START_DEMON_HUNTER_TRACKING_EVENT = 40076
};

class scene_demon_hunter_start : public SceneScript
{
public:
    scene_demon_hunter_start() : SceneScript("scene_demon_hunter_start") { }

    void OnSceneStart(Player* player, uint32 /*sceneInstanceID*/, SceneTemplate const* /*sceneTemplate*/) override
    {
        Quest const* quest = sObjectMgr->GetQuestTemplate(START_DEMON_HUNTER_TRACKING_EVENT);
        if (!quest)
            return;
        
        if (!player->GetQuestRewardStatus(START_DEMON_HUNTER_TRACKING_EVENT))
            player->AddQuestAndCheckCompletion(quest, NULL);
        else
            return;
    }
    void OnSceneTriggerEvent(Player* player, uint32 /*sceneInstanceID*/, SceneTemplate const* /*sceneTemplate*/, std::string const& triggerName) override
    {
        if (triggerName == "CUEILLIDANTH")
            // Illidan Conversation
            return;
    }
};
```

**Comment by djmafiaem** [comment]
Hi, I'm new here, I have a question, are we still working on this? ... can it already be implemented?

**Comment by MaxtorCoder** [comment]
> Hi, I'm new here, I have a question, are we still working on this? ... can it already be implemented?

It's a WIP for a reason lol

**Comment by Traesh** [comment]
> 
> 
> Hi, I'm new here, I have a question, are we still working on this? ... can it already be implemented?

Well this PR is like 1% of what is required to make Mardum "doable", and even that 1% is already under heavy discussion :p

@funjoker to be fair if you want to use serverside spells in script you probably should redo the whole "scripts" folder as Blizzard rely heavily on spells for their own script (yet i agree that the OnUpdate(player) is a shitty solution, the whole mardum script was made in 2 days and there is a reason it was never proposed to be merged on TC).

**Comment by funjoker** [comment]
@Traesh well, we just have to wait for serverside spells being added :D 
Alternatively we can use hotfix table for now. (Hack)

**Comment by funjoker** [comment]
Let’s see what I can do today. Serverside spells are implemented :D

**Comment by djmafiaem** [comment]
cool :D

**Comment by funjoker** [comment]
I'm working on Mardum myself now.
This PR seems to be abandoned by creator.

**Comment by funjoker** [comment]
#29211 here is some proper implementation of intro btw ;)

**Pull request closed without merging**
