### PR TITLE
Scripts/Spells: Wandering Plague should ignore targets under breakabl…

### LINKED ISSUE #26162: DK/Talent Wandering Plague shoud no longer damages secondary targets affected by Repentance
**Description:**

When you face two enemies and someone does cast [Repentance](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=20066) on one of them when you single target disease the other one , the Repentance enemie shoud not escape from cc by taking damage from [Wandering Plague](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=49655) talent.

**Expected behaviour:**

>[No longer damages secondary targets affected by  [Repentance].](https://wow.gamepedia.com/Wandering_Plague_(death_knight_talent))

**Steps to reproduce the problem:**

1. For a quick reproduction of the bug you need a Death Kningt Unholy with Wandering Plague talent (add some melee critical strike bonus) .
2. Fight two melee range enemies , cast on one of them Repentance .cast 20066 then keep disease the other one single target .
3. Notice the enemy with Repentance will get damage from Wandering Plague and will escape from Repentance Crowd Control.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 60680283db79 

TrinityCore rev. 60680283db79 2021-02-24 21:20:47 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/109160016-f336bc00-777d-11eb-825f-2a0696a1955b.mp4

### PR DESCRIPTION
**Pull request by r4d1sh**
…e by damage crowd control effects.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #26162

NOT TESTED

### CODE REVIEW

**Comment by jackpoz** [comment]
> NOT TESTED

Setting the status of this PR back to Draft as it's not tested, please publish it after it has been tested

**Comment by r4d1sh** [comment]
@CraftedRO can you please test this fix of your issue (#26162)?

**Comment by Jildor** [comment]
@r4d1sh you should check if target has aura with:
```AuraInterruptFlags & AURA_INTERRUPT_FLAG_TAKE_DAMAGE```
instead of: ```HasBreakableByDamageCrowdControlAura```

We need here to look for spells that are canceled when receiving damage, not just any CC

**Comment by r4d1sh** [comment]
> @r4d1sh I think you should check if target has aura with:
> `AuraInterruptFlags & AURA_INTERRUPT_FLAG_TAKE_DAMAGE` with negative effect
> instead of: `HasBreakableByDamageCrowdControlAura`
> 
> We need here to look for spells that are canceled when receiving damage, not just any CC with the AURA_INTERRUPT_FLAG_TAKE_DAMAGE
> 
> edit: I'm not sure if we would have any that didn't fit with HasBreakableByDamageCrowdControlAura, just in case
> 
> edit 2: well, I don't see any aura that doesn't go into HasBreakableByDamageCrowdControlAura, maybe that's enough

Well, if we take literally the description of spell in tooltip, then we need to remove all targets with damage breakable auras, even positive ones.

**Comment by CraftedRO** [comment]
Meh I tried to test but I found out that they just fk up mysql requirements meanwhile , on same mysql it worked until now , now it doesn't :)
`TrinityCore does not support MySQL versions below 5.7 (found id 50505, need id >= 50700), please update your MySQL server`
Now I need to revert mysql changes too lel ...

**Comment by Jinnaix** [comment]
Its not "fucked up" if TrinityCore decides to drop support for dead software versions.

Release | Release date | End of life
-- | -- | --
MySQL 5.7 | October 21, 2015 | October 21, 2023
MySQL 5.6 | February 5, 2013 | February 5, 2021
MySQL 5.5 | December 3, 2010 | December 3, 2018

**Comment by CraftedRO** [comment]
Il revert that anyway since I need xampp package with php 7.1.33 and I don't wanna upgrade it as they decided .

**Comment by CraftedRO** [comment]
ok I finally tested on latest revision and it seems it works

https://user-images.githubusercontent.com/24683355/132348862-7efca52f-0458-46fe-b4a7-e6526b772dc5.mp4

**Comment by CraftedRO** [comment]
another test

https://user-images.githubusercontent.com/24683355/132349569-0798bea2-bdf2-4672-b456-5a242e8e5f5a.mp4

**Comment by CraftedRO** [comment]
update : it doesn't brake any kind of crowd control now (tested with polymorph) , isn't supposed to not break only Repentance ?

**Comment by r4d1sh** [comment]
> update : it doesn't brake any kind of crowd control now (tested with polymorph) , isn't supposed to not break only Repentance ?

Spell description says about all breakable by damage effects.

**Comment by CraftedRO** [comment]
yes indeed then it wasn't worked for repentance and blizz updated for it too in 3.3.3 patch changes, good PR .

**Comment by r4d1sh** [comment]
> > NOT TESTED
> 
> Setting the status of this PR back to Draft as it's not tested, please publish it after it has been tested

@CraftedRO Thanks for testing!
@jackpoz marked as ready.

**Comment by Keader** [comment]
ty :)

**Pull request merged**
