### PR TITLE
[3.3.5] Scripts/Commands: Small QoL adjustments

### PR DESCRIPTION
**Pull request by Treeston**
- .debug hostil now shows spawn ID (DBGUID) in addition to current GUID (so you can .go creature to it)
- .npc temp now takes an additional argument before the creature entry that determines whether the spawned creature instantly despawns upon death. Default is instant despawn (current behavior).
- Add .npc evade command.
- Add .pet level command.
- .server shutdown and .server restart fail if time is less than a config parameter (default = 30 seconds) and another player is connected. Add new `force` param to override this behavior.

### CODE REVIEW

**Comment by Aokromes** [comment]
NPCs spawned from .npc add temp now despawn 2 minutes after death instead of instantly upon death to allow for looting

IMHO this must be a parameter.

how about don't allow shutdown / restart times under 30s if people is online  without a parameter (server restart/shutdown 10 force)

**Comment by Treeston** [comment]
> NPCs spawned from .npc add temp now despawn 2 minutes after death instead of instantly upon death to allow for looting
>IMHO this must be a parameter.

It's expected behavior imo. Maybe a param to disable it?

> how about don't allow shutdown / restart times under 30s if people is online without a parameter (server restart/shutdown 10 force)

Sounds reasonable.

**Comment by Shauren** [comment]
30 * IN_MILLISECONDS is not 2 minutes

**Comment by jackpoz** [comment]
I wonder if GMs do events spawning bosses and then manually give unrelated loot and would not like this change in .npc add spawn

**Comment by LordUsagi** [comment]
A param to disable loot would be a fantastic idea.

**Comment by jackpoz** [comment]
cs_debug.cpp change can be merged, the cs_npc.cpp one still need to keep current behavior by default

**Comment by Treeston** [comment]
Cleaned everything up by now.

Waiting on tests and review.

**Pull request merged**
