### PR TITLE
Few Main Quests for Tanaan Jungle

### PR DESCRIPTION
**Pull request by ghost**
Defined the Quest Starter and Endings for a few(!) Quests in the Tanaan
Jungle. That aren't all the quests!

### CODE REVIEW

**Comment by Kittnz** [comment]
We don't use PR's for SQL's.

**Comment by Aokromes** [comment]
Also, we don't use multiple sql files on a single target database :P

**Comment by iSwuerfel** [comment]
Ok. First thing I wanted to contribute. ^^ So can you tell me, what to do, to approve further pull requests? :)

**Comment by Kittnz** [comment]
Make an Issue ticket, not a pull request. PR's are for core improvements or changes. Issues are so issues and SQL files

**Comment by iSwuerfel** [comment]
Aaah now :D Thank I will put these things into 1 file and and make an issue. :)

**Comment by DDuarte** [comment]
@iSwuerfel: make sure that you are not introducing already existing data, most/all Tanaan quest starters/enders were already fixed in 4706e741a89a19fe7cfbc9795f57365464cc7404

**Comment by iSwuerfel** [comment]
Oh shiat, didn't see. Thank you for the info, I'm new to the TC Project, always worked private at mangos...
Tomorrow I will take a look at the db and then I think I can start here. x)

**Pull request closed without merging**
