### PR TITLE
Core/Object: Implement FindNearestCreatureWithAura

### PR DESCRIPTION
**Pull request by Nyr97**
**Changes proposed:**

-  Implement FindNearestCreatureWithAura method.
-  Implement NearestCreatureEntryWithLiveStateAndAuraInObjectRangeCheck class to support the searcher.

**Issues addressed:**

None.

**Tests performed:**

Waiting for this to be built.

**Known issues and TODO list:** (add/remove lines as needed)

None.

### CODE REVIEW

**Comment by Ovahlord** [comment]
At this point, I'd rather just add lambda predicate support and use that one instead of bloating the core with case specific selectors

**Comment by jackpoz** [comment]
> At this point, I'd rather just add lambda predicate support and use that one instead of bloating the core with case specific selectors

how do you store i_range with a lambda ? passing local variables as reference ? it's not as easy as it looks, it's more than just 1 function

**Comment by Ovahlord** [comment]
> > At this point, I'd rather just add lambda predicate support and use that one instead of bloating the core with case specific selectors
> 
> how do you store i_range with a lambda ? passing local variables as reference ? it's not as easy as it looks, it's more than just 1 function

so? use the default operator with its default args (entry, range etc) then filter the returned target list with lamda with either   erase_if or remove_if and then resize to 1

**Comment by Warpten** [comment]
> how do you store i_range with a lambda ?
Value capture? Nothing stops you from using lambdas with grid searchers today, all that would need to be added is deduction guides.

**Comment by jackpoz** [comment]
Can any of you 2 then show an example implementing the same as this PR does ? Because theories don't always work and one finds out only when doing a reality check

**Comment by Warpten** [comment]
Threw together one example on the first random snippet I found in IDE (`src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp`):

```cpp
                Creature* target = nullptr;
                // Trinity::FriendlyMostHPMissingInRange u_check(me, 60.0f, 0);
                auto check = [me = me, i_hp = 0](Unit* u) mutable -> bool {
                    if (u->IsAlive()
                        && u->IsInCombat()
                        && !me->IsHostileTo(u)
                        && me->IsWithinDistInMap(u, 60.0f)
                        && u->GetMaxHealth() - u->GetHealth() > i_hp)
                    {
                        i_hp = u->GetMaxHealth() - u->GetHealth();
                        return true;
                    }

                    return false;
                };

                Trinity::CreatureLastSearcher searcher(me, target, check);
                Cell::VisitGridObjects(me, searcher, 60.0f);
```
Didn't even need to add CTAD guides to `GridNotifiers.h` since C++17 is able to do that from constructors, but if it was needed, it'd be as simple as
```cpp
    template <typename C>
    CreatureLastSearcher(WorldObject const*, Creature*&, C&) -> CreatureLastSearcher<C>;
```
Or if you want to be pedantic about it, this also works:
```cpp
 Trinity::CreatureLastSearcher<decltype(check)> searcher(me, target, check);
```
Might take this to another PR.

**Comment by Nyr97** [comment]
Would you be interested in implementing it on your own knowledge and practice instead? I would close this PR in that case. It is just out of my knowledge to put into work if that's what you guys would rather go for.

**Comment by Warpten** [comment]
I mean, the lambda thing does not relate to your PR at all.

**Comment by Nyr97** [comment]
The only reason I wanted to add this helper is sometimes we want to look for a certain creature with a certain aura, and rather than having 2 lines involved for it after looking for the NearestCreature, set it all into one at least.

**Comment by jackpoz** [comment]
Thanks @Warpten for the example, that helps a lot.

Would it make sense to approve this PR anyway ? it's not like in the past we added these helpers only if there were at least 10 cases where they are used and the lambda is just one more possible way to do it.

**Comment by Warpten** [comment]
Lgtm?

**Comment by jackpoz** [comment]
Thanks for the PR 🚀 😃

**Pull request merged**
