### PR TITLE
[WIP] [3.3.5] Core/Battlefield: Wintergrasp rewrite

### PR DESCRIPTION
**Pull request by ccrs**
What the tittle says.
tagging many issues

#6132 #6133 #8413 #8474 #8661 #9035 #9205 #9423 #19241
ref #20144

Target branch(es): 3.3.5

### CODE REVIEW

**Comment by Keader** [comment]
Need resolve conflicts ccrs :)

**Comment by ccrs** [comment]
went from 850 to 760 commit behind, slowly but steady

**Comment by ccrs** [comment]
done, but dont be too hyped, August-September is still the planned date

**Comment by AByakugans** [comment]
Should I test it for you? There are many changes in Language.h why is that?

**Comment by illfated** [comment]
@AByakugans : check the TC 3.3.5 commits from the last 3 weeks and look for anything related to chat links (invalid messages). That should explain most of it.

**Comment by AByakugans** [comment]
Exactly... Can someone update it for latest core please? And tell me how to make it patch so I can only apply it? Thank you.

**Comment by ccrs** [comment]
I went mad, going to split this into different PRs

**Comment by AByakugans** [comment]
Ok and when we can see this new PR? I can test it for you first if you want.

**Comment by illfated** [comment]
@AByakugans : Patience is a virtue. Look for any small Pull Requests in the near future made by **ccrs** , but don't expect them to be specifically labeled "Wintergrasp" as such. Notice that he wrote
> going to split this into different PRs

I read that as if he is planning on splitting it into 10 or 20 different PRs, but I don't actually know.
As long as you are _watching_ the TrinityCore/TrinityCore repository, you should get a notice.

**Pull request closed without merging**
