### PR TITLE
Implement SPELL_AURA_DETECT_AMORE

### PR DESCRIPTION
**Pull request by funjoker**
(taken from 4.3.4)

**Changes proposed:**

-  Handle SPELL_AURA_DETECT_AMORE

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Works ingame as intended

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by P-Kito** [comment]
Whats Amore?

**Comment by illfated** [comment]
`//170 SPELL_AURA_DETECT_AMORE       various spells that change visual of units for aura target (clientside?)`

- https://www.wowhead.com/spell=26802/detect-amore

(BTW, "amore" is Italian for 'love' - like in the phrase "con amore" - with love.)

**Comment by funjoker** [comment]
We can Rename it xD. Anyway it might gets included in some cherrypicking with correct author

**Comment by xvwyh** [comment]
```cpp
    else
	    {
	        if (target->HasAuraType(SPELL_AURA_DETECT_AMORE))
	        {
	            Unit::AuraEffectList const& amoreAuras = target->GetAuraEffectsByType(SPELL_AURA_DETECT_AMORE);
	            for (Unit::AuraEffectList::const_iterator i = amoreAuras.begin(); i != amoreAuras.end(); ++i)
	            {
	                if (GetMiscValue() == (*i)->GetMiscValue())
	                    return;
	            }
	        }
	
	        target->RemoveByteFlag(ACTIVE_PLAYER_FIELD_BYTES2, PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION, 1 << (GetMiscValue() - 1));
	    }
```
can be simplified to
```cpp
    else if (!target->HasAuraTypeWithMiscvalue(SPELL_AURA_DETECT_AMORE, GetMiscValue()))
        target->RemoveByteFlag(ACTIVE_PLAYER_FIELD_BYTES2, PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION, 1 << (GetMiscValue() - 1));
```
Otherwise this is a correct implementation. The only thing this aura does is it allows the client to display aura visuals for spells with the respective value in SpellEntry::RequiredAuraVision field). The current name `SPELL_AURA_DETECT_AMORE` stems solely from the name of spell 26802 "Detect Amore" (which allows the client to display visuals for spell 26869 "Amorous", hence the name), but in later expansions we can find out what the correct name should be:
- 74967 Generic Mod Aura Vision - Quest Zone-Specific 01
- 74968 Generic Mod Aura Vision - Quest Zone-Specific 02
- 81548 Mod Aura Vision, Quest Zone-Specific 01
- 84300 Fuse Mod Aura Vision
- 85548 Mod Aura Vision - Scout's Journal
- 85559 Cancel Mod Aura Vision
- 85884 Powder Keg Mod Aura Vision
- 89270 Mod Aura Vision - Quest Zone-Specific 01
- 91870 Mod Aura Vision, Quest Zone-Specific 01
- 102645 Mod Aura Vision, Holiday 1
- 157882 Mod Aura Vision - Quest Zone-Specific 01
- and many many more

I think it's safe to say that it can be renamed to "Mod Aura Vision" `SPELL_AURA_MOD_AURA_VISION`.

**Comment by Warpten** [comment]
If i recall properly this implementation came from mangos.

**Comment by funjoker** [comment]
It is in a cherrypick of 3.3.5. but since CP progress kinda stopped. It might not be merged within this year or next year

**Comment by kelno** [comment]
Tested just now, seems to be working!
An example with "Detect Amore":
26802 - aura on the target
26869 - aura on the player to see the effect on the target

**Comment by funjoker** [comment]
Will be in some cherrypicking in future.
Prolly will rename it in CP already or later then

**Pull request closed without merging**
