### PR TITLE
Port some commits from master

### PR DESCRIPTION
**Pull request by RioMcBoo**
I don't know if the database update will install correctly. Need help from an experienced person.

### CODE REVIEW

**Comment by Nyr97** [comment]
I'm not sure if StringId existed back in WoTLK, someone else could confirm, not even sure they got it from retail to classic.

**Comment by RioMcBoo** [comment]
I don't even know what it is)) I just decided that it has no effect on the kernel and therefore added it. There was something about convenience.

**Comment by Shauren** [comment]
Please do not make PRs for porting commits between branches, especially if you do not know what they do

**Comment by RioMcBoo** [comment]
What kind of people? Why not just explain what it is? Just closed and threw a show-off. OK. Thank you.

**Comment by RioMcBoo** [comment]
How can I make a cherry-pick if I don't have the right to do so? Can you answer? You are not the first person to tell me this!

**Comment by CraftedRO** [comment]
they're not so interested in wotlk classic branch it seems, as I can see they do not like cherry-ing stuffs because if you miss a single quote or smth they better prefer to cherry the whole thing again by themself instead telling you missed that :)
so mate don't bother any longer and better work on your own fork
after all this time I understand why they are so focused on master branch more (only) because they work (paid) for a private project called firestorm so now everything make sense for me at least.

**Comment by jackpoz** [comment]
> after all this time I understand why they are so focused on master branch more (only) because they work (paid) for a private project called firestorm so now everything make sense for me at least.

lol 🤣
FYI we do not even accept donations, we do not want any money involved in this project, the only remote thing related to that is Bountysource where contributors (like you, if you send a PR) can get a bounty paid.

@RioMcBoo before you start working on something, spending time and putting effort into it, I would suggest to jump on TC discord at https://discord.com/invite/JMtzHqsV and ask "hey guys, would it be useful if I cherry-picked these commits from master to wotlk_classic ?" . That way you will know right away if that's something we need or if we want it done in a special way or if someone else is already working on it. It will result in you feeling less disappointed and more appreciated.

**Comment by CraftedRO** [comment]
> lol 🤣 FYI we do not even accept donations, we do not want any money involved in this project, the only remote thing related to that is Bountysource where contributors (like you, if you send a PR) can get a bounty paid.

who said I was talking about this project, you misunderstood ,they work for private server projects, this open source is just a hobby / bonus and that's why it (TC) will never receive all the data sniffed and hard worked for privates project for money.

(it seems who dislike my above comment already felt that it was about him among others)

but don't get me wrong, it is natural for everyone to earn their living

**Comment by RioMcBoo** [comment]
> > after all this time I understand why they are so focused on master branch more (only) because they work (paid) for a private project called firestorm so now everything make sense for me at least.
> 
> lol 🤣 FYI we do not even accept donations, we do not want any money involved in this project, the only remote thing related to that is Bountysource where contributors (like you, if you send a PR) can get a bounty paid.
> 
> @RioMcBoo before you start working on something, spending time and putting effort into it, I would suggest to jump on TC discord at https://discord.com/invite/JMtzHqsV and ask "hey guys, would it be useful if I cherry-picked these commits from master to wotlk_classic ?" . That way you will know right away if that's something we need or if we want it done in a special way or if someone else is already working on it. It will result in you feeling less disappointed and more appreciated.

I actually wrote to the author of this classic thread. From his dry answers, I realized that there was no point in asking anything at all. I created a dubious commit - and a bunch of accusations poured out.

I created two really useful commits, small, but useful and working - so far the author has not raised his hand to approve them.

Well, I'll just communicate with everyone the same way they communicate with me.

Somehow I'll figure it out the right way.

The only reason I wanted to approve these commits is that they change the database. And I wanted my base and the base of this branch to be identical. And since there has been a lull for a long time, and the author of the branch is simply silent and does not comment on anything, I decided to take active steps.

**Comment by MaxtorCoder** [comment]
You clearly told us you had no idea what these commits do, Shauren told you why it wouldn't be merged.

**Comment by RioMcBoo** [comment]
> I don't know if the database update will install correctly. **Need help from an experienced person.**

**Comment by RioMcBoo** [comment]
In any case, it doesn't matter anymore. I'll figure it out somehow. That's what the community is for, to share. If they make their own private server - then why do anything here at all?

My answer is because someone else is doing some of the work for them. Looking at the code base, one thing can be said - this code has been rotten for a long time. I took it up as a hobby and learning. I'm not losing money - I'll survive somehow.

**Comment by Nyr97** [comment]
It is not about being unacknowledged about something working correctly in what you tried to cherrypick. It is about the fact you did not even know what String ID is used for, which clearly tells reviewers to ignore it from the beginning.

**Comment by MaxtorCoder** [comment]
Don’t bother honestly, they made up their minds already about TrinityCore.

**Comment by CraftedRO** [comment]
It's not like we are not right , look at this pr if we talk about tc interest in wotlk classic (https://github.com/TrinityCore/TrinityCore/pull/ 28325) is there for months and will probably be even for years, even 3.3.5 is not doing much better look at this one (https://github.com/TrinityCore/TrinityCore/pull/ 27894) same for months what to talk about sql fixes that are waiting to be merged for weeks but if offl or killyana are not active the others won't merge them because there's no interest , so yea dude TC interest is only in that crap master branch full of crashes and so and if this doesn't lead you to put some questions then idk

**Comment by MaxtorCoder** [comment]
If you do not like TrinityCore why do you even come here to shittalk it??? It's useless and does not help at all.

**Comment by RioMcBoo** [comment]
Look, you don't have to say empty words here. There are specific reasons to say that no one cares: 1) If you are the author of the commit that caused the question - you know exactly whether this commit should or should not be moved. And you can just write two explanatory words, and not find an obvious excuse and do nothing. 2) If a person is busy and cannot devote time, then at the time of personal correspondence, you can say “You know, I have a lot of things to do now, I'll definitely check it out as soon as I get free ,” and not look for reasons not to talk to you. 3) If someone answered these questions in the discord, there would be no questions. 4) When I ask in the discord "why is this necessary", then I expect an answer of such a plan: "I don't know myself", and not: "This is done through a cherry pick". Fortunately, we are not yet robots to form an answer after the first unsuccessful check of the compatibility condition.

**Comment by MaxtorCoder** [comment]
> I don't even know what it is)) I just decided that it has no effect on the kernel and therefore added it. There was something about convenience.

Let me just quote this reply you posted earlier in this section saying you have no idea what either of these commits are hence this PR also being closed down BECAUSE of that reason.

Cherry-picking is done by the main contributers of this source as they usually know what each commit does and how to port code over (if needed)

**Comment by RioMcBoo** [comment]
Ok

**Pull request closed without merging**
