### PR TITLE
Core/CharacterHandler: Allow alliedraces.

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Allow developers to create alliedrace characters if "achievementId" is set to 0 in "world.race_unlock_requirement" table.

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x ] master

### CODE REVIEW

**Comment by jackpoz** [comment]
What was wrong with the other PR ?

**Comment by Varjgard** [comment]
missing function. this one is good to go.

**Comment by Varjgard** [comment]
updated the fork also so made a new request

**Comment by MaxtorCoder** [comment]
> 
> missing function. this one is good to go.

It's the exact same hahahah

**Comment by Varjgard** [comment]
> > missing function. this one is good to go.
> 
> It's the exact same hahahah

well actually it is not. this one passes circleci, and if you check the commits on the other one it had HasAchievement on the code line. fork was updated to make circleci pass. now it passes. on the other pr it did not pass even without HasAchievement.

**Pull request closed without merging**
