### PR TITLE
Created Old SQL Merger For ALL Old TDB's

### PR DESCRIPTION
**Pull request by alexandre433**
**Changes proposed:**
-  Adding this whould help loots of people who have older TDB's installed and it's easier to update their db's to have more fixes on their own compilations.
- Created a file which was modified, which creates all .sql's of the older TDB's.

**Target branch(es):** 3.3.5

**Tests performed:** Tested and works!

### CODE REVIEW

**Comment by DDuarte** [comment]
This isn't needed since the worldserver can automatically update the DBs.

**Comment by alexandre433** [comment]
This is for OLD TDB's not new ones.

The old one's can't update themselves.

**Comment by Treeston** [comment]
This isn't cross platform, and updating DBs that old is more effort than just getting latest TDB. Fixes from that long ago aren't going to work in the latest core anyway.

**Comment by Treeston** [comment]
(Feel free to put it on the forums though.)

**Pull request closed without merging**
