### PR TITLE
BG Deserters tracking system

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
A tracking system for deserters of any kind:

```
enum BattlegroundDesertionType
{
    BG_DESERTION_TYPE_LEAVE_BG        = 0, // player leaves the BG
    BG_DESERTION_TYPE_OFFLINE         = 1, // player is kicked from BG because offline
    BG_DESERTION_TYPE_LEAVE_QUEUE     = 2, // player is invited to join and refuses to do it
    BG_DESERTION_TYPE_NO_ENTER_BUTTON = 3, // player is invited to join and do nothing (time expires)
    BG_DESERTION_TYPE_INVITE_LOGOUT   = 4, // player is invited to join and logs out
};
```

It tracks who(player guid), when(datetime) and how(desertion type) deserts a BG and store it to a new table `battleground_deserters`.

This is a configurable feature, disabled by default:

```
#
#    Battleground.TrackDeserters.Enable
#        Description: Track deserters of Battlegrounds.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

Battleground.TrackDeserters.Enable = 0
```

After merge TODO: update wiki with the new table.

### CODE REVIEW

**Comment by MitchesD** [comment]
What's the usage of that? Can't get it

**Comment by pete318** [comment]
Presumably statistical tracking from external application. Just like the other stats tables.

**Comment by Shauren** [comment]
I wonder about this one - is there an achievement statistic criteria for it? Maybe you could use that if it existed

**Comment by ShinDarth** [comment]
@MitchesD @pete318  not necessarily for external application, a server admin may have interest to know about this kind of data (example: one can abuse and queue a BG just to give to the opponent faction one player more)

@Shauren I don't know about such an achievement

**Comment by Shauren** [comment]
Not achievement, statistic (blizz made a large amount of internal tracking criteria for various things - maybe there is one for this too)

**Comment by ShinDarth** [comment]
@Shauren is there a place where I can look for it? I have no idea

**Comment by Shauren** [comment]
@ShinDarth nvm, there isn't any, I checked.

**Pull request merged**
