### PR TITLE
Fix(Script/Quest) Help Those That Cannot Help Themselves

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Remove npc and item scripts and replace with go script.
-  Quest now looks blizzlike with Mammoth move distance fix and added creature text with sound.

**Tests performed:**

SQL inserts, script compiles, tested in game.

test by:

.tele borean
.quest add 11876

The script is designed so that if the trap is activated it will check every 5 seconds for a respawned calf to reset. It is done this way because there are many trap entries and it would be difficult to check them all from the calf. At first I had the initial timer longer but found that leaving the area would allow the calf to respawn but the script would not update so the trap could take a while to reset even though the calf had respawned.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]
Works for me.
Baby cthulhu loves you
^(;,,,;)^

**Comment by malcrom** [comment]
> Works for me. Baby cthulhu loves you ^(;,,,;)^

If he loves me why did he make me listen to you singing Careless whisper?

**Comment by acidmanifesto** [comment]
> > Works for me. Baby cthulhu loves you ^(;,,,;)^
> 
> If he loves me why did he make me listen to you singing Careless whisper?

I'm never gonna dance again
Guilty feet have got no rhythm

https://www.youtube.com/watch?v=S0L_n68bznE

**Comment by malcrom** [comment]
While waiting for approval: https://www.youtube.com/watch?v=S0L_n68bznE

**Pull request merged**
