### PR TITLE
Core/SmartAI: implement SMART_ACTION_OVERRIDE_LIGHT and SMART_ACTION_OVERRIDE_WEATHER

### LINKED ISSUE #24072: SAI: OVERRIDE_LIGHT and OVERRIDE_WEATHER actions
**Description:** We need 2 new actions, one that allow to change light and an other to change the weather.

For OVERRIDE_LIGHT:  packet field names are AreaLightID, OverrideLightID, TransitionMilliseconds

For OVERRIDE_WEATHER: packet field names are State, Grade, Unk Byte

https://github.com/TrinityCore/TrinityCore/commit/529cabea68ab90e34ccafa276fc40a8f2723902b#diff-9eea3ad0b189ac095427d3c6c6ff68e7R3490-R3536

Example of quest:
OVERRIDE_LIGHT: https://www.youtube.com/watch?v=KHcr8MjbrfU
OVERRIDE_WEATHER: https://www.youtube.com/watch?v=vG8fb_qMzho

**Branch(es):** Both

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  implement new SAI actions

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #24072

**Tests performed:** (Does it build, tested in-game, etc.) Build, tested

### CODE REVIEW

**Comment by Rushor** [comment]
Can you add worldobject targeting? So Every object can trigger the Action?

**Comment by Ovahlord** [comment]
It's actually pointless to do that because changing zone lighting and weather is object independed. Once called it's on a map level so any other object in existance can change it back and forth.

**Comment by Shauren** [comment]
zoneId should not be a parameter. you need to get it from the object

**Comment by Shauren** [comment]
Its redundant to execute it on every target, just use invoker if you want to have zoneid as parameter in db

**Comment by ForesterDev** [comment]
@Shauren, what about improve zoneId parameter with the following behavior;
if zoneId = 0 - then use current zone of invoker
or if zoneId manually set in db - use specific zone

This will add flexibility.

**Comment by Ovahlord** [comment]
Just go with zoneId for the sake of readability. If someone has to edit the sai it makes life significantly easier to just see the context right away instead of having to look up the parameters in the wiki.

**Comment by Shauren** [comment]
Use `GetBaseObject()` instead of `me` to make it work for both creature and gameobject, or invoker (for areatrigger)

**Comment by Killyana** [comment]
We can choose the duration of the light/weather change?

**Comment by Shauren** [comment]
No, you need to manually set it back later (same limitation as C++ scripts)

**Comment by soulfrost** [comment]
fadeInTime isnt related?

**Comment by jackpoz** [comment]
is this PR ready to be merged ?

**Comment by ForesterDev** [comment]
Yes, you can merge

**Comment by Killyana** [comment]
@ForesterDev can you explain what's fadeInTime and weatherGrade?

**Comment by Aokromes** [comment]
weatherGrade i suppose the amount of rain, etc

**Comment by ForesterDev** [comment]
I took these names from 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/Map.cpp#L4636
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/Map.cpp#L4655.

But they need some refactoring, according to opcodes parameter:
weatherGrade -> intensity
fadeInTime -> transitionMilliseconds

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
