### PR TITLE
[Network] Implement SO_REUSEADDR option

### PR DESCRIPTION
**Pull request by Palabola**
**Changes proposed:**
-  Allow to clean up TIME_WAIT connection which can cause false port bind error:

root@/etc# netstat |grep WAIT|grep 808
tcp        0      0 127.0.0.1:8086 192.168.2.2:46319 TIME_WAIT  
tcp        0      0 127.0.0.1:8085 192.168.2.2:46291 TIME_WAIT  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by funjoker** [comment]
learn how to rebase pls

**Comment by funjoker** [comment]
At least use naming standards (not all captial letters)

**Comment by illfated** [comment]
You mean something like `_SO_ReuseAddr` ? (I presume "SO" are initials for Socket Option.)

**Comment by funjoker** [comment]
`_SO_REUSEADDR = sConfigMgr->GetBoolDefault("Network.SO_REUSEADDR", false);`
---->
e.g.
`_socketOptionReuseAddr = sConfigMgr->GetBoolDefault("Network.SocketOptionReuseAddr", false);`

**Comment by jackpoz** [comment]
Does this add back code that was removed to fix some issues ? Could you check the hit history of the files just to be sure ?

**Comment by Palabola** [comment]
I just add the flag in the correct place, it seems to solve the mentioned network issue, but it need a workaround to avoid the emulator from running in multiple instances.

**Pull request closed without merging**
