### PR TITLE
[3.3.5] Core/Spells: Omen of Clarity

### LINKED ISSUE #3088: [Bug]Omen of Clarity
Sometimes when Omen of Clarity proces, you are unable to use the buff. For example a druid in cat form gets Clearcasting and has 0 energy at the moment and is trying to use the mangle ability. What will happen is that for a second it will look as if the ability is going to land but it just resets. So far i wasn't able to reproduce this bug since the proc chance is very low and happens quite rarely.

Clearcasting - http://old.wowhead.com/spell=16870

Core revision: 14b3ed91647b+
Database revision: TDB 335.11.42
Addons: AHbot & AC1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65743-bug-omen-of-clarity?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
by @robinsch; closes #3088.

Purpose: make the Omen of Clarity druid buff (http://wotlk.openwow.com/spell=16864) work as intended.

This change is an addition to @Shauren's commit 37145b6.
Before this change, spell mod auras lose charges when they are unable to be cast
as mentioned in the issue. As an example: **Omen of Clarity** loses its charge
when **Shred** can not be used, because it requires the caster to behind the target.

This change will restore the spell mod if CheckCast returns false for the initial cast.

### CODE REVIEW

**Comment by jackpoz** [comment]
which spells does this change affect ? can you post a list with the behavior before and after the code change to ensure it doesn't break anything ?
could you describe in detail how this change fixes the issue ?

**Comment by robinsch** [comment]
@jackpoz It will affect all spell mod auras. It's a addition to the commit from @Shauren (https://github.com/TrinityCore/TrinityCore/commit/37145b6203c5781856ca0546bd57798bbfcc8ab5). Before spell mod auras lost charges when they were unable to be casted, as mentioned in the issue for example Omen of Clarity lost charges when Shred could not be used because it req to behind the target. This change will restore the spell mod if CheckCast return false for the initial cast.

**Comment by jackpoz** [comment]
that makes things much more clear, thank you for the explaination

**Comment by tkrokli** [comment]
What else needs to be changed on this PR in order to have the label changed to [Feedback-PatchFix] ?

**Comment by Rushor** [comment]
feedbackbacktime: 
there seem to be no other issues with this patch (tested by ~1500 player)

But sometimes the issue mentioned in the Startpost:
'Sometimes when Omen of Clarity proces, you are unable to use the buff.'
still exists.
I don't know yet what causes this problem.
nevertheless the proc works if we excecuted the fakecast (shed in front of targets etc.)
Maybe the rest of the issue is related to movement - dunno yet - i will keep updating this

**Comment by robinsch** [comment]
Seems like we're missing some restoring of the spell mods. But this PR is fine to merge.

**Comment by tkrokli** [comment]
OK, sure, but in case any of the main TC devs find it necessary to add the "restoring of the spell mods",
will it be possible to find the missing code and add more code here? :smirk_cat:

**Comment by Goatform** [comment]
This looks fine.

**Comment by Rushor** [comment]
it works, all other issues can be ignored for now because they are not topic of the original issue

somone core devs can merge this :) 

much thanks to @robinsch

**Comment by tkrokli** [comment]
@jackpoz : could you change the label to [Feedback-PatchFix] until it is time to merge this? :shipit:

**Pull request merged**
