### PR TITLE
Scripting/Borean Tundra

### PR DESCRIPTION
**Pull request by ghost**
Rework of file. Multiple script reworked. This is an update if old scripts. Please do not fill this PR with request to do something another way.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

Updated all scripts to new format.
Added better comments and reordered scripts by quest number.

Removed Corastrasza script
----------------------------
Moved gossip to db. Tested and working properly.

Redid Quest 11590: Abduction
----------------------------
Added npc_captured_beryl_sorcerer
Added spell_arcane_chains_character_force_cast
Script converted Beryl Sorcerer to Captured Beryl_Sorcerer
when it should have spawned Captured Beryl_Sorcerer. Also
Combat spell Frostbolt was missing plus other wrong spells. 
Tested and now works properly.

Fixed Quest 11794: The hunt is on
---------------------------------
Moved gossip to db. 
Tested and working properly.

Redid Quest 11865: Unfit for Death
----------------------------------
Removed spell_q11865_place_fake_fur
Removed npc_nesingwary_trapper
Added go_caribou_trap
Much cleaner with one script. 
Tested and now works properly.

Redid Quest 11876: Help Those That Cannot Help Themselves
---------------------------------------------------------
Removed npc_trapped_mammoth_calf
Removed item_dehta_trap_smasher
Added go_mammoth_trap
Much cleaner with one script. 
Tested and now works properly.

Redid Quest 12019: Last Rites
-----------------------------
Redid npc_thassarian which now holds most of the script.
Fixed Thassarian Gossip, All pathing, 
Prince Valanar class, exp, combat spells, loot
fixed Thassarian missing aura. 
Tested and now works properly.

Tested Quest 11611: Taken by the Scourge
----------------------------------------
Needs some rework.

Tested Quest 11648: The Art of Persuasion
-----------------------------------------
Works properly.

Tested Quest 11653: Hah... You're Not So Big Now!
-------------------------------------------------
Works properly.

Quest 11661: Orabus the Helmsman
--------------------------------
Not Assigned in DB?
#include "CombatAI.h" was added for this script conversion.
Script may need to be removed?

Tested Quest 11719 A Suitable Test Subject
------------------------------------------
Works properly.

Tested Quest 11919: Drake Hunt
------------------------------
Needs rework.

Spell 46374 Windsoul Totem Aura
-------------------------------
Not tested. No idea what quest this is for.

npc_bloodmage_laurith
---------------------
 Not tested. No idea what this is for.

Valiance Keep Cannoneer script to activate cannons
--------------------------------------------------
Tested no working. Script is vist for visual. 
Gameobject spell cast issue.

### CODE REVIEW

**Comment by Shauren** [comment]
I agree with @offl, large pull requests like that have extremely low chances of being properly reviewed and merged

**Comment by malcrom** [comment]
I can close it but I'm not doing all those individually

**Comment by MaxtorCoder** [comment]
Best to do it per chapter or per quest :monkas:

**Comment by Faq** [comment]
Here are mentioned some issues, but no links to reports. None reported?

**Comment by malcrom** [comment]
> Here are mentioned some issues, but no links to reports. None reported?

What?

**Comment by malcrom** [comment]
> I agree with @offl, large pull requests like that have extremely low chances of being properly reviewed and merged

How to review: do quest on trinity. Install this code and redo quest. The code was hacks. I redid everything using sniffs and they are now blizzlike.

**Pull request closed without merging**
