### PR TITLE
Added very little range tolerance level to completed casts to ensure that spell cast is finished properly even if target moves a little

### LINKED ISSUE #15375: [3.3.5] Spell Channeling spell range tolerance
Branch 3.3.5a, revision dd90e51028b92cfe65abef72f599f32bc896a810
Possibly 6.x branch too (not tested). Same mechanic should apply

When channeling a spell. for example: Mind Flay
The target should be allowed to go beyond the max casting range of mind flay.

There should be a certain range tolerance before interrupting the spell.
While this is an easy fix as the pastebin below suggests, I don't know the correct number this tolerance should be.

A possible fix would be:
http://pastebin.com/deKkBi2x

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5

- [x] 3.3.5

**Issues addressed:** Closes #15375

**Tests performed:** Compiles

Review and tests are welcomed, tolerance is added to spell cast rechecking after cast is completed and channeled spells, when range is checked.

### CODE REVIEW

**Comment by P-Kito** [comment]
Can confirm this behaviour on retail server. Seems to be implemented correctly.

**Comment by Palabola** [comment]
Tested & recommended to merge.

**Comment by Palabola** [comment]
@xinef1 OFF: Have you got something to improve creature location when you getting attacked by multiple creature to not stack them each other?

**Comment by xinef1** [comment]
@Palabola Ill try to port some movemap fixes and some improvements for targetted movement generator and target selection (which will include fix for that)

**Pull request merged**
