### PR TITLE
[WIP] DBC and Gt extractor update for BFA

### PR DESCRIPTION
**Pull request by Palabola**
**Changes proposed:**

-  
-  
-  

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by illfated** [comment]
Looks like the content is shared evenly between **Core/DataStores** and **Tools/map_extractor**.
Not quite sure what to recommend as leading part of the PR title.

**Comment by illfated** [comment]
Hm. Would be nice to see a comment with "reason for closing". Oh well.

**Comment by Palabola** [comment]
@illfated I will make a new Pull request with categorized commits.

**Comment by illfated** [comment]
Very well. If the files will be the same as in this one, it should be safe to go with a title like
**[WIP] Core/DataStores: DBC and Gt extractor update for BFA**

**Comment by Palabola** [comment]
Do not re-open please, I made new PR.

**Pull request closed without merging**
