### PR TITLE
Scripts/Ulduar: Implemented Realm First! Death's Demise

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Implement https://www.wowhead.com/achievement=3117/realm-first-deaths-demise

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Tests performed:**

tested in-game

### CODE REVIEW

**Comment by jackpoz** [comment]
did you get the achievement the first time and didn't get it anymore the second ? did all the members of the party get the achievement ?

**Comment by Jildor** [comment]
Sure, only if you have rbac that avoid get realm first (GM accounts) or anyone have the achievement before kill boss you can't get it, otherwise, you are able to get it

**Comment by illfated** [comment]
cosmetic/codestyle: you may want to add a blank comment line (`--`) on top of your SQL, just in case someone commits some SQL update right before your PR gets merged, and forgets to add the last NewLine in their SQL... 😉

**Comment by Jildor** [comment]
yeah, i forgot, thanks to you both

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
