### PR TITLE
Core/SAI: Add support to friendly+hostile to SMART_EVENT_OOC_LOS and SMART_EVENT_IC_LOS

### LINKED ISSUE #24789: Core/SAI: SMART_EVENT_OOC_LOS & SMART_EVENT_IC_LOS NoHostile param
If creature is hostile to Alliance, then:
With param 0 it will NOT work for the Horde but will work for the Alliance
With param 1 it will work for the Horde but NOT for the Alliance
So we can't support LoS events for both factions in ONE event
Sometimes we need to support both cases in ONE event

For tests execute
```sql
-- To make event trigger always, currently the chance is lower
UPDATE `smart_scripts` SET `chance` = 100 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```

Currently the event works only for Horde players
Just in case if you want to set it back
```sql
UPDATE `smart_scripts` SET `event_param1` = 1 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```
This will make the event work only for Alliance players
```sql
UPDATE `smart_scripts` SET `event_param1` = 0 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```
.go c id 18428
(there's more creatures in the area)

Maybe we can just add param = 2 to support both hostile and non-hostile cases

**Branch:** both
**TC rev. hash/commit:** d81a9e5bc3b3

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

Change SMART_EVENT_OOC_LOS and SMART_EVENT_IC_LOS first parameter to have 3 values:
- 0 : Hostile
- 1 : Not hostile (not that Friendly and Not hostile have different meanings)
- 2 : Any, as in both Hostile and Not hostile

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Close #24789

**Tests performed:**

None

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Not sure if we have a codestyle to compare enum classes to uint32, I used static_cast

### CODE REVIEW

**Comment by jackpoz** [comment]
@offl could you please test this ?

**Comment by offl** [comment]
Tested with
```sql
UPDATE `smart_scripts` SET `event_chance` = 100 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
-- ally only
UPDATE `smart_scripts` SET `event_param1` = 0 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
-- horde only
UPDATE `smart_scripts` SET `event_param1` = 1 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
-- all
UPDATE `smart_scripts` SET `event_param1` = 2 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```
All works

**Comment by jackpoz** [comment]
Added some validation for allowed values on startup, 2 SAI rows have invalid values:
>SmartAIMgr: Entry 19283 SourceType 0 Event 3 Action 1 uses hostilityMode with invalid value 20 (max allowed value 2), skipped.
SmartAIMgr: Entry 23760 SourceType 0 Event 3 Action 11 uses hostilityMode with invalid value 24042 (max allowed value 2), skipped.

@offl could you please check if 0, 1 or 2 are the expected values in these cases ? Just to have a SQL update ready before the PR (you could even push the fix before I merge this)

**Comment by offl** [comment]
```sql
--
UPDATE `smart_scripts` SET `event_param1` = 2 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
UPDATE `smart_scripts` SET `event_param1` = 1, `event_param2` = 20 WHERE `entryorguid` = 19283 AND `source_type` = 0 AND `id` = 3;
UPDATE `smart_scripts` SET `event_type` = 1, `event_param1` = 6000, `event_param2` = 11000, `target_type` = 19, `target_param1` = 24042, `target_param2` = 40 WHERE `entryorguid` = 23760 AND `source_type` = 0 AND `id` = 3;
```

**Pull request merged**
