### PR TITLE
Cherrypicking db 3.3.5a -> master

### PR DESCRIPTION
**Pull request by funjoker**
**Changes proposed:**

-  Cherrypicks

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

### CODE REVIEW

**Comment by jackpoz** [comment]
ren't _335 sql files supposed to be used only in 335 branch ?

**Comment by illfated** [comment]
Yes, they as good as always contain game content removed in Cataclysm.

**Comment by funjoker** [comment]
Not all stuff changed in Cata. These npcs are actually still inside Game.  But untested tbh

**Comment by msoky** [comment]
probably we should take a look on all "world_335.sql" which was added before years if they are part of master branch now ? or it is case for only this 5 commits?

**Comment by funjoker** [comment]
Yeah take a Look. Actually i‘m more interessted into Core fixes.

**Comment by msoky** [comment]
is this mergable?

**Comment by illfated** [comment]
Seeing that this is only SQL content, it should be tested before merging by someone with current master branch compiled + up to date master TDB already running.

**Pull request merged**
