### PR TITLE
Missing rbac permissions

### PR DESCRIPTION
**Pull request by Shadowmaruz**
**Changes proposed:**

-  Adds the rbac permissions to the database in order to allow assignment
-  Adds the rbac permission for .character deleted delete
-  Adds the rbac permission for .character deleted old

**Target branch(es):** 3.3.5

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Verified through in-game commands.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by illfated** [comment]
This PR has got too many files in it. I recommend closing this one and open a new one to avoid having more than just a few files (just the required ones) in the PR.

**Comment by MaxtorCoder** [comment]
There is only 1 file for me.

**Comment by illfated** [comment]
OK, right. My bad. I still saw 7112 files before I updated the page. I will strike-through the text in my previous comment.

**Comment by illfated** [comment]
The case now is that the PR only contains 1 SQL file, which TC only deals with in regular issue tickets. PRs are meant for C++ files (in addition to SQL files, if present).

**Comment by jackpoz** [comment]
And with auth database updates it's even worse,
>Checking database 'auth' for missing filenames in tables...
>- "sql/updates/auth/9999_99_99_99_auth.sql" is missing in the 'auth'.'updates' table.
Fatal error:
  The Database Updater is broken for the 'auth' database,
  because the applied update is missing in the 'auth'.'updates' table.

but we can take care of updating the right sql

**Comment by Aokromes** [comment]
some RBAC permisions aren't into the database intended.

**Comment by illfated** [comment]
Any wiki references about that detail, Aok?

**Comment by jackpoz** [comment]
these RBAC were added in https://github.com/TrinityCore/TrinityCore/commit/28f9317698aec3eb8480e6682af3c4c65a98707c#diff-ff3b59d5f6fc8303cc01120ec5c190fcR180-R184 with comment "// Not in DB - console" but then the comment was removed in https://github.com/TrinityCore/TrinityCore/commit/1eee42433b429db690d1fd90513e021d9431c49e#diff-ff3b59d5f6fc8303cc01120ec5c190fcL180-L184

**Comment by illfated** [comment]
Maybe it is because I don't do much player management (only playing alone), but how important or useful is the addition of those RBAC permissions in the DB?

**Comment by Shadowmaruz** [comment]
@illfated It eases the ability to customize different permission ranks without having to dig through the core in order to find them because the tables are linked with foreign keys, they need to be present in the db in order to assign them *cough*

**Comment by Aokromes** [comment]
> @illfated It eases the ability to customize different permission ranks without having to dig through the core in order to find them.
> Because the tables are linked with foreign keys, they need to be present in the db in order to assign them _cough_

well, before the comment was removed it was clear it's intended not to be there, nothing stops you to add them to your own db.

**Comment by Shadowmaruz** [comment]
> > @illfated It eases the ability to customize different permission ranks without having to dig through the core in order to find them.
> > Because the tables are linked with foreign keys, they need to be present in the db in order to assign them _cough_
> 
> well, before the comment was removed it was clear it's intended not to be there, nothing stops you to add them to your own db.

Pardon my idiocy for a moment.

May I ask if it was not intended to be there, why would there be commands implemented into the core which use said permissions ?

**Comment by illfated** [comment]
It is likely that anything related to customization will not be used in default TC source or DB, either because it facilitates private server use for many users, or because it is not needed for personal testing & problem-solving via coding. TrinityCore is based on using coding skills to improve on the existing source. Adding some custom RBAC permissions to the DB does not demonstrate much coding skill or  solve any known issues to play the game (which is the testing basis for the TrinityCore project).

**Comment by Aokromes** [comment]
> 
> May I ask if it was not intended to be there, why would there be commands implemented into the core which use said permissions ?

server administrator only commands.

**Comment by jackpoz** [comment]
I'll merge this PR as soon as I find time to deal with the required manual SQL updates

**Comment by illfated** [comment]
I should have known this already, but, just to have it confirmed, is it because of the SQL-only content that those PR checks fail?

**Comment by Aokromes** [comment]
> I should have known this already, but, just to have it confirmed, is it because of the SQL-only content that those PR checks fail?

it fails because bots checks sql to be included on the base files.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
