### PR TITLE
Core/Player: Fixed Weapon Skillup on low level mobs

### LINKED ISSUE #15998: 3.3.5a Weapon skill not increasing against low level mobs
https://github.com/TrinityCore/TrinityCore/commit/187e45d24b07613447e449565cdff8015c3220ac

Weapon skill not increasing against mobs that don't grant experience.
Expected behavior is that all mobs should have a chance of granting weapon skill regardless of level.

sources:
http://wowwiki.wikia.com/wiki/Weapon_skill
https://typhoonandrew.wordpress.com/2008/01/08/how-to-raise-your-weapon-skill/
-second bullet

### PR DESCRIPTION
**Pull request by Rockz1152**
Closes #15998

Removed block for skill up on grey level mobs.

### CODE REVIEW

**Comment by jackpoz** [comment]
Please rename the commit to follow the TC standard

**Comment by rockz1152** [comment]
I apologize for the issues, I'm brand new to git hub

**Comment by rockz1152** [comment]
I'm sorry but I could not figure out how to do the git blame properly.
This is the oldest commit I could find containing the code.
c46c831

**Comment by jackpoz** [comment]
can I reopen it ? the changes should fix the issue and seems legit

**Comment by Kittnz** [comment]
as far as i remember you always could level up on low level mobs

**Comment by jackpoz** [comment]
https://sourceforge.net/p/mangos/code/2320/ found the commit that added the check
>Fixed rest points grow and health/mana regeneration in sit case. Patch provided by Ambal.
Crushing blows algorithm, weapon/defense skill grow and some other combat system changes. Patch provided by Ambal.
vladimir 2006-09-30

**Comment by rockz1152** [comment]
I couldn't figure out how to rename the commit like you requested, and I don't know how to use git on command line, I made the change through the website, the only way to rehash the commit was to recreate it I guess.

I would rather honestly someone whos knows how to use git more than me to make this change, I'm too new at this for it to be done properly its only 2 line changes to get this thing working.

**Comment by jackpoz** [comment]
oh well, it was a good chance to learn a bit more about git. I opened a pr at https://github.com/TrinityCore/TrinityCore/pull/16006

**Comment by rockz1152** [comment]
Thank you, I appreciate you help!

**Comment by rockz1152** [comment]
you didn't by any chance pull that from a branch I might have just deleted? would that cause an issue?

**Comment by jackpoz** [comment]
it seems I was fast enough to PR and merge it before you deleted it. after it is merged it can be deleted from your fork

**Comment by rockz1152** [comment]
ok, sorry about, again thank you for all the help.

**Comment by jackpoz** [comment]
thank you for the fix.
git might look scary but all you need to learn is where to click on TortoiseGit (or Git Extensions or any other git-GUI)

**Comment by rockz1152** [comment]
Well I did learn a lot from this so hopefully the next time I won't screw everything up lol.

**Comment by Demonid** [comment]
Btw, this was added before the first commit of TrinityCore

https://github.com/TrinityCore/TrinityCore/blob/9b1c0e006f20091f28f3f468cfcab1feb51286bd/src/game/Player.cpp#L4783

So, i believe this comes from Mangos.

**Comment by jackpoz** [comment]
@Demonid https://github.com/TrinityCore/TrinityCore/pull/16005#issuecomment-164878753
>https://sourceforge.net/p/mangos/code/2320/ found the commit that added the check

**Comment by rockz1152** [comment]
I built and tested the change this morning and it worked for me, I'm just surprised no one else noticed in all these years. Unless I'm really missing something, (I am new to this) and that check was in place for a different reason.

**Comment by tkrokli** [comment]
@rockz1152 : Fair enough. If you read jackpoz' comments and the linked pages, you see that the code has been there "forever", meaning from before TrinityCore (in MaNGOS code). Maybe recent changes have just made it more obvious to you, I don't know. :)

**Pull request closed without merging**
