### PR TITLE
Core/PacketIO: Updated CMSG_WORLD_TELEPORT (GM opcode)

### PR DESCRIPTION
**Pull request by ForesterDev**
**Changes proposed:**

-  cherry-picked https://github.com/TrinityCore/TrinityCore/commit/7632e1182584236ab2e8069ac6e3739fd7de47b0

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.) Build

### CODE REVIEW

**Comment by Shauren** [comment]
I just noticed something - why none of these cherry picks have a link to the source? How are you doing them? The way we've done them before was `git cherry-pick -x [commit_hash]` which set both author and appended "Cherry picked from" to commit message

**Comment by ForesterDev** [comment]
Forgot about -x flag

**Comment by illfated** [comment]
Fair enough. Can that command be re-run on this PR branch, or does it need a new PR branch?

**Review by jackpoz — CHANGES_REQUESTED** [review]
Please use the -x parameter and force push to this PR

**Pull request closed without merging**
