### PR TITLE
Server/Packets: implement BattlefieldPackets

### PR DESCRIPTION
**Pull request by ccrs**
**Changes proposed:**

implement BattlefieldPackets

**Tests performed:**

Can't, yet

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Review packet structure matches correctly

### CODE REVIEW

**Comment by ccrs** [comment]
pseudo port from master branch, packet structure comes from sniffs + sniffer packet definition

**Comment by ccrs** [comment]
oh, implementation in different PRs, this is just the packted definition, if matches, can be merged as-is

**Comment by Shauren** [comment]
This is just wrong, structure aren't anywhere close to what they should be in 3.3.5

**Comment by ccrs** [comment]
I've matched this with several-many 3.3.5 sniffs, but like I said, I could be completely wrong

I'll try jump to chat to discuss next steps, but don't hesitate to elaborate here, thanks!

**Comment by Shauren** [comment]
I simply opened 3.3.5 source code for the first packet (first in file) you added and compared - `WorldSession::HandleBattlefieldListOpcode`

**Comment by Shauren** [comment]
Nothing has happened here for a while, invalid structure feedback not addressed, closing

**Pull request closed without merging**
