### PR TITLE
Core/Maps: Implemented getting area id from gameobject spawns

### PR DESCRIPTION
**Pull request by Faq**
Cherry-pick https://github.com/TrinityCore/TrinityCore/commit/42f9deb21ec68e169f7ed1c8cf14092f144b22da

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Compiles

**Known issues and TODO list:** (add/remove lines as needed)

- [x] missing some changes, still not working;

Tests should be done, described here: 
https://github.com/TrinityCore/TrinityCore/issues/24600#issuecomment-626790233

### CODE REVIEW

**Comment by ccrs** [comment]
nopch build fails

**Comment by Keader** [comment]
```cpp
/home/circleci/project/src/common/Collision/Models/GameObjectModel.cpp:202:17: fatal error: member access into incomplete type 'VMAP::AreaInfo'
        if (info.ground_Z < world_Z)
                ^
/home/circleci/project/src/common/Collision/Models/WorldModel.h:32:12: note: forward declaration of 'VMAP::AreaInfo'
    struct AreaInfo;
 ```

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/42f9deb21ec68e169f7ed1c8cf14092f144b22da#diff-9eea3ad0b189ac095427d3c6c6ff68e7 changes seem to be missing

**Comment by Faq** [comment]
Closing in favor to https://github.com/TrinityCore/TrinityCore/pull/24906, there detailed can see porting process.

**Pull request closed without merging**
