### PR TITLE
Core/Guilds: Fix Guild::HandleSetMemberNote logic according to method…

### PR DESCRIPTION
**Pull request by r4d1sh**
… declaration.

This change has no effect on server behavior.

### CODE REVIEW

**Comment by Shauren** [comment]
It would have been easier to just rename the argument in declaration... https://github.com/Tonghost/TrinityCore/blob/3.3.5/src/server/game/Guilds/Guild.h#L675

**Comment by Tonghost** [comment]
@Shauren I know. I just prefer the current name of the argument.

**Comment by Aokromes** [comment]
Any reason to don't merge this?

**Comment by Tonghost** [comment]
:shipit:

**Pull request merged**
