### PR TITLE
Core/Spells: Correct swapped TARGET_UNIT_NEARBY_ALLY and TARGET_UNIT_NEARBY_PARTY

### PR DESCRIPTION
**Pull request by xvwyh**
**Changes proposed:**

`TARGET_UNIT_NEARBY_ALLY` and `TARGET_UNIT_NEARBY_PARTY` were wrongly named, with their functionality swapped around. This PR restores the functionality as it's coded in the Alpha client and based on some spell data. Proofs below:

<details>
<summary>Alpha</summary>

Alpha contains a function `CGTooltip::GetSpellTargetString` which constructs a string that describes which targets does the spell select in a human-readable fashion. It contains a switch statement that selects one of the strings from GlobalStrings.lua based on the spell's implicit target, among other things.

Here are the strings:
```lua
SPELL_TARGET_TYPE0_DESC = "caster";
SPELL_TARGET_TYPE1_DESC = "any";
SPELL_TARGET_TYPE2_DESC = "friendly";
SPELL_TARGET_TYPE3_DESC = "enemy";
SPELL_TARGET_TYPE4_DESC = "party member";
SPELL_TARGET_TYPE5_DESC = "item";
SPELL_TARGET_TYPE6_DESC = "location";
SPELL_TARGET_TYPE7_DESC = "object";
SPELL_TARGET_TYPE8_DESC = "pet";
SPELL_TARGET_TYPE9_DESC = "main-hand item";
SPELL_TARGET_TYPE10_DESC = "off-hand item";
SPELL_TARGET_TYPE11_DESC = "party";
SPELL_TARGET_TYPE12_DESC = "all";
SPELL_TARGET_TYPE13_DESC = "enemies";
SPELL_TARGET_TYPE14_DESC = "party members";
SPELL_TARGET_TYPE15_DESC = "master";
```

The number you see there is the value of this enum:
```cpp
enum SPELL_TARGET_TYPE
{
  TARGET_TYPE_CASTER  = 0,
  TARGET_TYPE_UNIT  = 1,
  TARGET_TYPE_FRIENDLY  = 2,
  TARGET_TYPE_ENEMY  = 3,
  TARGET_TYPE_PARTY_MEMBER  = 4,
  TARGET_TYPE_ITEM  = 5,
  TARGET_TYPE_LOCATION  = 6,
  TARGET_TYPE_OBJECT  = 7,
  TARGET_TYPE_PET  = 8,
  TARGET_TYPE_MAINHAND_ITEM  = 9,
  TARGET_TYPE_OFFHAND_ITEM  = 10,
  TARGET_TYPE_PARTY  = 11,
  TARGET_TYPE_MULTIPLE_UNITS  = 12,
  TARGET_TYPE_MULTIPLE_ENEMIES  = 13,
  TARGET_TYPE_MULTIPLE_PARTY_MEMBERS  = 14,
  TARGET_TYPE_MASTER  = 15,
  NUM_SPELL_TARGET_TYPES  = 16,
};
```

And here's a snippet of that code that deal with implicit targets.
```cpp
  targetType = NUM_SPELL_TARGET_TYPES;
...
  i = 0;
  do
  {
    if ( i )
      implicitTarget = spell->m_implicitTargetB[effectIndex];
    else
      implicitTarget = spell->m_implicitTargetA[effectIndex];
    switch ( implicitTarget )
    {
      case 1:
        targetType = 0;                         // caster
      case 22:
        centerOnCaster = 1;
        break;
      case 5:
        targetType = 8;                         // pet
        break;
      case 4:
      case 35:
        targetType = 4;                         // party member
        break;
      case 3:
      case 21:
        targetType = 2;                         // friendly
        break;
      case 2:
      case 6:
        targetType = 3;                         // enemy
        break;
      case 7:
        centerOnCaster = 1;
      case 8:
        targetType = 12;                        // all
        break;
      case 13:
        targetType = 9;                         // main-hand item
        break;
      case 14:
        targetType = 10;                        // off-hand item
        break;
      case 24:
        cone = 1;
      case 15:
        centerOnCaster = 1;
      case 16:
        targetType = 13;                        // enemies
        break;
      case 20:
        targetType = radius != 0 ? 14 : 11;     // ? party members : party
        centerOnCaster = 1;
        break;
      case 23:
      case 26:
        targetType = 7;                         // object
        break;
      case 25:
        targetType = 1;                         // any
        break;
      case 27:
        targetType = 15;                        // master
        break;
      default:
        break;
    }
    ++i;
  }
  while ( i < 2 );
  if ( spell->m_effect[effectIndex] == 35 )     // SPELL_EFFECT_APPLY_AREA_AURA_PARTY
    targetType = radius != 0 ? 14 : 11;         // ? party members : party
```

There's more code after that that transforms Spell's "m_targets" mask into the aforementioned SPELL_TARGET_TYPE if the above code doesn't handle any implicit target. We don't care about it here.

And now once again the same thing, but with enums (implicit target enum taken from TC):
```cpp
  do
  {
    if ( i )
      implicitTarget = spell->m_implicitTargetB[effectIndex];
    else
      implicitTarget = spell->m_implicitTargetA[effectIndex];
    switch ( implicitTarget )
    {
      case TARGET_UNIT_CASTER:
        targetType = TARGET_TYPE_CASTER;        // caster
      case TARGET_SRC_CASTER:
        centerOnCaster = 1;
        break;
      case TARGET_UNIT_PET:
        targetType = TARGET_TYPE_PET;           // pet
        break;
      case TARGET_UNIT_NEARBY_ALLY:
      case TARGET_UNIT_TARGET_PARTY:
        targetType = TARGET_TYPE_PARTY_MEMBER;  // party member
        break;
      case TARGET_UNIT_NEARBY_PARTY:
      case TARGET_UNIT_TARGET_ALLY:
        targetType = TARGET_TYPE_FRIENDLY;      // friendly
        break;
      case TARGET_UNIT_NEARBY_ENEMY:
      case TARGET_UNIT_TARGET_ENEMY:
        targetType = TARGET_TYPE_ENEMY;         // enemy
        break;
      case TARGET_UNIT_SRC_AREA_ENTRY:
        centerOnCaster = 1;
      case TARGET_UNIT_DEST_AREA_ENTRY:
        targetType = TARGET_TYPE_MULTIPLE_UNITS;// all
        break;
      case 13:
        targetType = TARGET_TYPE_MAINHAND_ITEM; // main-hand item
        break;
      case 14:
        targetType = TARGET_TYPE_OFFHAND_ITEM;  // off-hand item
        break;
      case TARGET_UNIT_CONE_ENEMY_24:
        cone = 1;
      case TARGET_UNIT_SRC_AREA_ENEMY:
        centerOnCaster = 1;
      case TARGET_UNIT_DEST_AREA_ENEMY:
        targetType = TARGET_TYPE_MULTIPLE_ENEMIES;// enemies
        break;
      case TARGET_UNIT_CASTER_AREA_PARTY:
        targetType = radius != 0 ? TARGET_TYPE_MULTIPLE_PARTY_MEMBERS : TARGET_TYPE_PARTY;// ? party members : party
        centerOnCaster = 1;
        break;
      case TARGET_GAMEOBJECT_TARGET:
      case TARGET_GAMEOBJECT_ITEM_TARGET:
        targetType = TARGET_TYPE_OBJECT;        // object
        break;
      case TARGET_UNIT_TARGET_ANY:
        targetType = TARGET_TYPE_UNIT;          // any
        break;
      case TARGET_UNIT_MASTER:
        targetType = TARGET_TYPE_MASTER;        // master
        break;
      default:
        break;
    }
    ++i;
  }
  while ( i < 2 );
  if ( spell->m_effect[effectIndex] == SPELL_EFFECT_APPLY_AREA_AURA_PARTY )
    targetType = radius != 0 ? TARGET_TYPE_MULTIPLE_PARTY_MEMBERS : TARGET_TYPE_PARTY;// ? party members : party
```

And here's our discrepancy:
```cpp
      case TARGET_UNIT_NEARBY_ALLY:
      case TARGET_UNIT_TARGET_PARTY:
        targetType = TARGET_TYPE_PARTY_MEMBER;  // party member
        break;
      case TARGET_UNIT_NEARBY_PARTY:
      case TARGET_UNIT_TARGET_ALLY:
        targetType = TARGET_TYPE_FRIENDLY;      // friendly
        break;
```

As you can see, TARGET_UNIT_NEARBY_ALLY and TARGET_UNIT_NEARBY_PARTY are in the wrong places.

Btw, enums for targets 13 and 14 are missing, and according to the code - they're supposed to implicitly target the item in main-hand (13) and off-hand (14). 13 was used by two spells in alpha: 6570 ("zzOLDSunder (NYI)" with SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY effect) and 7097 ("Sunder"). They aren't used anymore, and that "NYI" probably remained that way. Feel free to add them for historical reasons, or not. :D
</details>

<details>
<summary>Spells</summary>
There are very few spells that use them, but there are some things we can gleam from them.

36346 (Growth Ray): says "at a nearby friend" in the description, but uses TARGET_UNIT_NEARBY_PARTY.

152453 (Healing Light) and 152862 (Raven's Shadow): have two effects each with targets TARGET_UNIT_NEARBY_PARTY and TARGET_UNIT_TARGET_ALLY respectively, meaning most likely that the first effect selects the closest party member, and the second effects selects the same target, but then why have the first one be TARGET_UNIT_NEARBY_PARTY and not TARGET_UNIT_NEARBY_ALLY?

160433 (Burning Reflexes): says "Infuses an ally" in the descriptions, but uses TARGET_UNIT_NEARBY_PARTY.

As for TARGET_UNIT_NEARBY_ALLY, there's a bunch of spells that look like they were copy pasted. They all have the same target except one:

56445 (Retching Plague): this one changed 3rd effect's target to TARGET_UNIT_NEARBY_RAID. So now we have a discrepancy - the first two effects target any ally, but the third one - only a raid member. It would make *a bit* more sense if all the other effects were instead targeting party members, and this spell's 3rd effect was changed to "raid" to allow the spell to jump from target to target in raid instances, and not be limited to one subgroup. Regardless, it still looks wonky and doesn't seem to be used anywhere anyway.

</details>

Commits have bad names, used github's web editor, squash it please.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:**

My itch to get this barely useful info public after I stumbled across it on accident.

**Tests performed:**

Not tested, shouldn't affect build, affects a handful of spells that probably aren't used anyway.

### CODE REVIEW

**Comment by ccrs** [comment]
looks legit, @Shauren any comments?

**Comment by illfated** [comment]
> Commits have bad names, used github's web editor, squash it please.

Looks OK to me, I don't see the need for squashing.

**Comment by illfated** [comment]
By the way, in `SpellInfo.cpp`, in `std::array<SpellImplicitTargetInfo::StaticData, TOTAL_SPELL_TARGETS> SpellImplicitTargetInfo::_data`, I notice you have swapped the order of `TARGET_CHECK_PARTY` & `TARGET_CHECK_ALLY` only once, where they occur as a close pair. There are 5 more occurrences of `TARGET_CHECK_PARTY` and 6 more occurrences of `TARGET_CHECK_ALLY` in that same list, but I assume those are correct or maybe not affecting each other, since you have not suggested any more changes. OK?

**Comment by xvwyh** [comment]
I only altered the order of infos to match the changed order of enum values, as the enum serves as the index into that array. What was #3 became #4, what was #4 became #3.

**Comment by illfated** [comment]
Fair enough. I just noticed that I have confused the arguments with the actual full lines with their comment descriptors. Please ignore me.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Pull request merged**
