### PR TITLE
Scripts/Misc:fix npc_professions locale text

### PR DESCRIPTION
**Pull request by leelf00**
fix npc_professions locale text load from db

**Changes proposed:**
Fix gossip option not load from db.
- [x] Tailor
- [x] Alchemy
- [x] Leatherworking
- [x] Blacksmithing
- [x] Engineering
  
updates https://github.com/TrinityCore/TrinityCore/issues/22696

**Tests performed:**

build and tested with zhTW client in game.

### CODE REVIEW

**Comment by offl** [comment]
How money cost was displayed in game before \ after PR?

**Comment by leelf00** [comment]
before / after :
Weapon BlackSmiths & Amror BlackSmith unlearn use DoLowUnlearnCost(player) / 100000
Hammer BlackSmiths & Axe BlackSmiths & Sword BlackSmiths unlearn use DoLowUnlearnCost(player) use DoMedUnlearnCost(player) / 1000000
Engineering tele no cost / 0
Dragon Leatherworking & Element Dragon Leatherworking & Tribal Dragon Leatherworking unlearn use DoMedUnlearnCost / 200000
Spellfire Tailoring & Mooncloth tailor & Shadoweave tailor learn use DoLearnCost(player) / 200000
Spellfire Tailoring & Mooncloth tailor & Shadoweave tailor unlearn use DoHighUnlearnCost(player) / 1500000

**Comment by offl** [comment]
Without this PR money cost depends on player level (visually & after clicking on button)
With this PR money cost is always the same (at least visually, didn't checked if core really takes same value as shown in the box)
Didn't tried to figure out, maybe that is because you sent only one gossip option or because of changes to script

**Comment by leelf00** [comment]
I get it.I will add condition and gossip option for money cost depends on player level .

**Comment by leelf00** [comment]
update code and sql

**Comment by Aokromes** [comment]
@offl this can be merged?

**Comment by acidmanifesto** [comment]
This pr works fine on my end.

**Comment by jackpoz** [comment]
Thanks for the PR 🚀 😃

**Pull request merged**
