### PR TITLE
Core/Spells: Ice Barrier now shouldn't trigger Shattered Barrier on dispel

### LINKED ISSUE #14555: 3.3.5 Mage: Ice Barrier
Core revision: https://github.com/TrinityCore/TrinityCore/commit/df4b175d689fa99aa3876a2c26bb24ba09970a98
DB version: TDB 335.58
Script version: Mage_ai
Ice Barrier (http://wotlk.openwow.com/spell=43039)
Shattered Barrier (http://wotlk.openwow.com/spell=54787)
ice barrier gets dispelled it activates the Shattered Barrier
Ice Barrier's removal should only freeze surrounding enemies when the shield is broken by damage, not when it is dispelled or spell stolen.

Please excuse my English.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11210853-3-3-5-mage-ice-barrier?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Goatform**
Fix  #14555

### CODE REVIEW

**Comment by Aokromes** [comment]
Failed — The Travis CI build failed

**Comment by MitchesD** [comment]
travis fail is due to recent 335 commits

**Comment by Goatform** [comment]
yeah

**Comment by Goatform** [comment]
#14605

**Comment by ccrs** [comment]
````quote
[ 56%] /home/travis/build/TrinityCore/TrinityCore/src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp:279:37: fatal error: 
      use of undeclared identifier 'SAY_AGGRO'
                ironaya->AI()->Talk(SAY_AGGRO);
                                    ^
````
Not his fault though

**Pull request closed without merging**
