### PR TITLE
Core/Vehicle: Change vehicle accessories' phase according to the player on the vehicle

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Core/Vehicle: Change vehicle accessories' phase according to the player on the vehicle

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes https://github.com/TrinityCore/TrinityCore/issues/23210

**Tests performed:** (Does it build, tested in-game, etc.)
Tested various .mo pha ingame, while mounting and not mounting the vehicle or any of the accessories

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Sometimes I have to move very close to the vehicle for the accessories to appear
- [ ] There might be some quirks to the player interface when being on an accessory and that changes phase

### CODE REVIEW

**Comment by Killyana** [comment]
About: "Sometimes I have to move very close to the vehicle for the accessories to appear" it's not related to the distance, just the install of the accessory i delay client side to avoid being loaded before the main vehicle, that cause the accessory not being installed correctly for the client.

I tested the PR, and it works fine when the player is installed in the main vehicle, but in the case where the player is installed inside an accessory the phases shift still fails (I'm not sure how it mut work in this case.

**Comment by jackpoz** [comment]
> but in the case where the player is installed inside an accessory the phases shift still fails

did you change the phase of the Player, of the Vehicle or of the Accessory when testing ? Just to know which case to test

**Comment by Killyana** [comment]
I changed player's phase when he's inside an accessory.

**Comment by ccrs** [comment]
quest on argent crusade initial area involving cannons and killing lots of undeads.

when all the requirements are met, the area phase changes -> player changes phase

but, the player is still riding the cannon... -> this impl makes the cannon change phase too, right? -> it leaves the now "old" phase without a cannon till grid unload

**Comment by Killyana** [comment]
No the phase change in quest rewarded not complete: https://youtu.be/8sD5UN067m8?t=114

**Comment by Wyrserth** [comment]
Doesn't the phase change for [that quest](https://www.wowhead.com/quest=13086) happen when it's rewarded, and not when the objectives are complete?

**Comment by illfated** [comment]
Good point, I thought so too (on rewarded). Then again, I could be remembering this incorrectly due to playing on TC instead of retail for so long.

**Comment by Wyrserth** [comment]
Yeah I sent mine a few seconds after Killyana without realizing it :P

**Comment by jackpoz** [comment]
I updated the PR, please try again. I pretty much tested all the cases:
- Player on vehicle, .mo pha the player
- Player on vehicle, .mo pha the vehicle
- Player on accessory, .mo pha the player
- Player on accessory, .mo pha the accessory
- Player on accessory, .mo pha the vehicle

**Comment by Killyana** [comment]
I tested many cases and every thing looks fin for me.

**Pull request merged**
