### PR TITLE
Battlegrounds/buffs: Rework using areatriggers

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

-  Remove radius hack from battleground buffs
-  Add script for Old AreaTriggers (no assignment done)
-  Add script for new AreaTriggers
-  Spawn AreaTriggers in Arathi Basin

**Issues addressed:**

Closes: none?

**Tests performed:**

- Queued for Arathi & walk through buffs

**Known issues and TODO list:** (add/remove lines as needed)

- Buffs in other battlegrounds aren't working anymore.

### CODE REVIEW

**Comment by Traesh** [comment]
What about the respawn of a random buff ?

**Comment by Golrag** [comment]
Already handled in arathi using pooling

**Comment by Golrag** [comment]
@Shauren, something i forgot to check is if Battleground::m_BuffChange  is still needed after this, I think it  can be removed

**Comment by Shauren** [comment]
Yep, was unused

**Pull request merged**
