### PR TITLE
3.3.5 Fix for Quest 10873

### PR DESCRIPTION
**Pull request by Tauriella**
TrinityCore rev. b5eb67571099+ 2015-12-24 15:52:06 +0100 (HEAD branch)

Logic Mistak Fix in zone_terokkar_forest.cpp

Tested and Woks

On Blizzard Spawn only on Mob
FIX:

```
enum NetherwebVictim
{
    QUEST_TARGET            = 22459
    //SPELL_FREE_WEBBED       = 38950
};

const uint32 netherwebVictims[6] =
{
    18470, 16805, 21242, 18452, 22482, 21285
};

class npc_netherweb_victim : public CreatureScript
{
public:
    npc_netherweb_victim() : CreatureScript("npc_netherweb_victim") { }

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_netherweb_victimAI(creature);
    }

    struct npc_netherweb_victimAI : public ScriptedAI
    {
        npc_netherweb_victimAI(Creature* creature) : ScriptedAI(creature) { }

        void Reset() override { }
        void EnterCombat(Unit* /*who*/) override { }
        void MoveInLineOfSight(Unit* /*who*/) override { }


        void JustDied(Unit* killer) override
        {
            Player* player = killer->ToPlayer();
            if (!player)
                return;

            if (player->GetQuestStatus(10873) == QUEST_STATUS_INCOMPLETE)
            {
                if (rand32() % 100 < 25)
                {
                    me->SummonCreature(QUEST_TARGET, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
                    player->KilledMonsterCredit(QUEST_TARGET);
                }
                else
                    me->SummonCreature(netherwebVictims[rand32() % 6], 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);

            }
        }
    };
};
```

I removed 3 unneeded Lines in zone_terokkar_forest.cpp

```
if (rand32() % 100 < 75)
                    me->SummonCreature(netherwebVictims[rand32() % 6], 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);

                me->SummonCreature(netherwebVictims[rand32() % 6], 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000);
```

### CODE REVIEW

**Comment by Aokromes** [comment]
Incorrect branch :)

**Comment by Tauriella** [comment]
I curse git I give up :(

**Comment by DDuarte** [comment]
It's not a git problem. When you open the Pull Request in Github you have to select the correct target branch.

**Comment by Tauriella** [comment]
ok i test again

**Pull request closed without merging**
