### PR TITLE
Fix(DB/SAI) Update SAI for Falconwing Square

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Improve existing SAI for Falconwing Square to be more blizzlike

**Tests performed:**

SQL inserts
Tested in game

### CODE REVIEW

**Comment by malcrom** [comment]
While waiting for approval: https://www.youtube.com/watch?v=S0L_n68bznE

**Comment by CraftedRO** [comment]
just as a tip , for sql only you can open a SQLfix issue .

**Comment by CraftedRO** [comment]
I guess you can leave those ones as PR (will be beter noticed), however for some reasons probably because offl is busy I guess , noone else will pull them from issues into 3.3.5 , this also is frustrating only few people with write access and they are mostly focused on master branch.

**Comment by malcrom** [comment]
Moved to issues.

**Pull request closed without merging**
