### PR TITLE
Core/Creatures: Allow to change inhabit type of creatures with SetInhabitType() and SAI (SMART_ACTION_SET_INHABIT_TYPE).

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Enable changing the inhabittype in scripts (corescript or SAI)

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [X] master

**Issues addressed:** Closes #  (insert issue tracker number)
https://github.com/TrinityCore/TrinityCore/issues/18604
It will enable the possibility to make Rexxar no longer hovering in the air. Original patch by xjose93

**Tests performed:** (Does it build, tested in-game, etc.)
Yes and yes

[//]: # (**DEPRECATION NOTICE** Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE** If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

### CODE REVIEW

**Comment by xinef1** [comment]
Inhabit type should never be changed. Movement flags update should be fixed instead.

**Comment by Rushor** [comment]
@xinef1: could you fix this for SMART_ACTION_SET_FLY then? pls :)

**Comment by xinef1** [comment]
I'll make some pull requests for smartscripts later

**Comment by Rushor** [comment]
well then /closed. it will be fixed once https://github.com/TrinityCore/TrinityCore/pull/18673 was merged

**Pull request closed without merging**
