### PR TITLE
Core/Conditions: CONDITION_QUEST_OBJECTIVE_COMPLETE addition

### PR DESCRIPTION
**Pull request by funjoker**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

When using `IsQuestObjectiveComplete(obj)` for example at scripts, you don't need quest anymore.

**Changes proposed:**

-  Lesser Code

**Target branch(es):** 3.3.5/master
- [x ] master

**Tests performed:** (Does it build, tested in-game, etc.)
Built

### CODE REVIEW

**Comment by Rochet2** [comment]
Less code, but there is one line more of it :D

**Comment by funjoker** [comment]
i mean i future.
Guess waht happens if you write creature scripts to check objectives?

example: Without changes
```
        void MoveInLineOfSight(Unit* who) override
        {
            if (Player* player = who->ToPlayer())
                if (me->IsWithinDistInMap(who, 15.0f) && !player->GetQuestRewardStatus(QUEST_ENTER_THE_ILLIDARI_SHIVARRA) && player->GetQuestStatus(QUEST_ENTER_THE_ILLIDARI_SHIVARRA) == QUEST_STATUS_INCOMPLETE)
                {
                    QuestObjective const* obj = sObjectMgr->GetQuestObjective(OBJECTIVE_FIRST_SUMMONED_GUARDIAN_SHIVARRA);
                    if (!obj)
                        return;

                    Quest const* qInfo = sObjectMgr->GetQuestTemplate(QUEST_ENTER_THE_ILLIDARI_SHIVARRA);
                    ASSERT(qInfo);

                    if (!player->IsQuestObjectiveComplete(qInfo, *obj))
                    {
                        Talk(CREATURE_TEXT_ZERO, who);
                        player->KilledMonsterCredit(CREATURE_FIRST_SUMMONED_GUARDIAN);
                    }

                }
        }
```

With changes

```
        void MoveInLineOfSight(Unit* who) override
        {
            if (Player* player = who->ToPlayer())
                if (me->IsWithinDistInMap(who, 15.0f) && !player->GetQuestRewardStatus(QUEST_ENTER_THE_ILLIDARI_SHIVARRA) && player->GetQuestStatus(QUEST_ENTER_THE_ILLIDARI_SHIVARRA) == QUEST_STATUS_INCOMPLETE)
                {
                    QuestObjective const* obj = sObjectMgr->GetQuestObjective(OBJECTIVE_FIRST_SUMMONED_GUARDIAN_SHIVARRA);
                    if (!obj)
                        return;

                    if (!player->IsQuestObjectiveComplete(*obj))
                    {
                        Talk(CREATURE_TEXT_ZERO, who);
                        player->KilledMonsterCredit(CREATURE_FIRST_SUMMONED_GUARDIAN);
                    }

                }
        }
```

**Comment by funjoker** [comment]
We can also move the GetTemplate function to the switch case.
Making it searching for quest only when necessary

**Comment by Shauren** [comment]
Do it, add 20 more commits to it :D

**Review by Shauren — APPROVED** [review]

**Pull request merged**
