### PR TITLE
DB/GameTele: New game_tele and instance_template entries #25574

### LINKED ISSUE #25574: DB/GameTele New game_tele and instance_template entries
**Description:**
New game_tele and instance_template

**Branch(es):**
master

**TC rev. hash/commit:** 
acde5cc

**Operating system:** 
All

```sql
-- First you need instance templates
DELETE FROM `instance_template` WHERE `map` IN (1520, 1530, 1571, 1594, 1632, 1648, 1669, 1676, 1677, 1753, 1754, 1762, 1763, 1779, 1822, 1861, 2070, 2096, 2097, 2164, 2207, 2217);
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES
(1520, 0, '', 0),
(1530, 0, '', 0),
(1571, 0, '', 0),
(1594, 0, '', 0),
(1632, 0, '', 0),
(1648, 0, '', 0),
(1669, 0, '', 0),
(1676, 0, '', 0),
(1677, 0, '', 0),
(1753, 0, '', 0),
(1754, 0, '', 0),
(1762, 0, '', 0),
(1763, 0, '', 0),
(1779, 0, '', 0),
(1822, 0, '', 0),
(1861, 0, '', 0),
(2070, 0, '', 0),
(2096, 0, '', 0),
(2097, 0, '', 0),
(2164, 0, '', 0),
(2207, 0, '', 0),
(2217, 0, '', 0);

SET @ID := 1000000;
DELETE FROM `game_tele` WHERE (`id` BETWEEN @ID AND @ID+75);
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
(@ID +  0, -12635.5, -2819.78,  2475.47,   5.19324, 1669, 'TempleOfAnguish'),                    
(@ID +  1,     6382, -797.654,  1650.52,   5.96671, 1676, 'TombOfSargerasChamberOfTheAvatar'),   
(@ID +  2,  5837.07, -795.422,  2954.32,    6.2638, 1676, 'TombOfSargerasChamberOfTheMoon'),     
(@ID +  3,  6170.62, -967.469,  2891.91,    3.5306, 1676, 'TombOfSargerasTerraceOfTheMoon'),     
(@ID +  4,  5968.33, -1132.59,  2852.88,   1.22149, 1676, 'TombOfSargerasTheAbyssalThrone'),     
(@ID +  5,  6233.41, -795.194,  2959.68, 0.0316169, 1676, 'TombOfSargerasTheGuardiansSanctum'),  
(@ID +  6,  6541.97, -787.175,  1508.69,   6.26059, 1676, 'TombOfSargerasFelstormsBreach'),      
(@ID +  7,  4495.58, -1097.95,  5335.97,    4.7376, 1676, 'TombOfSargerasTheTwistingNether'),
(@ID +  8,  3643.32,  2035.12,  1.87964,   4.31871,  571, 'OldKingdom'),                         
(@ID +  9, -5646.25, -6504.49,  177.515,   5.38567, 1669, 'EscapeFromArgus'),                    
(@ID + 10,  1646.73,  1598.12,  107.126,   1.56215, 1208, 'GrimRail'),                           
(@ID + 11,  1231.91,  1713.28,  177.166,   2.98606, 1209, 'SkyReach'),                           
(@ID + 12,  3501.55,  7647.83, -7.68025,   3.26448, 1501, 'BlackRookHold'),                      
(@ID + 13,     1054,     3529,  3.87887,   5.18085, 1571, 'CourtOfStars'),                       
(@ID + 14,  3231.44,  1827.23,  233.304,   3.33988, 1466, 'DarkheartThicket'),                   
(@ID + 15, -3917.17,  4543.34,  87.3211,   5.83349, 1456, 'EyeOfAzshara'),                       
(@ID + 16,  3191.97,  2899.36,  639.659,   2.13033, 1477, 'HallsOfValor'),                       
(@ID + 17,  3798.41,  528.728,   603.33,   3.11993, 1477, 'HallsOfValorHighGate'),               
(@ID + 18,  7146.92,  7323.32,   13.791,   6.07021, 1492, 'MawOfSoulsHelmouthCliffs'),           
(@ID + 19,  2857.08,  1086.72,  98.7189,  0.726489, 2207, 'NeltharionsLair'),                    
(@ID + 20,   5401.2,  10819.9,  20.4223,   5.29925, 1753, 'SeatOfTheTriumvirate'),               
(@ID + 21,  3522.29,  4804.85,  590.072,   3.14332, 1632, 'Arcway'),                             
(@ID + 22,  4184.47,  -761.06,  269.521,   1.56861, 1493, 'VaultOfTheWardens'),                  
(@ID + 23, -7717.58,  1419.89, -228.648,   4.92218, 1520, 'EmeraldNightmareClutchOfCorruption'), 
(@ID + 24,  1835.04,  1405.57,  363.912,   5.06747, 1520, 'EmeraldNightmareClutchOfCorruption1'),
(@ID + 25,    11552,    11293, -35.1025,   3.01366, 1520, 'EmeraldNightmareMulgore'),            
(@ID + 26, -12842.6,  12286.5, -253.006,    1.0423, 1520, 'EmeraldNightmareUngoro'),             
(@ID + 27,  583.973,   -12824,  5.50463,   2.34999, 1520, 'EmeraldNightmareDragons'),            
(@ID + 28, -2915.01,  3744.98,  94.3729,   5.66828, 1520, 'EmeraldNightmareAshenvale'),          
(@ID + 29,  -2776.7,  2486.09,  92.6233,  0.343259, 1520, 'EmeraldNightmareHinterlands'),        
(@ID + 30, -2986.85,  1337.07,  45.3371, 0.0448046, 1520, 'EmeraldNightmareDuskwood'),           
(@ID + 31, -4124.38,   191.81,  30.8498,    5.7193, 1520, 'EmeraldNightmareFeralas'),            
(@ID + 32, -12414.7, -13117.9,  324.203, 0.0919226, 1520, 'EmeraldNightmareGrizzlyHills'),       
(@ID + 33,  11370.5, -12670.5,      487,   4.62758, 1520, 'EmeraldNightmareMoonglade'),          
(@ID + 34, -2925.02, -5050.25,  147.706,   4.28199, 1520, 'EmeraldNightmareRiftOfAln'),          
(@ID + 35, -3028.77,   8466.5,  27.4185,   3.74792, 1520, 'EmeraldNightmareEmeraldDream'),       
(@ID + 36,  3610.12,   5604.6,  38.7932,    2.3287, 1648, 'TrialOfValor'),                       
(@ID + 37,  3189.44,  528.932,   633.15,   3.14551, 1648, 'TrialOfValorOdyn'),                   
(@ID + 38,  321.321,  319.541,  31.4491,   1.07598, 1648, 'TrialOfValorHelheim'),                
(@ID + 39,  465.436,  3376.46,  44.7613,   3.21228, 1530, 'NightHoldArcingDepths'),              
(@ID + 40, -124.518,  3506.91, -253.876,   5.49778, 1530, 'NightHoldNightwell'),                 
(@ID + 41,   235.63,  3184.06,  289.415,   5.62263, 1530, 'NightHoldElisandeQuarters'),          
(@ID + 42, -3416.06,  9527.61,  8.80324,  0.219028, 1712, 'Antorus'),                            
(@ID + 43, -2817.92,  10871.5,  139.478,   4.08714, 1712, 'AntoranGazeOfTheLegion'),             
(@ID + 44, -4306.63, -11161.1,  771.558,   5.90698, 1712, 'ArgusElunaria'),                      
(@ID + 45, -10574.7,  8779.27,  1871.47,   4.71238, 1712, 'AntorusTheExodus'),                   
(@ID + 46, -12634.3, -3369.77,  2513.82,   1.56762, 1712, 'ArgusTheBurningThrone'),              
(@ID + 47, -3703.82, -1594.62,  634.295,   1.57944, 1712, 'AntorasHallsBounlessReach'),          
(@ID + 48,  2883.32, -4566.41,   291.96,   1.71831, 1712, 'AntorusSeatOfThePantheon'),           
(@ID + 49,  3136.79, -9635.33,  62.1518,   3.12024, 1712, 'AntorusVindicar'),                    
(@ID + 50,  4490.76,  6588.63,  42.0133,    3.1518, 1779, 'InvPointFolnuna'),                    
(@ID + 51,  5713.05, -1409.76,  29.9925,   3.83586, 1779, 'InvPointMeto'),                       
(@ID + 52,   5267.9, -9773.53,   10.521,   1.21419, 1779, 'InvPointAlluradel'),                  
(@ID + 53, -1384.46,  8353.95,  94.6257,    2.6389, 1779, 'InvPointSotanathor'),                 
(@ID + 54, -10034.3,  2793.49,  20.0162,   5.59592, 1779, 'InvPointOccularus'),                  
(@ID + 55, -9897.36, -4999.18,  129.274,  0.862324, 1779, 'InvPointVilemus'),                    
(@ID + 56, -2810.97,     9595, -174.035,   1.54158, 1669, 'Antoran'),                            
(@ID + 57, -847.591,  2042.83,  726.122,   1.55738, 1763, 'Atal\'dazar'),                        
(@ID + 58, -1591.18, -995.296,  73.3411,    2.7713, 1754, 'FreeholdInstance'),                   
(@ID + 59, -945.431,  2524.03,  833.583,   1.54564, 1762, 'KingsRest'),                          
(@ID + 60,  965.992, -386.025,  28.0247,   1.54564, 2097, 'Mechagon'),                           
(@ID + 61,  1089.06, -617.785,  17.6689,   0.78325, 1822, 'SiegeOfBoralus'),                     
(@ID + 62,  654.604, -3645.94,  1.92823,   5.90058, 1594, 'Motherlode'),                         
(@ID + 63, -375.973, -256.022,   1113.4, 0.0101462, 1861, 'UldirDungeon'),                       
(@ID + 64,    -2271,      803,  5.93201,   6.27085, 2070, 'BattleOfDazarAlor'),                  
(@ID + 65, -6012.03,  2412.94,  14.8388,   0.55387, 2070, 'BattleOfDazarAlorJaina'),             
(@ID + 66,  13384.6,   -13410,  41.0752,   4.67328, 2070, 'BatlleOfDazarAlorBoralus'),           
(@ID + 67,  3404.45,  -1847.6,  108.529,  0.436058, 2096, 'CrucibleOfStorms'),                   
(@ID + 68,  3654.81, -1735.71,   -350.5,   1.47828, 2096, 'CrucibleOfStormsTendrilOfCorruption'),
(@ID + 69,  297.645, -124.401,  1471.01,   1.56075, 2164, 'EternalPalace'),                      
(@ID + 70,  216.937,  2432.95,  717.702,   1.62915, 2164, 'EternalPalaceAzshara'),               
(@ID + 71, -1805.67,  -43.656, -519.746,   6.27478, 2217, 'Ny\'alotha'),                         
(@ID + 72,   -11586,  9318.02,    124.8,   6.15693, 2217, 'Ny\'AlothaLocusOfTheInfiniteTruths'), 
(@ID + 73, -700.783,  2529.79,  332.085,   6.24878, 1677, 'HallOfTheMoon'),                      
(@ID + 74,  747.861,  1693.89,  596.794,  0.716915, 1669, 'Krokuun'),                            
(@ID + 75,  5682.25,  9919.45, -72.6483,   3.91304, 1669, 'Mac\'aree');                          
```

### PR DESCRIPTION
**Pull request by gig64**
**Changes proposed:**

-  New game_tele and instance_template entries actually missing

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [X] master

**Issues addressed:**

Closes #25574

**Tests performed:**

tested in-game

**Known issues and TODO list:**

### CODE REVIEW

**Comment by Aokromes** [comment]
thx but we don't use prs for sql only fixes.

**Comment by TranceAccount** [comment]
+ you already have this sql fix posted

**Comment by gig64** [comment]
Ok but if my next commit need it to work i add again the sql script?

**Comment by TranceAccount** [comment]
You can apply this sql to your own server database if you need it right now

**Comment by illfated** [comment]
@gig64 : if you are talking about any PR to the TC source you are planning on creating, SQL files can be included in PRs containing C++ file changes. Pull Requests can contain C++ files and other core files, mixed with SQL files, but not SQL files without other files.

**Comment by gig64** [comment]
Ok i include only what i really need

**Pull request closed without merging**
